-- 1. 지역 코드 테이블 (참조용)
CREATE TABLE CD_REGION (
    REGION_CD VARCHAR2(5) PRIMARY KEY,
    REGION_NM VARCHAR2(50) NOT NULL
);

-- 2. 가구 테이블
CREATE TABLE HOUSEHOLD (
    HOUSEHOLD_ID NUMBER(12) PRIMARY KEY,
    REGION_CD VARCHAR2(5),
    MEMBERS_CNT NUMBER(2),
    CONSTRAINT FK_HOUSEHOLD_REGION FOREIGN KEY (REGION_CD) REFERENCES CD_REGION(REGION_CD)
);

-- 3. 인구통계 테이블 (프로토타입 명세 반영)
CREATE TABLE POPULATION (
    POP_ID NUMBER(12) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    REGION_CD VARCHAR2(5),
    POP_CNT NUMBER(10),
    SURVEY_DT DATE,
    GENDER_CD CHAR(1),
    SALARY NUMBER(10),
    HOUSEHOLD_ID NUMBER(12),
    MEMO VARCHAR2(500),
    CONSTRAINT FK_POP_REGION FOREIGN KEY (REGION_CD) REFERENCES CD_REGION(REGION_CD),
    CONSTRAINT FK_POP_HOUSEHOLD FOREIGN KEY (HOUSEHOLD_ID) REFERENCES HOUSEHOLD(HOUSEHOLD_ID)
);