-- [ADMIN_PURGE_PROJECT_CONTEXT]
SELECT P.PROJECT_ID
     , P.PROJECT_CODE
     , P.PROJECT_NAME
     , P.USER_ID
     , P.USER_EMAIL
     , (
        SELECT COUNT(*)
          FROM INIT$_TB_SCENARIO S
         WHERE S.PROJECT_ID = P.PROJECT_ID
       ) AS SCENARIO_COUNT
  FROM INIT$_TB_PROJECT P
 WHERE P.PROJECT_ID = :projectId
;

-- [ADMIN_PURGE_SCENARIO_CONTEXT]
SELECT S.SCENARIO_ID
     , S.SCENARIO_CODE
     , S.SCENARIO_NAME
     , S.PROJECT_ID
     , P.PROJECT_CODE
     , P.PROJECT_NAME
     , P.USER_ID
     , P.USER_EMAIL
  FROM INIT$_TB_SCENARIO S
  JOIN INIT$_TB_PROJECT P
    ON P.PROJECT_ID = S.PROJECT_ID
 WHERE S.SCENARIO_ID = :scenarioId
;

-- [ADMIN_PURGE_PROJECT_LOCK]
SELECT PROJECT_ID
  FROM INIT$_TB_PROJECT
 WHERE PROJECT_ID = :projectId
   FOR UPDATE NOWAIT
;

-- [ADMIN_PURGE_SCENARIO_LOCK]
SELECT SCENARIO_ID
  FROM INIT$_TB_SCENARIO
 WHERE SCENARIO_ID = :scenarioId
   FOR UPDATE NOWAIT
;

-- [ADMIN_PURGE_CURRENT_SCHEMA]
SELECT SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA') AS CURRENT_SCHEMA
  FROM DUAL
;

-- [ADMIN_PURGE_REQUIRED_TABLES_MISSING]
WITH REQUIRED_TABLES AS (
    SELECT 'INIT$_TB_PROJECT' AS TABLE_NAME FROM DUAL
    UNION ALL SELECT 'INIT$_TB_SCENARIO' FROM DUAL
    UNION ALL SELECT 'INIT$_TB_REPORT_TMPL_USE' FROM DUAL
    UNION ALL SELECT 'INIT$_TB_TABLES' FROM DUAL
    UNION ALL SELECT 'INIT$_TB_UPLOAD_TABLE_META' FROM DUAL
    UNION ALL SELECT 'INIT$_TB_TABLE_COLUMN_MAP' FROM DUAL
    UNION ALL SELECT 'INIT$_TB_COLTYPE_RESULT' FROM DUAL
    UNION ALL SELECT 'INIT$_TB_COLTYPE_FINAL' FROM DUAL
    UNION ALL SELECT 'INIT$_TB_COLTYPE_PROFILE' FROM DUAL
    UNION ALL SELECT 'INIT$_TB_COLTYPE_LABEL' FROM DUAL
    UNION ALL SELECT 'INIT$_TB_COLTYPE_LABEL_HIST' FROM DUAL
    UNION ALL SELECT 'INIT$_TB_COLREL_CAT_PAIR' FROM DUAL
    UNION ALL SELECT 'INIT$_TB_COLREL_CAT_SUMMARY' FROM DUAL
    UNION ALL SELECT 'INIT$_TB_COLREL_NUM_PAIR' FROM DUAL
    UNION ALL SELECT 'INIT$_TB_COLREL_NUM_SUMMARY' FROM DUAL
    UNION ALL SELECT 'INIT$_TB_COLREL_PAIR' FROM DUAL
    UNION ALL SELECT 'INIT$_TB_COLREL_SUMMARY' FROM DUAL
    UNION ALL SELECT 'INIT$_TB_COLREL_NETWORK_NODE' FROM DUAL
    UNION ALL SELECT 'INIT$_TB_COLREL_NETWORK_EDGE' FROM DUAL
    UNION ALL SELECT 'INIT$_TB_COLREL_LASSO_FEATURE' FROM DUAL
    UNION ALL SELECT 'INIT$_TB_RULEDISC_SYMBOLIC' FROM DUAL
    UNION ALL SELECT 'INIT$_TB_RULEVIOL_SYMBOLIC' FROM DUAL
    UNION ALL SELECT 'INIT$_TB_API_RESULT' FROM DUAL
    UNION ALL SELECT 'INIT$_TB_RULEDISC_ASSOC_SUM' FROM DUAL
    UNION ALL SELECT 'INIT$_TB_RULEVIOL_ASSOC' FROM DUAL
    UNION ALL SELECT 'INIT$_TB_DATA_WORK_JOB' FROM DUAL
    UNION ALL SELECT 'INIT$_TB_DATA_WORK_RUN' FROM DUAL
    UNION ALL SELECT 'INIT$_TB_FLOW_WORK' FROM DUAL
    UNION ALL SELECT 'INIT$_TB_FLOW_WORK_NODE' FROM DUAL
    UNION ALL SELECT 'INIT$_TB_FLOW_WORK_EDGE' FROM DUAL
    UNION ALL SELECT 'INIT$_TB_FLOW_WORK_RUN' FROM DUAL
    UNION ALL SELECT 'INIT$_TB_FLOW_WORK_NODE_RUN' FROM DUAL
    UNION ALL SELECT 'INIT$_TB_EDIT_RULE' FROM DUAL
    UNION ALL SELECT 'INIT$_TB_EDIT_SESSION' FROM DUAL
    UNION ALL SELECT 'INIT$_TB_EDIT_SESSION_RULE' FROM DUAL
    UNION ALL SELECT 'INIT$_TB_EDIT_CHANGE' FROM DUAL
    UNION ALL SELECT 'INIT$_TB_EDIT_DML' FROM DUAL
    UNION ALL SELECT 'INIT$_TB_EDIT_EVENT' FROM DUAL
)
SELECT R.TABLE_NAME
  FROM REQUIRED_TABLES R
 WHERE NOT EXISTS (
        SELECT 1
          FROM USER_TABLES T
         WHERE T.TABLE_NAME = R.TABLE_NAME
       )
 ORDER BY R.TABLE_NAME
;

-- [ADMIN_PURGE_PROJECT_MANAGED_TABLES]
WITH CANDIDATES AS (
    SELECT ST.OWNER_NAME AS SOURCE_OWNER
         , ST.TABLE_NAME AS SOURCE_TABLE
         , NVL(ST.EDIT_OWNER_NAME, ST.OWNER_NAME) AS EDIT_OWNER
         , NVL(
               ST.EDIT_TABLE_NAME
             , 'INITDN$' || SUBSTR(ST.TABLE_NAME, LENGTH('INITUP$') + 1)
           ) AS EDIT_TABLE
         , NVL(ST.DATA_ORIGIN_TYPE, 'LEGACY_MANAGED') AS DATA_ORIGIN_TYPE
      FROM INIT$_TB_TABLES ST
     WHERE ST.PROJECT_ID = :projectId
    UNION ALL
    SELECT UM.OWNER_NAME AS SOURCE_OWNER
         , UM.TABLE_NAME AS SOURCE_TABLE
         , UM.OWNER_NAME AS EDIT_OWNER
         , 'INITDN$' || SUBSTR(UM.TABLE_NAME, LENGTH('INITUP$') + 1) AS EDIT_TABLE
         , 'PROJECT_UPLOAD_META' AS DATA_ORIGIN_TYPE
      FROM INIT$_TB_UPLOAD_TABLE_META UM
     WHERE UM.PROJECT_ID = :projectId
       AND UM.TABLE_NAME LIKE 'INITUP$%'
)
SELECT SOURCE_OWNER
     , SOURCE_TABLE
     , EDIT_OWNER
     , EDIT_TABLE
     , MIN(DATA_ORIGIN_TYPE) AS DATA_ORIGIN_TYPE
  FROM CANDIDATES
 GROUP BY SOURCE_OWNER
        , SOURCE_TABLE
        , EDIT_OWNER
        , EDIT_TABLE
 ORDER BY SOURCE_OWNER
        , SOURCE_TABLE
;

-- [ADMIN_PURGE_SCENARIO_MANAGED_TABLES]
SELECT ST.OWNER_NAME AS SOURCE_OWNER
     , ST.TABLE_NAME AS SOURCE_TABLE
     , NVL(ST.EDIT_OWNER_NAME, ST.OWNER_NAME) AS EDIT_OWNER
     , NVL(
           ST.EDIT_TABLE_NAME
         , 'INITDN$' || SUBSTR(ST.TABLE_NAME, LENGTH('INITUP$') + 1)
       ) AS EDIT_TABLE
     , MIN(NVL(ST.DATA_ORIGIN_TYPE, 'LEGACY_MANAGED')) AS DATA_ORIGIN_TYPE
  FROM INIT$_TB_TABLES ST
 WHERE ST.PROJECT_ID = :projectId
   AND ST.SCENARIO_ID = :scenarioId
 GROUP BY ST.OWNER_NAME
        , ST.TABLE_NAME
        , NVL(ST.EDIT_OWNER_NAME, ST.OWNER_NAME)
        , NVL(
              ST.EDIT_TABLE_NAME
            , 'INITDN$' || SUBSTR(ST.TABLE_NAME, LENGTH('INITUP$') + 1)
          )
 ORDER BY ST.OWNER_NAME
        , ST.TABLE_NAME
;

-- [ADMIN_PURGE_MANAGED_TABLE_EXTERNAL_REFS]
SELECT COUNT(*) AS REFERENCE_COUNT
  FROM INIT$_TB_TABLES ST
 WHERE (
          (ST.OWNER_NAME = :sourceOwner AND ST.TABLE_NAME = :sourceTable)
       OR (ST.EDIT_OWNER_NAME = :sourceOwner AND ST.EDIT_TABLE_NAME = :sourceTable)
       OR (ST.OWNER_NAME = :editOwner AND ST.TABLE_NAME = :editTable)
       OR (ST.EDIT_OWNER_NAME = :editOwner AND ST.EDIT_TABLE_NAME = :editTable)
       )
   AND NOT (
           ST.PROJECT_ID = :projectId
       AND (:scenarioId IS NULL OR ST.SCENARIO_ID = :scenarioId)
       )
;

-- [ADMIN_PURGE_MANAGED_TABLE_PROJECT_OWNERS]
WITH MANAGED_TABLE_PROJECTS AS (
    SELECT UM.PROJECT_ID
         , UM.OWNER_NAME
         , UM.TABLE_NAME
      FROM INIT$_TB_UPLOAD_TABLE_META UM
     WHERE UM.TABLE_NAME LIKE 'INITUP$%'
    UNION
    SELECT UM.PROJECT_ID
         , UM.OWNER_NAME
         , 'INITDN$' || SUBSTR(UM.TABLE_NAME, LENGTH('INITUP$') + 1) AS TABLE_NAME
      FROM INIT$_TB_UPLOAD_TABLE_META UM
     WHERE UM.TABLE_NAME LIKE 'INITUP$%'
    UNION
    SELECT ST.PROJECT_ID
         , ST.OWNER_NAME
         , ST.TABLE_NAME
      FROM INIT$_TB_TABLES ST
    UNION
    SELECT ST.PROJECT_ID
         , ST.EDIT_OWNER_NAME AS OWNER_NAME
         , ST.EDIT_TABLE_NAME AS TABLE_NAME
      FROM INIT$_TB_TABLES ST
     WHERE ST.EDIT_OWNER_NAME IS NOT NULL
       AND ST.EDIT_TABLE_NAME IS NOT NULL
)
SELECT DISTINCT PROJECT_ID
  FROM MANAGED_TABLE_PROJECTS
 WHERE (OWNER_NAME = :sourceOwner AND TABLE_NAME = :sourceTable)
    OR (OWNER_NAME = :editOwner AND TABLE_NAME = :editTable)
 ORDER BY PROJECT_ID
;

-- [ADMIN_PURGE_PHYSICAL_TABLE_EXISTS]
SELECT COUNT(*) AS TABLE_COUNT
  FROM USER_TABLES
 WHERE TABLE_NAME = :tableName
;

-- [ADMIN_PURGE_ACTIVE_RUN_COUNT]
SELECT (
        SELECT COUNT(*)
          FROM INIT$_TB_DATA_WORK_RUN R
          JOIN INIT$_TB_DATA_WORK_JOB J
            ON J.WORK_JOB_ID = R.WORK_JOB_ID
         WHERE J.PROJECT_ID = :projectId
           AND (:scenarioId IS NULL OR J.SCENARIO_ID = :scenarioId)
           AND UPPER(R.STATUS) IN ('PENDING', 'QUEUED', 'SUBMITTED', 'STARTED', 'RUNNING', 'IN_PROGRESS')
       ) AS DATA_WORK_ACTIVE_COUNT
     , (
        SELECT COUNT(*)
          FROM INIT$_TB_FLOW_WORK_RUN R
          JOIN INIT$_TB_FLOW_WORK F
            ON F.FLOW_ID = R.FLOW_ID
         WHERE F.PROJECT_ID = :projectId
           AND (:scenarioId IS NULL OR F.SCENARIO_ID = :scenarioId)
           AND UPPER(R.STATUS) IN ('PENDING', 'QUEUED', 'SUBMITTED', 'STARTED', 'RUNNING', 'IN_PROGRESS')
       ) AS FLOW_WORK_ACTIVE_COUNT
  FROM DUAL
;

-- [ADMIN_PURGE_DATA_RUN_EXTERNAL_REFS]
WITH SCOPE_RUN_IDS AS (
    SELECT DISTINCT R.DATA_RUN_ID
      FROM INIT$_TB_DATA_WORK_RUN R
      JOIN INIT$_TB_DATA_WORK_JOB J
        ON J.WORK_JOB_ID = R.WORK_JOB_ID
     WHERE J.PROJECT_ID = :projectId
       AND (:scenarioId IS NULL OR J.SCENARIO_ID = :scenarioId)
       AND R.DATA_RUN_ID > 0
)
SELECT COUNT(*) AS REFERENCE_COUNT
  FROM INIT$_TB_DATA_WORK_RUN R
  JOIN INIT$_TB_DATA_WORK_JOB J
    ON J.WORK_JOB_ID = R.WORK_JOB_ID
 WHERE R.DATA_RUN_ID IN (
        SELECT DATA_RUN_ID
          FROM SCOPE_RUN_IDS
       )
   AND NOT (
           J.PROJECT_ID = :projectId
       AND (:scenarioId IS NULL OR J.SCENARIO_ID = :scenarioId)
       )
;

-- [ADMIN_PURGE_IMPACT_COUNTS]
SELECT (
        SELECT COUNT(*)
          FROM INIT$_TB_SCENARIO S
         WHERE S.PROJECT_ID = :projectId
           AND (:scenarioId IS NULL OR S.SCENARIO_ID = :scenarioId)
       ) AS SCENARIO_COUNT
     , (
        SELECT COUNT(*)
          FROM INIT$_TB_TABLES T
         WHERE T.PROJECT_ID = :projectId
           AND (:scenarioId IS NULL OR T.SCENARIO_ID = :scenarioId)
       ) AS SCENARIO_TABLE_COUNT
     , (
        SELECT COUNT(*)
          FROM INIT$_TB_DATA_WORK_JOB J
         WHERE J.PROJECT_ID = :projectId
           AND (:scenarioId IS NULL OR J.SCENARIO_ID = :scenarioId)
       ) AS DATA_WORK_JOB_COUNT
     , (
        SELECT COUNT(*)
          FROM INIT$_TB_DATA_WORK_RUN R
          JOIN INIT$_TB_DATA_WORK_JOB J
            ON J.WORK_JOB_ID = R.WORK_JOB_ID
         WHERE J.PROJECT_ID = :projectId
           AND (:scenarioId IS NULL OR J.SCENARIO_ID = :scenarioId)
       ) AS DATA_WORK_RUN_COUNT
     , (
        SELECT COUNT(*)
          FROM INIT$_TB_FLOW_WORK F
         WHERE F.PROJECT_ID = :projectId
           AND (:scenarioId IS NULL OR F.SCENARIO_ID = :scenarioId)
       ) AS FLOW_WORK_COUNT
     , (
        SELECT COUNT(*)
          FROM INIT$_TB_FLOW_WORK_RUN R
          JOIN INIT$_TB_FLOW_WORK F
            ON F.FLOW_ID = R.FLOW_ID
         WHERE F.PROJECT_ID = :projectId
           AND (:scenarioId IS NULL OR F.SCENARIO_ID = :scenarioId)
       ) AS FLOW_WORK_RUN_COUNT
     , (
        SELECT COUNT(*)
          FROM INIT$_TB_EDIT_RULE E
         WHERE E.PROJECT_ID = :projectId
           AND (:scenarioId IS NULL OR E.SCENARIO_ID = :scenarioId)
       ) AS EDIT_RULE_COUNT
     , (
        SELECT COUNT(*)
          FROM INIT$_TB_EDIT_SESSION E
         WHERE E.PROJECT_ID = :projectId
           AND (:scenarioId IS NULL OR E.SCENARIO_ID = :scenarioId)
       ) AS EDIT_SESSION_COUNT
  FROM DUAL
;

-- [ADMIN_PURGE_RUN_RESULTS_DELETE]
BEGIN
    DELETE FROM INIT$_TB_RULEVIOL_SYMBOLIC T
     WHERE (T.RUN_SOURCE_TYPE = 'DATA_WORK' AND T.RUN_ID IN (
               SELECT DISTINCT R.DATA_RUN_ID
                 FROM INIT$_TB_DATA_WORK_RUN R
                 JOIN INIT$_TB_DATA_WORK_JOB J ON J.WORK_JOB_ID = R.WORK_JOB_ID
                WHERE J.PROJECT_ID = :projectId
                  AND (:scenarioId IS NULL OR J.SCENARIO_ID = :scenarioId)
                  AND R.DATA_RUN_ID > 0
           ))
        OR (T.RUN_SOURCE_TYPE = 'FLOW_WORK' AND T.RUN_ID IN (
               SELECT R.FLOW_RUN_ID
                 FROM INIT$_TB_FLOW_WORK_RUN R
                 JOIN INIT$_TB_FLOW_WORK F ON F.FLOW_ID = R.FLOW_ID
                WHERE F.PROJECT_ID = :projectId
                  AND (:scenarioId IS NULL OR F.SCENARIO_ID = :scenarioId)
           ));

    DELETE FROM INIT$_TB_RULEDISC_SYMBOLIC T
     WHERE (T.RUN_SOURCE_TYPE = 'DATA_WORK' AND T.RUN_ID IN (
               SELECT DISTINCT R.DATA_RUN_ID FROM INIT$_TB_DATA_WORK_RUN R
               JOIN INIT$_TB_DATA_WORK_JOB J ON J.WORK_JOB_ID = R.WORK_JOB_ID
               WHERE J.PROJECT_ID = :projectId AND (:scenarioId IS NULL OR J.SCENARIO_ID = :scenarioId) AND R.DATA_RUN_ID > 0
           ))
        OR (T.RUN_SOURCE_TYPE = 'FLOW_WORK' AND T.RUN_ID IN (
               SELECT R.FLOW_RUN_ID FROM INIT$_TB_FLOW_WORK_RUN R
               JOIN INIT$_TB_FLOW_WORK F ON F.FLOW_ID = R.FLOW_ID
               WHERE F.PROJECT_ID = :projectId AND (:scenarioId IS NULL OR F.SCENARIO_ID = :scenarioId)
           ));

    DELETE FROM INIT$_TB_COLREL_LASSO_FEATURE T
     WHERE (T.RUN_SOURCE_TYPE = 'DATA_WORK' AND T.RUN_ID IN (
               SELECT DISTINCT R.DATA_RUN_ID FROM INIT$_TB_DATA_WORK_RUN R
               JOIN INIT$_TB_DATA_WORK_JOB J ON J.WORK_JOB_ID = R.WORK_JOB_ID
               WHERE J.PROJECT_ID = :projectId AND (:scenarioId IS NULL OR J.SCENARIO_ID = :scenarioId) AND R.DATA_RUN_ID > 0
           ))
        OR (T.RUN_SOURCE_TYPE = 'FLOW_WORK' AND T.RUN_ID IN (
               SELECT R.FLOW_RUN_ID FROM INIT$_TB_FLOW_WORK_RUN R
               JOIN INIT$_TB_FLOW_WORK F ON F.FLOW_ID = R.FLOW_ID
               WHERE F.PROJECT_ID = :projectId AND (:scenarioId IS NULL OR F.SCENARIO_ID = :scenarioId)
           ));

    DELETE FROM INIT$_TB_COLREL_NETWORK_EDGE T
     WHERE (T.RUN_SOURCE_TYPE = 'DATA_WORK' AND T.RUN_ID IN (
               SELECT DISTINCT R.DATA_RUN_ID FROM INIT$_TB_DATA_WORK_RUN R
               JOIN INIT$_TB_DATA_WORK_JOB J ON J.WORK_JOB_ID = R.WORK_JOB_ID
               WHERE J.PROJECT_ID = :projectId AND (:scenarioId IS NULL OR J.SCENARIO_ID = :scenarioId) AND R.DATA_RUN_ID > 0
           ))
        OR (T.RUN_SOURCE_TYPE = 'FLOW_WORK' AND T.RUN_ID IN (
               SELECT R.FLOW_RUN_ID FROM INIT$_TB_FLOW_WORK_RUN R
               JOIN INIT$_TB_FLOW_WORK F ON F.FLOW_ID = R.FLOW_ID
               WHERE F.PROJECT_ID = :projectId AND (:scenarioId IS NULL OR F.SCENARIO_ID = :scenarioId)
           ));

    DELETE FROM INIT$_TB_COLREL_NETWORK_NODE T
     WHERE (T.RUN_SOURCE_TYPE = 'DATA_WORK' AND T.RUN_ID IN (
               SELECT DISTINCT R.DATA_RUN_ID FROM INIT$_TB_DATA_WORK_RUN R
               JOIN INIT$_TB_DATA_WORK_JOB J ON J.WORK_JOB_ID = R.WORK_JOB_ID
               WHERE J.PROJECT_ID = :projectId AND (:scenarioId IS NULL OR J.SCENARIO_ID = :scenarioId) AND R.DATA_RUN_ID > 0
           ))
        OR (T.RUN_SOURCE_TYPE = 'FLOW_WORK' AND T.RUN_ID IN (
               SELECT R.FLOW_RUN_ID FROM INIT$_TB_FLOW_WORK_RUN R
               JOIN INIT$_TB_FLOW_WORK F ON F.FLOW_ID = R.FLOW_ID
               WHERE F.PROJECT_ID = :projectId AND (:scenarioId IS NULL OR F.SCENARIO_ID = :scenarioId)
           ));

    DELETE FROM INIT$_TB_COLREL_SUMMARY T
     WHERE (T.RUN_SOURCE_TYPE = 'DATA_WORK' AND T.RUN_ID IN (
               SELECT DISTINCT R.DATA_RUN_ID FROM INIT$_TB_DATA_WORK_RUN R
               JOIN INIT$_TB_DATA_WORK_JOB J ON J.WORK_JOB_ID = R.WORK_JOB_ID
               WHERE J.PROJECT_ID = :projectId AND (:scenarioId IS NULL OR J.SCENARIO_ID = :scenarioId) AND R.DATA_RUN_ID > 0
           ))
        OR (T.RUN_SOURCE_TYPE = 'FLOW_WORK' AND T.RUN_ID IN (
               SELECT R.FLOW_RUN_ID FROM INIT$_TB_FLOW_WORK_RUN R
               JOIN INIT$_TB_FLOW_WORK F ON F.FLOW_ID = R.FLOW_ID
               WHERE F.PROJECT_ID = :projectId AND (:scenarioId IS NULL OR F.SCENARIO_ID = :scenarioId)
           ));

    DELETE FROM INIT$_TB_COLREL_PAIR T
     WHERE (T.RUN_SOURCE_TYPE = 'DATA_WORK' AND T.RUN_ID IN (
               SELECT DISTINCT R.DATA_RUN_ID FROM INIT$_TB_DATA_WORK_RUN R
               JOIN INIT$_TB_DATA_WORK_JOB J ON J.WORK_JOB_ID = R.WORK_JOB_ID
               WHERE J.PROJECT_ID = :projectId AND (:scenarioId IS NULL OR J.SCENARIO_ID = :scenarioId) AND R.DATA_RUN_ID > 0
           ))
        OR (T.RUN_SOURCE_TYPE = 'FLOW_WORK' AND T.RUN_ID IN (
               SELECT R.FLOW_RUN_ID FROM INIT$_TB_FLOW_WORK_RUN R
               JOIN INIT$_TB_FLOW_WORK F ON F.FLOW_ID = R.FLOW_ID
               WHERE F.PROJECT_ID = :projectId AND (:scenarioId IS NULL OR F.SCENARIO_ID = :scenarioId)
           ));

    DELETE FROM INIT$_TB_COLREL_NUM_SUMMARY T
     WHERE (T.RUN_SOURCE_TYPE = 'DATA_WORK' AND T.RUN_ID IN (
               SELECT DISTINCT R.DATA_RUN_ID FROM INIT$_TB_DATA_WORK_RUN R
               JOIN INIT$_TB_DATA_WORK_JOB J ON J.WORK_JOB_ID = R.WORK_JOB_ID
               WHERE J.PROJECT_ID = :projectId AND (:scenarioId IS NULL OR J.SCENARIO_ID = :scenarioId) AND R.DATA_RUN_ID > 0
           ))
        OR (T.RUN_SOURCE_TYPE = 'FLOW_WORK' AND T.RUN_ID IN (
               SELECT R.FLOW_RUN_ID FROM INIT$_TB_FLOW_WORK_RUN R
               JOIN INIT$_TB_FLOW_WORK F ON F.FLOW_ID = R.FLOW_ID
               WHERE F.PROJECT_ID = :projectId AND (:scenarioId IS NULL OR F.SCENARIO_ID = :scenarioId)
           ));

    DELETE FROM INIT$_TB_COLREL_NUM_PAIR T
     WHERE (T.RUN_SOURCE_TYPE = 'DATA_WORK' AND T.RUN_ID IN (
               SELECT DISTINCT R.DATA_RUN_ID FROM INIT$_TB_DATA_WORK_RUN R
               JOIN INIT$_TB_DATA_WORK_JOB J ON J.WORK_JOB_ID = R.WORK_JOB_ID
               WHERE J.PROJECT_ID = :projectId AND (:scenarioId IS NULL OR J.SCENARIO_ID = :scenarioId) AND R.DATA_RUN_ID > 0
           ))
        OR (T.RUN_SOURCE_TYPE = 'FLOW_WORK' AND T.RUN_ID IN (
               SELECT R.FLOW_RUN_ID FROM INIT$_TB_FLOW_WORK_RUN R
               JOIN INIT$_TB_FLOW_WORK F ON F.FLOW_ID = R.FLOW_ID
               WHERE F.PROJECT_ID = :projectId AND (:scenarioId IS NULL OR F.SCENARIO_ID = :scenarioId)
           ));

    DELETE FROM INIT$_TB_API_RESULT T
     WHERE (T.RUN_SOURCE_TYPE = 'DATA_WORK' AND T.RUN_ID IN (
               SELECT DISTINCT R.DATA_RUN_ID FROM INIT$_TB_DATA_WORK_RUN R
               JOIN INIT$_TB_DATA_WORK_JOB J ON J.WORK_JOB_ID = R.WORK_JOB_ID
               WHERE J.PROJECT_ID = :projectId AND (:scenarioId IS NULL OR J.SCENARIO_ID = :scenarioId) AND R.DATA_RUN_ID > 0
           ))
        OR (T.RUN_SOURCE_TYPE = 'FLOW_WORK' AND T.RUN_ID IN (
               SELECT R.FLOW_RUN_ID FROM INIT$_TB_FLOW_WORK_RUN R
               JOIN INIT$_TB_FLOW_WORK F ON F.FLOW_ID = R.FLOW_ID
               WHERE F.PROJECT_ID = :projectId AND (:scenarioId IS NULL OR F.SCENARIO_ID = :scenarioId)
           ));

    DELETE FROM INIT$_TB_COLREL_CAT_SUMMARY T
     WHERE (T.RUN_SOURCE_TYPE = 'DATA_WORK' AND T.RUN_ID IN (
               SELECT DISTINCT R.DATA_RUN_ID FROM INIT$_TB_DATA_WORK_RUN R
               JOIN INIT$_TB_DATA_WORK_JOB J ON J.WORK_JOB_ID = R.WORK_JOB_ID
               WHERE J.PROJECT_ID = :projectId AND (:scenarioId IS NULL OR J.SCENARIO_ID = :scenarioId) AND R.DATA_RUN_ID > 0
           ))
        OR (T.RUN_SOURCE_TYPE = 'FLOW_WORK' AND T.RUN_ID IN (
               SELECT R.FLOW_RUN_ID FROM INIT$_TB_FLOW_WORK_RUN R
               JOIN INIT$_TB_FLOW_WORK F ON F.FLOW_ID = R.FLOW_ID
               WHERE F.PROJECT_ID = :projectId AND (:scenarioId IS NULL OR F.SCENARIO_ID = :scenarioId)
           ));

    DELETE FROM INIT$_TB_COLREL_CAT_PAIR T
     WHERE (T.RUN_SOURCE_TYPE = 'DATA_WORK' AND T.RUN_ID IN (
               SELECT DISTINCT R.DATA_RUN_ID FROM INIT$_TB_DATA_WORK_RUN R
               JOIN INIT$_TB_DATA_WORK_JOB J ON J.WORK_JOB_ID = R.WORK_JOB_ID
               WHERE J.PROJECT_ID = :projectId AND (:scenarioId IS NULL OR J.SCENARIO_ID = :scenarioId) AND R.DATA_RUN_ID > 0
           ))
        OR (T.RUN_SOURCE_TYPE = 'FLOW_WORK' AND T.RUN_ID IN (
               SELECT R.FLOW_RUN_ID FROM INIT$_TB_FLOW_WORK_RUN R
               JOIN INIT$_TB_FLOW_WORK F ON F.FLOW_ID = R.FLOW_ID
               WHERE F.PROJECT_ID = :projectId AND (:scenarioId IS NULL OR F.SCENARIO_ID = :scenarioId)
           ));

    DELETE FROM INIT$_TB_RULEVIOL_ASSOC T
     WHERE (T.RUN_SOURCE_TYPE = 'DATA_WORK' AND T.RUN_ID IN (
               SELECT DISTINCT R.DATA_RUN_ID FROM INIT$_TB_DATA_WORK_RUN R
               JOIN INIT$_TB_DATA_WORK_JOB J ON J.WORK_JOB_ID = R.WORK_JOB_ID
               WHERE J.PROJECT_ID = :projectId AND (:scenarioId IS NULL OR J.SCENARIO_ID = :scenarioId) AND R.DATA_RUN_ID > 0
           ))
        OR (T.RUN_SOURCE_TYPE = 'FLOW_WORK' AND T.RUN_ID IN (
               SELECT R.FLOW_RUN_ID FROM INIT$_TB_FLOW_WORK_RUN R
               JOIN INIT$_TB_FLOW_WORK F ON F.FLOW_ID = R.FLOW_ID
               WHERE F.PROJECT_ID = :projectId AND (:scenarioId IS NULL OR F.SCENARIO_ID = :scenarioId)
           ));

    DELETE FROM INIT$_TB_RULEDISC_ASSOC_SUM T
     WHERE (T.RUN_SOURCE_TYPE = 'DATA_WORK' AND T.RUN_ID IN (
               SELECT DISTINCT R.DATA_RUN_ID FROM INIT$_TB_DATA_WORK_RUN R
               JOIN INIT$_TB_DATA_WORK_JOB J ON J.WORK_JOB_ID = R.WORK_JOB_ID
               WHERE J.PROJECT_ID = :projectId AND (:scenarioId IS NULL OR J.SCENARIO_ID = :scenarioId) AND R.DATA_RUN_ID > 0
           ))
        OR (T.RUN_SOURCE_TYPE = 'FLOW_WORK' AND T.RUN_ID IN (
               SELECT R.FLOW_RUN_ID FROM INIT$_TB_FLOW_WORK_RUN R
               JOIN INIT$_TB_FLOW_WORK F ON F.FLOW_ID = R.FLOW_ID
               WHERE F.PROJECT_ID = :projectId AND (:scenarioId IS NULL OR F.SCENARIO_ID = :scenarioId)
           ));

    DELETE FROM INIT$_TB_COLTYPE_PROFILE T
     WHERE (T.RUN_SOURCE_TYPE = 'DATA_WORK' AND T.RUN_ID IN (
               SELECT DISTINCT R.DATA_RUN_ID FROM INIT$_TB_DATA_WORK_RUN R
               JOIN INIT$_TB_DATA_WORK_JOB J ON J.WORK_JOB_ID = R.WORK_JOB_ID
               WHERE J.PROJECT_ID = :projectId AND (:scenarioId IS NULL OR J.SCENARIO_ID = :scenarioId) AND R.DATA_RUN_ID > 0
           ))
        OR (T.RUN_SOURCE_TYPE = 'FLOW_WORK' AND T.RUN_ID IN (
               SELECT R.FLOW_RUN_ID FROM INIT$_TB_FLOW_WORK_RUN R
               JOIN INIT$_TB_FLOW_WORK F ON F.FLOW_ID = R.FLOW_ID
               WHERE F.PROJECT_ID = :projectId AND (:scenarioId IS NULL OR F.SCENARIO_ID = :scenarioId)
           ));

    DELETE FROM INIT$_TB_COLTYPE_RESULT T
     WHERE (T.RUN_SOURCE_TYPE = 'DATA_WORK' AND T.RUN_ID IN (
               SELECT DISTINCT R.DATA_RUN_ID FROM INIT$_TB_DATA_WORK_RUN R
               JOIN INIT$_TB_DATA_WORK_JOB J ON J.WORK_JOB_ID = R.WORK_JOB_ID
               WHERE J.PROJECT_ID = :projectId AND (:scenarioId IS NULL OR J.SCENARIO_ID = :scenarioId) AND R.DATA_RUN_ID > 0
           ))
        OR (T.RUN_SOURCE_TYPE = 'FLOW_WORK' AND T.RUN_ID IN (
               SELECT R.FLOW_RUN_ID FROM INIT$_TB_FLOW_WORK_RUN R
               JOIN INIT$_TB_FLOW_WORK F ON F.FLOW_ID = R.FLOW_ID
               WHERE F.PROJECT_ID = :projectId AND (:scenarioId IS NULL OR F.SCENARIO_ID = :scenarioId)
           ));
END;
/

-- [ADMIN_PURGE_MANAGED_OBJECT_DATA_DELETE]
BEGIN
    DELETE FROM INIT$_TB_COLTYPE_LABEL_HIST
     WHERE OWNER = :ownerName
       AND TABLE_NAME = :tableName;

    DELETE FROM INIT$_TB_COLTYPE_LABEL
     WHERE OWNER = :ownerName
       AND TABLE_NAME = :tableName;

    DELETE FROM INIT$_TB_COLTYPE_FINAL
     WHERE OWNER = :ownerName
       AND TABLE_NAME = :tableName;

    DELETE FROM INIT$_TB_COLTYPE_PROFILE
     WHERE OWNER = :ownerName
       AND TABLE_NAME = :tableName;

    DELETE FROM INIT$_TB_COLTYPE_RESULT
     WHERE OWNER = :ownerName
       AND TABLE_NAME = :tableName;

    DELETE FROM INIT$_TB_COLREL_CAT_PAIR WHERE OWNER = :ownerName AND TABLE_NAME = :tableName;
    DELETE FROM INIT$_TB_COLREL_CAT_SUMMARY WHERE OWNER = :ownerName AND TABLE_NAME = :tableName;
    DELETE FROM INIT$_TB_COLREL_NUM_PAIR WHERE OWNER = :ownerName AND TABLE_NAME = :tableName;
    DELETE FROM INIT$_TB_COLREL_NUM_SUMMARY WHERE OWNER = :ownerName AND TABLE_NAME = :tableName;
    DELETE FROM INIT$_TB_COLREL_PAIR WHERE OWNER = :ownerName AND TABLE_NAME = :tableName;
    DELETE FROM INIT$_TB_COLREL_SUMMARY WHERE OWNER = :ownerName AND TABLE_NAME = :tableName;
    DELETE FROM INIT$_TB_COLREL_NETWORK_NODE WHERE OWNER = :ownerName AND TABLE_NAME = :tableName;
    DELETE FROM INIT$_TB_COLREL_NETWORK_EDGE WHERE OWNER = :ownerName AND TABLE_NAME = :tableName;
    DELETE FROM INIT$_TB_COLREL_LASSO_FEATURE WHERE OWNER = :ownerName AND TABLE_NAME = :tableName;
    DELETE FROM INIT$_TB_RULEDISC_SYMBOLIC WHERE OWNER = :ownerName AND TABLE_NAME = :tableName;
    DELETE FROM INIT$_TB_RULEVIOL_SYMBOLIC WHERE TARGET_OWNER = :ownerName AND TARGET_TABLE = :tableName;
    DELETE FROM INIT$_TB_API_RESULT WHERE TARGET_OWNER = :ownerName AND TARGET_TABLE = :tableName;
    DELETE FROM INIT$_TB_RULEDISC_ASSOC_SUM WHERE TARGET_OWNER = :ownerName AND TARGET_TABLE = :tableName;
    DELETE FROM INIT$_TB_RULEVIOL_ASSOC WHERE TARGET_OWNER = :ownerName AND TARGET_TABLE = :tableName;
END;
/

-- [ADMIN_PURGE_UPLOAD_META_DELETE]
DELETE FROM INIT$_TB_UPLOAD_TABLE_META
 WHERE PROJECT_ID = :projectId
   AND OWNER_NAME = :ownerName
   AND TABLE_NAME = :tableName
;

-- [ADMIN_PURGE_SCOPE_DATA_DELETE]
BEGIN
    DELETE FROM INIT$_TB_EDIT_EVENT E
     WHERE E.EDIT_SESSION_ID IN (
        SELECT S.EDIT_SESSION_ID
          FROM INIT$_TB_EDIT_SESSION S
         WHERE S.PROJECT_ID = :projectId
           AND (:scenarioId IS NULL OR S.SCENARIO_ID = :scenarioId)
     );

    DELETE FROM INIT$_TB_EDIT_DML D
     WHERE D.EDIT_SESSION_ID IN (
        SELECT S.EDIT_SESSION_ID
          FROM INIT$_TB_EDIT_SESSION S
         WHERE S.PROJECT_ID = :projectId
           AND (:scenarioId IS NULL OR S.SCENARIO_ID = :scenarioId)
     );

    DELETE FROM INIT$_TB_EDIT_CHANGE C
     WHERE C.EDIT_SESSION_ID IN (
        SELECT S.EDIT_SESSION_ID
          FROM INIT$_TB_EDIT_SESSION S
         WHERE S.PROJECT_ID = :projectId
           AND (:scenarioId IS NULL OR S.SCENARIO_ID = :scenarioId)
     );

    DELETE FROM INIT$_TB_EDIT_SESSION_RULE R
     WHERE R.EDIT_SESSION_ID IN (
        SELECT S.EDIT_SESSION_ID
          FROM INIT$_TB_EDIT_SESSION S
         WHERE S.PROJECT_ID = :projectId
           AND (:scenarioId IS NULL OR S.SCENARIO_ID = :scenarioId)
     )
        OR R.EDIT_RULE_ID IN (
        SELECT E.EDIT_RULE_ID
          FROM INIT$_TB_EDIT_RULE E
         WHERE E.PROJECT_ID = :projectId
           AND (:scenarioId IS NULL OR E.SCENARIO_ID = :scenarioId)
     );

    DELETE FROM INIT$_TB_EDIT_SESSION
     WHERE PROJECT_ID = :projectId
       AND (:scenarioId IS NULL OR SCENARIO_ID = :scenarioId);

    DELETE FROM INIT$_TB_EDIT_RULE
     WHERE PROJECT_ID = :projectId
       AND (:scenarioId IS NULL OR SCENARIO_ID = :scenarioId);

    DELETE FROM INIT$_TB_FLOW_WORK_NODE_RUN N
     WHERE N.FLOW_RUN_ID IN (
        SELECT R.FLOW_RUN_ID
          FROM INIT$_TB_FLOW_WORK_RUN R
          JOIN INIT$_TB_FLOW_WORK F ON F.FLOW_ID = R.FLOW_ID
         WHERE F.PROJECT_ID = :projectId
           AND (:scenarioId IS NULL OR F.SCENARIO_ID = :scenarioId)
     );

    DELETE FROM INIT$_TB_FLOW_WORK_RUN R
     WHERE R.FLOW_ID IN (
        SELECT F.FLOW_ID
          FROM INIT$_TB_FLOW_WORK F
         WHERE F.PROJECT_ID = :projectId
           AND (:scenarioId IS NULL OR F.SCENARIO_ID = :scenarioId)
     );

    DELETE FROM INIT$_TB_FLOW_WORK_EDGE E
     WHERE E.FLOW_ID IN (
        SELECT F.FLOW_ID
          FROM INIT$_TB_FLOW_WORK F
         WHERE F.PROJECT_ID = :projectId
           AND (:scenarioId IS NULL OR F.SCENARIO_ID = :scenarioId)
     );

    DELETE FROM INIT$_TB_FLOW_WORK_NODE N
     WHERE N.FLOW_ID IN (
        SELECT F.FLOW_ID
          FROM INIT$_TB_FLOW_WORK F
         WHERE F.PROJECT_ID = :projectId
           AND (:scenarioId IS NULL OR F.SCENARIO_ID = :scenarioId)
     );

    DELETE FROM INIT$_TB_FLOW_WORK
     WHERE PROJECT_ID = :projectId
       AND (:scenarioId IS NULL OR SCENARIO_ID = :scenarioId);

    DELETE FROM INIT$_TB_DATA_WORK_RUN R
     WHERE R.WORK_JOB_ID IN (
        SELECT J.WORK_JOB_ID
          FROM INIT$_TB_DATA_WORK_JOB J
         WHERE J.PROJECT_ID = :projectId
           AND (:scenarioId IS NULL OR J.SCENARIO_ID = :scenarioId)
     );

    DELETE FROM INIT$_TB_DATA_WORK_JOB
     WHERE PROJECT_ID = :projectId
       AND (:scenarioId IS NULL OR SCENARIO_ID = :scenarioId);

    DELETE FROM INIT$_TB_TABLE_COLUMN_MAP M
     WHERE M.SCENARIO_TABLE_ID IN (
        SELECT T.SCENARIO_TABLE_ID
          FROM INIT$_TB_TABLES T
         WHERE T.PROJECT_ID = :projectId
           AND (:scenarioId IS NULL OR T.SCENARIO_ID = :scenarioId)
     );

    DELETE FROM INIT$_TB_TABLES
     WHERE PROJECT_ID = :projectId
       AND (:scenarioId IS NULL OR SCENARIO_ID = :scenarioId);

    IF :scenarioId IS NULL THEN
        DELETE FROM INIT$_TB_REPORT_TMPL_USE
         WHERE PROJECT_ID = :projectId;

        DELETE FROM INIT$_TB_UPLOAD_TABLE_META
         WHERE PROJECT_ID = :projectId;

        DELETE FROM INIT$_TB_SCENARIO
         WHERE PROJECT_ID = :projectId;

        DELETE FROM INIT$_TB_PROJECT
         WHERE PROJECT_ID = :projectId;
    ELSE
        UPDATE INIT$_TB_REPORT_TMPL_USE
           SET LAST_SCENARIO_ID = NULL
         WHERE PROJECT_ID = :projectId
           AND LAST_SCENARIO_ID = :scenarioId;

        DELETE FROM INIT$_TB_SCENARIO
         WHERE PROJECT_ID = :projectId
           AND SCENARIO_ID = :scenarioId;
    END IF;
END;
/
