-- [ANALYSIS_SAMPLE_FIRST_ROWS]
SELECT /*+ NO_PARALLEL(T) */ /*COLUMNS*/
  FROM /*TARGET*/ T
 WHERE ROWNUM <= :rowLimit
;

-- [ANALYSIS_SAMPLE_COUNT]
SELECT /*+ NO_PARALLEL(T) */ COUNT(*)
  FROM /*TARGET*/ T
;

-- [ANALYSIS_SAMPLE_HASH]
SELECT /*+ NO_PARALLEL(T) */ ROWIDTOCHAR(T.ROWID) AS SAMPLE_ROWID
     , ORA_HASH(ROWIDTOCHAR(T.ROWID), 4294967295, :sampleSeed) AS SAMPLE_HASH
     , /*COLUMNS*/
  FROM /*TARGET*/ T
 WHERE ORA_HASH(ROWIDTOCHAR(T.ROWID), 4294967295, :sampleSeed) <= :hashThreshold
;
