-- [AUTH_SIGNUP_EXISTING_USER]
SELECT USE_YN
  FROM "INIT$_TB_USER"
 WHERE LOGIN_ID = :loginId;

-- [AUTH_SIGNUP_INSERT_USER]
INSERT INTO "INIT$_TB_USER" (
    LOGIN_ID
  , USER_NAME
  , EMAIL
  , PASSWORD_HASH
  , ROLE_CODE
  , USE_YN
  , CREATED_AT
) VALUES (
    :loginId
  , :userName
  , :email
  , :passwordHash
  , :roleCode
  , :useYn
  , SYSTIMESTAMP
);

-- [AUTH_LOGIN_USER]
SELECT USER_ID
     , LOGIN_ID
     , USER_NAME
     , EMAIL
     , PASSWORD_HASH
     , USE_YN
     , ROLE_CODE
  FROM "INIT$_TB_USER"
 WHERE LOGIN_ID = :loginId;

-- [AUTH_SESSION_ENSURE_TABLE]
DECLARE
    V_COUNT NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO V_COUNT
      FROM USER_TABLES
     WHERE TABLE_NAME = 'INIT$_TB_AUTH_SESSION';

    IF V_COUNT = 0 THEN
        EXECUTE IMMEDIATE q'[
CREATE TABLE "INIT$_TB_AUTH_SESSION" (
    "SESSION_TOKEN_HASH" VARCHAR2(128 BYTE) NOT NULL ENABLE,
    "USER_ID" NUMBER NOT NULL ENABLE,
    "TARGET_CONNECTION_ID" NUMBER,
    "CREATED_AT" TIMESTAMP (6) DEFAULT LOCALTIMESTAMP NOT NULL ENABLE,
    "LAST_SEEN_AT" TIMESTAMP (6) DEFAULT LOCALTIMESTAMP NOT NULL ENABLE,
    "EXPIRES_AT" TIMESTAMP (6) NOT NULL ENABLE,
    "REVOKED_AT" TIMESTAMP (6),
    CONSTRAINT "INIT$_PK_AUTH_SESSION" PRIMARY KEY ("SESSION_TOKEN_HASH"),
    CONSTRAINT "INIT$_FK_AUTH_SESSION_USER" FOREIGN KEY ("USER_ID")
        REFERENCES "INIT$_TB_USER" ("USER_ID") ON DELETE CASCADE ENABLE
)
]';
        EXECUTE IMMEDIATE 'CREATE INDEX "INIT$_IX_AUTH_SESSION_USER" ON "INIT$_TB_AUTH_SESSION" ("USER_ID", "EXPIRES_AT")';
    END IF;
END;

-- [AUTH_SESSION_INSERT]
INSERT INTO "INIT$_TB_AUTH_SESSION" (
    SESSION_TOKEN_HASH
  , USER_ID
  , TARGET_CONNECTION_ID
  , CREATED_AT
  , LAST_SEEN_AT
  , EXPIRES_AT
) VALUES (
    :sessionTokenHash
  , :userId
  , :targetConnectionId
  , LOCALTIMESTAMP
  , LOCALTIMESTAMP
  , LOCALTIMESTAMP + NUMTODSINTERVAL(:ttlSeconds, 'SECOND')
);

-- [AUTH_SESSION_SELECT]
SELECT U.USER_ID
     , U.LOGIN_ID
     , U.USER_NAME
     , U.EMAIL
     , U.ROLE_CODE
     , S.TARGET_CONNECTION_ID
  FROM "INIT$_TB_AUTH_SESSION" S
  JOIN "INIT$_TB_USER" U
    ON U.USER_ID = S.USER_ID
 WHERE S.SESSION_TOKEN_HASH = :sessionTokenHash
   AND S.REVOKED_AT IS NULL
   AND S.EXPIRES_AT > LOCALTIMESTAMP
   AND U.USE_YN = 'Y';

-- [AUTH_SESSION_TOUCH]
UPDATE "INIT$_TB_AUTH_SESSION"
   SET LAST_SEEN_AT = LOCALTIMESTAMP
     , EXPIRES_AT = LOCALTIMESTAMP + NUMTODSINTERVAL(:ttlSeconds, 'SECOND')
 WHERE SESSION_TOKEN_HASH = :sessionTokenHash
   AND REVOKED_AT IS NULL;

-- [AUTH_SESSION_REVOKE]
UPDATE "INIT$_TB_AUTH_SESSION"
   SET REVOKED_AT = LOCALTIMESTAMP
 WHERE SESSION_TOKEN_HASH = :sessionTokenHash
   AND REVOKED_AT IS NULL;

-- [AUTH_SESSION_DELETE_EXPIRED]
DELETE
  FROM "INIT$_TB_AUTH_SESSION"
 WHERE EXPIRES_AT <= LOCALTIMESTAMP
    OR REVOKED_AT IS NOT NULL;
