-- [HOME_EXISTING_TABLES]
SELECT TABLE_NAME
  FROM USER_TABLES
 WHERE TABLE_NAME IN (/* --TABLE_BINDS-- */);

-- [HOME_CONNECTION_COUNT]
SELECT COUNT(*)
  FROM "INIT$_TB_DB_CONNECTION"
 WHERE (:includeAllUsers = 'Y' OR USER_ID = :userId);

-- [HOME_USER_COUNT]
SELECT COUNT(*)
  FROM "INIT$_TB_USER";

-- [HOME_ACTIVE_USER_COUNT]
SELECT COUNT(*)
  FROM "INIT$_TB_USER"
 WHERE USE_YN = 'Y';

-- [HOME_CONNECTION_DETAIL]
SELECT CONNECTION_ID
     , CONNECTION_NAME
     , DB_TYPE
     , HOST
     , PORT
     , SERVICE_NAME
     , SID
     , USERNAME
     , USE_YN
     , DEFAULT_YN
  FROM "INIT$_TB_DB_CONNECTION"
 WHERE (:includeAllUsers = 'Y' OR USER_ID = :userId)
   AND CONNECTION_ID = :connectionId;

-- [HOME_NOTICE_TABLE_EXISTS]
SELECT COUNT(*)
  FROM USER_TABLES
 WHERE TABLE_NAME = 'INIT$_TB_NOTICE';

-- [HOME_NOTICE_FILE_TABLE_EXISTS]
SELECT COUNT(*)
  FROM USER_TABLES
 WHERE TABLE_NAME = 'INIT$_TB_NOTICE_FILE';

-- [HOME_ACTIVE_NOTICES]
SELECT *
  FROM (
    SELECT N.NOTICE_ID
         , N.NOTICE_TYPE
         , N.TITLE
         , N.CONTENT
         , N.POPUP_YN
         , N.PIN_YN
         , N.POST_START_AT
         , N.POST_END_AT
         , N.CREATED_BY
         , N.CREATED_AT
         , U.USER_NAME AS CREATED_USER_NAME
         , U.LOGIN_ID AS CREATED_LOGIN_ID
      FROM "INIT$_TB_NOTICE" N
      LEFT JOIN "INIT$_TB_USER" U
        ON U.USER_ID = N.CREATED_BY
     WHERE N.USE_YN = 'Y'
       AND (N.POST_START_AT IS NULL OR N.POST_START_AT <= SYSTIMESTAMP)
       AND (N.POST_END_AT IS NULL OR N.POST_END_AT >= SYSTIMESTAMP)
     ORDER BY N.PIN_YN DESC, N.SORT_ORDER, N.CREATED_AT DESC, N.NOTICE_ID DESC
  )
 WHERE ROWNUM <= :limit;

-- [HOME_NOTICE_FILES_FOR_NOTICE]
SELECT FILE_ID
     , NOTICE_ID
     , FILE_NAME
     , CONTENT_TYPE
     , FILE_SIZE
     , SORT_ORDER
     , CREATED_AT
  FROM "INIT$_TB_NOTICE_FILE"
 WHERE NOTICE_ID = :noticeId
   AND USE_YN = 'Y'
 ORDER BY SORT_ORDER, FILE_ID;

-- [HOME_NOTICE_FILE_DOWNLOAD]
SELECT F.FILE_ID
     , F.NOTICE_ID
     , F.FILE_NAME
     , F.CONTENT_TYPE
     , F.FILE_SIZE
     , F.FILE_DATA
  FROM "INIT$_TB_NOTICE_FILE" F
  JOIN "INIT$_TB_NOTICE" N ON N.NOTICE_ID = F.NOTICE_ID
 WHERE F.FILE_ID = :fileId
   AND F.USE_YN = 'Y'
   AND N.USE_YN = 'Y'
   AND (N.POST_START_AT IS NULL OR N.POST_START_AT <= SYSTIMESTAMP)
   AND (N.POST_END_AT IS NULL OR N.POST_END_AT >= SYSTIMESTAMP);

-- [HOME_PROJECT_COUNT]
SELECT COUNT(*)
  FROM "INIT$_TB_PROJECT"
 WHERE (:includeAllUsers = 'Y' OR USER_ID = :userId)
   AND USE_YN = 'Y';

-- [HOME_SCENARIO_COUNT]
SELECT COUNT(*)
  FROM "INIT$_TB_SCENARIO" S
  JOIN "INIT$_TB_PROJECT" P ON P.PROJECT_ID = S.PROJECT_ID
 WHERE (:includeAllUsers = 'Y' OR P.USER_ID = :userId)
   AND S.USE_YN = 'Y';

-- [HOME_SCENARIO_TABLE_COUNT]
SELECT COUNT(*)
  FROM "INIT$_TB_TABLES" T
  JOIN "INIT$_TB_PROJECT" P ON P.PROJECT_ID = T.PROJECT_ID
 WHERE (:includeAllUsers = 'Y' OR P.USER_ID = :userId)
   AND T.USE_YN = 'Y';

-- [HOME_DATA_JOB_COUNT]
SELECT COUNT(*)
  FROM "INIT$_TB_DATA_WORK_JOB" J
  JOIN "INIT$_TB_PROJECT" P ON P.PROJECT_ID = J.PROJECT_ID
 WHERE (:includeAllUsers = 'Y' OR P.USER_ID = :userId)
   AND J.USE_YN = 'Y';

-- [HOME_DATA_RUN_COUNT]
SELECT COUNT(*)
  FROM "INIT$_TB_DATA_WORK_RUN" R
  JOIN "INIT$_TB_DATA_WORK_JOB" J ON J.WORK_JOB_ID = R.WORK_JOB_ID
  JOIN "INIT$_TB_PROJECT" P ON P.PROJECT_ID = J.PROJECT_ID
 WHERE (:includeAllUsers = 'Y' OR P.USER_ID = :userId);

-- [HOME_FLOW_COUNT]
SELECT COUNT(*)
  FROM "INIT$_TB_FLOW_WORK" F
  JOIN "INIT$_TB_PROJECT" P ON P.PROJECT_ID = F.PROJECT_ID
 WHERE (:includeAllUsers = 'Y' OR P.USER_ID = :userId)
   AND F.USE_YN = 'Y';

-- [HOME_FLOW_RUN_COUNT]
SELECT COUNT(*)
  FROM "INIT$_TB_FLOW_WORK_RUN" R
  JOIN "INIT$_TB_FLOW_WORK" F ON F.FLOW_ID = R.FLOW_ID
  JOIN "INIT$_TB_PROJECT" P ON P.PROJECT_ID = F.PROJECT_ID
 WHERE (:includeAllUsers = 'Y' OR P.USER_ID = :userId);

-- [HOME_PREDICTED_COLUMN_COUNT]
SELECT COUNT(*)
  FROM "INIT$_TB_PREDICTED_TYPE";

-- [HOME_CORRELATION_PAIR_COUNT]
SELECT COUNT(*)
  FROM "INIT$_TB_CAT_CORR_PAIR";

-- [HOME_SELECTED_CORRELATION_COUNT]
SELECT COUNT(*)
  FROM "INIT$_TB_CAT_CORR_SUMMARY"
 WHERE SELECTED_YN = 'Y';

-- [HOME_RUN_STATUS]
SELECT R.STATUS
     , COUNT(*) AS CNT
  FROM "INIT$_TB_DATA_WORK_RUN" R
  JOIN "INIT$_TB_DATA_WORK_JOB" J ON J.WORK_JOB_ID = R.WORK_JOB_ID
  JOIN "INIT$_TB_PROJECT" P ON P.PROJECT_ID = J.PROJECT_ID
 WHERE (:includeAllUsers = 'Y' OR P.USER_ID = :userId)
 GROUP BY R.STATUS
 ORDER BY CNT DESC;

-- [HOME_DATA_RUN_TREND]
SELECT TO_CHAR(TRUNC(R.CREATED_AT), 'MM-DD') AS RUN_DATE
     , COUNT(*) AS CNT
  FROM "INIT$_TB_DATA_WORK_RUN" R
  JOIN "INIT$_TB_DATA_WORK_JOB" J ON J.WORK_JOB_ID = R.WORK_JOB_ID
  JOIN "INIT$_TB_PROJECT" P ON P.PROJECT_ID = J.PROJECT_ID
 WHERE (:includeAllUsers = 'Y' OR P.USER_ID = :userId)
   AND R.CREATED_AT >= TRUNC(SYSDATE) - 6
 GROUP BY TRUNC(R.CREATED_AT)
 ORDER BY TRUNC(R.CREATED_AT);

-- [HOME_RULE_RUN_TREND]
WITH DAYS AS (
    SELECT TRUNC(SYSDATE) - 6 + LEVEL - 1 AS RUN_DAY
      FROM DUAL
   CONNECT BY LEVEL <= 7
),
MENUS AS (
    SELECT 'M03001' AS MENU_CODE, '데이터프로파일링' AS MENU_LABEL FROM DUAL
    UNION ALL
    SELECT 'M03002' AS MENU_CODE, '컬럼간상관분석' AS MENU_LABEL FROM DUAL
    UNION ALL
    SELECT 'M03003' AS MENU_CODE, '자동규칙발굴' AS MENU_LABEL FROM DUAL
    UNION ALL
    SELECT 'M03004' AS MENU_CODE, '규칙위반탐지' AS MENU_LABEL FROM DUAL
    UNION ALL
    SELECT 'M04001' AS MENU_CODE, '통합시나리오실행' AS MENU_LABEL FROM DUAL
),
STATUS_GROUPS AS (
    SELECT 'SUCCESS' AS STATUS_GROUP FROM DUAL
    UNION ALL
    SELECT 'FAILED' AS STATUS_GROUP FROM DUAL
),
COUNTS AS (
    SELECT TRUNC(CAST(R.CREATED_AT AS DATE)) AS RUN_DAY
         , J.MENU_CODE
         , CASE
               WHEN R.STATUS = 'SUCCESS' THEN 'SUCCESS'
               WHEN R.STATUS IN ('FAILED', 'SKIPPED') THEN 'FAILED'
               ELSE 'OTHER'
           END AS STATUS_GROUP
         , COUNT(*) AS CNT
     FROM "INIT$_TB_DATA_WORK_RUN" R
      JOIN "INIT$_TB_DATA_WORK_JOB" J ON J.WORK_JOB_ID = R.WORK_JOB_ID
      JOIN "INIT$_TB_PROJECT" P ON P.PROJECT_ID = J.PROJECT_ID
     WHERE (:includeAllUsers = 'Y' OR P.USER_ID = :userId)
       AND J.MENU_CODE IN ('M03001', 'M03002', 'M03003', 'M03004')
       AND R.CREATED_AT >= TRUNC(SYSDATE) - 6
     GROUP BY TRUNC(CAST(R.CREATED_AT AS DATE)),
              J.MENU_CODE,
              CASE
                  WHEN R.STATUS = 'SUCCESS' THEN 'SUCCESS'
                  WHEN R.STATUS IN ('FAILED', 'SKIPPED') THEN 'FAILED'
                  ELSE 'OTHER'
              END
    UNION ALL
    SELECT TRUNC(CAST(R.CREATED_AT AS DATE)) AS RUN_DAY
         , 'M04001' AS MENU_CODE
         , CASE
               WHEN R.STATUS = 'SUCCESS' THEN 'SUCCESS'
               WHEN R.STATUS IN ('FAILED', 'SKIPPED') THEN 'FAILED'
               ELSE 'OTHER'
           END AS STATUS_GROUP
         , COUNT(*) AS CNT
      FROM "INIT$_TB_FLOW_WORK_RUN" R
      JOIN "INIT$_TB_FLOW_WORK" F ON F.FLOW_ID = R.FLOW_ID
      JOIN "INIT$_TB_PROJECT" P ON P.PROJECT_ID = F.PROJECT_ID
     WHERE (:includeAllUsers = 'Y' OR P.USER_ID = :userId)
       AND F.MENU_CODE = 'M04001'
       AND R.CREATED_AT >= TRUNC(SYSDATE) - 6
     GROUP BY TRUNC(CAST(R.CREATED_AT AS DATE)),
              CASE
                  WHEN R.STATUS = 'SUCCESS' THEN 'SUCCESS'
                  WHEN R.STATUS IN ('FAILED', 'SKIPPED') THEN 'FAILED'
                  ELSE 'OTHER'
              END
)
SELECT TO_CHAR(D.RUN_DAY, 'MM-DD') AS RUN_DATE
     , M.MENU_CODE
     , M.MENU_LABEL
     , S.STATUS_GROUP
     , NVL(C.CNT, 0) AS CNT
  FROM DAYS D
 CROSS JOIN MENUS M
 CROSS JOIN STATUS_GROUPS S
  LEFT JOIN COUNTS C
    ON C.RUN_DAY = D.RUN_DAY
   AND C.MENU_CODE = M.MENU_CODE
   AND C.STATUS_GROUP = S.STATUS_GROUP
 ORDER BY D.RUN_DAY, M.MENU_CODE, S.STATUS_GROUP;

-- [HOME_FLOW_RUN_TREND]
WITH DAYS AS (
    SELECT TRUNC(SYSDATE) - 6 + LEVEL - 1 AS RUN_DAY
      FROM DUAL
   CONNECT BY LEVEL <= 7
),
STATUS_GROUPS AS (
    SELECT 'SUCCESS' AS STATUS_GROUP FROM DUAL
    UNION ALL
    SELECT 'FAILED' AS STATUS_GROUP FROM DUAL
),
COUNTS AS (
    SELECT TRUNC(CAST(R.CREATED_AT AS DATE)) AS RUN_DAY
         , CASE
               WHEN R.STATUS = 'SUCCESS' THEN 'SUCCESS'
               WHEN R.STATUS IN ('FAILED', 'SKIPPED') THEN 'FAILED'
               ELSE 'OTHER'
           END AS STATUS_GROUP
         , COUNT(*) AS CNT
      FROM "INIT$_TB_FLOW_WORK_RUN" R
      JOIN "INIT$_TB_FLOW_WORK" F ON F.FLOW_ID = R.FLOW_ID
      JOIN "INIT$_TB_PROJECT" P ON P.PROJECT_ID = F.PROJECT_ID
     WHERE (:includeAllUsers = 'Y' OR P.USER_ID = :userId)
       AND F.MENU_CODE = 'M04001'
       AND R.CREATED_AT >= TRUNC(SYSDATE) - 6
     GROUP BY TRUNC(CAST(R.CREATED_AT AS DATE)),
              CASE
                  WHEN R.STATUS = 'SUCCESS' THEN 'SUCCESS'
                  WHEN R.STATUS IN ('FAILED', 'SKIPPED') THEN 'FAILED'
                  ELSE 'OTHER'
              END
)
SELECT TO_CHAR(D.RUN_DAY, 'MM-DD') AS RUN_DATE
     , S.STATUS_GROUP
     , NVL(C.CNT, 0) AS CNT
  FROM DAYS D
 CROSS JOIN STATUS_GROUPS S
  LEFT JOIN COUNTS C
    ON C.RUN_DAY = D.RUN_DAY
   AND C.STATUS_GROUP = S.STATUS_GROUP
 ORDER BY D.RUN_DAY, S.STATUS_GROUP;

-- [HOME_RECENT_FLOW_RUNS]
SELECT *
  FROM (
    SELECT R.FLOW_RUN_ID
         , R.FLOW_ID
         , F.FLOW_NAME
         , F.FLOW_GROUP
         , F.PROJECT_ID
         , F.SCENARIO_ID
         , R.RUN_TYPE
         , R.STATUS
         , R.MESSAGE
         , R.STARTED_AT
         , R.FINISHED_AT
         , R.CREATED_AT
         , (SELECT COUNT(*)
              FROM "INIT$_TB_FLOW_WORK_NODE_RUN" NR
             WHERE NR.FLOW_RUN_ID = R.FLOW_RUN_ID) AS NODE_COUNT
         , (SELECT COUNT(*)
              FROM "INIT$_TB_FLOW_WORK_NODE_RUN" NR
             WHERE NR.FLOW_RUN_ID = R.FLOW_RUN_ID
               AND NR.STATUS = 'SUCCESS') AS SUCCESS_NODE_COUNT
         , (SELECT COUNT(*)
              FROM "INIT$_TB_FLOW_WORK_NODE_RUN" NR
             WHERE NR.FLOW_RUN_ID = R.FLOW_RUN_ID
               AND NR.STATUS IN ('FAILED', 'SKIPPED')) AS FAILED_NODE_COUNT
      FROM "INIT$_TB_FLOW_WORK_RUN" R
      JOIN "INIT$_TB_FLOW_WORK" F ON F.FLOW_ID = R.FLOW_ID
      JOIN "INIT$_TB_PROJECT" P ON P.PROJECT_ID = F.PROJECT_ID
     WHERE (:includeAllUsers = 'Y' OR P.USER_ID = :userId)
       AND F.MENU_CODE = 'M04001'
     ORDER BY R.FLOW_RUN_ID DESC
  )
 WHERE ROWNUM <= :limit;

-- [HOME_FLOW_RUN_NODES]
SELECT NR.FLOW_NODE_RUN_ID
     , NR.FLOW_RUN_ID
     , NR.FLOW_ID
     , NR.NODE_KEY
     , NR.NODE_NAME
     , NR.NODE_TYPE
     , NR.RUN_LEVEL
     , NR.SORT_ORDER
     , NR.STATUS
     , NR.MESSAGE
     , FN.NODE_DESC
     , FN.REF_MENU_CODE
     , FN.REF_WORK_JOB_ID
     , J.JOB_GROUP
     , J.JOB_NAME
     , J.JOB_DESC
     , J.EXEC_SOURCE_TYPE
     , J.EXEC_OBJECT_TYPE
     , J.EXEC_OBJECT_NAME
     , J.EXEC_OBJECT_LABEL
     , J.PARAM_JSON AS JOB_PARAM_JSON
     , NR.RUNTIME_PARAM_JSON
     , NR.NODE_PAYLOAD_JSON
     , NR.RUN_OUTPUT_JSON
     , NR.STARTED_AT
     , NR.FINISHED_AT
     , NR.CREATED_AT
     , NR.UPDATED_AT
  FROM "INIT$_TB_FLOW_WORK_NODE_RUN" NR
  JOIN "INIT$_TB_FLOW_WORK_RUN" R ON R.FLOW_RUN_ID = NR.FLOW_RUN_ID
  JOIN "INIT$_TB_FLOW_WORK" F ON F.FLOW_ID = R.FLOW_ID
  JOIN "INIT$_TB_PROJECT" P ON P.PROJECT_ID = F.PROJECT_ID
  LEFT JOIN "INIT$_TB_FLOW_WORK_NODE" FN
    ON FN.FLOW_ID = NR.FLOW_ID
   AND FN.NODE_KEY = NR.NODE_KEY
  LEFT JOIN "INIT$_TB_DATA_WORK_JOB" J
    ON J.WORK_JOB_ID = FN.REF_WORK_JOB_ID
 WHERE NR.FLOW_RUN_ID = :flowRunId
   AND F.MENU_CODE = 'M04001'
   AND (:includeAllUsers = 'Y' OR P.USER_ID = :userId)
 ORDER BY NR.RUN_LEVEL, NR.SORT_ORDER NULLS LAST, NR.FLOW_NODE_RUN_ID;

-- [HOME_MODEL_VIEW_SAMPLE]
SELECT *
  FROM (
        /* --DYNAMIC_SQL-- */
       )
 WHERE ROWNUM <= :limit;
