-- [HOME_EXISTING_TABLES]
SELECT TABLE_NAME
  FROM USER_TABLES
 WHERE TABLE_NAME IN (/* --TABLE_BINDS-- */);

-- [HOME_CONNECTION_COUNT]
SELECT COUNT(*)
  FROM "INIT$_TB_DB_CONNECTION"
 WHERE (:includeAllUsers = 'Y' OR USER_ID = :userId);

-- [HOME_USER_COUNT]
SELECT COUNT(*)
  FROM "INIT$_TB_USER";

-- [HOME_ACTIVE_USER_COUNT]
SELECT COUNT(*)
  FROM "INIT$_TB_USER"
 WHERE USE_YN = 'Y';

-- [HOME_CONNECTION_DETAIL]
SELECT CONNECTION_ID,
       CONNECTION_NAME,
       DB_TYPE,
       HOST,
       PORT,
       SERVICE_NAME,
       SID,
       USERNAME,
       USE_YN,
       DEFAULT_YN
  FROM "INIT$_TB_DB_CONNECTION"
 WHERE (:includeAllUsers = 'Y' OR USER_ID = :userId)
   AND CONNECTION_ID = :connectionId;

-- [HOME_NOTICE_TABLE_EXISTS]
SELECT COUNT(*)
  FROM USER_TABLES
 WHERE TABLE_NAME = 'INIT$_TB_NOTICE';

-- [HOME_ACTIVE_NOTICES]
SELECT *
  FROM (
    SELECT NOTICE_ID,
           NOTICE_TYPE,
           TITLE,
           CONTENT,
           POPUP_YN,
           PIN_YN,
           POST_START_AT,
           POST_END_AT,
           CREATED_AT
      FROM "INIT$_TB_NOTICE"
     WHERE USE_YN = 'Y'
       AND (POST_START_AT IS NULL OR POST_START_AT <= SYSTIMESTAMP)
       AND (POST_END_AT IS NULL OR POST_END_AT >= SYSTIMESTAMP)
     ORDER BY PIN_YN DESC, SORT_ORDER, CREATED_AT DESC, NOTICE_ID DESC
  )
 WHERE ROWNUM <= :limit;

-- [HOME_PROJECT_COUNT]
SELECT COUNT(*)
  FROM "INIT$_TB_PROJECT"
 WHERE (:includeAllUsers = 'Y' OR USER_ID = :userId)
   AND USE_YN = 'Y';

-- [HOME_SCENARIO_COUNT]
SELECT COUNT(*)
  FROM "INIT$_TB_SCENARIO" S
  JOIN "INIT$_TB_PROJECT" P ON P.PROJECT_ID = S.PROJECT_ID
 WHERE (:includeAllUsers = 'Y' OR P.USER_ID = :userId)
   AND S.USE_YN = 'Y';

-- [HOME_SCENARIO_TABLE_COUNT]
SELECT COUNT(*)
  FROM "INIT$_TB_TABLES" T
  JOIN "INIT$_TB_PROJECT" P ON P.PROJECT_ID = T.PROJECT_ID
 WHERE (:includeAllUsers = 'Y' OR P.USER_ID = :userId)
   AND T.USE_YN = 'Y';

-- [HOME_DATA_JOB_COUNT]
SELECT COUNT(*)
  FROM "INIT$_TB_DATA_WORK_JOB" J
  JOIN "INIT$_TB_PROJECT" P ON P.PROJECT_ID = J.PROJECT_ID
 WHERE (:includeAllUsers = 'Y' OR P.USER_ID = :userId)
   AND J.USE_YN = 'Y';

-- [HOME_DATA_RUN_COUNT]
SELECT COUNT(*)
  FROM "INIT$_TB_DATA_WORK_RUN" R
  JOIN "INIT$_TB_DATA_WORK_JOB" J ON J.WORK_JOB_ID = R.WORK_JOB_ID
  JOIN "INIT$_TB_PROJECT" P ON P.PROJECT_ID = J.PROJECT_ID
 WHERE (:includeAllUsers = 'Y' OR P.USER_ID = :userId);

-- [HOME_FLOW_COUNT]
SELECT COUNT(*)
  FROM "INIT$_TB_FLOW_WORK" F
  JOIN "INIT$_TB_PROJECT" P ON P.PROJECT_ID = F.PROJECT_ID
 WHERE (:includeAllUsers = 'Y' OR P.USER_ID = :userId)
   AND F.USE_YN = 'Y';

-- [HOME_FLOW_RUN_COUNT]
SELECT COUNT(*)
  FROM "INIT$_TB_FLOW_WORK_RUN" R
  JOIN "INIT$_TB_FLOW_WORK" F ON F.FLOW_ID = R.FLOW_ID
  JOIN "INIT$_TB_PROJECT" P ON P.PROJECT_ID = F.PROJECT_ID
 WHERE (:includeAllUsers = 'Y' OR P.USER_ID = :userId);

-- [HOME_PREDICTED_COLUMN_COUNT]
SELECT COUNT(*)
  FROM "INIT$_TB_PREDICTED_TYPE";

-- [HOME_CORRELATION_PAIR_COUNT]
SELECT COUNT(*)
  FROM "INIT$_TB_CAT_CORR_PAIR";

-- [HOME_SELECTED_CORRELATION_COUNT]
SELECT COUNT(*)
  FROM "INIT$_TB_CAT_CORR_SUMMARY"
 WHERE SELECTED_YN = 'Y';

-- [HOME_RUN_STATUS]
SELECT R.STATUS,
       COUNT(*) AS CNT
  FROM "INIT$_TB_DATA_WORK_RUN" R
  JOIN "INIT$_TB_DATA_WORK_JOB" J ON J.WORK_JOB_ID = R.WORK_JOB_ID
  JOIN "INIT$_TB_PROJECT" P ON P.PROJECT_ID = J.PROJECT_ID
 WHERE (:includeAllUsers = 'Y' OR P.USER_ID = :userId)
 GROUP BY R.STATUS
 ORDER BY CNT DESC;

-- [HOME_DATA_RUN_TREND]
SELECT TO_CHAR(TRUNC(R.CREATED_AT), 'MM-DD') AS RUN_DATE,
       COUNT(*) AS CNT
  FROM "INIT$_TB_DATA_WORK_RUN" R
  JOIN "INIT$_TB_DATA_WORK_JOB" J ON J.WORK_JOB_ID = R.WORK_JOB_ID
  JOIN "INIT$_TB_PROJECT" P ON P.PROJECT_ID = J.PROJECT_ID
 WHERE (:includeAllUsers = 'Y' OR P.USER_ID = :userId)
   AND R.CREATED_AT >= TRUNC(SYSDATE) - 6
 GROUP BY TRUNC(R.CREATED_AT)
 ORDER BY TRUNC(R.CREATED_AT);

-- [HOME_RULE_RUN_TREND]
WITH DAYS AS (
    SELECT TRUNC(SYSDATE) - 6 + LEVEL - 1 AS RUN_DAY
      FROM DUAL
   CONNECT BY LEVEL <= 7
),
MENUS AS (
    SELECT 'M03003' AS MENU_CODE, '자동규칙발굴' AS MENU_LABEL FROM DUAL
    UNION ALL
    SELECT 'M03004' AS MENU_CODE, '규칙위반탐지' AS MENU_LABEL FROM DUAL
    UNION ALL
    SELECT 'M04001' AS MENU_CODE, '통합시나리오실행' AS MENU_LABEL FROM DUAL
),
COUNTS AS (
    SELECT TRUNC(CAST(R.CREATED_AT AS DATE)) AS RUN_DAY,
           J.MENU_CODE,
           COUNT(*) AS CNT
      FROM "INIT$_TB_DATA_WORK_RUN" R
      JOIN "INIT$_TB_DATA_WORK_JOB" J ON J.WORK_JOB_ID = R.WORK_JOB_ID
      JOIN "INIT$_TB_PROJECT" P ON P.PROJECT_ID = J.PROJECT_ID
     WHERE (:includeAllUsers = 'Y' OR P.USER_ID = :userId)
       AND J.MENU_CODE IN ('M03003', 'M03004')
       AND R.CREATED_AT >= TRUNC(SYSDATE) - 6
     GROUP BY TRUNC(CAST(R.CREATED_AT AS DATE)), J.MENU_CODE
    UNION ALL
    SELECT TRUNC(CAST(R.CREATED_AT AS DATE)) AS RUN_DAY,
           'M04001' AS MENU_CODE,
           COUNT(*) AS CNT
      FROM "INIT$_TB_FLOW_WORK_RUN" R
      JOIN "INIT$_TB_FLOW_WORK" F ON F.FLOW_ID = R.FLOW_ID
      JOIN "INIT$_TB_PROJECT" P ON P.PROJECT_ID = F.PROJECT_ID
     WHERE (:includeAllUsers = 'Y' OR P.USER_ID = :userId)
       AND F.MENU_CODE = 'M04001'
       AND R.CREATED_AT >= TRUNC(SYSDATE) - 6
     GROUP BY TRUNC(CAST(R.CREATED_AT AS DATE))
)
SELECT TO_CHAR(D.RUN_DAY, 'MM-DD') AS RUN_DATE,
       M.MENU_CODE,
       M.MENU_LABEL,
       NVL(C.CNT, 0) AS CNT
  FROM DAYS D
 CROSS JOIN MENUS M
  LEFT JOIN COUNTS C
    ON C.RUN_DAY = D.RUN_DAY
   AND C.MENU_CODE = M.MENU_CODE
 ORDER BY D.RUN_DAY, M.MENU_CODE;
