-- [M02001_PROJECT_OWNER_CONTEXT]
SELECT P.PROJECT_ID
     , P.USER_ID
     , P.PROJECT_CODE
  FROM INIT$_TB_PROJECT P
 WHERE P.PROJECT_ID = :projectId
   AND P.PROJECT_CODE = :projectCode
   AND P.USE_YN = 'Y'
;

-- [M02001_PROJECT_OWNER_LOGIN]
SELECT U.USER_ID
     , U.LOGIN_ID
  FROM INIT$_TB_USER U
 WHERE U.USER_ID = :userId
   AND U.USE_YN = 'Y'
;

-- [M02001_UPLOAD_TABLE_TREE]
SELECT SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA') AS OWNER
     , T.TABLE_NAME
     , C.COMMENTS
     , T.NUM_ROWS
     , T.LAST_ANALYZED
  FROM USER_TABLES T
  LEFT OUTER JOIN USER_TAB_COMMENTS C
    ON C.TABLE_NAME = T.TABLE_NAME
 WHERE T.TABLE_NAME LIKE :tablePrefix || '%'
   AND T.TABLE_NAME NOT LIKE 'BIN$%'
   AND T.NESTED = 'NO'
   AND T.SECONDARY = 'N'
 ORDER BY T.TABLE_NAME
;

-- [M02001_UPLOAD_TABLE_COLUMNS]
SELECT SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA') AS OWNER
     , C.TABLE_NAME AS TABLE_ID
     , T.COMMENTS AS TABLE_COMMENT
     , C.COLUMN_ID
     , C.COLUMN_NAME AS COLUMN_NAME
     , C.DATA_TYPE
     , C.DATA_LENGTH
     , C.NULLABLE
     , C.DATA_DEFAULT
     , CC.COMMENTS AS COLUMN_COMMENT
  FROM USER_TAB_COLUMNS C
  LEFT OUTER JOIN USER_TAB_COMMENTS T
    ON T.TABLE_NAME = C.TABLE_NAME
  LEFT OUTER JOIN USER_COL_COMMENTS CC
    ON CC.TABLE_NAME = C.TABLE_NAME
   AND CC.COLUMN_NAME = C.COLUMN_NAME
 WHERE C.TABLE_NAME = :tableName
 ORDER BY C.COLUMN_ID
;

-- [M02001_UPLOAD_TABLE_DATA_COUNT]
SELECT COUNT(*) AS TOTAL_COUNT
  FROM /* --DYNAMIC_TABLE-- */
;

-- [M02001_UPLOAD_TABLE_DATA_PAGE]
SELECT *
  FROM /* --DYNAMIC_TABLE-- */
 ORDER BY ROWID
 OFFSET :offset ROWS FETCH NEXT :limit ROWS ONLY
;

-- [M02001_SQL_WORKSHEET_COUNT]
SELECT COUNT(*) AS TOTAL_COUNT
  FROM (
/* --DYNAMIC_SQL-- */
  )
;

-- [M02001_SQL_WORKSHEET_PAGE]
SELECT *
  FROM (
/* --DYNAMIC_SQL-- */
  )
 OFFSET :offset ROWS FETCH NEXT :limit ROWS ONLY
;
