
-- [M02002_TABLE_TREE]
WITH REGISTERED_TABLES AS (
    SELECT DISTINCT ST.OWNER_NAME
         , ST.TABLE_NAME
      FROM INIT$_TB_TABLES ST
     WHERE ST.PROJECT_ID = :projectId
       AND (:scenarioId IS NULL OR ST.SCENARIO_ID = :scenarioId)
    UNION
    SELECT DISTINCT ST.EDIT_OWNER_NAME AS OWNER_NAME
         , ST.EDIT_TABLE_NAME AS TABLE_NAME
      FROM INIT$_TB_TABLES ST
     WHERE ST.PROJECT_ID = :projectId
       AND (:scenarioId IS NULL OR ST.SCENARIO_ID = :scenarioId)
       AND ST.EDIT_OWNER_NAME IS NOT NULL
       AND ST.EDIT_TABLE_NAME IS NOT NULL
)
, IMPORTED_ORIGINAL_TABLES AS (
    SELECT DISTINCT ST.ORIGINAL_OWNER_NAME AS OWNER_NAME
         , ST.ORIGINAL_TABLE_NAME AS TABLE_NAME
      FROM INIT$_TB_TABLES ST
     WHERE ST.PROJECT_ID = :projectId
       AND (:scenarioId IS NULL OR ST.SCENARIO_ID = :scenarioId)
       AND ST.TABLE_NAME LIKE 'INITUP$%'
       AND ST.ORIGINAL_OWNER_NAME IS NOT NULL
       AND ST.ORIGINAL_TABLE_NAME IS NOT NULL
       AND (
              ST.ORIGINAL_OWNER_NAME <> ST.OWNER_NAME
           OR ST.ORIGINAL_TABLE_NAME <> ST.TABLE_NAME
       )
)
, PROJECT_UPLOAD_TABLES AS (
    SELECT UM.OWNER_NAME
         , UM.TABLE_NAME
         , UM.FILE_EXTENSION
         , UM.FILE_NAME
         , UM.FILE_SIZE
      FROM "INIT$_TB_UPLOAD_TABLE_META" UM
     WHERE UM.PROJECT_ID = :projectId
)
, PROJECT_MANAGED_TABLES AS (
    SELECT UM.OWNER_NAME
         , UM.TABLE_NAME
      FROM "INIT$_TB_UPLOAD_TABLE_META" UM
     WHERE UM.PROJECT_ID = :projectId
       AND UM.TABLE_NAME LIKE 'INITUP$%'
    UNION
    SELECT UM.OWNER_NAME
         , 'INITDN$' || SUBSTR(UM.TABLE_NAME, LENGTH('INITUP$') + 1) AS TABLE_NAME
      FROM "INIT$_TB_UPLOAD_TABLE_META" UM
     WHERE UM.PROJECT_ID = :projectId
       AND UM.TABLE_NAME LIKE 'INITUP$%'
    UNION
    SELECT ST.OWNER_NAME
         , ST.TABLE_NAME
      FROM INIT$_TB_TABLES ST
     WHERE ST.PROJECT_ID = :projectId
       AND ST.TABLE_NAME LIKE 'INITUP$%'
    UNION
    SELECT ST.EDIT_OWNER_NAME AS OWNER_NAME
         , ST.EDIT_TABLE_NAME AS TABLE_NAME
      FROM INIT$_TB_TABLES ST
     WHERE ST.PROJECT_ID = :projectId
       AND ST.EDIT_OWNER_NAME IS NOT NULL
       AND ST.EDIT_TABLE_NAME LIKE 'INITDN$%'
)
, BASE_TABLES AS (
    SELECT T.OWNER
         , T.TABLE_NAME
         , T.NESTED
         , T.SECONDARY
         , C.COMMENTS
      FROM ALL_TABLES T
      LEFT JOIN ALL_TAB_COMMENTS C
        ON C.OWNER = T.OWNER
       AND C.TABLE_NAME = T.TABLE_NAME
     WHERE T.NESTED = 'NO'
       AND T.SECONDARY = 'N'
       AND T.TABLE_NAME NOT LIKE 'BIN$%'
       AND (:ownerPattern IS NULL OR T.OWNER LIKE :ownerPattern)
       AND (:excludePattern1 IS NULL OR T.TABLE_NAME NOT LIKE :excludePattern1)
       AND (:excludePattern2 IS NULL OR T.TABLE_NAME NOT LIKE :excludePattern2)
       AND (:excludePattern3 IS NULL OR T.TABLE_NAME NOT LIKE :excludePattern3)
       AND (:excludePattern4 IS NULL OR T.TABLE_NAME NOT LIKE :excludePattern4)
       AND (:excludePattern5 IS NULL OR T.TABLE_NAME NOT LIKE :excludePattern5)
       AND (
              :keyword IS NULL
           OR UPPER(T.OWNER) LIKE :keyword
           OR UPPER(T.TABLE_NAME) LIKE :keyword
           OR UPPER(C.COMMENTS) LIKE :keyword
       )
)
, TABLE_CANDIDATES AS (
    SELECT B.OWNER
         , B.TABLE_NAME
         , B.NESTED
         , B.SECONDARY
         , B.COMMENTS
         , PUT.FILE_EXTENSION AS ORIGINAL_FILE_EXTENSION
         , PUT.FILE_NAME AS ORIGINAL_FILE_NAME
         , PUT.FILE_SIZE AS ORIGINAL_FILE_SIZE
      FROM BASE_TABLES B
      LEFT JOIN PROJECT_UPLOAD_TABLES PUT
        ON PUT.OWNER_NAME = B.OWNER
       AND PUT.TABLE_NAME = B.TABLE_NAME
      JOIN PROJECT_MANAGED_TABLES PMT
        ON PMT.OWNER_NAME = B.OWNER
       AND PMT.TABLE_NAME = B.TABLE_NAME
     WHERE (B.TABLE_NAME LIKE 'INITUP$%' OR B.TABLE_NAME LIKE 'INITDN$%')
    UNION ALL
    SELECT B.OWNER
         , B.TABLE_NAME
         , B.NESTED
         , B.SECONDARY
         , B.COMMENTS
         , CAST(NULL AS VARCHAR2(20)) AS ORIGINAL_FILE_EXTENSION
         , CAST(NULL AS VARCHAR2(500)) AS ORIGINAL_FILE_NAME
         , CAST(NULL AS NUMBER) AS ORIGINAL_FILE_SIZE
      FROM BASE_TABLES B
     WHERE B.TABLE_NAME NOT LIKE 'INITUP$%'
       AND B.TABLE_NAME NOT LIKE 'INITDN$%'
)
SELECT OWNER
     , TABLE_NAME
     , COMMENTS
     , IS_REGISTERED
     , IS_MANAGED_SOURCE
     , ORIGINAL_FILE_EXTENSION
     , ORIGINAL_FILE_NAME
     , ORIGINAL_FILE_SIZE
  FROM (
    SELECT T.OWNER
         , T.TABLE_NAME
         , T.COMMENTS
         , T.ORIGINAL_FILE_EXTENSION
         , T.ORIGINAL_FILE_NAME
         , T.ORIGINAL_FILE_SIZE
         , CASE
               WHEN RT.TABLE_NAME IS NOT NULL
               THEN 'Y'
               ELSE 'N'
           END AS IS_REGISTERED
         , CASE
               WHEN T.TABLE_NAME LIKE 'INITUP$%'
                AND EXISTS (
                    SELECT 1
                      FROM ALL_TAB_COLUMNS TC
                     WHERE TC.OWNER = T.OWNER
                       AND TC.TABLE_NAME = T.TABLE_NAME
                       AND TC.COLUMN_NAME = 'FILE_ROW_NO'
                )
               THEN 'Y'
               ELSE 'N'
           END AS IS_MANAGED_SOURCE
         , ROW_NUMBER() OVER (ORDER BY T.OWNER, T.TABLE_NAME) AS RN
      FROM TABLE_CANDIDATES T
      LEFT JOIN REGISTERED_TABLES RT
        ON RT.OWNER_NAME = T.OWNER
       AND RT.TABLE_NAME = T.TABLE_NAME
      LEFT JOIN IMPORTED_ORIGINAL_TABLES IOT
        ON IOT.OWNER_NAME = T.OWNER
       AND IOT.TABLE_NAME = T.TABLE_NAME
     WHERE IOT.TABLE_NAME IS NULL
       AND (
              :registeredOnly = 'N'
           OR RT.TABLE_NAME IS NOT NULL
           )
  )
 WHERE RN > :offset
   AND RN <= :endRow
 ORDER BY RN
;

-- [M02002_TABLE_INFO]
SELECT T.OWNER
     , T.TABLE_NAME
     , C.COMMENTS
     , (
         SELECT MAX(ST.ORIGINAL_OWNER_NAME)
           FROM INIT$_TB_TABLES ST
          WHERE ST.OWNER_NAME = T.OWNER
            AND ST.TABLE_NAME = T.TABLE_NAME
            AND ST.DATA_ORIGIN_TYPE = 'DB_TABLE_IMPORT'
            AND (:projectId IS NULL OR ST.PROJECT_ID = :projectId)
            AND (:scenarioId IS NULL OR ST.SCENARIO_ID = :scenarioId)
       ) AS ORIGINAL_OWNER_NAME
     , (
         SELECT MAX(ST.ORIGINAL_TABLE_NAME)
           FROM INIT$_TB_TABLES ST
          WHERE ST.OWNER_NAME = T.OWNER
            AND ST.TABLE_NAME = T.TABLE_NAME
            AND ST.DATA_ORIGIN_TYPE = 'DB_TABLE_IMPORT'
            AND (:projectId IS NULL OR ST.PROJECT_ID = :projectId)
            AND (:scenarioId IS NULL OR ST.SCENARIO_ID = :scenarioId)
       ) AS ORIGINAL_TABLE_NAME
     , TO_CHAR(O.CREATED, 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT
     , T.NUM_ROWS
     , T.LAST_ANALYZED
  FROM ALL_TABLES T
  LEFT JOIN ALL_TAB_COMMENTS C
    ON C.OWNER = T.OWNER
   AND C.TABLE_NAME = T.TABLE_NAME
  LEFT JOIN ALL_OBJECTS O
    ON O.OWNER = T.OWNER
   AND O.OBJECT_NAME = T.TABLE_NAME
   AND O.OBJECT_TYPE = 'TABLE'
 WHERE T.OWNER = :owner
   AND T.TABLE_NAME = :tableName
;

-- [M02002_TABLE_COLUMNS]
SELECT C.OWNER
     , C.TABLE_NAME AS TABLE_ID
     , TC.COMMENTS AS TABLE_COMMENT
     , C.COLUMN_ID
     , C.COLUMN_NAME
     , CC.COMMENTS AS COLUMN_COMMENT
     , C.DATA_TYPE
     , C.DATA_LENGTH
     , C.CHAR_LENGTH
     , C.DATA_PRECISION
     , C.DATA_SCALE
     , C.NULLABLE
     , C.DATA_DEFAULT
     , CASE
        WHEN PK.COLUMN_NAME IS NOT NULL THEN 'Y'
        ELSE 'N'
    END AS PRIMARY_KEY_YN
     , C.NUM_DISTINCT
     , C.NUM_NULLS
     , C.DENSITY
     , C.LAST_ANALYZED
  FROM ALL_TAB_COLUMNS C
  LEFT JOIN ALL_TAB_COMMENTS TC
    ON TC.OWNER = C.OWNER
   AND TC.TABLE_NAME = C.TABLE_NAME
  LEFT JOIN ALL_COL_COMMENTS CC
    ON CC.OWNER = C.OWNER
   AND CC.TABLE_NAME = C.TABLE_NAME
   AND CC.COLUMN_NAME = C.COLUMN_NAME
  LEFT JOIN (
        SELECT ACC.OWNER, ACC.TABLE_NAME, ACC.COLUMN_NAME
          FROM ALL_CONSTRAINTS AC
          JOIN ALL_CONS_COLUMNS ACC
            ON ACC.OWNER = AC.OWNER
           AND ACC.CONSTRAINT_NAME = AC.CONSTRAINT_NAME
         WHERE AC.CONSTRAINT_TYPE = 'P'
  ) PK
    ON PK.OWNER = C.OWNER
   AND PK.TABLE_NAME = C.TABLE_NAME
   AND PK.COLUMN_NAME = C.COLUMN_NAME
 WHERE C.OWNER = :owner
   AND C.TABLE_NAME = :tableName
 ORDER BY C.COLUMN_ID
;

-- [M02002_TABLE_DATA_COUNT]
SELECT COUNT(*) AS TOTAL_COUNT
  FROM /* --DYNAMIC_TABLE-- */
;

-- [M02002_TABLE_DATA_PAGE]
SELECT *
  FROM /* --DYNAMIC_TABLE-- */
 ORDER BY ROWID
 OFFSET :offset ROWS
 FETCH NEXT :limit ROWS ONLY
;

-- [M02002_SQL_WORKSHEET_COUNT]
SELECT COUNT(*) AS TOTAL_COUNT
  FROM (
/* --DYNAMIC_SQL-- */
  )
;

-- [M02002_SQL_WORKSHEET_PAGE]
SELECT *
  FROM (
/* --DYNAMIC_SQL-- */
  )
 OFFSET :offset ROWS
 FETCH NEXT :limit ROWS ONLY
;

-- [M02002_SCENARIO_TABLE_LIST]
SELECT ST.SCENARIO_TABLE_ID
     , ST.PROJECT_ID
     , ST.SCENARIO_ID
     , ST.OWNER_NAME
     , ST.TABLE_NAME
     , ST.ORIGINAL_OWNER_NAME
     , ST.ORIGINAL_TABLE_NAME
     , ST.EDIT_OWNER_NAME
     , ST.EDIT_TABLE_NAME
     , ST.DATA_ORIGIN_TYPE
     , ST.CASE_ID_COLUMN
     , ST.IMPORTED_AT
     , ST.TABLE_COMMENT
     , ST.USE_YN
     , ST.SORT_ORDER
     , ST.CREATED_AT
     , ST.UPDATED_AT
     , SC.COMMENTS AS SOURCE_TABLE_COMMENT
     , TO_CHAR(SO.CREATED, 'YYYY-MM-DD HH24:MI:SS') AS SOURCE_CREATED_AT
     , CASE
           WHEN EO.OBJECT_NAME IS NOT NULL THEN 'Y'
           ELSE 'N'
       END AS EDIT_TABLE_EXISTS
     , EC.COMMENTS AS EDIT_TABLE_COMMENT
     , TO_CHAR(EO.CREATED, 'YYYY-MM-DD HH24:MI:SS') AS EDIT_CREATED_AT
     , OC.COMMENTS AS ORIGINAL_TABLE_COMMENT
     , TO_CHAR(OO.CREATED, 'YYYY-MM-DD HH24:MI:SS') AS ORIGINAL_CREATED_AT
     , UM.FILE_EXTENSION AS ORIGINAL_FILE_EXTENSION
     , UM.FILE_NAME AS ORIGINAL_FILE_NAME
     , UM.FILE_SIZE AS ORIGINAL_FILE_SIZE
  FROM INIT$_TB_TABLES ST
  LEFT JOIN "INIT$_TB_UPLOAD_TABLE_META" UM
    ON UM.OWNER_NAME = ST.OWNER_NAME
   AND UM.TABLE_NAME = ST.TABLE_NAME
  LEFT JOIN ALL_TAB_COMMENTS SC
    ON SC.OWNER = ST.OWNER_NAME
   AND SC.TABLE_NAME = ST.TABLE_NAME
  LEFT JOIN ALL_OBJECTS SO
    ON SO.OWNER = ST.OWNER_NAME
   AND SO.OBJECT_NAME = ST.TABLE_NAME
   AND SO.OBJECT_TYPE = 'TABLE'
  LEFT JOIN ALL_TAB_COMMENTS EC
    ON EC.OWNER = ST.EDIT_OWNER_NAME
   AND EC.TABLE_NAME = ST.EDIT_TABLE_NAME
  LEFT JOIN ALL_OBJECTS EO
    ON EO.OWNER = ST.EDIT_OWNER_NAME
   AND EO.OBJECT_NAME = ST.EDIT_TABLE_NAME
   AND EO.OBJECT_TYPE = 'TABLE'
  LEFT JOIN ALL_TAB_COMMENTS OC
    ON OC.OWNER = ST.ORIGINAL_OWNER_NAME
   AND OC.TABLE_NAME = ST.ORIGINAL_TABLE_NAME
  LEFT JOIN ALL_OBJECTS OO
    ON OO.OWNER = ST.ORIGINAL_OWNER_NAME
   AND OO.OBJECT_NAME = ST.ORIGINAL_TABLE_NAME
   AND OO.OBJECT_TYPE = 'TABLE'
 WHERE ST.PROJECT_ID = :projectId
   AND (:scenarioId IS NULL OR ST.SCENARIO_ID = :scenarioId)
 ORDER BY ST.SORT_ORDER NULLS LAST, ST.OWNER_NAME, ST.TABLE_NAME, ST.SCENARIO_TABLE_ID
;

-- [M02002_UPLOAD_TABLE_META_EXISTS]
SELECT COUNT(*) AS TABLE_COUNT
  FROM USER_TABLES
 WHERE TABLE_NAME = 'INIT$_TB_UPLOAD_TABLE_META'
;

-- [M02002_UPLOAD_TABLE_META_CREATE]
CREATE TABLE "INIT$_TB_UPLOAD_TABLE_META" (
    "OWNER_NAME" VARCHAR2(128 BYTE) NOT NULL ENABLE
  , "TABLE_NAME" VARCHAR2(128 BYTE) NOT NULL ENABLE
  , "PROJECT_ID" NUMBER
  , "FILE_EXTENSION" VARCHAR2(20 BYTE)
  , "FILE_NAME" VARCHAR2(500 BYTE)
  , "FILE_SIZE" NUMBER
  , "CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE
  , "UPDATED_AT" TIMESTAMP (6)
  , CONSTRAINT "PK_INIT$_TB_UPLOAD_TABLE_META" PRIMARY KEY ("OWNER_NAME", "TABLE_NAME")
)
;

-- [M02002_UPLOAD_TABLE_META_PROJECT_EXISTS]
SELECT COUNT(*) AS COLUMN_COUNT
  FROM USER_TAB_COLUMNS
 WHERE TABLE_NAME = 'INIT$_TB_UPLOAD_TABLE_META'
   AND COLUMN_NAME = 'PROJECT_ID'
;

-- [M02002_UPLOAD_TABLE_META_PROJECT_ADD]
ALTER TABLE "INIT$_TB_UPLOAD_TABLE_META"
  ADD ("PROJECT_ID" NUMBER)
;

-- [M02002_SCENARIO_TABLE_INSERT]
INSERT INTO INIT$_TB_TABLES (
    PROJECT_ID
  , SCENARIO_ID
  , OWNER_NAME
  , TABLE_NAME
  , ORIGINAL_OWNER_NAME
  , ORIGINAL_TABLE_NAME
  , EDIT_OWNER_NAME
  , EDIT_TABLE_NAME
  , DATA_ORIGIN_TYPE
  , CASE_ID_COLUMN
  , IMPORTED_AT
  , TABLE_COMMENT
  , USE_YN
  , SORT_ORDER
  , CREATED_AT
) VALUES (
    :projectId
  , :scenarioId
  , :ownerName
  , :tableName
  , :originalOwnerName
  , :originalTableName
  , :editOwnerName
  , :editTableName
  , :dataOriginType
  , :caseIdColumn
  , CASE WHEN :dataOriginType = 'DB_TABLE_IMPORT' THEN SYSTIMESTAMP END
  , :tableComment
  , :useYn
  , :sortOrder
  , SYSTIMESTAMP
)
;

-- [M02002_SCENARIO_TABLE_BY_ORIGINAL]
SELECT SCENARIO_TABLE_ID
     , OWNER_NAME
     , TABLE_NAME
     , EDIT_OWNER_NAME
     , EDIT_TABLE_NAME
  FROM INIT$_TB_TABLES
 WHERE PROJECT_ID = :projectId
   AND SCENARIO_ID = :scenarioId
   AND (
          (
              ORIGINAL_OWNER_NAME = :originalOwnerName
            AND ORIGINAL_TABLE_NAME = :originalTableName
          )
       OR (
              OWNER_NAME = :originalOwnerName
            AND TABLE_NAME = :originalTableName
            AND DATA_ORIGIN_TYPE = 'MANAGED_TABLE'
          )
       )
   AND (:scenarioTableId IS NULL OR SCENARIO_TABLE_ID <> :scenarioTableId)
;

-- [M02002_PROJECT_SCENARIO_ACCESS]
SELECT COUNT(*) AS ACCESS_COUNT
  FROM INIT$_TB_PROJECT P
  JOIN INIT$_TB_SCENARIO S
    ON S.PROJECT_ID = P.PROJECT_ID
   AND S.SCENARIO_ID = :scenarioId
 WHERE P.PROJECT_ID = :projectId
   AND (:includeAllUsers = 'Y' OR P.USER_ID = :userId)
;

-- [M02002_PROJECT_ACCESS]
SELECT COUNT(*) AS ACCESS_COUNT
  FROM INIT$_TB_PROJECT P
 WHERE P.PROJECT_ID = :projectId
   AND (:includeAllUsers = 'Y' OR P.USER_ID = :userId)
;

-- [M02002_MANAGED_TABLE_PROJECT_OWNERS]
WITH MANAGED_TABLE_PROJECTS AS (
    SELECT UM.PROJECT_ID
         , UM.OWNER_NAME
         , UM.TABLE_NAME
      FROM "INIT$_TB_UPLOAD_TABLE_META" UM
     WHERE UM.TABLE_NAME LIKE 'INITUP$%'
    UNION
    SELECT UM.PROJECT_ID
         , UM.OWNER_NAME
         , 'INITDN$' || SUBSTR(UM.TABLE_NAME, LENGTH('INITUP$') + 1) AS TABLE_NAME
      FROM "INIT$_TB_UPLOAD_TABLE_META" UM
     WHERE UM.TABLE_NAME LIKE 'INITUP$%'
    UNION
    SELECT ST.PROJECT_ID
         , ST.OWNER_NAME
         , ST.TABLE_NAME
      FROM INIT$_TB_TABLES ST
     WHERE ST.TABLE_NAME LIKE 'INITUP$%'
    UNION
    SELECT ST.PROJECT_ID
         , ST.EDIT_OWNER_NAME AS OWNER_NAME
         , ST.EDIT_TABLE_NAME AS TABLE_NAME
      FROM INIT$_TB_TABLES ST
     WHERE ST.EDIT_OWNER_NAME IS NOT NULL
       AND ST.EDIT_TABLE_NAME LIKE 'INITDN$%'
)
SELECT DISTINCT PROJECT_ID
  FROM MANAGED_TABLE_PROJECTS
 WHERE OWNER_NAME = :ownerName
   AND TABLE_NAME = :tableName
;

-- [M02002_MANAGED_TABLE_META_BACKFILL]
MERGE INTO "INIT$_TB_UPLOAD_TABLE_META" T
USING (
    SELECT DISTINCT ST.PROJECT_ID
         , ST.OWNER_NAME
         , ST.TABLE_NAME
      FROM INIT$_TB_TABLES ST
     WHERE ST.PROJECT_ID = :projectId
       AND ST.SCENARIO_ID = :scenarioId
       AND (:scenarioTableId IS NULL OR ST.SCENARIO_TABLE_ID = :scenarioTableId)
       AND ST.TABLE_NAME LIKE 'INITUP$%'
) S
   ON (T.OWNER_NAME = S.OWNER_NAME AND T.TABLE_NAME = S.TABLE_NAME)
 WHEN NOT MATCHED THEN
      INSERT (
          OWNER_NAME
        , TABLE_NAME
        , PROJECT_ID
        , CREATED_AT
      ) VALUES (
          S.OWNER_NAME
        , S.TABLE_NAME
        , S.PROJECT_ID
        , SYSTIMESTAMP
      )
;

-- [M02002_MANAGED_TABLE_META_DELETE]
DELETE FROM "INIT$_TB_UPLOAD_TABLE_META"
 WHERE PROJECT_ID = :projectId
   AND OWNER_NAME = :ownerName
   AND TABLE_NAME = :tableName
;

-- [M02002_PROJECT_CODE]
SELECT PROJECT_CODE
  FROM INIT$_TB_PROJECT
 WHERE PROJECT_ID = :projectId
;

-- [M02002_SCENARIO_TABLE_BY_ID]
SELECT SCENARIO_TABLE_ID
     , OWNER_NAME
     , TABLE_NAME
     , EDIT_OWNER_NAME
     , EDIT_TABLE_NAME
  FROM INIT$_TB_TABLES
 WHERE SCENARIO_TABLE_ID = :scenarioTableId
   AND PROJECT_ID = :projectId
   AND SCENARIO_ID = :scenarioId
;

-- [M02002_SCENARIO_TABLE_LOCK]
SELECT SCENARIO_TABLE_ID
     , OWNER_NAME
     , TABLE_NAME
     , EDIT_OWNER_NAME
     , EDIT_TABLE_NAME
  FROM INIT$_TB_TABLES
 WHERE SCENARIO_TABLE_ID = :scenarioTableId
   AND PROJECT_ID = :projectId
   AND SCENARIO_ID = :scenarioId
   FOR UPDATE
;

-- [M02002_SOURCE_TABLE_EXISTS]
SELECT COUNT(*) AS TABLE_COUNT
  FROM ALL_TABLES
 WHERE OWNER = :ownerName
   AND TABLE_NAME = :tableName
;

-- [M02002_SOURCE_TABLE_COMMENT]
SELECT COMMENTS AS TABLE_COMMENT
  FROM ALL_TAB_COMMENTS
 WHERE OWNER = :ownerName
   AND TABLE_NAME = :tableName
;

-- [M02002_SOURCE_COLUMN_COMMENTS]
SELECT C.COLUMN_NAME
     , CC.COMMENTS AS COLUMN_COMMENT
  FROM ALL_TAB_COLS C
  LEFT JOIN ALL_COL_COMMENTS CC
    ON CC.OWNER = C.OWNER
   AND CC.TABLE_NAME = C.TABLE_NAME
   AND CC.COLUMN_NAME = C.COLUMN_NAME
 WHERE C.OWNER = :ownerName
   AND C.TABLE_NAME = :tableName
   AND C.HIDDEN_COLUMN = 'NO'
   AND C.COLUMN_ID IS NOT NULL
 ORDER BY C.COLUMN_ID
;

-- [M02002_SOURCE_COLUMNS]
SELECT COLUMN_NAME
  FROM ALL_TAB_COLS
 WHERE OWNER = :ownerName
   AND TABLE_NAME = :tableName
   AND HIDDEN_COLUMN = 'NO'
   AND COLUMN_ID IS NOT NULL
 ORDER BY COLUMN_ID
;

-- [M02002_TABLE_COLUMN_MAP_MERGE]
MERGE INTO INIT$_TB_TABLE_COLUMN_MAP T
USING (
    SELECT :scenarioTableId AS SCENARIO_TABLE_ID
         , :sourceColumnName AS SOURCE_COLUMN_NAME
         , :managedColumnName AS MANAGED_COLUMN_NAME
         , :mappingType AS MAPPING_TYPE
      FROM DUAL
) S
   ON (
          T.SCENARIO_TABLE_ID = S.SCENARIO_TABLE_ID
      AND T.SOURCE_COLUMN_NAME = S.SOURCE_COLUMN_NAME
   )
 WHEN MATCHED THEN
      UPDATE
         SET T.MANAGED_COLUMN_NAME = S.MANAGED_COLUMN_NAME
           , T.MAPPING_TYPE = S.MAPPING_TYPE
 WHEN NOT MATCHED THEN
      INSERT (
          SCENARIO_TABLE_ID
        , SOURCE_COLUMN_NAME
        , MANAGED_COLUMN_NAME
        , MAPPING_TYPE
      ) VALUES (
          S.SCENARIO_TABLE_ID
        , S.SOURCE_COLUMN_NAME
        , S.MANAGED_COLUMN_NAME
        , S.MAPPING_TYPE
      )
;

-- [M02002_TABLE_COLUMN_MAP_EXISTS]
SELECT COUNT(*) AS TABLE_COUNT
  FROM USER_TABLES
 WHERE TABLE_NAME = 'INIT$_TB_TABLE_COLUMN_MAP'
;

-- [M02002_TABLE_COLUMN_MAP_CREATE]
CREATE TABLE "INIT$_TB_TABLE_COLUMN_MAP" (
    "TABLE_COLUMN_MAP_ID" NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL ENABLE
  , "SCENARIO_TABLE_ID" NUMBER NOT NULL ENABLE
  , "SOURCE_COLUMN_NAME" VARCHAR2(128 BYTE) NOT NULL ENABLE
  , "MANAGED_COLUMN_NAME" VARCHAR2(128 BYTE) NOT NULL ENABLE
  , "MAPPING_TYPE" VARCHAR2(30 BYTE) NOT NULL ENABLE
  , "CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE
  , CONSTRAINT "PK_INIT$_TB_TABLE_COL_MAP" PRIMARY KEY ("TABLE_COLUMN_MAP_ID")
  , CONSTRAINT "UK_INIT$_TB_TABLE_COL_MAP" UNIQUE ("SCENARIO_TABLE_ID", "SOURCE_COLUMN_NAME")
  , CONSTRAINT "FK_INIT$_TB_TABLE_COL_MAP" FOREIGN KEY ("SCENARIO_TABLE_ID")
        REFERENCES "INIT$_TB_TABLES" ("SCENARIO_TABLE_ID") ON DELETE CASCADE ENABLE
)
;

-- [M02002_DISABLE_PARALLEL_DML]
ALTER SESSION DISABLE PARALLEL DML
;

-- [M02002_DISABLE_PARALLEL_QUERY]
ALTER SESSION DISABLE PARALLEL QUERY
;

-- [M02002_SCENARIO_TABLE_UPDATE]
UPDATE INIT$_TB_TABLES
   SET TABLE_COMMENT = :tableComment
     , USE_YN = :useYn
     , SORT_ORDER = :sortOrder
     , UPDATED_AT = SYSTIMESTAMP
 WHERE SCENARIO_TABLE_ID = :scenarioTableId
   AND PROJECT_ID = :projectId
   AND SCENARIO_ID = :scenarioId
;

-- [M02002_SCENARIO_TABLE_MAPPING_UPDATE]
UPDATE INIT$_TB_TABLES
   SET OWNER_NAME = :ownerName
     , TABLE_NAME = :tableName
     , ORIGINAL_OWNER_NAME = :originalOwnerName
     , ORIGINAL_TABLE_NAME = :originalTableName
     , EDIT_OWNER_NAME = :editOwnerName
     , EDIT_TABLE_NAME = :editTableName
     , DATA_ORIGIN_TYPE = :dataOriginType
     , CASE_ID_COLUMN = :caseIdColumn
     , IMPORTED_AT = CASE WHEN :dataOriginType = 'DB_TABLE_IMPORT' THEN SYSTIMESTAMP END
     , TABLE_COMMENT = :tableComment
     , USE_YN = :useYn
     , SORT_ORDER = :sortOrder
     , UPDATED_AT = SYSTIMESTAMP
 WHERE SCENARIO_TABLE_ID = :scenarioTableId
   AND PROJECT_ID = :projectId
   AND SCENARIO_ID = :scenarioId
;

-- [M02002_SCENARIO_TABLE_ID_BY_KEY]
SELECT SCENARIO_TABLE_ID
  FROM INIT$_TB_TABLES
 WHERE PROJECT_ID = :projectId
   AND SCENARIO_ID = :scenarioId
   AND OWNER_NAME = :ownerName
   AND TABLE_NAME = :tableName
;

-- [M02002_SCENARIO_TABLE_DELETE]
DELETE FROM INIT$_TB_TABLES
 WHERE SCENARIO_TABLE_ID = :scenarioTableId
   AND PROJECT_ID = :projectId
   AND SCENARIO_ID = :scenarioId
;

-- [M02002_SCENARIO_TABLE_DELETE_ALL]
DELETE FROM INIT$_TB_TABLES
 WHERE PROJECT_ID = :projectId
   AND SCENARIO_ID = :scenarioId
;

-- [M02002_SCENARIO_TABLE_MANAGED_DROP_TARGET]
SELECT OWNER_NAME
     , TABLE_NAME
     , EDIT_OWNER_NAME
     , EDIT_TABLE_NAME
  FROM INIT$_TB_TABLES
 WHERE SCENARIO_TABLE_ID = :scenarioTableId
   AND PROJECT_ID = :projectId
   AND SCENARIO_ID = :scenarioId
;

-- [M02002_SCENARIO_TABLE_BY_PHYSICAL_TABLE]
SELECT SCENARIO_TABLE_ID
     , OWNER_NAME
     , TABLE_NAME
     , EDIT_OWNER_NAME
     , EDIT_TABLE_NAME
  FROM INIT$_TB_TABLES
 WHERE PROJECT_ID = :projectId
   AND SCENARIO_ID = :scenarioId
   AND (
          (OWNER_NAME = :ownerName AND TABLE_NAME = :tableName)
       OR (EDIT_OWNER_NAME = :ownerName AND EDIT_TABLE_NAME = :tableName)
   )
;

-- [M02002_MANAGED_TABLE_REFERENCE_COUNT]
SELECT COUNT(*) AS REFERENCE_COUNT
  FROM INIT$_TB_TABLES ST
 WHERE ST.SCENARIO_TABLE_ID <> :scenarioTableId
   AND (
          (ST.OWNER_NAME = :sourceOwnerName AND ST.TABLE_NAME = :sourceTableName)
       OR (ST.EDIT_OWNER_NAME = :sourceOwnerName AND ST.EDIT_TABLE_NAME = :sourceTableName)
       OR (ST.OWNER_NAME = :editOwnerName AND ST.TABLE_NAME = :editTableName)
       OR (ST.EDIT_OWNER_NAME = :editOwnerName AND ST.EDIT_TABLE_NAME = :editTableName)
   )
;

-- [M02002_MANAGED_TABLE_ANY_REFERENCE_COUNT]
SELECT COUNT(*) AS REFERENCE_COUNT
  FROM INIT$_TB_TABLES ST
 WHERE (ST.OWNER_NAME = :ownerName AND ST.TABLE_NAME = :tableName)
    OR (ST.EDIT_OWNER_NAME = :ownerName AND ST.EDIT_TABLE_NAME = :tableName)
;

-- [M02002_EDIT_SESSION_REFERENCE_COUNT]
SELECT COUNT(*) AS REFERENCE_COUNT
  FROM INIT$_TB_EDIT_SESSION
 WHERE TARGET_OWNER = :targetOwner
   AND (SOURCE_TABLE = :sourceTable OR EDIT_TABLE = :editTable)
;

-- [M02002_EDIT_SESSION_PHYSICAL_TABLE_REFERENCE_COUNT]
SELECT COUNT(*) AS REFERENCE_COUNT
  FROM INIT$_TB_EDIT_SESSION
 WHERE TARGET_OWNER = :targetOwner
   AND (SOURCE_TABLE = :tableName OR EDIT_TABLE = :tableName)
;

-- [M02002_EDIT_SESSION_TABLE_EXISTS]
SELECT COUNT(*) AS TABLE_COUNT
  FROM USER_TABLES
 WHERE TABLE_NAME = 'INIT$_TB_EDIT_SESSION'
;

-- [M02002_EXCLUDE_TABLE_FILTER_SETTING]
SELECT SETTING_VALUE
  FROM "INIT$_TB_SYSTEM_SETTING"
 WHERE USER_ID = :userId
   AND CONNECTION_ID = :connectionId
   AND CATEGORY_CODE = 'M02002_TABLE_FILTER'
   AND SETTING_KEY = 'EXCLUDE_TABLE_LIKE'
   AND USE_YN = 'Y'
;

-- [M02002_INCLUDE_OWNER_FILTER_SETTING]
SELECT SETTING_VALUE
  FROM "INIT$_TB_SYSTEM_SETTING"
 WHERE USER_ID = :userId
   AND CONNECTION_ID = :connectionId
   AND CATEGORY_CODE = 'M02002_TABLE_FILTER'
   AND SETTING_KEY = 'INCLUDE_OWNER'
   AND USE_YN = 'Y'
;

-- [M02002_CURRENT_SCHEMA]
SELECT SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA')
  FROM DUAL
;
