
-- [M02002_TABLE_TREE]
SELECT
    OWNER,
    TABLE_NAME,
    COMMENTS
  FROM (
    SELECT
        T.OWNER,
        T.TABLE_NAME,
        C.COMMENTS,
        ROW_NUMBER() OVER (ORDER BY T.OWNER, T.TABLE_NAME) AS RN
      FROM ALL_TABLES T
      LEFT JOIN ALL_TAB_COMMENTS C
        ON C.OWNER = T.OWNER
       AND C.TABLE_NAME = T.TABLE_NAME
     WHERE T.NESTED = 'NO'
       AND T.SECONDARY = 'N'
       AND T.TABLE_NAME NOT LIKE 'BIN$%'
       AND (:ownerPattern IS NULL OR T.OWNER LIKE :ownerPattern)
       AND (:excludePattern1 IS NULL OR T.TABLE_NAME NOT LIKE :excludePattern1)
       AND (:excludePattern2 IS NULL OR T.TABLE_NAME NOT LIKE :excludePattern2)
       AND (:excludePattern3 IS NULL OR T.TABLE_NAME NOT LIKE :excludePattern3)
       AND (:excludePattern4 IS NULL OR T.TABLE_NAME NOT LIKE :excludePattern4)
       AND (:excludePattern5 IS NULL OR T.TABLE_NAME NOT LIKE :excludePattern5)
       AND (
              :keyword IS NULL
           OR UPPER(T.OWNER) LIKE :keyword
           OR UPPER(T.TABLE_NAME) LIKE :keyword
           OR UPPER(C.COMMENTS) LIKE :keyword
       )
  )
 WHERE RN > :offset
   AND RN <= :endRow
 ORDER BY RN
;

-- [M02002_TABLE_INFO]
SELECT
    T.OWNER,
    T.TABLE_NAME,
    C.COMMENTS,
    TO_CHAR(O.CREATED, 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT,
    T.NUM_ROWS,
    T.LAST_ANALYZED
  FROM ALL_TABLES T
  LEFT JOIN ALL_TAB_COMMENTS C
    ON C.OWNER = T.OWNER
   AND C.TABLE_NAME = T.TABLE_NAME
  LEFT JOIN ALL_OBJECTS O
    ON O.OWNER = T.OWNER
   AND O.OBJECT_NAME = T.TABLE_NAME
   AND O.OBJECT_TYPE = 'TABLE'
 WHERE T.OWNER = :owner
   AND T.TABLE_NAME = :tableName
;

-- [M02002_TABLE_COLUMNS]
SELECT
    C.OWNER,
    C.TABLE_NAME AS TABLE_ID,
    TC.COMMENTS AS TABLE_COMMENT,
    C.COLUMN_ID,
    C.COLUMN_NAME,
    CC.COMMENTS AS COLUMN_COMMENT,
    C.DATA_TYPE,
    C.DATA_LENGTH,
    C.CHAR_LENGTH,
    C.DATA_PRECISION,
    C.DATA_SCALE,
    C.NULLABLE,
    C.DATA_DEFAULT,
    CASE
        WHEN PK.COLUMN_NAME IS NOT NULL THEN 'Y'
        ELSE 'N'
    END AS PRIMARY_KEY_YN,
    C.NUM_DISTINCT,
    C.NUM_NULLS,
    C.DENSITY,
    C.LAST_ANALYZED
  FROM ALL_TAB_COLUMNS C
  LEFT JOIN ALL_TAB_COMMENTS TC
    ON TC.OWNER = C.OWNER
   AND TC.TABLE_NAME = C.TABLE_NAME
  LEFT JOIN ALL_COL_COMMENTS CC
    ON CC.OWNER = C.OWNER
   AND CC.TABLE_NAME = C.TABLE_NAME
   AND CC.COLUMN_NAME = C.COLUMN_NAME
  LEFT JOIN (
        SELECT ACC.OWNER, ACC.TABLE_NAME, ACC.COLUMN_NAME
          FROM ALL_CONSTRAINTS AC
          JOIN ALL_CONS_COLUMNS ACC
            ON ACC.OWNER = AC.OWNER
           AND ACC.CONSTRAINT_NAME = AC.CONSTRAINT_NAME
         WHERE AC.CONSTRAINT_TYPE = 'P'
  ) PK
    ON PK.OWNER = C.OWNER
   AND PK.TABLE_NAME = C.TABLE_NAME
   AND PK.COLUMN_NAME = C.COLUMN_NAME
 WHERE C.OWNER = :owner
   AND C.TABLE_NAME = :tableName
 ORDER BY C.COLUMN_ID
;

-- [M02002_TABLE_DATA]
SELECT *
  FROM /* --DYNAMIC_TABLE-- */
 WHERE ROWNUM <= :limit
;

-- [M02002_SQL_WORKSHEET]
SELECT *
  FROM (
/* --DYNAMIC_SQL-- */
  )
 WHERE ROWNUM <= :limit
;

-- [M02002_SCENARIO_TABLE_LIST]
SELECT
    SCENARIO_TABLE_ID,
    PROJECT_ID,
    SCENARIO_ID,
    OWNER_NAME,
    TABLE_NAME,
    TABLE_COMMENT,
    USE_YN,
    SORT_ORDER,
    CREATED_AT,
    UPDATED_AT
  FROM INIT$_TB_TABLES
 WHERE PROJECT_ID = :projectId
   AND SCENARIO_ID = :scenarioId
 ORDER BY SORT_ORDER NULLS LAST, OWNER_NAME, TABLE_NAME, SCENARIO_TABLE_ID
;

-- [M02002_SCENARIO_TABLE_INSERT]
INSERT INTO INIT$_TB_TABLES (
    PROJECT_ID,
    SCENARIO_ID,
    OWNER_NAME,
    TABLE_NAME,
    TABLE_COMMENT,
    USE_YN,
    SORT_ORDER,
    CREATED_AT
) VALUES (
    :projectId,
    :scenarioId,
    :ownerName,
    :tableName,
    :tableComment,
    :useYn,
    :sortOrder,
    SYSTIMESTAMP
)
;

-- [M02002_SCENARIO_TABLE_UPDATE]
UPDATE INIT$_TB_TABLES
   SET TABLE_COMMENT = :tableComment,
       USE_YN = :useYn,
       SORT_ORDER = :sortOrder,
       UPDATED_AT = SYSTIMESTAMP
 WHERE SCENARIO_TABLE_ID = :scenarioTableId
   AND PROJECT_ID = :projectId
   AND SCENARIO_ID = :scenarioId
;

-- [M02002_SCENARIO_TABLE_ID_BY_KEY]
SELECT SCENARIO_TABLE_ID
  FROM INIT$_TB_TABLES
 WHERE PROJECT_ID = :projectId
   AND SCENARIO_ID = :scenarioId
   AND OWNER_NAME = :ownerName
   AND TABLE_NAME = :tableName
;

-- [M02002_SCENARIO_TABLE_DELETE]
DELETE FROM INIT$_TB_TABLES
 WHERE SCENARIO_TABLE_ID = :scenarioTableId
   AND PROJECT_ID = :projectId
   AND SCENARIO_ID = :scenarioId
;

-- [M02002_SCENARIO_TABLE_DELETE_ALL]
DELETE FROM INIT$_TB_TABLES
 WHERE PROJECT_ID = :projectId
   AND SCENARIO_ID = :scenarioId
;

-- [M02002_EXCLUDE_TABLE_FILTER_SETTING]
SELECT SETTING_VALUE
  FROM "INIT$_TB_SYSTEM_SETTING"
 WHERE USER_ID = :userId
   AND CONNECTION_ID = :connectionId
   AND CATEGORY_CODE = 'M02002_TABLE_FILTER'
   AND SETTING_KEY = 'EXCLUDE_TABLE_LIKE'
   AND USE_YN = 'Y'
;

-- [M02002_INCLUDE_OWNER_FILTER_SETTING]
SELECT SETTING_VALUE
  FROM "INIT$_TB_SYSTEM_SETTING"
 WHERE USER_ID = :userId
   AND CONNECTION_ID = :connectionId
   AND CATEGORY_CODE = 'M02002_TABLE_FILTER'
   AND SETTING_KEY = 'INCLUDE_OWNER'
   AND USE_YN = 'Y'
;

-- [M02002_CURRENT_SCHEMA]
SELECT SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA')
  FROM DUAL
;
