-- [M02001_PROJECT_OWNER_CONTEXT]
SELECT P.PROJECT_ID
     , P.USER_ID
     , P.PROJECT_CODE
  FROM INIT$_TB_PROJECT P
 WHERE P.PROJECT_ID = :projectId
   AND P.PROJECT_CODE = :projectCode
   AND P.USE_YN = 'Y'
;

-- [M02001_CURRENT_SCHEMA]
SELECT SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA') AS OWNER_NAME
  FROM DUAL
;

-- [M02001_STALE_UPLOAD_STAGE_TABLES]
SELECT T.TABLE_NAME
  FROM USER_TABLES T
  JOIN USER_OBJECTS O
    ON O.OBJECT_NAME = T.TABLE_NAME
   AND O.OBJECT_TYPE = 'TABLE'
 WHERE REGEXP_LIKE(T.TABLE_NAME, '^INITSTG\$_[A-F0-9]{32}$')
   AND O.CREATED < SYSDATE - (:maxAgeSeconds / 86400)
 ORDER BY O.CREATED
;

-- [M02001_STALE_LOADING_UPLOAD_TABLES]
SELECT M.TABLE_NAME
  FROM INIT$_TB_UPLOAD_TABLE_META M
 WHERE M.OWNER_NAME = SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA')
   AND M.LOAD_STATUS = 'LOADING'
   AND REGEXP_LIKE(M.TABLE_NAME, '^INITUP\$_[A-Z0-9_$#_]*[0-9]{13}$')
   AND NVL(M.UPDATED_AT, M.CREATED_AT) < SYSTIMESTAMP - NUMTODSINTERVAL(:maxAgeSeconds, 'SECOND')
 ORDER BY NVL(M.UPDATED_AT, M.CREATED_AT)
;

-- [M02001_PROJECT_OWNER_LOGIN]
SELECT U.USER_ID
     , U.LOGIN_ID
  FROM INIT$_TB_USER U
 WHERE U.USER_ID = :userId
   AND U.USE_YN = 'Y'
;

-- [M02001_UPLOAD_TABLE_TREE]
SELECT SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA') AS OWNER
     , T.TABLE_NAME
     , C.COMMENTS
     , T.NUM_ROWS
     , T.LAST_ANALYZED
  FROM USER_TABLES T
  JOIN INIT$_TB_UPLOAD_TABLE_META M
    ON M.OWNER_NAME = SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA')
   AND M.TABLE_NAME = T.TABLE_NAME
   AND M.PROJECT_ID = :projectId
   AND NVL(M.LOAD_STATUS, 'READY') = 'READY'
  LEFT OUTER JOIN USER_TAB_COMMENTS C
    ON C.TABLE_NAME = T.TABLE_NAME
 WHERE T.TABLE_NAME LIKE :tablePrefix || '%'
   AND T.TABLE_NAME NOT LIKE 'BIN$%'
   AND T.NESTED = 'NO'
   AND T.SECONDARY = 'N'
 ORDER BY T.TABLE_NAME
;

-- [M02001_UPLOAD_TABLE_COLUMNS]
SELECT SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA') AS OWNER
     , C.TABLE_NAME AS TABLE_ID
     , T.COMMENTS AS TABLE_COMMENT
     , C.COLUMN_ID
     , C.COLUMN_NAME AS COLUMN_NAME
     , C.DATA_TYPE
     , C.DATA_LENGTH
     , C.NULLABLE
     , C.DATA_DEFAULT
     , CC.COMMENTS AS COLUMN_COMMENT
  FROM USER_TAB_COLUMNS C
  LEFT OUTER JOIN USER_TAB_COMMENTS T
    ON T.TABLE_NAME = C.TABLE_NAME
  LEFT OUTER JOIN USER_COL_COMMENTS CC
    ON CC.TABLE_NAME = C.TABLE_NAME
   AND CC.COLUMN_NAME = C.COLUMN_NAME
 WHERE C.TABLE_NAME = :tableName
 ORDER BY C.COLUMN_ID
;

-- [M02001_UPLOAD_TABLE_DATA_COUNT]
SELECT COUNT(*) AS TOTAL_COUNT
  FROM /* --DYNAMIC_TABLE-- */
;

-- [M02001_UPLOAD_TABLE_DATA_PAGE]
SELECT *
  FROM /* --DYNAMIC_TABLE-- */
 ORDER BY ROWID
 OFFSET :offset ROWS FETCH NEXT :limit ROWS ONLY
;

-- [M02001_UPLOAD_TABLE_META_EXISTS]
SELECT COUNT(*) AS TABLE_COUNT
  FROM USER_TABLES
 WHERE TABLE_NAME = 'INIT$_TB_UPLOAD_TABLE_META'
;

-- [M02001_UPLOAD_TABLE_META_CREATE]
CREATE TABLE "INIT$_TB_UPLOAD_TABLE_META" (
    "OWNER_NAME" VARCHAR2(128 BYTE) NOT NULL ENABLE
  , "TABLE_NAME" VARCHAR2(128 BYTE) NOT NULL ENABLE
  , "PROJECT_ID" NUMBER
  , "FILE_EXTENSION" VARCHAR2(20 BYTE)
  , "FILE_NAME" VARCHAR2(500 BYTE)
  , "FILE_SIZE" NUMBER
  , "UPLOAD_ID" VARCHAR2(64 BYTE)
  , "ROW_COUNT" NUMBER
  , "CONTENT_SHA256" VARCHAR2(64 BYTE)
  , "LOAD_STATUS" VARCHAR2(20 BYTE) DEFAULT 'READY' NOT NULL ENABLE
  , "CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE
  , "UPDATED_AT" TIMESTAMP (6)
  , CONSTRAINT "PK_INIT$_TB_UPLOAD_TABLE_META" PRIMARY KEY ("OWNER_NAME", "TABLE_NAME")
)
;

-- [M02001_UPLOAD_TABLE_META_PROJECT_EXISTS]
SELECT COUNT(*) AS COLUMN_COUNT
  FROM USER_TAB_COLUMNS
 WHERE TABLE_NAME = 'INIT$_TB_UPLOAD_TABLE_META'
   AND COLUMN_NAME = 'PROJECT_ID'
;

-- [M02001_UPLOAD_TABLE_META_PROJECT_ADD]
ALTER TABLE "INIT$_TB_UPLOAD_TABLE_META"
  ADD ("PROJECT_ID" NUMBER)
;

-- [M02001_UPLOAD_TABLE_META_UPLOAD_ID_EXISTS]
SELECT COUNT(*) AS COLUMN_COUNT
  FROM USER_TAB_COLUMNS
 WHERE TABLE_NAME = 'INIT$_TB_UPLOAD_TABLE_META'
   AND COLUMN_NAME = 'UPLOAD_ID'
;

-- [M02001_UPLOAD_TABLE_META_UPLOAD_ID_ADD]
ALTER TABLE "INIT$_TB_UPLOAD_TABLE_META"
  ADD ("UPLOAD_ID" VARCHAR2(64 BYTE))
;

-- [M02001_UPLOAD_TABLE_META_ROW_COUNT_EXISTS]
SELECT COUNT(*) AS COLUMN_COUNT
  FROM USER_TAB_COLUMNS
 WHERE TABLE_NAME = 'INIT$_TB_UPLOAD_TABLE_META'
   AND COLUMN_NAME = 'ROW_COUNT'
;

-- [M02001_UPLOAD_TABLE_META_ROW_COUNT_ADD]
ALTER TABLE "INIT$_TB_UPLOAD_TABLE_META"
  ADD ("ROW_COUNT" NUMBER)
;

-- [M02001_UPLOAD_TABLE_META_CONTENT_SHA256_EXISTS]
SELECT COUNT(*) AS COLUMN_COUNT
  FROM USER_TAB_COLUMNS
 WHERE TABLE_NAME = 'INIT$_TB_UPLOAD_TABLE_META'
   AND COLUMN_NAME = 'CONTENT_SHA256'
;

-- [M02001_UPLOAD_TABLE_META_CONTENT_SHA256_ADD]
ALTER TABLE "INIT$_TB_UPLOAD_TABLE_META"
  ADD ("CONTENT_SHA256" VARCHAR2(64 BYTE))
;

-- [M02001_UPLOAD_TABLE_META_LOAD_STATUS_EXISTS]
SELECT COUNT(*) AS COLUMN_COUNT
  FROM USER_TAB_COLUMNS
 WHERE TABLE_NAME = 'INIT$_TB_UPLOAD_TABLE_META'
   AND COLUMN_NAME = 'LOAD_STATUS'
;

-- [M02001_UPLOAD_TABLE_META_LOAD_STATUS_ADD]
ALTER TABLE "INIT$_TB_UPLOAD_TABLE_META"
  ADD ("LOAD_STATUS" VARCHAR2(20 BYTE) DEFAULT 'READY' NOT NULL)
;

-- [M02001_UPLOAD_TABLE_META_MERGE]
MERGE INTO "INIT$_TB_UPLOAD_TABLE_META" T
USING (
    SELECT SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA') AS OWNER_NAME
         , :tableName AS TABLE_NAME
         , :projectId AS PROJECT_ID
         , :fileExtension AS FILE_EXTENSION
         , :fileName AS FILE_NAME
         , :fileSize AS FILE_SIZE
         , :uploadId AS UPLOAD_ID
         , :rowCount AS ROW_COUNT
         , :contentSha256 AS CONTENT_SHA256
         , :loadStatus AS LOAD_STATUS
      FROM DUAL
) S
   ON (T.OWNER_NAME = S.OWNER_NAME AND T.TABLE_NAME = S.TABLE_NAME)
 WHEN MATCHED THEN
      UPDATE
         SET T.PROJECT_ID = S.PROJECT_ID
           , T.FILE_EXTENSION = S.FILE_EXTENSION
           , T.FILE_NAME = S.FILE_NAME
           , T.FILE_SIZE = S.FILE_SIZE
           , T.UPLOAD_ID = S.UPLOAD_ID
           , T.ROW_COUNT = S.ROW_COUNT
           , T.CONTENT_SHA256 = S.CONTENT_SHA256
           , T.LOAD_STATUS = S.LOAD_STATUS
           , T.UPDATED_AT = SYSTIMESTAMP
 WHEN NOT MATCHED THEN
      INSERT (
          OWNER_NAME
        , TABLE_NAME
        , PROJECT_ID
        , FILE_EXTENSION
        , FILE_NAME
        , FILE_SIZE
        , UPLOAD_ID
        , ROW_COUNT
        , CONTENT_SHA256
        , LOAD_STATUS
      ) VALUES (
          S.OWNER_NAME
        , S.TABLE_NAME
        , S.PROJECT_ID
        , S.FILE_EXTENSION
        , S.FILE_NAME
        , S.FILE_SIZE
        , S.UPLOAD_ID
        , S.ROW_COUNT
        , S.CONTENT_SHA256
        , S.LOAD_STATUS
      )
;

-- [M02001_UPLOAD_TABLE_META_RESERVE]
INSERT INTO INIT$_TB_UPLOAD_TABLE_META (
    OWNER_NAME
  , TABLE_NAME
  , PROJECT_ID
  , FILE_EXTENSION
  , FILE_NAME
  , FILE_SIZE
  , UPLOAD_ID
  , ROW_COUNT
  , CONTENT_SHA256
  , LOAD_STATUS
) VALUES (
    SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA')
  , :tableName
  , :projectId
  , :fileExtension
  , :fileName
  , :fileSize
  , :uploadId
  , NULL
  , :contentSha256
  , 'LOADING'
)
;

-- [M02001_UPLOAD_TABLE_STATS_GATHER]
BEGIN
    DBMS_STATS.GATHER_TABLE_STATS(
        ownname => USER
      , tabname => :tableName
      , estimate_percent => DBMS_STATS.AUTO_SAMPLE_SIZE
      , method_opt => 'FOR ALL COLUMNS SIZE 1'
      , cascade => FALSE
      , no_invalidate => FALSE
    );
END;

-- [M02001_UPLOAD_TABLE_META_DELETE]
DELETE FROM "INIT$_TB_UPLOAD_TABLE_META"
 WHERE OWNER_NAME = SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA')
   AND TABLE_NAME = :tableName
;

-- [M02001_SQL_WORKSHEET_COUNT]
SELECT COUNT(*) AS TOTAL_COUNT
  FROM (
/* --DYNAMIC_SQL-- */
  )
;

-- [M02001_SQL_WORKSHEET_PAGE]
SELECT *
  FROM (
/* --DYNAMIC_SQL-- */
  )
 OFFSET :offset ROWS FETCH NEXT :limit ROWS ONLY
;
