-- [M03001_SCENARIO_TABLE_LIST]
SELECT SCENARIO_TABLE_ID
     , PROJECT_ID
     , SCENARIO_ID
     , OWNER_NAME
     , TABLE_NAME
     , TABLE_COMMENT
     , USE_YN
     , SORT_ORDER
     , CREATED_AT
     , UPDATED_AT
  FROM INIT$_TB_TABLES
 WHERE PROJECT_ID = :projectId
   AND SCENARIO_ID = :scenarioId
 ORDER BY SORT_ORDER NULLS LAST, OWNER_NAME, TABLE_NAME, SCENARIO_TABLE_ID
;

-- [M03001_EXECUTABLE_OBJECT_LIST]
SELECT OBJECT_ID
     , OWNER
     , OBJECT_TYPE
     , OBJECT_NAME
     , OBJECT_LABEL
     , DESCRIPTION
     , USE_YN
     , SORT_ORDER
  FROM INIT$_TB_OBJECT
 WHERE USE_YN = 'Y'
   AND OBJECT_TYPE IN (
        'PROCEDURE',
        'FUNCTION',
        'PACKAGE_PROCEDURE',
        'PACKAGE_FUNCTION',
        'MINING_MODEL'
   )
 ORDER BY SORT_ORDER NULLS LAST, OWNER, OBJECT_TYPE, OBJECT_NAME
;

-- [M03001_EXECUTABLE_OBJECT_DETAIL]
SELECT OBJECT_ID
     , OWNER
     , OBJECT_TYPE
     , OBJECT_NAME
     , ITEM_NAME
     , ITEM_VALUE
     , ITEM_DESC
     , ITEM_DEFAULT
     , ITEM_ORDER
  FROM INIT$_TB_OBJECT_DETAIL
 WHERE OBJECT_ID = :objectId
 ORDER BY ITEM_ORDER NULLS LAST, ITEM_NAME
;

-- [M03001_TABLE_COLUMNS]
SELECT C.OWNER
     , C.TABLE_NAME AS TABLE_ID
     , TC.COMMENTS AS TABLE_COMMENT
     , C.COLUMN_ID
     , C.COLUMN_NAME AS COLUMN_NAME
     , CC.COMMENTS AS COLUMN_COMMENT
     , C.DATA_TYPE
     , C.DATA_LENGTH
     , C.CHAR_LENGTH
     , C.DATA_PRECISION
     , C.DATA_SCALE
     , C.NULLABLE
     , C.DATA_DEFAULT
  FROM ALL_TAB_COLUMNS C
  LEFT JOIN ALL_TAB_COMMENTS TC
    ON TC.OWNER = C.OWNER
   AND TC.TABLE_NAME = C.TABLE_NAME
  LEFT JOIN ALL_COL_COMMENTS CC
    ON CC.OWNER = C.OWNER
   AND CC.TABLE_NAME = C.TABLE_NAME
   AND CC.COLUMN_NAME = C.COLUMN_NAME
 WHERE C.OWNER = :owner
   AND C.TABLE_NAME = :tableName
 ORDER BY C.COLUMN_ID
;

-- [M03001_TABLE_DATA]
SELECT *
  FROM /* --DYNAMIC_TABLE-- */
 WHERE ROWNUM <= :limit
;

-- [M03001_SQL_WORKSHEET]
SELECT *
  FROM (
/* --DYNAMIC_SQL-- */
  )
 WHERE ROWNUM <= :limit
;

