-- [M03003_SCENARIO_TABLE_LIST]
SELECT SCENARIO_TABLE_ID
     , PROJECT_ID
     , SCENARIO_ID
     , OWNER_NAME
     , TABLE_NAME
     , TABLE_COMMENT
     , USE_YN
     , SORT_ORDER
     , CREATED_AT
     , UPDATED_AT
  FROM INIT$_TB_TABLES
 WHERE PROJECT_ID = :projectId
   AND SCENARIO_ID = :scenarioId
 ORDER BY SORT_ORDER NULLS LAST, OWNER_NAME, TABLE_NAME, SCENARIO_TABLE_ID
;

-- [M03003_EXECUTABLE_OBJECT_LIST]
WITH RESULT_META AS (
    SELECT OBJECT_ID
         , MAX(CASE WHEN ITEM_NAME = 'INIT$RESULT_CREATE_YN' THEN ITEM_DEFAULT END) AS RESULT_CREATE_YN
         , MAX(CASE WHEN ITEM_NAME = 'INIT$RESULT_OWNER' THEN ITEM_DEFAULT END) AS RESULT_OWNER
         , MAX(CASE WHEN ITEM_NAME = 'INIT$RESULT_TABLE_NAME' THEN ITEM_DEFAULT END) AS RESULT_TABLE_NAME
      FROM INIT$_TB_OBJECT_DETAIL
     WHERE ITEM_NAME IN (
              'INIT$RESULT_CREATE_YN'
            , 'INIT$RESULT_OWNER'
            , 'INIT$RESULT_TABLE_NAME'
           )
     GROUP BY OBJECT_ID
)
SELECT O.OBJECT_ID
     , O.OWNER
     , O.OBJECT_TYPE
     , O.OBJECT_NAME
     , O.OBJECT_LABEL
     , O.DESCRIPTION
     , O.USE_YN
     , O.SORT_ORDER
     , COALESCE(R.RESULT_CREATE_YN, 'N') AS RESULT_CREATE_YN
     , R.RESULT_OWNER
     , R.RESULT_TABLE_NAME
  FROM INIT$_TB_OBJECT O
  LEFT JOIN RESULT_META R
    ON R.OBJECT_ID = O.OBJECT_ID
 WHERE O.USE_YN = 'Y'
   AND O.OBJECT_TYPE IN (
        'PROCEDURE',
        'FUNCTION',
        'PACKAGE_PROCEDURE',
        'PACKAGE_FUNCTION',
        'MINING_MODEL'
   )
 ORDER BY O.SORT_ORDER NULLS LAST, O.OWNER, O.OBJECT_TYPE, O.OBJECT_NAME
;

-- [M03003_EXECUTABLE_OBJECT_DETAIL]
SELECT OBJECT_ID
     , OWNER
     , OBJECT_TYPE
     , OBJECT_NAME
     , ITEM_NAME
     , ITEM_VALUE
     , ITEM_DESC
     , ITEM_DEFAULT
     , ITEM_ORDER
  FROM INIT$_TB_OBJECT_DETAIL
 WHERE OBJECT_ID = :objectId
   AND ITEM_NAME NOT IN (
        'INIT$RESULT_CREATE_YN',
        'INIT$RESULT_OWNER',
        'INIT$RESULT_TABLE_NAME'
   )
 ORDER BY ITEM_ORDER NULLS LAST, ITEM_NAME
;

-- [M03003_TABLE_COLUMNS]
SELECT C.OWNER
     , C.TABLE_NAME AS TABLE_ID
     , TC.COMMENTS AS TABLE_COMMENT
     , C.COLUMN_ID
     , C.COLUMN_NAME AS COLUMN_NAME
     , CC.COMMENTS AS COLUMN_COMMENT
     , C.DATA_TYPE
     , C.DATA_LENGTH
     , C.CHAR_LENGTH
     , C.DATA_PRECISION
     , C.DATA_SCALE
     , C.NULLABLE
     , C.DATA_DEFAULT
  FROM ALL_TAB_COLUMNS C
  LEFT JOIN ALL_TAB_COMMENTS TC
    ON TC.OWNER = C.OWNER
   AND TC.TABLE_NAME = C.TABLE_NAME
  LEFT JOIN ALL_COL_COMMENTS CC
    ON CC.OWNER = C.OWNER
   AND CC.TABLE_NAME = C.TABLE_NAME
   AND CC.COLUMN_NAME = C.COLUMN_NAME
 WHERE C.OWNER = :owner
   AND C.TABLE_NAME = :tableName
 ORDER BY C.COLUMN_ID
;

-- [M03003_TABLE_DATA]
SELECT *
  FROM /* --DYNAMIC_TABLE-- */
 WHERE ROWNUM <= :limit
;

-- [M03003_SQL_WORKSHEET]
SELECT *
  FROM (
/* --DYNAMIC_SQL-- */
  )
 WHERE ROWNUM <= :limit
;
