-- [M04001_FLOW_NODE_TYPE_LIST]
SELECT 'TABLE_INPUT' AS NODE_TYPE,
       'Source Table' AS NODE_TYPE_NAME,
       CAST(NULL AS VARCHAR2(30)) AS MENU_CODE,
       'TABLE' AS DEFAULT_OUTPUT_TYPE,
       10 AS SORT_ORDER
  FROM DUAL
UNION ALL
SELECT 'VALUE_INPUT' AS NODE_TYPE,
       'Value Input' AS NODE_TYPE_NAME,
       CAST(NULL AS VARCHAR2(30)) AS MENU_CODE,
       'VALUE' AS DEFAULT_OUTPUT_TYPE,
       20 AS SORT_ORDER
  FROM DUAL
UNION ALL
SELECT 'ARRAY_INPUT' AS NODE_TYPE,
       'Array Input' AS NODE_TYPE_NAME,
       CAST(NULL AS VARCHAR2(30)) AS MENU_CODE,
       'ARRAY' AS DEFAULT_OUTPUT_TYPE,
       30 AS SORT_ORDER
  FROM DUAL
UNION ALL
SELECT
       JOB_GROUP AS NODE_TYPE,
       CASE
           WHEN JOB_GROUP = 'M03001' THEN '데이터 프로파일링'
           WHEN JOB_GROUP = 'M03002' THEN '컬럼간 상관 분석'
           WHEN JOB_GROUP = 'M03003' THEN '자동 규칙 발굴'
           WHEN JOB_GROUP = 'M03004' THEN '규칙 위반 탐지'
           ELSE JOB_GROUP
       END AS NODE_TYPE_NAME,
       MIN(MENU_CODE) AS MENU_CODE,
       CASE
           WHEN MIN(MENU_CODE) IN ('M03002', 'M03003') THEN 'ARRAY'
           ELSE 'TABLE'
       END AS DEFAULT_OUTPUT_TYPE,
       100 + DENSE_RANK() OVER (ORDER BY JOB_GROUP) AS SORT_ORDER
  FROM INIT$_TB_DATA_WORK_JOB
 WHERE USE_YN = 'Y'
   AND (:projectId IS NULL OR PROJECT_ID = :projectId)
   AND (:scenarioId IS NULL OR SCENARIO_ID = :scenarioId)
 GROUP BY JOB_GROUP
 ORDER BY SORT_ORDER
;

-- [M04001_FLOW_DEFAULT_VARIABLE_LIST]
SELECT 'min_confidence' AS VARIABLE_NAME,
       'VALUE' AS VARIABLE_TYPE,
       '0.95' AS DEFAULT_VALUE,
       'rule-mining-01' AS VARIABLE_SCOPE,
       10 AS SORT_ORDER
  FROM DUAL
UNION ALL
SELECT 'target_columns' AS VARIABLE_NAME,
       'ARRAY' AS VARIABLE_TYPE,
       'EMAIL, PHONE_NO, ZIP_CODE' AS DEFAULT_VALUE,
       'flow' AS VARIABLE_SCOPE,
       20 AS SORT_ORDER
  FROM DUAL
UNION ALL
SELECT 'result_owner' AS VARIABLE_NAME,
       'VALUE' AS VARIABLE_TYPE,
       'EDT_RESULT' AS DEFAULT_VALUE,
       'flow' AS VARIABLE_SCOPE,
       30 AS SORT_ORDER
  FROM DUAL
 ORDER BY SORT_ORDER
;
