-- [M04001_FLOW_NODE_TYPE_LIST]
SELECT 'TABLE_INPUT' AS NODE_TYPE,
       'Source Table' AS NODE_TYPE_NAME,
       'TABLE' AS DEFAULT_OUTPUT_TYPE,
       10 AS SORT_ORDER
  FROM DUAL
UNION ALL
SELECT 'PROFILING' AS NODE_TYPE,
       'Profiling' AS NODE_TYPE_NAME,
       'TABLE' AS DEFAULT_OUTPUT_TYPE,
       20 AS SORT_ORDER
  FROM DUAL
UNION ALL
SELECT 'CORRELATION' AS NODE_TYPE,
       'Correlation Analysis' AS NODE_TYPE_NAME,
       'ARRAY' AS DEFAULT_OUTPUT_TYPE,
       30 AS SORT_ORDER
  FROM DUAL
UNION ALL
SELECT 'RULE_MINING' AS NODE_TYPE,
       'Rule Discovery' AS NODE_TYPE_NAME,
       'ARRAY' AS DEFAULT_OUTPUT_TYPE,
       40 AS SORT_ORDER
  FROM DUAL
UNION ALL
SELECT 'VIOLATION_SEARCH' AS NODE_TYPE,
       'Violation Search' AS NODE_TYPE_NAME,
       'TABLE' AS DEFAULT_OUTPUT_TYPE,
       50 AS SORT_ORDER
  FROM DUAL
UNION ALL
SELECT 'VALUE_INPUT' AS NODE_TYPE,
       'Value Input' AS NODE_TYPE_NAME,
       'VALUE' AS DEFAULT_OUTPUT_TYPE,
       60 AS SORT_ORDER
  FROM DUAL
UNION ALL
SELECT 'ARRAY_INPUT' AS NODE_TYPE,
       'Array Input' AS NODE_TYPE_NAME,
       'ARRAY' AS DEFAULT_OUTPUT_TYPE,
       70 AS SORT_ORDER
  FROM DUAL
 ORDER BY SORT_ORDER
;

-- [M04001_FLOW_DEFAULT_VARIABLE_LIST]
SELECT 'min_confidence' AS VARIABLE_NAME,
       'VALUE' AS VARIABLE_TYPE,
       '0.95' AS DEFAULT_VALUE,
       'rule-mining-01' AS VARIABLE_SCOPE,
       10 AS SORT_ORDER
  FROM DUAL
UNION ALL
SELECT 'target_columns' AS VARIABLE_NAME,
       'ARRAY' AS VARIABLE_TYPE,
       'EMAIL, PHONE_NO, ZIP_CODE' AS DEFAULT_VALUE,
       'flow' AS VARIABLE_SCOPE,
       20 AS SORT_ORDER
  FROM DUAL
UNION ALL
SELECT 'result_owner' AS VARIABLE_NAME,
       'VALUE' AS VARIABLE_TYPE,
       'EDT_RESULT' AS DEFAULT_VALUE,
       'flow' AS VARIABLE_SCOPE,
       30 AS SORT_ORDER
  FROM DUAL
 ORDER BY SORT_ORDER
;
