-- [M90001_OBJECT_TREE]
-- Lightweight M90001 DB object tree. Object rows are loaded lazily per group.
WITH
USER_OWNERS AS (
    SELECT SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA') AS OWNER
      FROM DUAL
),
OWNER_ROWS AS (
    SELECT U.OWNER
         , 'OWNER' AS OBJECT_TYPE
         , U.OWNER AS OBJECT_NAME
         , U.OWNER AS OBJECT_LABEL
         , 'OWNER:' || U.OWNER AS NODE_ID
         , CAST(NULL AS VARCHAR2(4000)) AS PARENT_ID
         , 1 AS LEVEL_NO
         , 'N' AS IS_SELECTABLE
         , 'N' AS IS_REGISTERED
         , CAST(NULL AS NUMBER) AS CHILD_COUNT
         , CAST(NULL AS VARCHAR2(30)) AS OBJECT_STATUS
         , U.OWNER AS SORT_OWNER
         , 10 AS SORT_GROUP
         , U.OWNER AS SORT_NAME
      FROM USER_OWNERS U
),
GROUP_DEFS AS (
    SELECT 'PLSQL' AS CATEGORY_CODE, 'Procedures / Functions' AS GROUP_NAME, 'PROCEDURES' AS GROUP_KEY, 30 AS SORT_GROUP FROM DUAL
    UNION ALL SELECT 'PACKAGE', 'Packages', 'PACKAGES', 40 FROM DUAL
    UNION ALL SELECT 'MODEL', 'Models', 'MODELS', 50 FROM DUAL
),
GROUP_ROWS AS (
    SELECT U.OWNER
         , 'GROUP' AS OBJECT_TYPE
         , G.GROUP_NAME AS OBJECT_NAME
         , G.GROUP_NAME AS OBJECT_LABEL
         , 'GROUP:' || U.OWNER || ':' || G.GROUP_KEY AS NODE_ID
         , 'OWNER:' || U.OWNER AS PARENT_ID
         , 2 AS LEVEL_NO
         , 'N' AS IS_SELECTABLE
         , CASE
            WHEN EXISTS (
                SELECT 1
                  FROM INIT$_TB_OBJECT M
                 WHERE M.OWNER = U.OWNER
                   AND (
                          (G.CATEGORY_CODE = 'PLSQL' AND M.OBJECT_TYPE IN ('PROCEDURE', 'FUNCTION'))
                       OR (G.CATEGORY_CODE = 'PACKAGE' AND M.OBJECT_TYPE = 'PACKAGE')
                       OR (G.CATEGORY_CODE = 'MODEL' AND M.OBJECT_TYPE = 'MINING_MODEL')
                   )
            ) THEN 'Y'
            ELSE 'N'
        END AS IS_REGISTERED
         , CAST(NULL AS NUMBER) AS CHILD_COUNT
         , CAST(NULL AS VARCHAR2(30)) AS OBJECT_STATUS
         , U.OWNER AS SORT_OWNER
         , G.SORT_GROUP
         , G.GROUP_NAME AS SORT_NAME
         , G.CATEGORY_CODE
     FROM USER_OWNERS U
      CROSS JOIN GROUP_DEFS G
     WHERE (:categoryFilter = 'ALL' OR INSTR(',' || :categoryFilter || ',', ',' || G.CATEGORY_CODE || ',') > 0)
       AND (:registeredOnly = 'N' OR EXISTS (
            SELECT 1
              FROM INIT$_TB_OBJECT M
             WHERE M.OWNER = U.OWNER
               AND (
                      (G.CATEGORY_CODE = 'PLSQL' AND M.OBJECT_TYPE IN ('PROCEDURE', 'FUNCTION'))
                   OR (G.CATEGORY_CODE = 'PACKAGE' AND M.OBJECT_TYPE = 'PACKAGE')
                   OR (G.CATEGORY_CODE = 'MODEL' AND M.OBJECT_TYPE = 'MINING_MODEL')
               )
        ))
),
TREE_ROWS AS (
    SELECT OWNER, OBJECT_TYPE, OBJECT_NAME, OBJECT_LABEL, NODE_ID, PARENT_ID, LEVEL_NO
         , IS_SELECTABLE, IS_REGISTERED, CHILD_COUNT, OBJECT_STATUS, SORT_OWNER, SORT_GROUP, SORT_NAME
      FROM OWNER_ROWS
     WHERE :registeredOnly = 'N' OR EXISTS (
        SELECT 1 FROM GROUP_ROWS G WHERE G.OWNER = OWNER_ROWS.OWNER
     )
    UNION ALL
    SELECT OWNER, OBJECT_TYPE, OBJECT_NAME, OBJECT_LABEL, NODE_ID, PARENT_ID, LEVEL_NO
         , IS_SELECTABLE, IS_REGISTERED, CHILD_COUNT, OBJECT_STATUS, SORT_OWNER, SORT_GROUP, SORT_NAME
      FROM GROUP_ROWS
),
ORDERED_ROWS AS (
    SELECT R.*
         , ROW_NUMBER() OVER (ORDER BY SORT_OWNER, SORT_GROUP, SORT_NAME) AS RN
      FROM TREE_ROWS R
)
SELECT OWNER, OBJECT_TYPE, OBJECT_NAME, OBJECT_LABEL, NODE_ID, PARENT_ID, LEVEL_NO, IS_SELECTABLE, IS_REGISTERED, CHILD_COUNT, OBJECT_STATUS
  FROM ORDERED_ROWS
 WHERE RN > :offset
   AND RN <= :endRow
 ORDER BY RN
;

-- [M90001_OBJECT_CHILDREN]
-- Lazy-loaded object rows under a selected M90001 owner/group node.
WITH
BASE_ROWS AS (
    SELECT O.OWNER
         , O.OBJECT_TYPE
         , O.OBJECT_NAME
         , O.OBJECT_NAME AS OBJECT_LABEL
         , O.OBJECT_TYPE || ':' || O.OWNER || ':' || O.OBJECT_NAME AS NODE_ID
         , 'GROUP:' || O.OWNER || ':PROCEDURES' AS PARENT_ID
         , 3 AS LEVEL_NO
         , 'Y' AS IS_SELECTABLE
         , CASE WHEN M.OBJECT_ID IS NOT NULL THEN 'Y' ELSE 'N' END AS IS_REGISTERED
         , CAST(NULL AS NUMBER) AS CHILD_COUNT
         , O.STATUS AS OBJECT_STATUS
         , O.OBJECT_NAME AS SORT_NAME
      FROM ALL_OBJECTS O
      LEFT JOIN INIT$_TB_OBJECT M
        ON M.OWNER = O.OWNER
       AND M.OBJECT_TYPE = O.OBJECT_TYPE
       AND M.OBJECT_NAME = O.OBJECT_NAME
     WHERE :groupType = 'PROCEDURES'
       AND O.OWNER = :owner
       AND O.OWNER = SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA')
       AND O.OBJECT_TYPE IN ('PROCEDURE', 'FUNCTION')
       AND O.GENERATED = 'N'
       AND O.OBJECT_NAME NOT LIKE 'BIN$%'
    UNION ALL
    SELECT O.OWNER
         , 'PACKAGE' AS OBJECT_TYPE
         , O.OBJECT_NAME
         , O.OBJECT_NAME AS OBJECT_LABEL
         , 'PACKAGE:' || O.OWNER || ':' || O.OBJECT_NAME AS NODE_ID
         , 'GROUP:' || O.OWNER || ':PACKAGES' AS PARENT_ID
         , 3 AS LEVEL_NO
         , 'N' AS IS_SELECTABLE
         , CASE
            WHEN M.OBJECT_ID IS NOT NULL THEN 'Y'
            WHEN EXISTS (
                SELECT 1
                  FROM INIT$_TB_OBJECT PM
                 WHERE PM.OWNER = O.OWNER
                   AND PM.OBJECT_NAME LIKE O.OBJECT_NAME || '.%'
                   AND PM.OBJECT_TYPE IN ('PACKAGE_PROCEDURE', 'PACKAGE_FUNCTION')
            ) THEN 'Y'
            ELSE 'N'
        END AS IS_REGISTERED
         , CAST(NULL AS NUMBER) AS CHILD_COUNT
         , O.STATUS AS OBJECT_STATUS
         , O.OBJECT_NAME AS SORT_NAME
      FROM ALL_OBJECTS O
      LEFT JOIN INIT$_TB_OBJECT M
        ON M.OWNER = O.OWNER
       AND M.OBJECT_TYPE = 'PACKAGE'
       AND M.OBJECT_NAME = O.OBJECT_NAME
     WHERE :groupType = 'PACKAGES'
       AND O.OWNER = :owner
       AND O.OWNER = SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA')
       AND O.OBJECT_TYPE = 'PACKAGE'
       AND O.GENERATED = 'N'
       AND O.OBJECT_NAME NOT LIKE 'BIN$%'
    UNION ALL
    SELECT M.OWNER
         , 'MINING_MODEL' AS OBJECT_TYPE
         , M.MODEL_NAME AS OBJECT_NAME
         , M.MODEL_NAME || NVL2(M.MINING_FUNCTION, ' (' || M.MINING_FUNCTION || ')', '') AS OBJECT_LABEL
         , 'MINING_MODEL:' || M.OWNER || ':' || M.MODEL_NAME AS NODE_ID
         , 'GROUP:' || M.OWNER || ':MODELS' AS PARENT_ID
         , 3 AS LEVEL_NO
         , 'Y' AS IS_SELECTABLE
         , CASE WHEN R.OBJECT_ID IS NOT NULL THEN 'Y' ELSE 'N' END AS IS_REGISTERED
         , CAST(NULL AS NUMBER) AS CHILD_COUNT
         , CAST(NULL AS VARCHAR2(30)) AS OBJECT_STATUS
         , M.MODEL_NAME AS SORT_NAME
      FROM ALL_MINING_MODELS M
      LEFT JOIN INIT$_TB_OBJECT R
        ON R.OWNER = M.OWNER
       AND R.OBJECT_TYPE = 'MINING_MODEL'
       AND R.OBJECT_NAME = M.MODEL_NAME
     WHERE :groupType = 'MODELS'
       AND M.OWNER = :owner
       AND M.OWNER = SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA')
),
ORDERED_ROWS AS (
    SELECT B.*
         , ROW_NUMBER() OVER (ORDER BY SORT_NAME) AS RN
         , COUNT(*) OVER () AS TOTAL_COUNT
      FROM BASE_ROWS B
     WHERE (:registeredOnly = 'N' OR B.IS_REGISTERED = 'Y')
)
SELECT OWNER, OBJECT_TYPE, OBJECT_NAME, OBJECT_LABEL, NODE_ID, PARENT_ID, LEVEL_NO, IS_SELECTABLE, IS_REGISTERED, CHILD_COUNT, OBJECT_STATUS, TOTAL_COUNT
  FROM ORDERED_ROWS
 WHERE RN > :offset
   AND RN <= :endRow
 ORDER BY RN
;

-- [M90001_OBJECT_SEARCH]
-- Search selectable dictionary objects only when the user explicitly searches.
WITH
USER_OWNERS AS (
    SELECT SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA') AS OWNER FROM DUAL
),
MATCHED AS (
    SELECT O.OWNER, O.OBJECT_TYPE, O.OBJECT_NAME, O.OBJECT_NAME AS OBJECT_LABEL
         , O.OBJECT_TYPE || ':' || O.OWNER || ':' || O.OBJECT_NAME AS NODE_ID, CAST(NULL AS VARCHAR2(4000)) AS PARENT_ID
         , 1 AS LEVEL_NO, 'Y' AS IS_SELECTABLE
         , CASE WHEN R.OBJECT_ID IS NOT NULL THEN 'Y' ELSE 'N' END AS IS_REGISTERED
         , CAST(NULL AS NUMBER) AS CHILD_COUNT, O.STATUS AS OBJECT_STATUS, O.OBJECT_NAME AS SORT_NAME
     FROM ALL_OBJECTS O
      JOIN USER_OWNERS U ON U.OWNER = O.OWNER
      LEFT JOIN INIT$_TB_OBJECT R ON R.OWNER = O.OWNER AND R.OBJECT_TYPE = O.OBJECT_TYPE AND R.OBJECT_NAME = O.OBJECT_NAME
     WHERE (:categoryFilter = 'ALL' OR INSTR(',' || :categoryFilter || ',', ',PLSQL,') > 0)
       AND O.OBJECT_TYPE IN ('PROCEDURE', 'FUNCTION')
       AND O.GENERATED = 'N'
       AND O.OBJECT_NAME NOT LIKE 'BIN$%'
    UNION ALL
    SELECT O.OWNER, 'PACKAGE' AS OBJECT_TYPE, O.OBJECT_NAME, O.OBJECT_NAME AS OBJECT_LABEL
         , 'PACKAGE:' || O.OWNER || ':' || O.OBJECT_NAME AS NODE_ID, CAST(NULL AS VARCHAR2(4000)) AS PARENT_ID
         , 1 AS LEVEL_NO, 'N' AS IS_SELECTABLE
         , CASE WHEN R.OBJECT_ID IS NOT NULL THEN 'Y' ELSE 'N' END AS IS_REGISTERED
         , CAST(NULL AS NUMBER) AS CHILD_COUNT, O.STATUS AS OBJECT_STATUS, O.OBJECT_NAME AS SORT_NAME
      FROM ALL_OBJECTS O
      JOIN USER_OWNERS U ON U.OWNER = O.OWNER
      LEFT JOIN INIT$_TB_OBJECT R ON R.OWNER = O.OWNER AND R.OBJECT_TYPE = 'PACKAGE' AND R.OBJECT_NAME = O.OBJECT_NAME
     WHERE (:categoryFilter = 'ALL' OR INSTR(',' || :categoryFilter || ',', ',PACKAGE,') > 0)
       AND O.OBJECT_TYPE = 'PACKAGE'
       AND O.GENERATED = 'N'
       AND O.OBJECT_NAME NOT LIKE 'BIN$%'
    UNION ALL
    SELECT M.OWNER, 'MINING_MODEL' AS OBJECT_TYPE, M.MODEL_NAME AS OBJECT_NAME
         , M.MODEL_NAME || NVL2(M.MINING_FUNCTION, ' (' || M.MINING_FUNCTION || ')', '') AS OBJECT_LABEL
         , 'MINING_MODEL:' || M.OWNER || ':' || M.MODEL_NAME AS NODE_ID, CAST(NULL AS VARCHAR2(4000)) AS PARENT_ID
         , 1 AS LEVEL_NO, 'Y' AS IS_SELECTABLE
         , CASE WHEN R.OBJECT_ID IS NOT NULL THEN 'Y' ELSE 'N' END AS IS_REGISTERED
         , CAST(NULL AS NUMBER) AS CHILD_COUNT, CAST(NULL AS VARCHAR2(30)) AS OBJECT_STATUS, M.MODEL_NAME AS SORT_NAME
      FROM ALL_MINING_MODELS M
      JOIN USER_OWNERS U ON U.OWNER = M.OWNER
      LEFT JOIN INIT$_TB_OBJECT R ON R.OWNER = M.OWNER AND R.OBJECT_TYPE = 'MINING_MODEL' AND R.OBJECT_NAME = M.MODEL_NAME
     WHERE (:categoryFilter = 'ALL' OR INSTR(',' || :categoryFilter || ',', ',MODEL,') > 0)
),
FILTERED_MATCHED AS (
    SELECT *
      FROM MATCHED
     WHERE (:registeredOnly = 'N' OR IS_REGISTERED = 'Y')
       AND (UPPER(OWNER) LIKE :keyword OR UPPER(OBJECT_TYPE) LIKE :keyword OR UPPER(OBJECT_NAME) LIKE :keyword OR UPPER(OBJECT_LABEL) LIKE :keyword)
),
ORDERED_ROWS AS (
    SELECT M.*, ROW_NUMBER() OVER (ORDER BY OWNER, OBJECT_TYPE, SORT_NAME) AS RN
      FROM FILTERED_MATCHED M
)
SELECT OWNER, OBJECT_TYPE, OBJECT_NAME, OBJECT_LABEL, NODE_ID, PARENT_ID, LEVEL_NO, IS_SELECTABLE, IS_REGISTERED, CHILD_COUNT, OBJECT_STATUS
  FROM ORDERED_ROWS
 WHERE RN > :offset
   AND RN <= :endRow
 ORDER BY RN
;

-- [M90001_PACKAGE_MEMBERS]
-- Lazy-loaded package procedures/functions for a selected package node.
SELECT P.OWNER
     , CASE
        WHEN EXISTS (
            SELECT 1
              FROM ALL_ARGUMENTS A
             WHERE A.OWNER = P.OWNER
               AND A.PACKAGE_NAME = P.OBJECT_NAME
               AND A.OBJECT_NAME = P.PROCEDURE_NAME
               AND A.POSITION = 0
        ) THEN 'PACKAGE_FUNCTION'
        ELSE 'PACKAGE_PROCEDURE'
    END AS OBJECT_TYPE
     , P.OBJECT_NAME || '.' || P.PROCEDURE_NAME AS OBJECT_NAME
     , P.OBJECT_NAME || '.' || P.PROCEDURE_NAME AS OBJECT_LABEL
     , 'PACKAGE_MEMBER:' || P.OWNER || ':' || P.OBJECT_NAME || ':' || P.PROCEDURE_NAME AS NODE_ID
     , 'PACKAGE:' || P.OWNER || ':' || P.OBJECT_NAME AS PARENT_ID
     , 4 AS LEVEL_NO
     , 'Y' AS IS_SELECTABLE
     , CASE
        WHEN M.OBJECT_ID IS NOT NULL THEN 'Y'
        ELSE 'N'
    END AS IS_REGISTERED
     , CAST(NULL AS NUMBER) AS CHILD_COUNT
     , O.STATUS AS OBJECT_STATUS
  FROM ALL_PROCEDURES P
  LEFT JOIN ALL_OBJECTS O
    ON O.OWNER = P.OWNER
   AND O.OBJECT_NAME = P.OBJECT_NAME
   AND O.OBJECT_TYPE = 'PACKAGE'
  LEFT JOIN INIT$_TB_OBJECT M
    ON M.OWNER = P.OWNER
   AND M.OBJECT_NAME = P.OBJECT_NAME || '.' || P.PROCEDURE_NAME
   AND M.OBJECT_TYPE IN ('PACKAGE_PROCEDURE', 'PACKAGE_FUNCTION')
 WHERE P.OWNER = :owner
   AND P.OWNER = SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA')
   AND P.OBJECT_NAME = :packageName
   AND P.PROCEDURE_NAME IS NOT NULL
   AND (
          :registeredOnly = 'N'
       OR M.OBJECT_ID IS NOT NULL
   )
 ORDER BY P.PROCEDURE_NAME
;

-- [M90001_OBJECT_SOURCE]
SELECT TEXT
  FROM ALL_SOURCE
 WHERE OWNER = :owner
   AND NAME = :sourceName
   AND TYPE = :sourceType
 ORDER BY LINE
;

-- [M90001_OBJECT_META]
-- Object master metadata. Saved values are preferred; dictionary comments are used as editable defaults.
WITH DICT_META AS (
    SELECT :owner AS OWNER
         , :objectType AS OBJECT_TYPE
         , :objectName AS OBJECT_NAME
         , CASE
            WHEN :objectType = 'TABLE' THEN (
                SELECT COMMENTS
                  FROM ALL_TAB_COMMENTS
                 WHERE OWNER = :owner
                   AND TABLE_NAME = :objectName
            )
            WHEN :objectType IN ('PACKAGE_PROCEDURE', 'PACKAGE_FUNCTION') THEN (
                SELECT 'PACKAGE=' || REGEXP_SUBSTR(:objectName, '^[^.]+')
                    || ', MEMBER=' || REGEXP_SUBSTR(:objectName, '[^.]+$', 1, 1)
                  FROM DUAL
            )
            WHEN :objectType = 'MINING_MODEL' THEN (
                SELECT 'MINING_FUNCTION=' || MINING_FUNCTION
                    || NVL2(ALGORITHM, ', ALGORITHM=' || ALGORITHM, '')
                  FROM ALL_MINING_MODELS
                 WHERE OWNER = :owner
                   AND MODEL_NAME = :objectName
                   AND ROWNUM = 1
            )
            ELSE (
                SELECT 'STATUS=' || STATUS || ', CREATED=' || TO_CHAR(CREATED, 'YYYY-MM-DD HH24:MI:SS')
                  FROM ALL_OBJECTS
                 WHERE OWNER = :owner
                   AND OBJECT_NAME = :objectName
                   AND OBJECT_TYPE = :objectType
                   AND ROWNUM = 1
            )
        END AS DICTIONARY_COMMENT
      FROM DUAL
)
SELECT M.OBJECT_ID
     , D.OWNER
     , COALESCE(M.OBJECT_TYPE, D.OBJECT_TYPE) AS OBJECT_TYPE
     , COALESCE(M.OBJECT_NAME, D.OBJECT_NAME) AS OBJECT_NAME
     , COALESCE(M.OBJECT_LABEL, D.OBJECT_NAME) AS OBJECT_LABEL
     , COALESCE(M.DESCRIPTION, D.DICTIONARY_COMMENT, D.OBJECT_NAME) AS DESCRIPTION
     , COALESCE(M.USE_YN, 'Y') AS USE_YN
     , COALESCE(M.SORT_ORDER, 0) AS SORT_ORDER
     , COALESCE(R.RESULT_CREATE_YN, 'N') AS RESULT_CREATE_YN
     , R.RESULT_OWNER
     , R.RESULT_TABLE_NAME
     , D.DICTIONARY_COMMENT
  FROM DICT_META D
  LEFT JOIN INIT$_TB_OBJECT M
    ON M.OWNER = D.OWNER
   AND M.OBJECT_TYPE = D.OBJECT_TYPE
   AND M.OBJECT_NAME = D.OBJECT_NAME
  LEFT JOIN (
      SELECT OBJECT_ID
           , MAX(CASE WHEN ITEM_NAME = 'INIT$RESULT_CREATE_YN' THEN ITEM_DEFAULT END) AS RESULT_CREATE_YN
           , MAX(CASE WHEN ITEM_NAME = 'INIT$RESULT_OWNER' THEN ITEM_DEFAULT END) AS RESULT_OWNER
           , MAX(CASE WHEN ITEM_NAME = 'INIT$RESULT_TABLE_NAME' THEN ITEM_DEFAULT END) AS RESULT_TABLE_NAME
        FROM INIT$_TB_OBJECT_DETAIL
       WHERE ITEM_NAME IN (
                'INIT$RESULT_CREATE_YN'
              , 'INIT$RESULT_OWNER'
              , 'INIT$RESULT_TABLE_NAME'
             )
       GROUP BY OBJECT_ID
  ) R
    ON R.OBJECT_ID = M.OBJECT_ID
;

-- [M90001_OBJECT_UPSERT]
-- Insert or update object master metadata before saving detail rows.
MERGE INTO INIT$_TB_OBJECT T
USING (
    SELECT :owner AS OWNER
         , :objectType AS OBJECT_TYPE
         , :objectName AS OBJECT_NAME
         , :objectLabel AS OBJECT_LABEL
         , :description AS DESCRIPTION
         , :useYn AS USE_YN
         , :sortOrder AS SORT_ORDER
      FROM DUAL
) S
ON (
       T.OWNER = S.OWNER
   AND T.OBJECT_TYPE = S.OBJECT_TYPE
   AND T.OBJECT_NAME = S.OBJECT_NAME
)
WHEN MATCHED THEN
    UPDATE SET
        T.OBJECT_LABEL = S.OBJECT_LABEL
      , T.DESCRIPTION = S.DESCRIPTION
      , T.USE_YN = S.USE_YN
      , T.SORT_ORDER = S.SORT_ORDER
      , T.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN
    INSERT (
        OWNER
      , OBJECT_TYPE
      , OBJECT_NAME
      , OBJECT_LABEL
      , DESCRIPTION
      , USE_YN
      , SORT_ORDER
      , CREATED_AT
    ) VALUES (
        S.OWNER
      , S.OBJECT_TYPE
      , S.OBJECT_NAME
      , S.OBJECT_LABEL
      , S.DESCRIPTION
      , S.USE_YN
      , S.SORT_ORDER
      , SYSTIMESTAMP
    )
;

-- [M90001_OBJECT_ID_SELECT]
-- Select the object master key after upsert.
SELECT OBJECT_ID
  FROM INIT$_TB_OBJECT
 WHERE OWNER = :owner
   AND OBJECT_TYPE = :objectType
   AND OBJECT_NAME = :objectName
;

-- [M90001_OBJECT_DETAIL_COUNT]
-- Count saved child detail rows before deleting the object master.
SELECT COUNT(*) AS DETAIL_COUNT
  FROM INIT$_TB_OBJECT_DETAIL
 WHERE OBJECT_ID = :objectId
;

-- [M90001_OBJECT_DELETE_SCOPE]
-- Select object master rows that must be removed together.
-- PACKAGE deletes include registered package member objects.
SELECT OBJECT_ID
  FROM INIT$_TB_OBJECT
 WHERE (
          (:objectId IS NOT NULL AND OBJECT_ID = :objectId)
       OR (
              OWNER = :owner
          AND OBJECT_TYPE = :objectType
          AND OBJECT_NAME = :objectName
          )
       OR (
              :objectType = 'PACKAGE'
          AND OWNER = :owner
          AND OBJECT_TYPE IN ('PACKAGE_PROCEDURE', 'PACKAGE_FUNCTION')
          AND OBJECT_NAME LIKE :objectName || '.%'
          )
       )
 ORDER BY CASE WHEN OBJECT_ID = :objectId THEN 0 ELSE 1 END,
          OBJECT_ID
;

-- [M90001_OBJECT_REFERENCE_COUNT]
-- Count saved data work jobs that reference the registered object.
SELECT COUNT(*) AS REF_COUNT
  FROM INIT$_TB_DATA_WORK_JOB
 WHERE EXEC_OBJECT_ID = :objectId
;

-- [M90001_OBJECT_REFERENCE_CLEAR]
-- Keep saved job text metadata, but detach the FK before deleting object master.
UPDATE INIT$_TB_DATA_WORK_JOB
   SET EXEC_OBJECT_ID = NULL
     , UPDATED_AT = SYSTIMESTAMP
 WHERE EXEC_OBJECT_ID = :objectId
;

-- [M90001_OBJECT_DETAIL]
-- DB dictionary rows are the base; saved detail rows are left-joined for editable descriptions/defaults.
WITH SAVED AS (
    SELECT OBJECT_ID
         , OWNER
         , OBJECT_TYPE
         , OBJECT_NAME
         , ITEM_NAME
         , ITEM_VALUE
         , ITEM_DESC
         , ITEM_DEFAULT
         , ITEM_ORDER
         , 'SAVED' AS DETAIL_SOURCE
      FROM INIT$_TB_OBJECT_DETAIL
     WHERE (
              (:objectId IS NOT NULL AND OBJECT_ID = :objectId)
           OR (:objectId IS NULL AND OWNER = :owner AND OBJECT_TYPE = :objectType AND OBJECT_NAME = :objectName)
           )
),
DICTIONARY_ROWS AS (
    SELECT CAST(:objectId AS NUMBER) AS OBJECT_ID
         , C.COLUMN_NAME AS ITEM_NAME
         , C.DATA_TYPE
            || CASE
                WHEN C.DATA_TYPE IN ('VARCHAR2', 'CHAR', 'NVARCHAR2', 'NCHAR') THEN '(' || C.CHAR_LENGTH || ')'
                WHEN C.DATA_TYPE = 'NUMBER' AND C.DATA_PRECISION IS NOT NULL THEN '(' || C.DATA_PRECISION || NVL2(C.DATA_SCALE, ',' || C.DATA_SCALE, '') || ')'
                ELSE ''
               END
            || CASE WHEN C.NULLABLE = 'N' THEN ' NOT NULL' ELSE '' END AS ITEM_VALUE
         , CC.COMMENTS AS ITEM_DESC
         , CAST(NULL AS VARCHAR2(4000)) AS ITEM_DEFAULT
         , C.COLUMN_ID AS ITEM_ORDER
         , 'DICTIONARY' AS DETAIL_SOURCE
      FROM ALL_TAB_COLUMNS C
      LEFT JOIN ALL_COL_COMMENTS CC
        ON CC.OWNER = C.OWNER
       AND CC.TABLE_NAME = C.TABLE_NAME
       AND CC.COLUMN_NAME = C.COLUMN_NAME
     WHERE :objectType = 'TABLE'
       AND C.OWNER = :owner
       AND C.TABLE_NAME = :objectName
    UNION ALL
    SELECT CAST(:objectId AS NUMBER) AS OBJECT_ID
         , A.ARGUMENT_NAME AS ITEM_NAME
         , A.IN_OUT || ' ' || A.DATA_TYPE AS ITEM_VALUE
         , CAST(NULL AS VARCHAR2(4000)) AS ITEM_DESC
         , CAST(NULL AS VARCHAR2(4000)) AS ITEM_DEFAULT
         , A.POSITION AS ITEM_ORDER
         , 'DICTIONARY' AS DETAIL_SOURCE
      FROM ALL_ARGUMENTS A
     WHERE :objectType IN ('PROCEDURE', 'FUNCTION')
       AND A.OWNER = :owner
       AND A.OBJECT_NAME = :objectName
       AND A.ARGUMENT_NAME IS NOT NULL
    UNION ALL
    SELECT CAST(:objectId AS NUMBER) AS OBJECT_ID
         , P.PROCEDURE_NAME AS ITEM_NAME
         , CASE
            WHEN EXISTS (
                SELECT 1
                  FROM ALL_ARGUMENTS A
                 WHERE A.OWNER = P.OWNER
                   AND A.PACKAGE_NAME = P.OBJECT_NAME
                   AND A.OBJECT_NAME = P.PROCEDURE_NAME
                   AND A.POSITION = 0
            ) THEN 'FUNCTION'
            ELSE 'PROCEDURE'
        END AS ITEM_VALUE
         , CAST(NULL AS VARCHAR2(4000)) AS ITEM_DESC
         , CAST(NULL AS VARCHAR2(4000)) AS ITEM_DEFAULT
         , ROW_NUMBER() OVER (ORDER BY P.PROCEDURE_NAME) AS ITEM_ORDER
         , 'DICTIONARY' AS DETAIL_SOURCE
      FROM ALL_PROCEDURES P
     WHERE :objectType = 'PACKAGE'
       AND P.OWNER = :owner
       AND P.OBJECT_NAME = :objectName
       AND P.PROCEDURE_NAME IS NOT NULL
    UNION ALL
    SELECT CAST(:objectId AS NUMBER) AS OBJECT_ID
         , A.ARGUMENT_NAME AS ITEM_NAME
         , A.IN_OUT || ' ' || A.DATA_TYPE AS ITEM_VALUE
         , CAST(NULL AS VARCHAR2(4000)) AS ITEM_DESC
         , CAST(NULL AS VARCHAR2(4000)) AS ITEM_DEFAULT
         , A.POSITION AS ITEM_ORDER
         , 'DICTIONARY' AS DETAIL_SOURCE
      FROM ALL_ARGUMENTS A
     WHERE :objectType IN ('PACKAGE_PROCEDURE', 'PACKAGE_FUNCTION')
       AND A.OWNER = :owner
       AND A.PACKAGE_NAME = REGEXP_SUBSTR(:objectName, '^[^.]+')
       AND A.OBJECT_NAME = REGEXP_SUBSTR(:objectName, '[^.]+$', 1, 1)
       AND A.ARGUMENT_NAME IS NOT NULL
    UNION ALL
    SELECT CAST(:objectId AS NUMBER) AS OBJECT_ID
         , A.ATTRIBUTE_NAME AS ITEM_NAME
         , A.ATTRIBUTE_TYPE || NVL2(A.DATA_TYPE, ' ' || A.DATA_TYPE, '') AS ITEM_VALUE
         , CAST(NULL AS VARCHAR2(4000)) AS ITEM_DESC
         , CAST(NULL AS VARCHAR2(4000)) AS ITEM_DEFAULT
         , ROW_NUMBER() OVER (ORDER BY A.ATTRIBUTE_NAME) AS ITEM_ORDER
         , 'DICTIONARY' AS DETAIL_SOURCE
      FROM ALL_MINING_MODEL_ATTRIBUTES A
     WHERE :objectType = 'MINING_MODEL'
       AND A.OWNER = :owner
       AND A.MODEL_NAME = :objectName
)
SELECT COALESCE(S.OBJECT_ID, D.OBJECT_ID) AS OBJECT_ID
     , D.ITEM_NAME
     , D.ITEM_VALUE
     , COALESCE(S.ITEM_DESC, D.ITEM_DESC) AS ITEM_DESC
     , S.ITEM_DEFAULT
     , D.ITEM_ORDER
     , CASE WHEN S.OBJECT_ID IS NOT NULL THEN 'SAVED' ELSE D.DETAIL_SOURCE END AS DETAIL_SOURCE
  FROM DICTIONARY_ROWS D
  LEFT JOIN SAVED S
    ON S.ITEM_NAME = D.ITEM_NAME
   AND (
           (:objectId IS NOT NULL AND S.OBJECT_ID = :objectId)
        OR (:objectId IS NULL AND S.OWNER = :owner AND S.OBJECT_TYPE = :objectType AND S.OBJECT_NAME = :objectName)
       )
 ORDER BY D.ITEM_ORDER
;

-- [M90001_OBJECT_DETAIL_DELETE]
-- Delete previous saved metadata for the selected object before inserting the edited list.
DELETE FROM INIT$_TB_OBJECT_DETAIL
 WHERE OBJECT_ID = :objectId
;

-- [M90001_OBJECT_DELETE]
-- Delete the selected object master after its child detail rows have been deleted.
DELETE FROM INIT$_TB_OBJECT
 WHERE OBJECT_ID = :objectId
;

-- [M90001_OBJECT_DETAIL_INSERT]
-- Sample insert target table:
-- INIT$_TB_OBJECT_DETAIL(OBJECT_ID, OWNER, OBJECT_TYPE, OBJECT_NAME, ITEM_NAME, ITEM_VALUE, ITEM_DESC, ITEM_DEFAULT, ITEM_ORDER, CREATED_AT)
INSERT INTO INIT$_TB_OBJECT_DETAIL (
    OBJECT_ID
  , OWNER
  , OBJECT_TYPE
  , OBJECT_NAME
  , ITEM_NAME
  , ITEM_VALUE
  , ITEM_DESC
  , ITEM_DEFAULT
  , ITEM_ORDER
  , CREATED_AT
) VALUES (
    :objectId
  , :owner
  , :objectType
  , :objectName
  , :itemName
  , :itemValue
  , :itemDesc
  , :itemDefault
  , :itemOrder
  , SYSTIMESTAMP
)
;
