-- M90003 Oracle Machine Learning model training and lifecycle management

-- [M90003_MODEL_FAMILY_LIST]
WITH MODEL_KEYS AS
     (
      SELECT 'COLUMN_TYPE' AS MODEL_KEY FROM DUAL
       UNION
      SELECT MODEL_KEY FROM "INIT$_TB_OML_MODEL_REGISTRY"
       UNION
      SELECT MODEL_KEY FROM "INIT$_TB_OML_TRAIN_RUN"
     )
SELECT K.MODEL_KEY
     , (SELECT COUNT(*)
          FROM "INIT$_TB_OML_MODEL_REGISTRY" R
         WHERE R.MODEL_KEY = K.MODEL_KEY) AS MODEL_COUNT
     , (SELECT COUNT(*)
          FROM "INIT$_TB_OML_TRAIN_RUN" T
         WHERE T.MODEL_KEY = K.MODEL_KEY) AS RUN_COUNT
     , (SELECT A.MODEL_VERSION_ID
          FROM "INIT$_TB_OML_ACTIVE_MODEL" A
         WHERE A.MODEL_KEY = K.MODEL_KEY) AS ACTIVE_MODEL_VERSION_ID
     , (SELECT MAX(R.VERSION_NO)
          FROM "INIT$_TB_OML_MODEL_REGISTRY" R
         WHERE R.MODEL_KEY = K.MODEL_KEY) AS LATEST_VERSION_NO
  FROM MODEL_KEYS K
 ORDER BY CASE K.MODEL_KEY WHEN 'COLUMN_TYPE' THEN 0 ELSE 1 END
        , K.MODEL_KEY
;

-- [M90003_MODEL_SUMMARY]
SELECT R.MODEL_VERSION_ID
     , R.VERSION_NO
     , R.PHYSICAL_MODEL_NAME
     , R.ALGORITHM_CODE
     , R.FEATURE_VERSION
     , R.STATUS_CODE AS MODEL_STATUS_CODE
     , R.MACRO_F1
     , R.BALANCED_ACCURACY
     , R.VALID_ROW_COUNT
     , R.TEST_ROW_COUNT
     , R.CREATED_AT AS TRAINED_AT
     , 0 AS CONFIRMED_ELIGIBLE_COUNT
     , 0 AS EXCLUDED_AUTO_COUNT
     , 0 AS EXCLUDED_LEGACY_COUNT
     , 0 AS CONFLICT_COUNT
     , 0 AS DUPLICATE_COUNT
     , 0 AS TOTAL_PROFILE_COUNT
     , 0 AS IMPORTED_GOLD_COUNT
     , 0 AS USER_CONFIRMED_COUNT
     , 0 AS ADDITIONAL_USER_COUNT
     , CAST(NULL AS TIMESTAMP) AS LAST_SUCCESSFUL_TRAINED_AT
  FROM "INIT$_TB_OML_ACTIVE_MODEL" A
  JOIN "INIT$_TB_OML_MODEL_REGISTRY" R
    ON R.MODEL_VERSION_ID = A.MODEL_VERSION_ID
 WHERE 1=1
   AND A.MODEL_KEY = :modelKey
;

-- [M90003_SUMMARY]
WITH PROFILE_RUN_PREDICTION AS
     (
      SELECT X.RUN_SOURCE_TYPE
           , X.RUN_ID
           , X.OWNER
           , X.TABLE_NAME
           , X.COLUMN_NAME
           , COALESCE(X.BASE_TYPE_CODE, INIT$_FN_TYPE_CODE(X.BASE_PREDICTED_TYPE)) AS BASE_TYPE_CODE
           , COALESCE(X.MODL_TYPE_CODE, INIT$_FN_TYPE_CODE(X.MODL_PREDICTED_TYPE)) AS MODL_TYPE_CODE
        FROM
           (
            SELECT P.*
                 , ROW_NUMBER() OVER (
                       PARTITION BY P.RUN_SOURCE_TYPE, P.RUN_ID, P.OWNER, P.TABLE_NAME, P.COLUMN_NAME
                           ORDER BY P.CREATE_DT DESC
                                  , NVL(P.MODEL_VERSION_ID, -1) DESC
                                  , P.MODEL_NAME DESC
                   ) AS PREDICTION_RN
              FROM "INIT$_TB_COLTYPE_RESULT" P
           ) X
       WHERE 1=1
         AND X.PREDICTION_RN = 1
     )
   , CONFIRMED_V2_PROFILE AS
     (
      SELECT F.PROFILE_ID
           , F.RUN_SOURCE_TYPE
           , F.RUN_ID
           , F.OWNER
           , F.TABLE_NAME
           , F.COLUMN_NAME
           , F.DATA_TYPE
           , F.TOTAL_ROWS
           , F.NON_NULL_ROWS
           , F.SAMPLE_ROWS
           , F.SAMPLE_NOT_NULL_ROWS
           , F.NUM_DISTINCT
           , F.SAMPLE_DISTINCT
           , F.DISTINCT_RATIO
           , F.NULL_RATIO
           , F.LOG_DATA_TYPE
           , F.ENTROPY
           , F.NORM_ENTROPY
           , F.NUMERIC_RATIO
           , F.INTEGER_RATIO
           , F.MIN_NUM_VALUE
           , F.MAX_NUM_VALUE
           , F.AVG_TEXT_LENGTH
           , F.MAX_TEXT_LENGTH
        FROM "INIT$_TB_COLTYPE_PROFILE" F
       WHERE 1=1
         AND F.FEATURE_VERSION = 'V2'
     )
   , LAST_SUCCESSFUL_TRAINING AS
     (
      SELECT MAX(T.FINISHED_AT) AS LAST_SUCCESSFUL_TRAINED_AT
        FROM "INIT$_TB_OML_TRAIN_RUN" T
       WHERE 1=1
         AND T.MODEL_KEY = :modelKey
         AND T.STATUS_CODE = 'SUCCESS'
     )
   , LABEL_COUNTS AS
     (
      SELECT COUNT(
                 CASE
                     WHEN L.CONFIRMED_YN = 'Y'
                      AND L.LABEL_SOURCE IN ('USER_CONFIRMED', 'IMPORTED_GOLD')
                      AND F.OWNER IS NOT NULL
                     THEN 1
                 END
             ) AS RAW_CONFIRMED_ELIGIBLE_COUNT
           , COUNT(
                 CASE
                     WHEN L.LABEL_SOURCE IN ('AUTO_RULE', 'AUTO_MODEL', 'AUTO_BOTH')
                     THEN 1
                 END
             ) AS EXCLUDED_AUTO_COUNT
           , COUNT(
                 CASE
                     WHEN L.LABEL_SOURCE = 'LEGACY_UNKNOWN'
                     THEN 1
                 END
             ) AS EXCLUDED_LEGACY_COUNT
           , COUNT(
                 CASE
                     WHEN L.CONFIRMED_YN = 'Y'
                      AND L.LABEL_SOURCE IN ('USER_CONFIRMED', 'IMPORTED_GOLD')
                      AND (
                             P.BASE_TYPE_CODE IS NOT NULL AND P.BASE_TYPE_CODE <> L.TYPE_CODE
                          OR P.MODL_TYPE_CODE IS NOT NULL AND P.MODL_TYPE_CODE <> L.TYPE_CODE
                      )
                     THEN 1
                 END
             ) AS CONFLICT_COUNT
           , COUNT(
                 CASE
                     WHEN L.CONFIRMED_YN = 'Y'
                      AND L.LABEL_SOURCE = 'IMPORTED_GOLD'
                      AND F.OWNER IS NOT NULL
                     THEN 1
                 END
             ) AS IMPORTED_GOLD_COUNT
           , COUNT(
                 CASE
                     WHEN L.CONFIRMED_YN = 'Y'
                      AND L.LABEL_SOURCE = 'USER_CONFIRMED'
                      AND F.OWNER IS NOT NULL
                     THEN 1
                 END
             ) AS USER_CONFIRMED_COUNT
           , COUNT(
                 CASE
                     WHEN L.CONFIRMED_YN = 'Y'
                      AND L.LABEL_SOURCE = 'USER_CONFIRMED'
                      AND F.OWNER IS NOT NULL
                      AND (
                             S.LAST_SUCCESSFUL_TRAINED_AT IS NULL
                          OR L.UPDATED_AT > S.LAST_SUCCESSFUL_TRAINED_AT
                      )
                     THEN 1
                 END
             ) AS ADDITIONAL_USER_COUNT
           , MAX(S.LAST_SUCCESSFUL_TRAINED_AT) AS LAST_SUCCESSFUL_TRAINED_AT
        FROM "INIT$_TB_COLTYPE_LABEL" L
       CROSS JOIN LAST_SUCCESSFUL_TRAINING S
        LEFT JOIN CONFIRMED_V2_PROFILE F
          ON F.PROFILE_ID = L.SOURCE_PROFILE_ID
         AND F.OWNER = L.OWNER
         AND F.TABLE_NAME = L.TABLE_NAME
         AND F.COLUMN_NAME = L.COLUMN_NAME
        LEFT JOIN PROFILE_RUN_PREDICTION P
          ON P.RUN_SOURCE_TYPE = F.RUN_SOURCE_TYPE
         AND P.RUN_ID = F.RUN_ID
         AND P.OWNER = L.OWNER
         AND P.TABLE_NAME = L.TABLE_NAME
         AND P.COLUMN_NAME = L.COLUMN_NAME
     )
   , ELIGIBLE_PROFILE AS
     (
      SELECT CAST(NVL(F.DATA_TYPE, 'UNKNOWN') AS VARCHAR2(128)) AS DATA_TYPE
           , CAST(NVL(F.TOTAL_ROWS, 0) AS NUMBER) AS TOTAL_ROWS
           , CAST(NVL(F.NON_NULL_ROWS, 0) AS NUMBER) AS NON_NULL_ROWS
           , CAST(NVL(F.SAMPLE_ROWS, 0) AS NUMBER) AS SAMPLE_ROWS
           , CAST(NVL(F.SAMPLE_NOT_NULL_ROWS, 0) AS NUMBER) AS SAMPLE_NOT_NULL_ROWS
           , CAST(NVL(F.NUM_DISTINCT, 0) AS NUMBER) AS NUM_DISTINCT
           , CAST(NVL(F.SAMPLE_DISTINCT, 0) AS NUMBER) AS SAMPLE_DISTINCT
           , CAST(NVL(F.DISTINCT_RATIO, 0) AS NUMBER) AS DIST_VAL_RT
           , CAST(NVL(F.NULL_RATIO, 0) AS NUMBER) AS NULL_RATIO
           , CAST(NVL(F.LOG_DATA_TYPE, 'UNKNOWN') AS VARCHAR2(30)) AS LOG_DATA_TYPE
           , CAST(NVL(F.ENTROPY, 0) AS NUMBER) AS ENTROPY
           , CAST(NVL(F.NORM_ENTROPY, 0) AS NUMBER) AS NORM_ENTROPY
           , CAST(NVL(F.NUMERIC_RATIO, 0) AS NUMBER) AS NUMERIC_RATIO
           , CAST(NVL(F.INTEGER_RATIO, 0) AS NUMBER) AS INTEGER_RATIO
           , CAST(NVL(F.MIN_NUM_VALUE, 0) AS NUMBER) AS MIN_NUM_VALUE
           , CAST(NVL(F.MAX_NUM_VALUE, 0) AS NUMBER) AS MAX_NUM_VALUE
           , CAST(NVL(F.AVG_TEXT_LENGTH, 0) AS NUMBER) AS AVG_TEXT_LENGTH
           , CAST(NVL(F.MAX_TEXT_LENGTH, 0) AS NUMBER) AS MAX_TEXT_LENGTH
           , CAST(L.TYPE_CODE AS VARCHAR2(40)) AS TYPE_CODE
        FROM "INIT$_TB_COLTYPE_LABEL" L
        JOIN CONFIRMED_V2_PROFILE F
          ON F.PROFILE_ID = L.SOURCE_PROFILE_ID
         AND F.OWNER = L.OWNER
         AND F.TABLE_NAME = L.TABLE_NAME
         AND F.COLUMN_NAME = L.COLUMN_NAME
       WHERE 1=1
         AND L.CONFIRMED_YN = 'Y'
         AND L.LABEL_SOURCE IN ('USER_CONFIRMED', 'IMPORTED_GOLD')
         AND L.TYPE_CODE IS NOT NULL
     )
   , SIGNED_ELIGIBLE AS
     (
      SELECT RAWTOHEX(
                 STANDARD_HASH(
                     NVL(CAST(E.DATA_TYPE AS VARCHAR2(128)), 'UNKNOWN')
                     || CHR(31) || TO_CHAR(NVL(E.TOTAL_ROWS, 0), 'TM9', 'NLS_NUMERIC_CHARACTERS=.,')
                     || CHR(31) || TO_CHAR(NVL(E.NON_NULL_ROWS, 0), 'TM9', 'NLS_NUMERIC_CHARACTERS=.,')
                     || CHR(31) || TO_CHAR(NVL(E.SAMPLE_ROWS, 0), 'TM9', 'NLS_NUMERIC_CHARACTERS=.,')
                     || CHR(31) || TO_CHAR(NVL(E.SAMPLE_NOT_NULL_ROWS, 0), 'TM9', 'NLS_NUMERIC_CHARACTERS=.,')
                     || CHR(31) || TO_CHAR(NVL(E.NUM_DISTINCT, 0), 'TM9', 'NLS_NUMERIC_CHARACTERS=.,')
                     || CHR(31) || TO_CHAR(NVL(E.SAMPLE_DISTINCT, 0), 'TM9', 'NLS_NUMERIC_CHARACTERS=.,')
                     || CHR(31) || TO_CHAR(NVL(E.DIST_VAL_RT, 0), 'TM9', 'NLS_NUMERIC_CHARACTERS=.,')
                     || CHR(31) || TO_CHAR(NVL(E.NULL_RATIO, 0), 'TM9', 'NLS_NUMERIC_CHARACTERS=.,')
                     || CHR(31) || NVL(CAST(E.LOG_DATA_TYPE AS VARCHAR2(30)), 'UNKNOWN')
                     || CHR(31) || TO_CHAR(NVL(E.ENTROPY, 0), 'TM9', 'NLS_NUMERIC_CHARACTERS=.,')
                     || CHR(31) || TO_CHAR(NVL(E.NORM_ENTROPY, 0), 'TM9', 'NLS_NUMERIC_CHARACTERS=.,')
                     || CHR(31) || TO_CHAR(NVL(E.NUMERIC_RATIO, 0), 'TM9', 'NLS_NUMERIC_CHARACTERS=.,')
                     || CHR(31) || TO_CHAR(NVL(E.INTEGER_RATIO, 0), 'TM9', 'NLS_NUMERIC_CHARACTERS=.,')
                     || CHR(31) || TO_CHAR(NVL(E.MIN_NUM_VALUE, 0), 'TM9', 'NLS_NUMERIC_CHARACTERS=.,')
                     || CHR(31) || TO_CHAR(NVL(E.MAX_NUM_VALUE, 0), 'TM9', 'NLS_NUMERIC_CHARACTERS=.,')
                     || CHR(31) || TO_CHAR(NVL(E.AVG_TEXT_LENGTH, 0), 'TM9', 'NLS_NUMERIC_CHARACTERS=.,')
                     || CHR(31) || TO_CHAR(NVL(E.MAX_TEXT_LENGTH, 0), 'TM9', 'NLS_NUMERIC_CHARACTERS=.,')
                   , 'SHA256'
                 )
             ) AS FEATURE_SIGNATURE
           , E.*
        FROM ELIGIBLE_PROFILE E
     )
   , DEDUP_ELIGIBLE AS
     (
      SELECT DISTINCT E.FEATURE_SIGNATURE
           , E.DATA_TYPE
           , E.TOTAL_ROWS
           , E.NON_NULL_ROWS
           , E.SAMPLE_ROWS
           , E.SAMPLE_NOT_NULL_ROWS
           , E.NUM_DISTINCT
           , E.SAMPLE_DISTINCT
           , E.DIST_VAL_RT
           , E.NULL_RATIO
           , E.LOG_DATA_TYPE
           , E.ENTROPY
           , E.NORM_ENTROPY
           , E.NUMERIC_RATIO
           , E.INTEGER_RATIO
           , E.MIN_NUM_VALUE
           , E.MAX_NUM_VALUE
           , E.AVG_TEXT_LENGTH
           , E.MAX_TEXT_LENGTH
           , E.TYPE_CODE
        FROM SIGNED_ELIGIBLE E
     )
   , TRAINING_COUNTS AS
     (
      SELECT COUNT(*) AS CONFIRMED_ELIGIBLE_COUNT
           , GREATEST(MAX(L.RAW_CONFIRMED_ELIGIBLE_COUNT) - COUNT(*), 0) AS DUPLICATE_COUNT
        FROM DEDUP_ELIGIBLE E
       CROSS JOIN LABEL_COUNTS L
     )
   , PROFILE_COUNTS AS
     (
      SELECT COUNT(*) AS TOTAL_PROFILE_COUNT
        FROM "INIT$_TB_COLTYPE_PROFILE" F
       WHERE 1=1
         AND F.FEATURE_VERSION = 'V2'
     )
   , ACTIVE_MODEL AS
     (
      SELECT R.MODEL_VERSION_ID
           , R.VERSION_NO
           , R.PHYSICAL_MODEL_NAME
           , R.ALGORITHM_CODE
           , R.FEATURE_VERSION
           , R.STATUS_CODE AS MODEL_STATUS_CODE
           , R.MACRO_F1
           , R.BALANCED_ACCURACY
           , R.VALID_ROW_COUNT
           , R.TEST_ROW_COUNT
           , R.CREATED_AT AS TRAINED_AT
        FROM "INIT$_TB_OML_ACTIVE_MODEL" A
        JOIN "INIT$_TB_OML_MODEL_REGISTRY" R
          ON R.MODEL_VERSION_ID = A.MODEL_VERSION_ID
       WHERE 1=1
         AND A.MODEL_KEY = :modelKey
     )
SELECT A.MODEL_VERSION_ID
     , A.VERSION_NO
     , A.PHYSICAL_MODEL_NAME
     , A.ALGORITHM_CODE
     , A.FEATURE_VERSION
     , A.MODEL_STATUS_CODE
     , A.MACRO_F1
     , A.BALANCED_ACCURACY
     , A.VALID_ROW_COUNT
     , A.TEST_ROW_COUNT
     , A.TRAINED_AT
     , T.CONFIRMED_ELIGIBLE_COUNT
     , L.EXCLUDED_AUTO_COUNT
     , L.EXCLUDED_LEGACY_COUNT
     , L.CONFLICT_COUNT
     , T.DUPLICATE_COUNT
     , P.TOTAL_PROFILE_COUNT
     , L.IMPORTED_GOLD_COUNT
     , L.USER_CONFIRMED_COUNT
     , L.ADDITIONAL_USER_COUNT
     , L.LAST_SUCCESSFUL_TRAINED_AT
  FROM LABEL_COUNTS L
 CROSS JOIN TRAINING_COUNTS T
 CROSS JOIN PROFILE_COUNTS P
  LEFT JOIN ACTIVE_MODEL A
    ON 1=1
;

-- [M90003_ADDITIONAL_LABEL_INFO]
WITH LAST_SUCCESSFUL_TRAINING AS
     (
      SELECT MAX(T.FINISHED_AT) AS LAST_SUCCESSFUL_TRAINED_AT
        FROM "INIT$_TB_OML_TRAIN_RUN" T
       WHERE 1=1
         AND T.MODEL_KEY = :modelKey
         AND T.STATUS_CODE = 'SUCCESS'
     )
SELECT S.LAST_SUCCESSFUL_TRAINED_AT
     , COUNT(
           CASE
               WHEN L.CONFIRMED_YN = 'Y'
                AND L.LABEL_SOURCE = 'USER_CONFIRMED'
                AND (
                       S.LAST_SUCCESSFUL_TRAINED_AT IS NULL
                    OR L.UPDATED_AT > S.LAST_SUCCESSFUL_TRAINED_AT
                )
                AND EXISTS
                    (
                     SELECT 1
                       FROM "INIT$_TB_COLTYPE_PROFILE" F
                      WHERE 1=1
                        AND F.PROFILE_ID = L.SOURCE_PROFILE_ID
                        AND F.OWNER = L.OWNER
                        AND F.TABLE_NAME = L.TABLE_NAME
                        AND F.COLUMN_NAME = L.COLUMN_NAME
                        AND F.FEATURE_VERSION = 'V2'
                    )
               THEN 1
           END
       ) AS ADDITIONAL_USER_COUNT
  FROM LAST_SUCCESSFUL_TRAINING S
  LEFT JOIN "INIT$_TB_COLTYPE_LABEL" L
    ON 1=1
 GROUP BY S.LAST_SUCCESSFUL_TRAINED_AT
;

-- [M90003_ACTIVE_MODEL_METRIC_LIST]
SELECT M.SPLIT_CODE
     , M.ACTUAL_CLASS_CODE AS TYPE_CODE
     , M.PREDICTED_CLASS_CODE AS PREDICTED_TYPE_CODE
     , M.CLASS_GROUP_CODE AS TYPE_GROUP_CODE
     , M.METRIC_NAME
     , M.METRIC_VALUE
     , M.SUPPORT_COUNT
  FROM "INIT$_TB_OML_ACTIVE_MODEL" A
  JOIN "INIT$_TB_OML_MODEL_METRIC" M
    ON M.MODEL_VERSION_ID = A.MODEL_VERSION_ID
 WHERE 1=1
   AND A.MODEL_KEY = :modelKey
 ORDER BY M.SPLIT_CODE
        , NVL(M.CLASS_GROUP_CODE, '~')
        , NVL(M.ACTUAL_CLASS_CODE, '~')
        , NVL(M.PREDICTED_CLASS_CODE, '~')
        , M.METRIC_NAME
;

-- [M90003_DATASET_GROUP_DISTRIBUTION]
WITH ELIGIBLE_PROFILE AS
     (
      SELECT CAST(NVL(F.DATA_TYPE, 'UNKNOWN') AS VARCHAR2(128)) AS DATA_TYPE
           , CAST(NVL(F.TOTAL_ROWS, 0) AS NUMBER) AS TOTAL_ROWS
           , CAST(NVL(F.NON_NULL_ROWS, 0) AS NUMBER) AS NON_NULL_ROWS
           , CAST(NVL(F.SAMPLE_ROWS, 0) AS NUMBER) AS SAMPLE_ROWS
           , CAST(NVL(F.SAMPLE_NOT_NULL_ROWS, 0) AS NUMBER) AS SAMPLE_NOT_NULL_ROWS
           , CAST(NVL(F.NUM_DISTINCT, 0) AS NUMBER) AS NUM_DISTINCT
           , CAST(NVL(F.SAMPLE_DISTINCT, 0) AS NUMBER) AS SAMPLE_DISTINCT
           , CAST(NVL(F.DISTINCT_RATIO, 0) AS NUMBER) AS DIST_VAL_RT
           , CAST(NVL(F.NULL_RATIO, 0) AS NUMBER) AS NULL_RATIO
           , CAST(NVL(F.LOG_DATA_TYPE, 'UNKNOWN') AS VARCHAR2(30)) AS LOG_DATA_TYPE
           , CAST(NVL(F.ENTROPY, 0) AS NUMBER) AS ENTROPY
           , CAST(NVL(F.NORM_ENTROPY, 0) AS NUMBER) AS NORM_ENTROPY
           , CAST(NVL(F.NUMERIC_RATIO, 0) AS NUMBER) AS NUMERIC_RATIO
           , CAST(NVL(F.INTEGER_RATIO, 0) AS NUMBER) AS INTEGER_RATIO
           , CAST(NVL(F.MIN_NUM_VALUE, 0) AS NUMBER) AS MIN_NUM_VALUE
           , CAST(NVL(F.MAX_NUM_VALUE, 0) AS NUMBER) AS MAX_NUM_VALUE
           , CAST(NVL(F.AVG_TEXT_LENGTH, 0) AS NUMBER) AS AVG_TEXT_LENGTH
           , CAST(NVL(F.MAX_TEXT_LENGTH, 0) AS NUMBER) AS MAX_TEXT_LENGTH
           , CAST(L.TYPE_CODE AS VARCHAR2(40)) AS TYPE_CODE
        FROM "INIT$_TB_COLTYPE_LABEL" L
        JOIN "INIT$_TB_COLTYPE_PROFILE" F
          ON F.PROFILE_ID = L.SOURCE_PROFILE_ID
         AND F.OWNER = L.OWNER
         AND F.TABLE_NAME = L.TABLE_NAME
         AND F.COLUMN_NAME = L.COLUMN_NAME
         AND F.FEATURE_VERSION = 'V2'
       WHERE 1=1
         AND L.CONFIRMED_YN = 'Y'
         AND L.LABEL_SOURCE IN ('USER_CONFIRMED', 'IMPORTED_GOLD')
         AND L.TYPE_CODE IS NOT NULL
     )
   , SIGNED_ELIGIBLE AS
     (
      SELECT RAWTOHEX(
                 STANDARD_HASH(
                     NVL(CAST(E.DATA_TYPE AS VARCHAR2(128)), 'UNKNOWN')
                     || CHR(31) || TO_CHAR(NVL(E.TOTAL_ROWS, 0), 'TM9', 'NLS_NUMERIC_CHARACTERS=.,')
                     || CHR(31) || TO_CHAR(NVL(E.NON_NULL_ROWS, 0), 'TM9', 'NLS_NUMERIC_CHARACTERS=.,')
                     || CHR(31) || TO_CHAR(NVL(E.SAMPLE_ROWS, 0), 'TM9', 'NLS_NUMERIC_CHARACTERS=.,')
                     || CHR(31) || TO_CHAR(NVL(E.SAMPLE_NOT_NULL_ROWS, 0), 'TM9', 'NLS_NUMERIC_CHARACTERS=.,')
                     || CHR(31) || TO_CHAR(NVL(E.NUM_DISTINCT, 0), 'TM9', 'NLS_NUMERIC_CHARACTERS=.,')
                     || CHR(31) || TO_CHAR(NVL(E.SAMPLE_DISTINCT, 0), 'TM9', 'NLS_NUMERIC_CHARACTERS=.,')
                     || CHR(31) || TO_CHAR(NVL(E.DIST_VAL_RT, 0), 'TM9', 'NLS_NUMERIC_CHARACTERS=.,')
                     || CHR(31) || TO_CHAR(NVL(E.NULL_RATIO, 0), 'TM9', 'NLS_NUMERIC_CHARACTERS=.,')
                     || CHR(31) || NVL(CAST(E.LOG_DATA_TYPE AS VARCHAR2(30)), 'UNKNOWN')
                     || CHR(31) || TO_CHAR(NVL(E.ENTROPY, 0), 'TM9', 'NLS_NUMERIC_CHARACTERS=.,')
                     || CHR(31) || TO_CHAR(NVL(E.NORM_ENTROPY, 0), 'TM9', 'NLS_NUMERIC_CHARACTERS=.,')
                     || CHR(31) || TO_CHAR(NVL(E.NUMERIC_RATIO, 0), 'TM9', 'NLS_NUMERIC_CHARACTERS=.,')
                     || CHR(31) || TO_CHAR(NVL(E.INTEGER_RATIO, 0), 'TM9', 'NLS_NUMERIC_CHARACTERS=.,')
                     || CHR(31) || TO_CHAR(NVL(E.MIN_NUM_VALUE, 0), 'TM9', 'NLS_NUMERIC_CHARACTERS=.,')
                     || CHR(31) || TO_CHAR(NVL(E.MAX_NUM_VALUE, 0), 'TM9', 'NLS_NUMERIC_CHARACTERS=.,')
                     || CHR(31) || TO_CHAR(NVL(E.AVG_TEXT_LENGTH, 0), 'TM9', 'NLS_NUMERIC_CHARACTERS=.,')
                     || CHR(31) || TO_CHAR(NVL(E.MAX_TEXT_LENGTH, 0), 'TM9', 'NLS_NUMERIC_CHARACTERS=.,')
                   , 'SHA256'
                 )
             ) AS FEATURE_SIGNATURE
           , E.*
        FROM ELIGIBLE_PROFILE E
     )
   , DEDUP_ELIGIBLE AS
     (
      SELECT DISTINCT E.FEATURE_SIGNATURE
           , E.DATA_TYPE
           , E.TOTAL_ROWS
           , E.NON_NULL_ROWS
           , E.SAMPLE_ROWS
           , E.SAMPLE_NOT_NULL_ROWS
           , E.NUM_DISTINCT
           , E.SAMPLE_DISTINCT
           , E.DIST_VAL_RT
           , E.NULL_RATIO
           , E.LOG_DATA_TYPE
           , E.ENTROPY
           , E.NORM_ENTROPY
           , E.NUMERIC_RATIO
           , E.INTEGER_RATIO
           , E.MIN_NUM_VALUE
           , E.MAX_NUM_VALUE
           , E.AVG_TEXT_LENGTH
           , E.MAX_TEXT_LENGTH
           , E.TYPE_CODE
        FROM SIGNED_ELIGIBLE E
     )
SELECT INIT$_FN_TYPE_GROUP_CODE(E.TYPE_CODE) AS TYPE_GROUP_CODE
     , COUNT(*) AS LABEL_COUNT
     , ROUND(100 * COUNT(*) / NULLIF(SUM(COUNT(*)) OVER (), 0), 2) AS PERCENTAGE
  FROM DEDUP_ELIGIBLE E
 GROUP BY INIT$_FN_TYPE_GROUP_CODE(E.TYPE_CODE)
 ORDER BY CASE INIT$_FN_TYPE_GROUP_CODE(E.TYPE_CODE)
              WHEN 'CATEGORICAL' THEN 1
              WHEN 'CONTINUOUS' THEN 2
              ELSE 3
          END
;

-- [M90003_DATASET_DETAIL_DISTRIBUTION]
WITH ELIGIBLE_PROFILE AS
     (
      SELECT CAST(NVL(F.DATA_TYPE, 'UNKNOWN') AS VARCHAR2(128)) AS DATA_TYPE
           , CAST(NVL(F.TOTAL_ROWS, 0) AS NUMBER) AS TOTAL_ROWS
           , CAST(NVL(F.NON_NULL_ROWS, 0) AS NUMBER) AS NON_NULL_ROWS
           , CAST(NVL(F.SAMPLE_ROWS, 0) AS NUMBER) AS SAMPLE_ROWS
           , CAST(NVL(F.SAMPLE_NOT_NULL_ROWS, 0) AS NUMBER) AS SAMPLE_NOT_NULL_ROWS
           , CAST(NVL(F.NUM_DISTINCT, 0) AS NUMBER) AS NUM_DISTINCT
           , CAST(NVL(F.SAMPLE_DISTINCT, 0) AS NUMBER) AS SAMPLE_DISTINCT
           , CAST(NVL(F.DISTINCT_RATIO, 0) AS NUMBER) AS DIST_VAL_RT
           , CAST(NVL(F.NULL_RATIO, 0) AS NUMBER) AS NULL_RATIO
           , CAST(NVL(F.LOG_DATA_TYPE, 'UNKNOWN') AS VARCHAR2(30)) AS LOG_DATA_TYPE
           , CAST(NVL(F.ENTROPY, 0) AS NUMBER) AS ENTROPY
           , CAST(NVL(F.NORM_ENTROPY, 0) AS NUMBER) AS NORM_ENTROPY
           , CAST(NVL(F.NUMERIC_RATIO, 0) AS NUMBER) AS NUMERIC_RATIO
           , CAST(NVL(F.INTEGER_RATIO, 0) AS NUMBER) AS INTEGER_RATIO
           , CAST(NVL(F.MIN_NUM_VALUE, 0) AS NUMBER) AS MIN_NUM_VALUE
           , CAST(NVL(F.MAX_NUM_VALUE, 0) AS NUMBER) AS MAX_NUM_VALUE
           , CAST(NVL(F.AVG_TEXT_LENGTH, 0) AS NUMBER) AS AVG_TEXT_LENGTH
           , CAST(NVL(F.MAX_TEXT_LENGTH, 0) AS NUMBER) AS MAX_TEXT_LENGTH
           , CAST(L.TYPE_CODE AS VARCHAR2(40)) AS TYPE_CODE
        FROM "INIT$_TB_COLTYPE_LABEL" L
        JOIN "INIT$_TB_COLTYPE_PROFILE" F
          ON F.PROFILE_ID = L.SOURCE_PROFILE_ID
         AND F.OWNER = L.OWNER
         AND F.TABLE_NAME = L.TABLE_NAME
         AND F.COLUMN_NAME = L.COLUMN_NAME
         AND F.FEATURE_VERSION = 'V2'
       WHERE 1=1
         AND L.CONFIRMED_YN = 'Y'
         AND L.LABEL_SOURCE IN ('USER_CONFIRMED', 'IMPORTED_GOLD')
         AND L.TYPE_CODE IS NOT NULL
     )
   , SIGNED_ELIGIBLE AS
     (
      SELECT RAWTOHEX(
                 STANDARD_HASH(
                     NVL(CAST(E.DATA_TYPE AS VARCHAR2(128)), 'UNKNOWN')
                     || CHR(31) || TO_CHAR(NVL(E.TOTAL_ROWS, 0), 'TM9', 'NLS_NUMERIC_CHARACTERS=.,')
                     || CHR(31) || TO_CHAR(NVL(E.NON_NULL_ROWS, 0), 'TM9', 'NLS_NUMERIC_CHARACTERS=.,')
                     || CHR(31) || TO_CHAR(NVL(E.SAMPLE_ROWS, 0), 'TM9', 'NLS_NUMERIC_CHARACTERS=.,')
                     || CHR(31) || TO_CHAR(NVL(E.SAMPLE_NOT_NULL_ROWS, 0), 'TM9', 'NLS_NUMERIC_CHARACTERS=.,')
                     || CHR(31) || TO_CHAR(NVL(E.NUM_DISTINCT, 0), 'TM9', 'NLS_NUMERIC_CHARACTERS=.,')
                     || CHR(31) || TO_CHAR(NVL(E.SAMPLE_DISTINCT, 0), 'TM9', 'NLS_NUMERIC_CHARACTERS=.,')
                     || CHR(31) || TO_CHAR(NVL(E.DIST_VAL_RT, 0), 'TM9', 'NLS_NUMERIC_CHARACTERS=.,')
                     || CHR(31) || TO_CHAR(NVL(E.NULL_RATIO, 0), 'TM9', 'NLS_NUMERIC_CHARACTERS=.,')
                     || CHR(31) || NVL(CAST(E.LOG_DATA_TYPE AS VARCHAR2(30)), 'UNKNOWN')
                     || CHR(31) || TO_CHAR(NVL(E.ENTROPY, 0), 'TM9', 'NLS_NUMERIC_CHARACTERS=.,')
                     || CHR(31) || TO_CHAR(NVL(E.NORM_ENTROPY, 0), 'TM9', 'NLS_NUMERIC_CHARACTERS=.,')
                     || CHR(31) || TO_CHAR(NVL(E.NUMERIC_RATIO, 0), 'TM9', 'NLS_NUMERIC_CHARACTERS=.,')
                     || CHR(31) || TO_CHAR(NVL(E.INTEGER_RATIO, 0), 'TM9', 'NLS_NUMERIC_CHARACTERS=.,')
                     || CHR(31) || TO_CHAR(NVL(E.MIN_NUM_VALUE, 0), 'TM9', 'NLS_NUMERIC_CHARACTERS=.,')
                     || CHR(31) || TO_CHAR(NVL(E.MAX_NUM_VALUE, 0), 'TM9', 'NLS_NUMERIC_CHARACTERS=.,')
                     || CHR(31) || TO_CHAR(NVL(E.AVG_TEXT_LENGTH, 0), 'TM9', 'NLS_NUMERIC_CHARACTERS=.,')
                     || CHR(31) || TO_CHAR(NVL(E.MAX_TEXT_LENGTH, 0), 'TM9', 'NLS_NUMERIC_CHARACTERS=.,')
                   , 'SHA256'
                 )
             ) AS FEATURE_SIGNATURE
           , E.*
        FROM ELIGIBLE_PROFILE E
     )
   , DEDUP_ELIGIBLE AS
     (
      SELECT DISTINCT E.FEATURE_SIGNATURE
           , E.DATA_TYPE
           , E.TOTAL_ROWS
           , E.NON_NULL_ROWS
           , E.SAMPLE_ROWS
           , E.SAMPLE_NOT_NULL_ROWS
           , E.NUM_DISTINCT
           , E.SAMPLE_DISTINCT
           , E.DIST_VAL_RT
           , E.NULL_RATIO
           , E.LOG_DATA_TYPE
           , E.ENTROPY
           , E.NORM_ENTROPY
           , E.NUMERIC_RATIO
           , E.INTEGER_RATIO
           , E.MIN_NUM_VALUE
           , E.MAX_NUM_VALUE
           , E.AVG_TEXT_LENGTH
           , E.MAX_TEXT_LENGTH
           , E.TYPE_CODE
        FROM SIGNED_ELIGIBLE E
     )
SELECT E.TYPE_CODE
     , INIT$_FN_TYPE_GROUP_CODE(E.TYPE_CODE) AS TYPE_GROUP_CODE
     , COUNT(*) AS LABEL_COUNT
     , ROUND(100 * COUNT(*) / NULLIF(SUM(COUNT(*)) OVER (), 0), 2) AS PERCENTAGE
  FROM DEDUP_ELIGIBLE E
 GROUP BY E.TYPE_CODE
        , INIT$_FN_TYPE_GROUP_CODE(E.TYPE_CODE)
 ORDER BY INIT$_FN_TYPE_GROUP_CODE(E.TYPE_CODE)
        , E.TYPE_CODE
;

-- [M90003_LABEL_LIST]
WITH PROFILE_COUNTS AS
     (
      SELECT F.OWNER
           , F.TABLE_NAME
           , F.COLUMN_NAME
           , SUM(F.HASH_COUNT) AS PROFILE_COUNT
           , SUM(
                 CASE
                     WHEN F.PROFILE_HASH IS NULL THEN 0
                     ELSE GREATEST(F.HASH_COUNT - 1, 0)
                 END
             ) AS DUPLICATE_COUNT
        FROM
           (
            SELECT F0.OWNER
                 , F0.TABLE_NAME
                 , F0.COLUMN_NAME
                 , F0.PROFILE_HASH
                 , COUNT(*) AS HASH_COUNT
              FROM "INIT$_TB_COLTYPE_PROFILE" F0
             WHERE 1=1
               AND F0.FEATURE_VERSION = 'V2'
             GROUP BY F0.OWNER
                    , F0.TABLE_NAME
                    , F0.COLUMN_NAME
                    , F0.PROFILE_HASH
           ) F
       GROUP BY F.OWNER
              , F.TABLE_NAME
              , F.COLUMN_NAME
     )
   , CONFIRMED_PROFILE AS
     (
      SELECT F.*
        FROM "INIT$_TB_COLTYPE_PROFILE" F
       WHERE 1=1
         AND F.FEATURE_VERSION = 'V2'
     )
   , PROFILE_RUN_PREDICTION AS
     (
      SELECT X.RUN_SOURCE_TYPE
           , X.RUN_ID
           , X.OWNER
           , X.TABLE_NAME
           , X.COLUMN_NAME
           , COALESCE(X.BASE_TYPE_CODE, INIT$_FN_TYPE_CODE(X.BASE_PREDICTED_TYPE)) AS BASE_TYPE_CODE
           , COALESCE(X.MODL_TYPE_CODE, INIT$_FN_TYPE_CODE(X.MODL_PREDICTED_TYPE)) AS MODL_TYPE_CODE
        FROM
           (
            SELECT R.*
                 , ROW_NUMBER() OVER (
                       PARTITION BY R.RUN_SOURCE_TYPE, R.RUN_ID, R.OWNER, R.TABLE_NAME, R.COLUMN_NAME
                           ORDER BY R.CREATE_DT DESC
                                  , NVL(R.MODEL_VERSION_ID, -1) DESC
                                  , R.MODEL_NAME DESC
                   ) AS PREDICTION_RN
              FROM "INIT$_TB_COLTYPE_RESULT" R
           ) X
       WHERE 1=1
         AND X.PREDICTION_RN = 1
     )
   , FILTERED AS
     (
      SELECT L.LABEL_ID
           , L.OWNER
           , L.TABLE_NAME
           , L.COLUMN_NAME
           , P.COLUMN_DESC
           , P.COLUMN_ID
           , CAST(L.OWNER || '|' || L.TABLE_NAME || '|' || L.COLUMN_NAME AS VARCHAR2(4000)) AS CASE_ID
           , P.PROFILE_ID
           , P.FEATURE_VERSION
           , P.DATA_TYPE
           , P.TOTAL_ROWS
           , P.NON_NULL_ROWS
           , P.SAMPLE_ROWS
           , P.SAMPLE_NOT_NULL_ROWS
           , P.NUM_DISTINCT
           , P.SAMPLE_DISTINCT
           , P.DISTINCT_RATIO AS DIST_VAL_RT
           , P.NULL_RATIO
           , P.LOG_DATA_TYPE
           , P.ENTROPY
           , P.NORM_ENTROPY
           , P.NUMERIC_RATIO
           , P.INTEGER_RATIO
           , P.MIN_NUM_VALUE
           , P.MAX_NUM_VALUE
           , P.AVG_TEXT_LENGTH
           , P.MAX_TEXT_LENGTH
           , L.TYPE_CODE
           , L.TYPE_GROUP_CODE
           , L.DISPLAY_TYPE_VALUE
           , L.LABEL_SOURCE
           , L.CONFIRMED_YN
           , L.LABEL_CONFIDENCE
           , L.LABEL_REASON
           , L.CONFIRMED_BY
           , L.CONFIRMED_AT
           , L.UPDATED_AT
           , NVL(C.PROFILE_COUNT, 0) AS PROFILE_COUNT
           , NVL(C.DUPLICATE_COUNT, 0) AS DUPLICATE_COUNT
           , CASE
                 WHEN L.CONFIRMED_YN = 'Y'
                  AND L.LABEL_SOURCE IN ('USER_CONFIRMED', 'IMPORTED_GOLD')
                  AND P.PROFILE_ID IS NOT NULL
                 THEN 'Y'
                 ELSE 'N'
             END AS TRAINING_ELIGIBLE_YN
           , CASE
                 WHEN L.CONFIRMED_YN = 'Y'
                  AND L.LABEL_SOURCE IN ('USER_CONFIRMED', 'IMPORTED_GOLD')
                  AND (
                         R.BASE_TYPE_CODE IS NOT NULL AND R.BASE_TYPE_CODE <> L.TYPE_CODE
                      OR R.MODL_TYPE_CODE IS NOT NULL AND R.MODL_TYPE_CODE <> L.TYPE_CODE
                  )
                 THEN 'Y'
                 ELSE 'N'
             END AS CONFLICT_YN
        FROM "INIT$_TB_COLTYPE_LABEL" L
        LEFT JOIN CONFIRMED_PROFILE P
          ON P.PROFILE_ID = L.SOURCE_PROFILE_ID
         AND P.OWNER = L.OWNER
         AND P.TABLE_NAME = L.TABLE_NAME
         AND P.COLUMN_NAME = L.COLUMN_NAME
        LEFT JOIN PROFILE_COUNTS C
          ON C.OWNER = L.OWNER
         AND C.TABLE_NAME = L.TABLE_NAME
         AND C.COLUMN_NAME = L.COLUMN_NAME
        LEFT JOIN PROFILE_RUN_PREDICTION R
          ON R.RUN_SOURCE_TYPE = P.RUN_SOURCE_TYPE
         AND R.RUN_ID = P.RUN_ID
         AND R.OWNER = L.OWNER
         AND R.TABLE_NAME = L.TABLE_NAME
         AND R.COLUMN_NAME = L.COLUMN_NAME
       WHERE 1=1
         AND (
                :labelSource = 'ALL'
             OR L.LABEL_SOURCE = :labelSource
         )
         AND (
                :scope = 'ALL'
             OR :scope = 'ELIGIBLE'
                AND L.CONFIRMED_YN = 'Y'
                AND L.LABEL_SOURCE IN ('USER_CONFIRMED', 'IMPORTED_GOLD')
                AND P.PROFILE_ID IS NOT NULL
             OR :scope = 'EXCLUDED'
                AND NOT (
                        L.CONFIRMED_YN = 'Y'
                    AND L.LABEL_SOURCE IN ('USER_CONFIRMED', 'IMPORTED_GOLD')
                    AND P.PROFILE_ID IS NOT NULL
                )
             OR :scope = 'EXCLUDED_AUTO'
                AND L.LABEL_SOURCE IN ('AUTO_RULE', 'AUTO_MODEL', 'AUTO_BOTH')
             OR :scope = 'EXCLUDED_LEGACY'
                AND L.LABEL_SOURCE = 'LEGACY_UNKNOWN'
             OR :scope = 'CONFLICT'
                AND L.CONFIRMED_YN = 'Y'
                AND L.LABEL_SOURCE IN ('USER_CONFIRMED', 'IMPORTED_GOLD')
                AND (
                       R.BASE_TYPE_CODE IS NOT NULL AND R.BASE_TYPE_CODE <> L.TYPE_CODE
                    OR R.MODL_TYPE_CODE IS NOT NULL AND R.MODL_TYPE_CODE <> L.TYPE_CODE
                )
         )
         AND (:typeGroupCode = 'ALL' OR L.TYPE_GROUP_CODE = :typeGroupCode)
         AND (
                :keyword IS NULL
             OR UPPER(L.OWNER) LIKE '%' || :keyword || '%'
             OR UPPER(L.TABLE_NAME) LIKE '%' || :keyword || '%'
             OR UPPER(L.COLUMN_NAME) LIKE '%' || :keyword || '%'
             OR UPPER(NVL(P.COLUMN_DESC, '')) LIKE '%' || :keyword || '%'
         )
     )
SELECT X.LABEL_ID
     , X.OWNER
     , X.TABLE_NAME
     , X.COLUMN_NAME
     , X.COLUMN_DESC
     , X.COLUMN_ID
     , X.CASE_ID
     , X.PROFILE_ID
     , X.FEATURE_VERSION
     , X.DATA_TYPE
     , X.TOTAL_ROWS
     , X.NON_NULL_ROWS
     , X.SAMPLE_ROWS
     , X.SAMPLE_NOT_NULL_ROWS
     , X.NUM_DISTINCT
     , X.SAMPLE_DISTINCT
     , X.DIST_VAL_RT
     , X.NULL_RATIO
     , X.LOG_DATA_TYPE
     , X.ENTROPY
     , X.NORM_ENTROPY
     , X.NUMERIC_RATIO
     , X.INTEGER_RATIO
     , X.MIN_NUM_VALUE
     , X.MAX_NUM_VALUE
     , X.AVG_TEXT_LENGTH
     , X.MAX_TEXT_LENGTH
     , X.TYPE_CODE
     , X.TYPE_GROUP_CODE
     , X.DISPLAY_TYPE_VALUE
     , X.LABEL_SOURCE
     , X.CONFIRMED_YN
     , X.LABEL_CONFIDENCE
     , X.LABEL_REASON
     , X.CONFIRMED_BY
     , X.CONFIRMED_AT
     , X.UPDATED_AT
     , X.PROFILE_COUNT
     , X.DUPLICATE_COUNT
     , X.TRAINING_ELIGIBLE_YN
     , X.CONFLICT_YN
     , X.TOTAL_COUNT
  FROM
     (
      SELECT F.*
           , ROW_NUMBER() OVER (ORDER BY F.UPDATED_AT DESC, F.OWNER, F.TABLE_NAME, F.COLUMN_NAME) AS RN
           , COUNT(*) OVER () AS TOTAL_COUNT
        FROM FILTERED F
     ) X
 WHERE 1=1
   AND X.RN > :offsetRows
   AND X.RN <= :endRow
 ORDER BY X.RN
;

-- [M90003_MODEL_VERSION_LIST]
SELECT X.MODEL_VERSION_ID AS MODEL_ID
     , X.MODEL_KEY
     , X.VERSION_NO AS MODEL_VERSION
     , X.PHYSICAL_MODEL_NAME
     , X.ALGORITHM_CODE
     , X.FEATURE_VERSION
     , X.LABEL_VERSION
     , X.EFFECTIVE_STATUS_CODE AS STATUS
     , X.TRAIN_RUN_ID
     , X.TRAIN_ROW_COUNT AS TRAINED_ROWS
     , X.VALID_ROW_COUNT AS VALIDATION_ROWS
     , X.TEST_ROW_COUNT AS TEST_ROWS
     , X.ACCURACY
     , X.BALANCED_ACCURACY
     , X.MACRO_F1
     , X.CREATED_BY
     , X.CREATED_AT
     , X.ACTIVATED_BY
     , X.ACTIVATED_AT
     , X.ARCHIVED_BY
     , X.ARCHIVED_AT
  FROM
     (
      SELECT R.*
           , CASE
                 WHEN A.MODEL_VERSION_ID = R.MODEL_VERSION_ID THEN 'ACTIVE'
                 WHEN R.STATUS_CODE = 'ACTIVE' THEN 'ARCHIVED'
                 ELSE R.STATUS_CODE
             END AS EFFECTIVE_STATUS_CODE
           , ROW_NUMBER() OVER (
                 ORDER BY CASE
                              WHEN A.MODEL_VERSION_ID = R.MODEL_VERSION_ID THEN 0
                              WHEN R.STATUS_CODE = 'CANDIDATE' THEN 1
                              ELSE 2
                          END
                        , R.VERSION_NO DESC
             ) AS RN
        FROM "INIT$_TB_OML_MODEL_REGISTRY" R
        LEFT JOIN "INIT$_TB_OML_ACTIVE_MODEL" A
          ON A.MODEL_KEY = R.MODEL_KEY
       WHERE 1=1
         AND R.MODEL_KEY = :modelKey
         AND (
                 :statusCode = 'ALL'
              OR CASE
                     WHEN A.MODEL_VERSION_ID = R.MODEL_VERSION_ID THEN 'ACTIVE'
                     WHEN R.STATUS_CODE = 'ACTIVE' THEN 'ARCHIVED'
                     ELSE R.STATUS_CODE
                 END = :statusCode
             )
     ) X
 WHERE 1=1
   AND X.RN <= :limitRows
 ORDER BY X.RN
;

-- [M90003_TRAIN_RUN_LIST]
SELECT X.TRAIN_RUN_ID AS RUN_ID
     , X.MODEL_KEY
     , X.STATUS_CODE AS STATUS
     , X.ALGORITHM_CODE
     , X.FEATURE_VERSION
     , X.LABEL_VERSION
     , X.TRAIN_SOURCE_FILTER AS LABEL_SOURCE_FILTER
     , X.MIN_TRAIN_ROWS AS MIN_CONFIRMED_ROWS
     , X.HOLDOUT_PERCENT / 100 AS HOLDOUT_RATIO
     , X.MAX_INPUT_ROWS AS MAX_ROWS
     , X.RANDOM_SEED AS SEED
     , X.CANDIDATE_MODEL_NAME
     , X.MODEL_VERSION_ID
     , X.REQUESTED_BY
     , X.REQUESTED_AT
     , X.STARTED_AT
     , X.FINISHED_AT
     , X.TRAIN_ROW_COUNT
     , X.VALID_ROW_COUNT
     , X.TEST_ROW_COUNT
     , NVL(X.TRAIN_ROW_COUNT, 0) + NVL(X.VALID_ROW_COUNT, 0) + NVL(X.TEST_ROW_COUNT, 0) AS ELIGIBLE_ROWS
     , X.MACRO_F1
     , X.BALANCED_ACCURACY
     , X.ERROR_MESSAGE
     , X.TOTAL_COUNT
  FROM
     (
      SELECT Q.*
        FROM
           (
            SELECT R.*
                 , M.MACRO_F1
                 , M.BALANCED_ACCURACY
                 , ROW_NUMBER() OVER (ORDER BY R.TRAIN_RUN_ID DESC) AS RN
                 , COUNT(*) OVER () AS TOTAL_COUNT
              FROM "INIT$_TB_OML_TRAIN_RUN" R
              LEFT JOIN "INIT$_TB_OML_MODEL_REGISTRY" M
                ON M.MODEL_VERSION_ID = R.MODEL_VERSION_ID
             WHERE 1=1
               AND R.MODEL_KEY = :modelKey
               AND (:statusCode = 'ALL' OR R.STATUS_CODE = :statusCode)
           ) Q
       WHERE 1=1
         AND Q.RN > :offsetRows
         AND Q.RN <= :endRow
     ) X
 ORDER BY X.TRAIN_RUN_ID DESC
;

-- [M90003_TRAIN_RUN_DETAIL]
SELECT R.TRAIN_RUN_ID
     , R.MODEL_KEY
     , R.STATUS_CODE
     , R.ALGORITHM_CODE
     , R.FEATURE_VERSION
     , R.LABEL_VERSION
     , R.TRAIN_SOURCE_FILTER AS LABEL_SOURCE_FILTER
     , R.MIN_TRAIN_ROWS AS MIN_CONFIRMED_ROWS
     , R.HOLDOUT_PERCENT
     , R.MAX_INPUT_ROWS
     , R.RANDOM_SEED
     , R.CONFIG_JSON
     , R.CANDIDATE_MODEL_NAME
     , R.MODEL_VERSION_ID
     , R.REQUESTED_BY
     , R.REQUESTED_AT
     , R.STARTED_AT
     , R.FINISHED_AT
     , R.TRAIN_ROW_COUNT
     , R.VALID_ROW_COUNT
     , R.TEST_ROW_COUNT
     , R.ERROR_MESSAGE
  FROM "INIT$_TB_OML_TRAIN_RUN" R
 WHERE 1=1
   AND R.TRAIN_RUN_ID = :trainRunId
;

-- [M90003_TRAIN_RUN_METRIC_LIST]
SELECT M.METRIC_ID
     , M.MODEL_VERSION_ID
     , M.SPLIT_CODE
     , M.ACTUAL_CLASS_CODE AS TYPE_CODE
     , M.PREDICTED_CLASS_CODE AS PREDICTED_TYPE_CODE
     , M.CLASS_GROUP_CODE AS TYPE_GROUP_CODE
     , M.METRIC_NAME
     , M.METRIC_VALUE
     , M.SUPPORT_COUNT
     , M.CREATED_AT
  FROM "INIT$_TB_OML_TRAIN_RUN" R
  JOIN "INIT$_TB_OML_MODEL_METRIC" M
    ON M.MODEL_VERSION_ID = R.MODEL_VERSION_ID
 WHERE 1=1
   AND R.TRAIN_RUN_ID = :trainRunId
 ORDER BY M.SPLIT_CODE
        , NVL(M.CLASS_GROUP_CODE, '~')
        , NVL(M.ACTUAL_CLASS_CODE, '~')
        , NVL(M.PREDICTED_CLASS_CODE, '~')
        , M.METRIC_NAME
;

-- [M90003_TRAIN_RUN_CREATE]
INSERT INTO "INIT$_TB_OML_TRAIN_RUN" (
    MODEL_KEY
  , STATUS_CODE
  , ALGORITHM_CODE
  , FEATURE_VERSION
  , LABEL_VERSION
  , TRAIN_SOURCE_FILTER
  , MIN_TRAIN_ROWS
  , HOLDOUT_PERCENT
  , MAX_INPUT_ROWS
  , RANDOM_SEED
  , CONFIG_JSON
  , REQUESTED_BY
  , REQUESTED_AT
) VALUES (
    :modelKey
  , 'REQUESTED'
  , :algorithmCode
  , :featureVersion
  , :labelVersion
  , :trainSourceFilter
  , :minConfirmedLabels
  , :holdoutPercent
  , :maxTrainingRows
  , :randomSeed
  , :configJson
  , :requestedBy
  , SYSTIMESTAMP
)
RETURNING TRAIN_RUN_ID INTO :trainRunId
;

-- [M90003_ACTIVE_TRAIN_RUN_COUNT]
SELECT COUNT(*) AS ACTIVE_RUN_COUNT
  FROM "INIT$_TB_OML_TRAIN_RUN"
 WHERE 1=1
   AND MODEL_KEY = :modelKey
   AND STATUS_CODE IN ('REQUESTED', 'RUNNING')
;

-- [M90003_TRAIN_RUN_QUEUE_FAILED]
UPDATE "INIT$_TB_OML_TRAIN_RUN"
   SET STATUS_CODE = 'FAILED'
     , FINISHED_AT = SYSTIMESTAMP
     , ERROR_MESSAGE = :errorMessage
 WHERE 1=1
   AND TRAIN_RUN_ID = :trainRunId
   AND STATUS_CODE = 'REQUESTED'
;

-- [M90003_TRAIN_RUN_EXECUTION_FAILED]
UPDATE "INIT$_TB_OML_TRAIN_RUN"
   SET STATUS_CODE = 'FAILED'
     , FINISHED_AT = SYSTIMESTAMP
     , ERROR_MESSAGE = :errorMessage
 WHERE 1=1
   AND TRAIN_RUN_ID = :trainRunId
   AND STATUS_CODE NOT IN ('SUCCESS', 'CANCELLED')
;

-- [M90003_LABEL_DELETE_SELECTED]
DECLARE
BEGIN
    INSERT INTO "INIT$_TB_COLTYPE_LABEL_HIST" (
        "LABEL_ID", "OWNER", "TABLE_NAME", "COLUMN_NAME", "PREVIOUS_TYPE_CODE", "NEW_TYPE_CODE",
        "PREVIOUS_GROUP_CODE", "NEW_GROUP_CODE", "PREVIOUS_DISPLAY_VALUE", "NEW_DISPLAY_VALUE",
        "LABEL_SOURCE", "CONFIRMED_YN", "CHANGE_REASON", "SOURCE_RUN_SOURCE_TYPE", "SOURCE_RUN_ID",
        "SOURCE_MODEL_NAME", "CHANGED_BY", "CHANGED_AT"
    )
    SELECT L."LABEL_ID"
         , L."OWNER"
         , L."TABLE_NAME"
         , L."COLUMN_NAME"
         , L."TYPE_CODE"
         , NULL
         , L."TYPE_GROUP_CODE"
         , NULL
         , L."DISPLAY_TYPE_VALUE"
         , NULL
         , L."LABEL_SOURCE"
         , L."CONFIRMED_YN"
         , 'M90003 selected training label deletion'
         , L."SOURCE_RUN_SOURCE_TYPE"
         , L."SOURCE_RUN_ID"
         , L."SOURCE_MODEL_NAME"
         , :requestedBy
         , SYSTIMESTAMP
      FROM "INIT$_TB_COLTYPE_LABEL" L
     WHERE L."LABEL_ID" IN (
               SELECT TO_NUMBER(REGEXP_SUBSTR(:labelIds, '[^,]+', 1, LEVEL))
                 FROM DUAL
              CONNECT BY REGEXP_SUBSTR(:labelIds, '[^,]+', 1, LEVEL) IS NOT NULL
           );

    DELETE FROM "INIT$_TB_COLTYPE_LABEL" L
     WHERE L."LABEL_ID" IN (
               SELECT TO_NUMBER(REGEXP_SUBSTR(:labelIds, '[^,]+', 1, LEVEL))
                 FROM DUAL
              CONNECT BY REGEXP_SUBSTR(:labelIds, '[^,]+', 1, LEVEL) IS NOT NULL
           );
END;
/

-- [M90003_LABEL_RESET_TRAINING]
DECLARE
BEGIN
    INSERT INTO "INIT$_TB_COLTYPE_LABEL_HIST" (
        "LABEL_ID", "OWNER", "TABLE_NAME", "COLUMN_NAME", "PREVIOUS_TYPE_CODE", "NEW_TYPE_CODE",
        "PREVIOUS_GROUP_CODE", "NEW_GROUP_CODE", "PREVIOUS_DISPLAY_VALUE", "NEW_DISPLAY_VALUE",
        "LABEL_SOURCE", "CONFIRMED_YN", "CHANGE_REASON", "SOURCE_RUN_SOURCE_TYPE", "SOURCE_RUN_ID",
        "SOURCE_MODEL_NAME", "CHANGED_BY", "CHANGED_AT"
    )
    SELECT L."LABEL_ID"
         , L."OWNER"
         , L."TABLE_NAME"
         , L."COLUMN_NAME"
         , L."TYPE_CODE"
         , NULL
         , L."TYPE_GROUP_CODE"
         , NULL
         , L."DISPLAY_TYPE_VALUE"
         , NULL
         , L."LABEL_SOURCE"
         , L."CONFIRMED_YN"
         , 'M90003 training label reset'
         , L."SOURCE_RUN_SOURCE_TYPE"
         , L."SOURCE_RUN_ID"
         , L."SOURCE_MODEL_NAME"
         , :requestedBy
         , SYSTIMESTAMP
      FROM "INIT$_TB_COLTYPE_LABEL" L
     WHERE L."CONFIRMED_YN" = 'Y'
       AND L."LABEL_SOURCE" IN ('USER_CONFIRMED', 'IMPORTED_GOLD')
       AND EXISTS (
               SELECT 1
                 FROM "INIT$_TB_COLTYPE_PROFILE" P
                WHERE P."PROFILE_ID" = L."SOURCE_PROFILE_ID"
                  AND P."OWNER" = L."OWNER"
                  AND P."TABLE_NAME" = L."TABLE_NAME"
                  AND P."COLUMN_NAME" = L."COLUMN_NAME"
                  AND P."FEATURE_VERSION" = 'V2'
           );

    DELETE FROM "INIT$_TB_COLTYPE_LABEL" L
     WHERE L."CONFIRMED_YN" = 'Y'
       AND L."LABEL_SOURCE" IN ('USER_CONFIRMED', 'IMPORTED_GOLD')
       AND EXISTS (
               SELECT 1
                 FROM "INIT$_TB_COLTYPE_PROFILE" P
                WHERE P."PROFILE_ID" = L."SOURCE_PROFILE_ID"
                  AND P."OWNER" = L."OWNER"
                  AND P."TABLE_NAME" = L."TABLE_NAME"
                  AND P."COLUMN_NAME" = L."COLUMN_NAME"
                  AND P."FEATURE_VERSION" = 'V2'
           );
END;
/

-- [M90003_LABEL_CREATE_INITIAL_SAMPLE]
BEGIN
    MERGE INTO "INIT$_TB_COLTYPE_PROFILE" T
    USING (
        SELECT J."RUN_SOURCE_TYPE"
             , J."RUN_ID"
             , J."OWNER"
             , J."TABLE_NAME"
             , J."COLUMN_NAME"
             , J."FEATURE_VERSION"
             , J."COLUMN_DESC"
             , J."COLUMN_ID"
             , J."DATA_TYPE"
             , J."TOTAL_ROWS"
             , J."NON_NULL_ROWS"
             , J."SAMPLE_ROWS"
             , J."SAMPLE_NOT_NULL_ROWS"
             , J."NUM_DISTINCT"
             , J."SAMPLE_DISTINCT"
             , J."DISTINCT_RATIO"
             , J."NULL_RATIO"
             , J."LOG_DATA_TYPE"
             , J."ENTROPY"
             , J."NORM_ENTROPY"
             , J."NUMERIC_RATIO"
             , J."INTEGER_RATIO"
             , J."MIN_NUM_VALUE"
             , J."MAX_NUM_VALUE"
             , J."AVG_TEXT_LENGTH"
             , J."MAX_TEXT_LENGTH"
             , J."PROFILE_HASH"
          FROM JSON_TABLE(
                   :samplePayload
                 , '$.profiles[*]'
                   COLUMNS (
                       "RUN_SOURCE_TYPE" VARCHAR2(30) PATH '$.runSourceType'
                     , "RUN_ID" NUMBER PATH '$.runId'
                     , "OWNER" VARCHAR2(128) PATH '$.owner'
                     , "TABLE_NAME" VARCHAR2(128) PATH '$.tableName'
                     , "COLUMN_NAME" VARCHAR2(128) PATH '$.columnName'
                     , "FEATURE_VERSION" VARCHAR2(30) PATH '$.featureVersion'
                     , "COLUMN_DESC" VARCHAR2(4000) PATH '$.columnDesc'
                     , "COLUMN_ID" NUMBER PATH '$.columnId'
                     , "DATA_TYPE" VARCHAR2(128) PATH '$.dataType'
                     , "TOTAL_ROWS" NUMBER PATH '$.totalRows'
                     , "NON_NULL_ROWS" NUMBER PATH '$.nonNullRows'
                     , "SAMPLE_ROWS" NUMBER PATH '$.sampleRows'
                     , "SAMPLE_NOT_NULL_ROWS" NUMBER PATH '$.sampleNotNullRows'
                     , "NUM_DISTINCT" NUMBER PATH '$.numDistinct'
                     , "SAMPLE_DISTINCT" NUMBER PATH '$.sampleDistinct'
                     , "DISTINCT_RATIO" NUMBER PATH '$.distinctRatio'
                     , "NULL_RATIO" NUMBER PATH '$.nullRatio'
                     , "LOG_DATA_TYPE" VARCHAR2(30) PATH '$.logDataType'
                     , "ENTROPY" NUMBER PATH '$.entropy'
                     , "NORM_ENTROPY" NUMBER PATH '$.normEntropy'
                     , "NUMERIC_RATIO" NUMBER PATH '$.numericRatio'
                     , "INTEGER_RATIO" NUMBER PATH '$.integerRatio'
                     , "MIN_NUM_VALUE" NUMBER PATH '$.minNumValue' NULL ON ERROR
                     , "MAX_NUM_VALUE" NUMBER PATH '$.maxNumValue' NULL ON ERROR
                     , "AVG_TEXT_LENGTH" NUMBER PATH '$.avgTextLength' NULL ON ERROR
                     , "MAX_TEXT_LENGTH" NUMBER PATH '$.maxTextLength' NULL ON ERROR
                     , "PROFILE_HASH" VARCHAR2(64) PATH '$.profileHash'
                   )
               ) J
    ) S
       ON (
               T."RUN_SOURCE_TYPE" = S."RUN_SOURCE_TYPE"
           AND T."RUN_ID" = S."RUN_ID"
           AND T."OWNER" = S."OWNER"
           AND T."TABLE_NAME" = S."TABLE_NAME"
           AND T."COLUMN_NAME" = S."COLUMN_NAME"
           AND T."FEATURE_VERSION" = S."FEATURE_VERSION"
       )
     WHEN NOT MATCHED THEN
        INSERT (
            "RUN_SOURCE_TYPE", "RUN_ID", "OWNER", "TABLE_NAME", "COLUMN_NAME", "FEATURE_VERSION"
          , "COLUMN_DESC", "COLUMN_ID", "DATA_TYPE", "TOTAL_ROWS", "NON_NULL_ROWS", "SAMPLE_ROWS"
          , "SAMPLE_NOT_NULL_ROWS", "NUM_DISTINCT", "SAMPLE_DISTINCT", "DISTINCT_RATIO", "NULL_RATIO"
          , "LOG_DATA_TYPE", "ENTROPY", "NORM_ENTROPY", "NUMERIC_RATIO", "INTEGER_RATIO", "MIN_NUM_VALUE"
          , "MAX_NUM_VALUE", "AVG_TEXT_LENGTH", "MAX_TEXT_LENGTH", "PROFILE_HASH"
        ) VALUES (
            S."RUN_SOURCE_TYPE", S."RUN_ID", S."OWNER", S."TABLE_NAME", S."COLUMN_NAME", S."FEATURE_VERSION"
          , S."COLUMN_DESC", S."COLUMN_ID", S."DATA_TYPE", S."TOTAL_ROWS", S."NON_NULL_ROWS", S."SAMPLE_ROWS"
          , S."SAMPLE_NOT_NULL_ROWS", S."NUM_DISTINCT", S."SAMPLE_DISTINCT", S."DISTINCT_RATIO", S."NULL_RATIO"
          , S."LOG_DATA_TYPE", S."ENTROPY", S."NORM_ENTROPY", S."NUMERIC_RATIO", S."INTEGER_RATIO", S."MIN_NUM_VALUE"
          , S."MAX_NUM_VALUE", S."AVG_TEXT_LENGTH", S."MAX_TEXT_LENGTH", S."PROFILE_HASH"
        );

    MERGE INTO "INIT$_TB_COLTYPE_LABEL" T
    USING (
        SELECT P."OWNER"
             , P."TABLE_NAME"
             , P."COLUMN_NAME"
             , J."TYPE_CODE"
             , J."TYPE_GROUP_CODE"
             , J."DISPLAY_TYPE_VALUE"
             , J."LABEL_REASON"
             , P."PROFILE_ID"
          FROM JSON_TABLE(
                   :samplePayload
                 , '$.profiles[*]'
                   COLUMNS (
                       "RUN_SOURCE_TYPE" VARCHAR2(30) PATH '$.runSourceType'
                     , "RUN_ID" NUMBER PATH '$.runId'
                     , "OWNER" VARCHAR2(128) PATH '$.owner'
                     , "TABLE_NAME" VARCHAR2(128) PATH '$.tableName'
                     , "COLUMN_NAME" VARCHAR2(128) PATH '$.columnName'
                     , "FEATURE_VERSION" VARCHAR2(30) PATH '$.featureVersion'
                     , "TYPE_CODE" VARCHAR2(40) PATH '$.typeCode'
                     , "TYPE_GROUP_CODE" VARCHAR2(20) PATH '$.typeGroupCode'
                     , "DISPLAY_TYPE_VALUE" VARCHAR2(4000) PATH '$.displayTypeValue'
                     , "LABEL_REASON" VARCHAR2(1000) PATH '$.labelReason'
                   )
               ) J
          JOIN "INIT$_TB_COLTYPE_PROFILE" P
            ON P."RUN_SOURCE_TYPE" = J."RUN_SOURCE_TYPE"
           AND P."RUN_ID" = J."RUN_ID"
           AND P."OWNER" = J."OWNER"
           AND P."TABLE_NAME" = J."TABLE_NAME"
           AND P."COLUMN_NAME" = J."COLUMN_NAME"
           AND P."FEATURE_VERSION" = J."FEATURE_VERSION"
    ) S
       ON (
               T."OWNER" = S."OWNER"
           AND T."TABLE_NAME" = S."TABLE_NAME"
           AND T."COLUMN_NAME" = S."COLUMN_NAME"
       )
     WHEN NOT MATCHED THEN
        INSERT (
            "OWNER", "TABLE_NAME", "COLUMN_NAME", "TYPE_CODE", "TYPE_GROUP_CODE", "DISPLAY_TYPE_VALUE"
          , "LABEL_SOURCE", "CONFIRMED_YN", "LABEL_CONFIDENCE", "SOURCE_PROFILE_ID", "SOURCE_RUN_SOURCE_TYPE"
          , "SOURCE_RUN_ID", "LABEL_REASON", "CONFIRMED_BY", "CONFIRMED_AT"
        ) VALUES (
            S."OWNER", S."TABLE_NAME", S."COLUMN_NAME", S."TYPE_CODE", S."TYPE_GROUP_CODE", S."DISPLAY_TYPE_VALUE"
          , 'IMPORTED_GOLD', 'Y', 1, S."PROFILE_ID", 'DATA_WORK'
          , 0, S."LABEL_REASON", :requestedBy, SYSTIMESTAMP
        );
END;
/

-- [M90003_TYPE_MODEL_TRAIN_CALL]
BEGIN
    INIT$_SP_TYPE_MODEL_TRAIN(
        P_TRAIN_RUN_ID => :trainRunId
      , P_REQUESTED_BY => :requestedBy
    );
END;
/

-- [M90003_TYPE_MODEL_ACTIVATE_CALL]
BEGIN
    INIT$_SP_TYPE_MODEL_ACTIVATE(
        P_MODEL_VERSION_ID => :modelVersionId
      , P_USER_ID => :userId
    );
END;
/

-- [M90003_TYPE_MODEL_ARCHIVE_CALL]
BEGIN
    INIT$_SP_TYPE_MODEL_ARCHIVE(
        P_MODEL_VERSION_ID => :modelVersionId
      , P_USER_ID => :userId
    );
END;
/

-- [M90003_TYPE_MODEL_DELETE_CALL]
BEGIN
    INIT$_SP_TYPE_MODEL_DELETE(
        P_MODEL_VERSION_ID => :modelVersionId
      , P_USER_ID => :userId
    );
END;
/

-- [M90003_TYPE_MODEL_ROLLBACK_CALL]
BEGIN
    INIT$_SP_TYPE_MODEL_ROLLBACK(
        P_USER_ID => :userId
      , P_MODEL_KEY => :modelKey
    );
END;
/
