-- [M91002_SETTING_EXISTS]
SELECT COUNT(*)
  FROM "INIT$_TB_SYSTEM_SETTING"
 WHERE USER_ID = :userId
   AND CONNECTION_ID = :connectionId
   AND CATEGORY_CODE = :categoryCode
   AND SETTING_KEY = :settingKey;

-- [M91002_ACCOUNT_ME]
SELECT USER_ID,
       LOGIN_ID,
       USER_NAME,
       EMAIL,
       ROLE_CODE,
       USE_YN,
       CREATED_AT,
       UPDATED_AT
  FROM "INIT$_TB_USER"
 WHERE USER_ID = :userId;

-- [M91002_ACTIVE_SETTING_VALUE]
SELECT SETTING_VALUE
  FROM "INIT$_TB_SYSTEM_SETTING"
 WHERE USER_ID = :userId
   AND CONNECTION_ID = :connectionId
   AND CATEGORY_CODE = :categoryCode
   AND SETTING_KEY = :settingKey
   AND USE_YN = 'Y';

-- [M91002_USER_NAME_UPDATE]
UPDATE "INIT$_TB_USER"
   SET USER_NAME = :userName,
       UPDATED_AT = SYSTIMESTAMP
 WHERE USER_ID = :userId
   AND USE_YN = 'Y';

-- [M91002_ACTIVE_USER_PASSWORD]
SELECT PASSWORD_HASH
  FROM "INIT$_TB_USER"
 WHERE USER_ID = :userId
   AND USE_YN = 'Y';

-- [M91002_EMAIL_DUPLICATE_COUNT]
SELECT COUNT(*)
  FROM "INIT$_TB_USER"
 WHERE EMAIL = :email
   AND USER_ID <> :userId;

-- [M91002_EMAIL_UPDATE]
UPDATE "INIT$_TB_USER"
   SET EMAIL = :email,
       UPDATED_AT = SYSTIMESTAMP
 WHERE USER_ID = :userId;

-- [M91002_PASSWORD_UPDATE]
UPDATE "INIT$_TB_USER"
   SET PASSWORD_HASH = :passwordHash,
       UPDATED_AT = SYSTIMESTAMP
 WHERE USER_ID = :userId;

-- [M91002_CURRENT_SCHEMA]
SELECT SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA')
  FROM DUAL;

-- [M91002_CONNECTION_OWNER_COUNT]
SELECT COUNT(*)
  FROM "INIT$_TB_DB_CONNECTION" C
  JOIN "INIT$_TB_USER" U
    ON U.USER_ID = C.USER_ID
 WHERE C.CONNECTION_ID = :connectionId
   AND C.USE_YN = 'Y'
   AND (C.USER_ID = :userId OR (U.ROLE_CODE = 'ADMIN' AND C.SHARED_YN = 'Y'));
