-- [M91003_SETTING_EXISTS]
SELECT COUNT(*)
  FROM "INIT$_TB_TARGET_SETTING"
 WHERE CATEGORY_CODE = :categoryCode
   AND SETTING_KEY = :settingKey;

-- [M91003_SETTING_LIST]
SELECT
    CATEGORY_CODE,
    SETTING_KEY,
    SETTING_VALUE,
    SETTING_DESC,
    SORT_ORDER,
    USE_YN,
    UPDATED_AT
  FROM "INIT$_TB_TARGET_SETTING"
 WHERE (:categoryCode IS NULL OR CATEGORY_CODE = :categoryCode)
 ORDER BY CATEGORY_CODE, SORT_ORDER NULLS LAST, SETTING_KEY;

-- [M91003_SETTING_MERGE]
MERGE INTO "INIT$_TB_TARGET_SETTING" T
USING (
    SELECT
        :categoryCode AS CATEGORY_CODE,
        :settingKey AS SETTING_KEY,
        :settingValue AS SETTING_VALUE,
        :settingDesc AS SETTING_DESC,
        :sortOrder AS SORT_ORDER,
        :useYn AS USE_YN
      FROM DUAL
) S
ON (T.CATEGORY_CODE = S.CATEGORY_CODE AND T.SETTING_KEY = S.SETTING_KEY)
WHEN MATCHED THEN
    UPDATE SET
        T.SETTING_VALUE = S.SETTING_VALUE,
        T.SETTING_DESC = S.SETTING_DESC,
        T.SORT_ORDER = S.SORT_ORDER,
        T.USE_YN = S.USE_YN,
        T.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN
    INSERT (
        CATEGORY_CODE,
        SETTING_KEY,
        SETTING_VALUE,
        SETTING_DESC,
        SORT_ORDER,
        USE_YN,
        UPDATED_AT
    ) VALUES (
        S.CATEGORY_CODE,
        S.SETTING_KEY,
        S.SETTING_VALUE,
        S.SETTING_DESC,
        S.SORT_ORDER,
        S.USE_YN,
        SYSTIMESTAMP
    );

-- [M91003_SETTING_DELETE]
DELETE FROM "INIT$_TB_TARGET_SETTING"
 WHERE CATEGORY_CODE = :categoryCode
   AND SETTING_KEY = :settingKey;
