-- [M91002_SETTING_EXISTS]
SELECT COUNT(*)
  FROM "INIT$_TB_SYSTEM_SETTING"
 WHERE USER_ID = :userId
   AND CONNECTION_ID = :connectionId
   AND CATEGORY_CODE = :categoryCode
   AND SETTING_KEY = :settingKey;

-- [M91002_ACCOUNT_ME]
SELECT USER_ID
     , LOGIN_ID
     , USER_NAME
     , EMAIL
     , ROLE_CODE
     , USE_YN
     , CREATED_AT
     , UPDATED_AT
  FROM "INIT$_TB_USER"
 WHERE USER_ID = :userId;

-- [M91002_ACTIVE_SETTING_VALUE]
SELECT SETTING_VALUE
  FROM "INIT$_TB_SYSTEM_SETTING"
 WHERE USER_ID = :userId
   AND CONNECTION_ID = :connectionId
   AND CATEGORY_CODE = :categoryCode
   AND SETTING_KEY = :settingKey
   AND USE_YN = 'Y';

-- [M91002_ACTIVE_SERVER_RESOURCE_LIMITS]
SELECT SETTING_KEY
     , SETTING_VALUE
  FROM "INIT$_TB_SYSTEM_SETTING"
 WHERE USER_ID = :userId
   AND CONNECTION_ID = :connectionId
   AND CATEGORY_CODE = 'SERVER_RESOURCE_LIMITS'
   AND SETTING_KEY IN (
       'TARGET_DB_POOL_WAIT_TIMEOUT_MS'
     , 'APP_RULE_SUMMARY_TIMEOUT_MS'
     , 'APP_ML_MAX_IN_MEMORY_ROWS'
     , 'APP_ML_MAX_INPUT_FEATURES'
   )
   AND USE_YN = 'Y';

-- [M91002_USER_NAME_UPDATE]
UPDATE "INIT$_TB_USER"
   SET USER_NAME = :userName
     , UPDATED_AT = SYSTIMESTAMP
 WHERE USER_ID = :userId
   AND USE_YN = 'Y';

-- [M91002_ACTIVE_USER_PASSWORD]
SELECT PASSWORD_HASH
  FROM "INIT$_TB_USER"
 WHERE USER_ID = :userId
   AND USE_YN = 'Y';

-- [M91002_EMAIL_DUPLICATE_COUNT]
SELECT COUNT(*)
  FROM "INIT$_TB_USER"
 WHERE EMAIL = :email
   AND USER_ID <> :userId;

-- [M91002_EMAIL_UPDATE]
UPDATE "INIT$_TB_USER"
   SET EMAIL = :email
     , UPDATED_AT = SYSTIMESTAMP
 WHERE USER_ID = :userId;

-- [M91002_PASSWORD_UPDATE]
UPDATE "INIT$_TB_USER"
   SET PASSWORD_HASH = :passwordHash
     , UPDATED_AT = SYSTIMESTAMP
 WHERE USER_ID = :userId;

-- [M91002_CURRENT_SCHEMA]
SELECT SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA')
  FROM DUAL;

-- [M91002_CONNECTION_OWNER_COUNT]
SELECT COUNT(*)
  FROM "INIT$_TB_DB_CONNECTION" C
  JOIN "INIT$_TB_USER" U
    ON U.USER_ID = C.USER_ID
 WHERE C.CONNECTION_ID = :connectionId
   AND C.USE_YN = 'Y'
   AND (C.USER_ID = :userId OR (U.ROLE_CODE = 'ADMIN' AND C.SHARED_YN = 'Y'));
