-- [M99002_OBJECT_TREE]
WITH OBJECT_COUNTS AS (
    SELECT OWNER, 'TABLE' AS CATEGORY_CODE, COUNT(*) AS CNT
      FROM ALL_TABLES
     WHERE TABLE_NAME NOT LIKE 'BIN$%'
       AND NESTED = 'NO'
       AND SECONDARY = 'N'
     GROUP BY OWNER
    UNION ALL
    SELECT OWNER, 'VIEW' AS CATEGORY_CODE, COUNT(*) AS CNT
      FROM ALL_VIEWS
     GROUP BY OWNER
    UNION ALL
    SELECT OWNER, TYPE AS CATEGORY_CODE, COUNT(DISTINCT NAME) AS CNT
      FROM ALL_SOURCE
     WHERE TYPE IN ('PACKAGE', 'PROCEDURE', 'FUNCTION')
       AND NAME NOT LIKE 'BIN$%'
     GROUP BY OWNER, TYPE
),
OWNER_LIST AS (
    SELECT DISTINCT OWNER FROM OBJECT_COUNTS
)
SELECT OWNER,
       'OWNER' AS OBJECT_TYPE,
       OWNER AS OBJECT_NAME,
       OWNER AS OBJECT_LABEL,
       'OWNER:' || OWNER AS NODE_ID,
       CAST(NULL AS VARCHAR2(4000)) AS PARENT_ID,
       1 AS LEVEL_NO,
       'N' AS IS_SELECTABLE,
       CAST(NULL AS NUMBER) AS CHILD_COUNT,
       CASE
           WHEN OWNER = SYS_CONTEXT('USERENV', 'SESSION_USER') THEN 0
           WHEN OWNER = SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA') THEN 1
           ELSE 2
       END AS OWNER_SORT,
       0 AS SORT_GROUP
  FROM OWNER_LIST
UNION ALL
SELECT C.OWNER,
       'GROUP' AS OBJECT_TYPE,
       C.CATEGORY_CODE AS OBJECT_NAME,
       CASE C.CATEGORY_CODE
           WHEN 'TABLE' THEN 'Tables'
           WHEN 'VIEW' THEN 'Views'
           WHEN 'PACKAGE' THEN 'Packages'
           WHEN 'PROCEDURE' THEN 'Procedures'
           WHEN 'FUNCTION' THEN 'Functions'
       END AS OBJECT_LABEL,
       'GROUP:' || C.OWNER || ':' || C.CATEGORY_CODE AS NODE_ID,
       'OWNER:' || C.OWNER AS PARENT_ID,
       2 AS LEVEL_NO,
       'N' AS IS_SELECTABLE,
       C.CNT AS CHILD_COUNT,
       CASE
           WHEN C.OWNER = SYS_CONTEXT('USERENV', 'SESSION_USER') THEN 0
           WHEN C.OWNER = SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA') THEN 1
           ELSE 2
       END AS OWNER_SORT,
       CASE C.CATEGORY_CODE
           WHEN 'TABLE' THEN 10
           WHEN 'VIEW' THEN 20
           WHEN 'PACKAGE' THEN 30
           WHEN 'PROCEDURE' THEN 40
           WHEN 'FUNCTION' THEN 50
       END AS SORT_GROUP
  FROM OBJECT_COUNTS C
 WHERE C.CNT > 0
 ORDER BY OWNER_SORT, OWNER, SORT_GROUP, OBJECT_NAME;

-- [M99002_OBJECT_CHILD_TABLES]
SELECT T.OWNER,
       'TABLE' AS OBJECT_TYPE,
       T.TABLE_NAME AS OBJECT_NAME,
       T.TABLE_NAME || NVL2(T.COMMENTS, ' - ' || T.COMMENTS, '') AS OBJECT_LABEL,
       'TABLE:' || T.OWNER || ':' || T.TABLE_NAME AS NODE_ID,
       'GROUP:' || T.OWNER || ':TABLE' AS PARENT_ID,
       3 AS LEVEL_NO,
       'Y' AS IS_SELECTABLE,
       CAST(NULL AS NUMBER) AS CHILD_COUNT,
       T.COMMENTS AS OBJECT_COMMENT,
       TO_CHAR(O.CREATED, 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT
  FROM ALL_TAB_COMMENTS T
  LEFT JOIN ALL_OBJECTS O
    ON O.OWNER = T.OWNER
   AND O.OBJECT_NAME = T.TABLE_NAME
   AND O.OBJECT_TYPE = 'TABLE'
 WHERE T.OWNER = :owner
   AND T.TABLE_TYPE = 'TABLE'
   AND T.TABLE_NAME NOT LIKE 'BIN$%';

-- [M99002_OBJECT_CHILD_VIEWS]
SELECT OWNER,
       'VIEW' AS OBJECT_TYPE,
       VIEW_NAME AS OBJECT_NAME,
       VIEW_NAME AS OBJECT_LABEL,
       'VIEW:' || OWNER || ':' || VIEW_NAME AS NODE_ID,
       'GROUP:' || OWNER || ':VIEW' AS PARENT_ID,
       3 AS LEVEL_NO,
       'Y' AS IS_SELECTABLE,
       CAST(NULL AS NUMBER) AS CHILD_COUNT,
       CAST(NULL AS VARCHAR2(4000)) AS OBJECT_COMMENT,
       CAST(NULL AS VARCHAR2(19)) AS CREATED_AT
  FROM ALL_VIEWS
 WHERE OWNER = :owner;

-- [M99002_OBJECT_CHILD_PLSQL]
SELECT S.OWNER,
       S.OBJECT_TYPE,
       S.OBJECT_NAME,
       S.OBJECT_NAME AS OBJECT_LABEL,
       S.OBJECT_TYPE || ':' || S.OWNER || ':' || S.OBJECT_NAME AS NODE_ID,
       'GROUP:' || S.OWNER || ':' || S.OBJECT_TYPE AS PARENT_ID,
       3 AS LEVEL_NO,
       'Y' AS IS_SELECTABLE,
       CASE
           WHEN S.OBJECT_TYPE = 'PACKAGE' THEN (
               SELECT COUNT(*)
                 FROM ALL_PROCEDURES P
                WHERE P.OWNER = S.OWNER
                  AND P.OBJECT_NAME = S.OBJECT_NAME
                  AND P.PROCEDURE_NAME IS NOT NULL
           )
           ELSE CAST(NULL AS NUMBER)
       END AS CHILD_COUNT
  FROM (
        SELECT DISTINCT OWNER, TYPE AS OBJECT_TYPE, NAME AS OBJECT_NAME
          FROM ALL_SOURCE
         WHERE OWNER = :owner
           AND TYPE = :category
           AND NAME NOT LIKE 'BIN$%'
  ) S;

-- [M99002_PACKAGE_MEMBERS]
SELECT P.OWNER,
       'PACKAGE_PROCEDURE' AS OBJECT_TYPE,
       P.OBJECT_NAME || '.' || P.PROCEDURE_NAME AS OBJECT_NAME,
       P.PROCEDURE_NAME AS OBJECT_LABEL,
       'PACKAGE_MEMBER:' || P.OWNER || ':' || P.OBJECT_NAME || ':' || P.PROCEDURE_NAME AS NODE_ID,
       'PACKAGE:' || P.OWNER || ':' || P.OBJECT_NAME AS PARENT_ID,
       4 AS LEVEL_NO,
       'Y' AS IS_SELECTABLE,
       CAST(NULL AS NUMBER) AS CHILD_COUNT
  FROM ALL_PROCEDURES P
 WHERE P.OWNER = :owner
   AND P.OBJECT_NAME = :packageName
   AND P.PROCEDURE_NAME IS NOT NULL
 ORDER BY P.PROCEDURE_NAME;

-- [M99002_SEARCH_TABLES]
SELECT T.OWNER,
       'TABLE' AS OBJECT_TYPE,
       T.TABLE_NAME AS OBJECT_NAME,
       T.TABLE_NAME || NVL2(T.COMMENTS, ' - ' || T.COMMENTS, '') AS OBJECT_LABEL,
       'SEARCH:TABLE:' || T.OWNER || ':' || T.TABLE_NAME AS NODE_ID,
       CAST(NULL AS VARCHAR2(4000)) AS PARENT_ID,
       1 AS LEVEL_NO,
       'Y' AS IS_SELECTABLE,
       CAST(NULL AS NUMBER) AS CHILD_COUNT,
       'TABLE' AS ROOT_CATEGORY,
       T.COMMENTS AS OBJECT_COMMENT,
       TO_CHAR(O.CREATED, 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT
  FROM ALL_TAB_COMMENTS T
  LEFT JOIN ALL_OBJECTS O
    ON O.OWNER = T.OWNER
   AND O.OBJECT_NAME = T.TABLE_NAME
   AND O.OBJECT_TYPE = 'TABLE'
 WHERE T.TABLE_TYPE = 'TABLE'
   AND T.TABLE_NAME NOT LIKE 'BIN$%'
   AND (UPPER(T.OWNER) LIKE :keyword OR UPPER(T.TABLE_NAME) LIKE :keyword OR UPPER(NVL(T.COMMENTS, '')) LIKE :keyword);

-- [M99002_SEARCH_VIEWS]
SELECT OWNER,
       'VIEW' AS OBJECT_TYPE,
       VIEW_NAME AS OBJECT_NAME,
       VIEW_NAME AS OBJECT_LABEL,
       'SEARCH:VIEW:' || OWNER || ':' || VIEW_NAME AS NODE_ID,
       CAST(NULL AS VARCHAR2(4000)) AS PARENT_ID,
       1 AS LEVEL_NO,
       'Y' AS IS_SELECTABLE,
       CAST(NULL AS NUMBER) AS CHILD_COUNT,
       'VIEW' AS ROOT_CATEGORY,
       CAST(NULL AS VARCHAR2(4000)) AS OBJECT_COMMENT,
       CAST(NULL AS VARCHAR2(19)) AS CREATED_AT
  FROM ALL_VIEWS
 WHERE UPPER(OWNER) LIKE :keyword
    OR UPPER(VIEW_NAME) LIKE :keyword;

-- [M99002_SEARCH_PLSQL]
SELECT OWNER,
       OBJECT_TYPE,
       OBJECT_NAME,
       OBJECT_NAME AS OBJECT_LABEL,
       'SEARCH:' || OBJECT_TYPE || ':' || OWNER || ':' || OBJECT_NAME AS NODE_ID,
       CAST(NULL AS VARCHAR2(4000)) AS PARENT_ID,
       1 AS LEVEL_NO,
       'Y' AS IS_SELECTABLE,
       CAST(NULL AS NUMBER) AS CHILD_COUNT,
       OBJECT_TYPE AS ROOT_CATEGORY,
       CAST(NULL AS VARCHAR2(4000)) AS OBJECT_COMMENT,
       TO_CHAR(CREATED, 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT
  FROM (
        SELECT S.OWNER,
               S.TYPE AS OBJECT_TYPE,
               S.NAME AS OBJECT_NAME,
               MIN(O.CREATED) AS CREATED
          FROM ALL_SOURCE S
          LEFT JOIN ALL_OBJECTS O
            ON O.OWNER = S.OWNER
           AND O.OBJECT_NAME = S.NAME
           AND O.OBJECT_TYPE = S.TYPE
         WHERE S.TYPE IN (/* --OBJECT_TYPE_LIST-- */)
           AND S.NAME NOT LIKE 'BIN$%'
         GROUP BY S.OWNER, S.TYPE, S.NAME
  ) O
 WHERE UPPER(OWNER) LIKE :keyword
    OR UPPER(OBJECT_NAME) LIKE :keyword;

-- [M99002_SEARCH_WRAPPER]
SELECT *
  FROM (
    SELECT R.*, ROW_NUMBER() OVER (ORDER BY OWNER, ROOT_CATEGORY, OBJECT_NAME) AS RN
      FROM (
        /* --SEARCH_SQL-- */
      ) R
  )
 WHERE RN > :offset
   AND RN <= :endRow
 ORDER BY RN;

-- [M99002_OBJECT_DETAIL_TABLE]
SELECT T.OWNER,
       'TABLE' AS OBJECT_TYPE,
       T.TABLE_NAME AS OBJECT_NAME,
       T.TABLE_NAME AS OBJECT_LABEL,
       C.COMMENTS AS OBJECT_COMMENT,
       TO_CHAR(O.CREATED, 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT
  FROM ALL_TABLES T
  LEFT JOIN ALL_TAB_COMMENTS C
    ON C.OWNER = T.OWNER
   AND C.TABLE_NAME = T.TABLE_NAME
  LEFT JOIN ALL_OBJECTS O
    ON O.OWNER = T.OWNER
   AND O.OBJECT_NAME = T.TABLE_NAME
   AND O.OBJECT_TYPE = 'TABLE'
 WHERE T.OWNER = :owner
   AND T.TABLE_NAME = :objectName;

-- [M99002_OBJECT_DETAIL_VIEW]
SELECT V.OWNER,
       'VIEW' AS OBJECT_TYPE,
       V.VIEW_NAME AS OBJECT_NAME,
       V.VIEW_NAME AS OBJECT_LABEL,
       C.COMMENTS AS OBJECT_COMMENT,
       TO_CHAR(O.CREATED, 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT
  FROM ALL_VIEWS V
  LEFT JOIN ALL_TAB_COMMENTS C
    ON C.OWNER = V.OWNER
   AND C.TABLE_NAME = V.VIEW_NAME
  LEFT JOIN ALL_OBJECTS O
    ON O.OWNER = V.OWNER
   AND O.OBJECT_NAME = V.VIEW_NAME
   AND O.OBJECT_TYPE = 'VIEW'
 WHERE V.OWNER = :owner
   AND V.VIEW_NAME = :objectName;

-- [M99002_OBJECT_DETAIL_PLSQL]
SELECT O.OWNER,
       :objectType AS OBJECT_TYPE,
       :displayName AS OBJECT_NAME,
       :displayName AS OBJECT_LABEL,
       CAST(NULL AS VARCHAR2(4000)) AS OBJECT_COMMENT,
       TO_CHAR(O.CREATED, 'YYYY-MM-DD HH24:MI:SS') AS CREATED_AT
  FROM ALL_OBJECTS O
 WHERE O.OWNER = :owner
   AND O.OBJECT_NAME = :objectName
   AND O.OBJECT_TYPE = :baseObjectType
   AND O.GENERATED = 'N'
   AND EXISTS (
        SELECT 1
          FROM ALL_SOURCE S
         WHERE S.OWNER = O.OWNER
           AND S.NAME = O.OBJECT_NAME
           AND S.TYPE = O.OBJECT_TYPE
   );

-- [M99002_TABLE_COLUMNS]
SELECT C.COLUMN_ID,
       C.COLUMN_NAME,
       C.DATA_TYPE,
       C.DATA_LENGTH,
       C.DATA_PRECISION,
       C.DATA_SCALE,
       C.NULLABLE,
       C.DATA_DEFAULT,
       CC.COMMENTS
  FROM ALL_TAB_COLUMNS C
  LEFT JOIN ALL_COL_COMMENTS CC
    ON CC.OWNER = C.OWNER
   AND CC.TABLE_NAME = C.TABLE_NAME
   AND CC.COLUMN_NAME = C.COLUMN_NAME
 WHERE C.OWNER = :owner
   AND C.TABLE_NAME = :tableName
 ORDER BY C.COLUMN_ID;

-- [M99002_TABLE_DATA]
SELECT *
  FROM /* --OWNER_TABLE-- */
 WHERE ROWNUM <= :limit;

-- [M99002_OBJECT_SOURCE]
SELECT DBMS_METADATA.GET_DDL(:objectType, :objectName, :owner) AS SOURCE_TEXT
  FROM DUAL;

-- [M99002_OBJECT_SOURCE_LINES]
SELECT TEXT
  FROM ALL_SOURCE
 WHERE OWNER = :owner
   AND NAME = :objectName
   AND TYPE = :objectType
 ORDER BY LINE;

-- [M99002_LIMITED_SELECT_WRAPPER]
SELECT *
  FROM (
    /* --READONLY_SQL-- */
  )
 WHERE ROWNUM <= :limit;

-- [M99002_PAGED_SELECT_WRAPPER]
SELECT *
  FROM (
    SELECT R.*, ROW_NUMBER() OVER (ORDER BY /* --ORDER_BY-- */) AS RN
      FROM (
        /* --BASE_SQL-- */
      ) R
  )
 WHERE RN > :offset
   AND RN <= :endRow
 ORDER BY RN;
