-- [M99003_CHECK_INIT_TABLES]
SELECT TABLE_NAME
  FROM USER_TABLES
 WHERE TABLE_NAME IN (/* --INIT_TABLE_BINDS-- */);

-- [M99003_SYSTEM_TABLE_COLUMNS]
SELECT C.COLUMN_ID,
       C.COLUMN_NAME,
       C.DATA_TYPE,
       C.DATA_LENGTH,
       C.DATA_PRECISION,
       C.DATA_SCALE,
       C.NULLABLE,
       CC.COMMENTS
  FROM USER_TAB_COLUMNS C
  LEFT JOIN USER_COL_COMMENTS CC
    ON CC.TABLE_NAME = C.TABLE_NAME
   AND CC.COLUMN_NAME = C.COLUMN_NAME
 WHERE C.TABLE_NAME = :tableName
 ORDER BY C.COLUMN_ID;

-- [M99003_SYSTEM_USER_DATA]
SELECT *
  FROM (
    SELECT *
      FROM /* --SYSTEM_TABLE-- */
      /* --STATUS_CLAUSE-- */
     ORDER BY USER_ID
  )
 WHERE ROWNUM <= :limit;

-- [M99003_SYSTEM_TABLE_DATA]
SELECT *
  FROM /* --SYSTEM_TABLE-- */
 WHERE ROWNUM <= :limit;

-- [M99003_USER_APPROVE]
UPDATE "INIT$_TB_USER"
   SET USE_YN = 'Y',
       UPDATED_AT = SYSTIMESTAMP
 WHERE USE_YN = 'N'
   AND USER_ID IN (/* --USER_ID_BINDS-- */);

-- [M99003_USER_LIST_BY_IDS]
SELECT USER_ID,
       LOGIN_ID,
       USER_NAME,
       EMAIL
  FROM "INIT$_TB_USER"
 WHERE USER_ID IN (/* --USER_ID_BINDS-- */)
 ORDER BY USER_ID;

-- [M99003_USER_RESET_PASSWORD]
UPDATE "INIT$_TB_USER"
   SET PASSWORD_HASH = :passwordHash,
       UPDATED_AT = SYSTIMESTAMP
 WHERE USER_ID = :userId;

-- [M99003_USER_DEACTIVATE]
UPDATE "INIT$_TB_USER"
   SET USE_YN = 'N',
       UPDATED_AT = SYSTIMESTAMP
 WHERE USER_ID IN (/* --USER_ID_BINDS-- */);

-- [M99003_LIMITED_SELECT_WRAPPER]
SELECT *
  FROM (
    /* --READONLY_SQL-- */
  )
 WHERE ROWNUM <= :limit;
