-- [FLOW_WORK_SCENARIO_TABLE_LIST]
SELECT T.SCENARIO_TABLE_ID
     , T.PROJECT_ID
     , T.SCENARIO_ID
     , T.OWNER_NAME
     , T.TABLE_NAME
     , T.EDIT_OWNER_NAME
     , T.EDIT_TABLE_NAME
     , CASE
           WHEN ET.TABLE_NAME IS NOT NULL THEN 'Y'
           ELSE 'N'
       END AS EDIT_TABLE_EXISTS_YN
     , T.TABLE_COMMENT
     , T.USE_YN
     , T.SORT_ORDER
     , T.CREATED_AT
     , T.UPDATED_AT
  FROM INIT$_TB_TABLES T
  LEFT JOIN ALL_TABLES ET
    ON ET.OWNER = T.EDIT_OWNER_NAME
   AND ET.TABLE_NAME = T.EDIT_TABLE_NAME
 WHERE T.PROJECT_ID = :projectId
   AND T.SCENARIO_ID = :scenarioId
 ORDER BY T.SORT_ORDER NULLS LAST
        , T.OWNER_NAME
        , T.TABLE_NAME
        , T.SCENARIO_TABLE_ID
;

-- [FLOW_WORK_RUNTIME_TABLE_PAIR]
SELECT T.SCENARIO_TABLE_ID
     , T.OWNER_NAME
     , T.TABLE_NAME
     , T.EDIT_OWNER_NAME
     , T.EDIT_TABLE_NAME
  FROM INIT$_TB_TABLES T
  JOIN ALL_TABLES ET
    ON ET.OWNER = T.EDIT_OWNER_NAME
   AND ET.TABLE_NAME = T.EDIT_TABLE_NAME
 WHERE T.PROJECT_ID = :projectId
   AND T.SCENARIO_ID = :scenarioId
   AND T.EDIT_OWNER_NAME = :editOwnerName
   AND T.EDIT_TABLE_NAME = :editTableName
;

-- [FLOW_WORK_DATA_JOB_ASSET_LIST]
SELECT WORK_JOB_ID
     , MENU_CODE
     , PROJECT_ID
     , SCENARIO_ID
     , SCENARIO_TABLE_ID
     , JOB_GROUP
     , JOB_NAME
     , JOB_DESC
     , OWNER_NAME
     , TABLE_NAME
     , EXEC_SOURCE_TYPE
     , EXEC_RESOURCE_ID
     , EXEC_METHOD
     , EXEC_SPEC_JSON
     , EXEC_OBJECT_ID
     , EXEC_OWNER
     , EXEC_OBJECT_TYPE
     , EXEC_OBJECT_NAME
     , EXEC_OBJECT_LABEL
     , EXEC_PLSQL
     , PARAM_JSON
     , USE_YN
     , SORT_ORDER
     , RESULT_CREATE_YN
     , RESULT_OWNER
     , RESULT_TABLE_NAME
     , STATUS
     , CREATED_AT
     , UPDATED_AT
  FROM INIT$_TB_DATA_WORK_JOB
 WHERE PROJECT_ID = :projectId
   AND SCENARIO_ID = :scenarioId
   AND USE_YN = 'Y'
   AND (:menuCode IS NULL OR MENU_CODE = :menuCode)
 ORDER BY JOB_GROUP, MENU_CODE, SORT_ORDER NULLS LAST, WORK_JOB_ID
;

-- [FLOW_WORK_EXECUTABLE_OBJECT_LIST]
SELECT OBJECT_ID
     , OWNER
     , OBJECT_TYPE
     , OBJECT_NAME
     , OBJECT_LABEL
     , DESCRIPTION
     , USE_YN
     , SORT_ORDER
  FROM INIT$_TB_OBJECT
 WHERE USE_YN = 'Y'
   AND OBJECT_TYPE IN (
        'PROCEDURE',
        'FUNCTION',
        'PACKAGE_PROCEDURE',
        'PACKAGE_FUNCTION',
        'MINING_MODEL'
   )
 ORDER BY SORT_ORDER NULLS LAST, OWNER, OBJECT_TYPE, OBJECT_NAME
;

-- [FLOW_WORK_EXECUTABLE_OBJECT_DETAIL]
SELECT OBJECT_ID
     , OWNER
     , OBJECT_TYPE
     , OBJECT_NAME
     , ITEM_NAME
     , ITEM_VALUE
     , ITEM_DESC
     , ITEM_DEFAULT
     , ITEM_ORDER
  FROM INIT$_TB_OBJECT_DETAIL
 WHERE OBJECT_ID = :objectId
 ORDER BY ITEM_ORDER NULLS LAST, ITEM_NAME
;

-- [FLOW_WORK_LIST]
SELECT FLOW_ID
     , MENU_CODE
     , PROJECT_ID
     , SCENARIO_ID
     , FLOW_GROUP
     , FLOW_NAME
     , FLOW_DESC
     , FLOW_TYPE
     , EXECUTION_MODE
     , USE_YN
     , VERSION_NO
     , STATUS
     , CREATED_AT
     , UPDATED_AT
  FROM INIT$_TB_FLOW_WORK
 WHERE MENU_CODE = :menuCode
   AND PROJECT_ID = :projectId
   AND SCENARIO_ID = :scenarioId
 ORDER BY FLOW_ID ASC
;

-- [FLOW_WORK_DETAIL]
SELECT FLOW_ID
     , MENU_CODE
     , PROJECT_ID
     , SCENARIO_ID
     , FLOW_GROUP
     , FLOW_NAME
     , FLOW_DESC
     , FLOW_TYPE
     , EXECUTION_MODE
     , USE_YN
     , VERSION_NO
     , STATUS
     , GRAPH_JSON
     , CREATED_AT
     , UPDATED_AT
  FROM INIT$_TB_FLOW_WORK
 WHERE MENU_CODE = :menuCode
   AND FLOW_ID = :flowId
;

-- [FLOW_WORK_IMPORT_FLOW_LIST]
SELECT F.FLOW_ID
     , F.FLOW_GROUP
     , F.FLOW_NAME
     , F.FLOW_DESC
     , F.USE_YN
     , F.UPDATED_AT
  FROM INIT$_TB_FLOW_WORK F
  JOIN INIT$_TB_PROJECT P
    ON P.PROJECT_ID = F.PROJECT_ID
 WHERE F.MENU_CODE = :menuCode
   AND F.PROJECT_ID = :projectId
   AND F.SCENARIO_ID = :scenarioId
   AND (:includeAllUsers = 'Y' OR P.USER_ID = :userId)
 ORDER BY F.UPDATED_AT DESC NULLS LAST
        , F.FLOW_ID DESC
;

-- [FLOW_WORK_IMPORT_FLOW_DETAIL]
SELECT F.FLOW_ID
  FROM INIT$_TB_FLOW_WORK F
  JOIN INIT$_TB_PROJECT P
    ON P.PROJECT_ID = F.PROJECT_ID
 WHERE F.MENU_CODE = :menuCode
   AND F.FLOW_ID = :flowId
   AND F.PROJECT_ID = :projectId
   AND F.SCENARIO_ID = :scenarioId
   AND (:includeAllUsers = 'Y' OR P.USER_ID = :userId)
;

-- [FLOW_WORK_INSERT]
INSERT INTO INIT$_TB_FLOW_WORK (
    MENU_CODE
  , PROJECT_ID
  , SCENARIO_ID
  , FLOW_GROUP
  , FLOW_NAME
  , FLOW_DESC
  , FLOW_TYPE
  , EXECUTION_MODE
  , USE_YN
  , VERSION_NO
  , STATUS
  , GRAPH_JSON
  , CREATED_AT
) VALUES (
    :menuCode
  , :projectId
  , :scenarioId
  , :flowGroup
  , :flowName
  , :flowDesc
  , :flowType
  , :executionMode
  , :useYn
  , 1
  , :status
  , :graphJson
  , SYSTIMESTAMP
)
;

-- [FLOW_WORK_UPDATE]
UPDATE INIT$_TB_FLOW_WORK
   SET FLOW_GROUP = :flowGroup
     , FLOW_NAME = :flowName
     , FLOW_DESC = :flowDesc
     , FLOW_TYPE = :flowType
     , EXECUTION_MODE = :executionMode
     , USE_YN = :useYn
     , STATUS = :status
     , GRAPH_JSON = :graphJson
     , UPDATED_AT = SYSTIMESTAMP
 WHERE MENU_CODE = :menuCode
   AND FLOW_ID = :flowId
   AND PROJECT_ID = :projectId
   AND SCENARIO_ID = :scenarioId
;

-- [FLOW_WORK_ID_LATEST]
SELECT MAX(FLOW_ID) AS FLOW_ID
  FROM INIT$_TB_FLOW_WORK
 WHERE MENU_CODE = :menuCode
   AND PROJECT_ID = :projectId
   AND SCENARIO_ID = :scenarioId
   AND FLOW_GROUP = :flowGroup
   AND FLOW_NAME = :flowName
;

-- [FLOW_WORK_DELETE]
DELETE FROM INIT$_TB_FLOW_WORK
 WHERE MENU_CODE = :menuCode
   AND FLOW_ID = :flowId
   AND PROJECT_ID = :projectId
   AND SCENARIO_ID = :scenarioId
;

-- [FLOW_WORK_NODE_LIST]
SELECT FLOW_NODE_ID
     , FLOW_ID
     , NODE_KEY
     , NODE_TYPE
     , NODE_NAME
     , NODE_DESC
     , USE_YN
     , REF_MENU_CODE
     , REF_WORK_JOB_ID
     , REF_OBJECT_ID
     , OWNER_NAME
     , TABLE_NAME
     , POSITION_LEFT
     , POSITION_TOP
     , NODE_WIDTH
     , NODE_HEIGHT
     , INPUT_JSON
     , OUTPUT_JSON
     , PARAM_JSON
     , EXEC_PLSQL
     , SORT_ORDER
     , CREATED_AT
     , UPDATED_AT
  FROM INIT$_TB_FLOW_WORK_NODE
 WHERE FLOW_ID = :flowId
 ORDER BY SORT_ORDER NULLS LAST, FLOW_NODE_ID
;

-- [FLOW_WORK_NODE_DELETE_BY_FLOW]
DELETE FROM INIT$_TB_FLOW_WORK_NODE
 WHERE FLOW_ID = :flowId
;

-- [FLOW_WORK_NODE_KEY_LIST]
SELECT NODE_KEY
  FROM INIT$_TB_FLOW_WORK_NODE
 WHERE FLOW_ID = :flowId
;

-- [FLOW_WORK_NODE_INSERT]
INSERT INTO INIT$_TB_FLOW_WORK_NODE (
    FLOW_ID
  , NODE_KEY
  , NODE_TYPE
  , NODE_NAME
  , NODE_DESC
  , USE_YN
  , REF_MENU_CODE
  , REF_WORK_JOB_ID
  , REF_OBJECT_ID
  , OWNER_NAME
  , TABLE_NAME
  , POSITION_LEFT
  , POSITION_TOP
  , NODE_WIDTH
  , NODE_HEIGHT
  , INPUT_JSON
  , OUTPUT_JSON
  , PARAM_JSON
  , EXEC_PLSQL
  , SORT_ORDER
  , CREATED_AT
) VALUES (
    :flowId
  , :nodeKey
  , :nodeType
  , :nodeName
  , :nodeDesc
  , :useYn
  , :refMenuCode
  , :refWorkJobId
  , :refObjectId
  , :ownerName
  , :tableName
  , :positionLeft
  , :positionTop
  , :nodeWidth
  , :nodeHeight
  , :inputJson
  , :outputJson
  , :paramJson
  , :execPlsql
  , :sortOrder
  , SYSTIMESTAMP
)
;

-- [FLOW_WORK_NODE_UPDATE_BY_KEY]
UPDATE INIT$_TB_FLOW_WORK_NODE
   SET NODE_TYPE = :nodeType
     , NODE_NAME = :nodeName
     , NODE_DESC = :nodeDesc
     , USE_YN = :useYn
     , REF_MENU_CODE = :refMenuCode
     , REF_WORK_JOB_ID = :refWorkJobId
     , REF_OBJECT_ID = :refObjectId
     , OWNER_NAME = :ownerName
     , TABLE_NAME = :tableName
     , POSITION_LEFT = :positionLeft
     , POSITION_TOP = :positionTop
     , NODE_WIDTH = :nodeWidth
     , NODE_HEIGHT = :nodeHeight
     , INPUT_JSON = :inputJson
     , OUTPUT_JSON = :outputJson
     , PARAM_JSON = :paramJson
     , EXEC_PLSQL = :execPlsql
     , SORT_ORDER = :sortOrder
     , UPDATED_AT = SYSTIMESTAMP
 WHERE FLOW_ID = :flowId
   AND NODE_KEY = :nodeKey
;

-- [FLOW_WORK_NODE_DELETE_BY_KEY]
DELETE FROM INIT$_TB_FLOW_WORK_NODE
 WHERE FLOW_ID = :flowId
   AND NODE_KEY = :nodeKey
;

-- [FLOW_WORK_EDGE_LIST]
SELECT FLOW_EDGE_ID
     , FLOW_ID
     , FROM_NODE_KEY
     , FROM_PORT
     , TO_NODE_KEY
     , TO_PORT
     , EDGE_MODE
     , DASHED_YN
     , SORT_ORDER
     , PARAM_JSON
     , CREATED_AT
  FROM INIT$_TB_FLOW_WORK_EDGE
 WHERE FLOW_ID = :flowId
 ORDER BY SORT_ORDER NULLS LAST, FLOW_EDGE_ID
;

-- [FLOW_WORK_EDGE_DELETE_BY_FLOW]
DELETE FROM INIT$_TB_FLOW_WORK_EDGE
 WHERE FLOW_ID = :flowId
;

-- [FLOW_WORK_EDGE_INSERT]
INSERT INTO INIT$_TB_FLOW_WORK_EDGE (
    FLOW_ID
  , FROM_NODE_KEY
  , FROM_PORT
  , TO_NODE_KEY
  , TO_PORT
  , EDGE_MODE
  , DASHED_YN
  , SORT_ORDER
  , PARAM_JSON
  , CREATED_AT
) VALUES (
    :flowId
  , :fromNodeKey
  , :fromPort
  , :toNodeKey
  , :toPort
  , :edgeMode
  , :dashedYn
  , :sortOrder
  , :paramJson
  , SYSTIMESTAMP
)
;

-- [FLOW_WORK_RUN_INSERT]
INSERT INTO INIT$_TB_FLOW_WORK_RUN (
    FLOW_ID
  , RUN_TYPE
  , STATUS
  , MESSAGE
  , PLAN_JSON
  , STARTED_AT
  , CREATED_AT
) VALUES (
    :flowId
  , :runType
  , :status
  , :message
  , :planJson
  , SYSTIMESTAMP
  , SYSTIMESTAMP
)
;

-- [FLOW_WORK_RUN_SCOPE_LOCK]
SELECT FLOW_ID
  FROM INIT$_TB_FLOW_WORK
 WHERE 1=1
   AND MENU_CODE = :menuCode
   AND FLOW_ID = :flowId
   AND PROJECT_ID = :projectId
   AND SCENARIO_ID = :scenarioId
   FOR UPDATE WAIT 15
;

-- [FLOW_WORK_RUN_BY_REQUEST_TOKEN]
SELECT FLOW_RUN_ID
     , FLOW_ID
     , RUN_TYPE
     , STATUS
     , MESSAGE
     , PLAN_JSON
     , STARTED_AT
     , FINISHED_AT
     , CREATED_AT
  FROM INIT$_TB_FLOW_WORK_RUN
 WHERE 1=1
   AND FLOW_ID = :flowId
   AND DBMS_LOB.INSTR(PLAN_JSON, :requestTokenMarker) > 0
 ORDER BY FLOW_RUN_ID DESC
 FETCH FIRST 1 ROW ONLY
;

-- [FLOW_WORK_QUICK_EDIT_HISTORY_LIST]
WITH ELIGIBLE_RUNS AS
     (
      SELECT R.FLOW_RUN_ID
           , R.FLOW_ID
           , F.PROJECT_ID
           , P.PROJECT_CODE
           , P.PROJECT_NAME
           , F.SCENARIO_ID
           , S.SCENARIO_CODE
           , S.SCENARIO_NAME
           , F.FLOW_NAME
           , R.RUN_TYPE
           , R.STATUS
           , R.STARTED_AT
           , R.FINISHED_AT
           , R.CREATED_AT
           , COUNT(*) OVER () AS TOTAL_COUNT
           , ROW_NUMBER() OVER (
                 ORDER BY COALESCE(R.STARTED_AT, R.CREATED_AT) DESC
                        , R.FLOW_RUN_ID DESC
             ) AS RN
        FROM INIT$_TB_FLOW_WORK_RUN R
        JOIN INIT$_TB_FLOW_WORK F
          ON F.FLOW_ID = R.FLOW_ID
        JOIN INIT$_TB_PROJECT P
          ON P.PROJECT_ID = F.PROJECT_ID
        LEFT JOIN INIT$_TB_SCENARIO S
          ON S.SCENARIO_ID = F.SCENARIO_ID
         AND S.PROJECT_ID = F.PROJECT_ID
       WHERE 1=1
         AND F.MENU_CODE = :menuCode
         AND (
              R.RUN_TYPE = 'QUICK_EDIT'
           OR (
                  NVL(R.RUN_TYPE, 'MANUAL') <> 'QUICK_EDIT'
              AND (
                   P.PROJECT_CODE LIKE 'QE\_%' ESCAPE '\'
                OR P.PROJECT_CODE LIKE 'QEDIT\_%' ESCAPE '\'
                  )
              )
             )
         AND (:includeAllUsers = 'Y' OR P.USER_ID = :userId)
     )
   , PAGED_RUNS AS
     (
      SELECT /*+ MATERIALIZE */ *
        FROM ELIGIBLE_RUNS
       WHERE 1=1
         AND RN > :offset
         AND RN <= :endRow
     )
   , NODE_COUNTS AS
     (
      SELECT NR.FLOW_RUN_ID
           , COUNT(*) AS NODE_COUNT
           , SUM(CASE WHEN NR.STATUS = 'SUCCESS' THEN 1 ELSE 0 END) AS SUCCESS_NODE_COUNT
           , SUM(CASE WHEN NR.STATUS IN ('FAILED', 'ERROR', 'CANCELLED') THEN 1 ELSE 0 END) AS FAILED_NODE_COUNT
        FROM INIT$_TB_FLOW_WORK_NODE_RUN NR
       WHERE 1=1
         AND EXISTS (
              SELECT 1
                FROM PAGED_RUNS PR
               WHERE PR.FLOW_RUN_ID = NR.FLOW_RUN_ID
             )
       GROUP BY NR.FLOW_RUN_ID
     )
SELECT PR.FLOW_RUN_ID
     , PR.FLOW_ID
     , PR.PROJECT_ID
     , COALESCE(QS.PROJECT_CODE, PR.PROJECT_CODE) AS PROJECT_CODE
     , COALESCE(QS.PROJECT_NAME, PR.PROJECT_NAME) AS PROJECT_NAME
     , QS.PROJECT_CREATED_AT
     , PR.SCENARIO_ID
     , COALESCE(QS.SCENARIO_CODE, PR.SCENARIO_CODE) AS SCENARIO_CODE
     , COALESCE(QS.SCENARIO_NAME, PR.SCENARIO_NAME) AS SCENARIO_NAME
     , QS.SCENARIO_CREATED_AT
     , QS.OWNER_NAME
     , QS.TABLE_NAME
     , COALESCE(QS.FLOW_NAME, PR.FLOW_NAME) AS FLOW_NAME
     , QS.JOB_COUNT
     , PR.RUN_TYPE
     , PR.STATUS
     , PR.STARTED_AT
     , PR.FINISHED_AT
     , PR.CREATED_AT
     , NVL(NC.NODE_COUNT, 0) AS NODE_COUNT
     , NVL(NC.SUCCESS_NODE_COUNT, 0) AS SUCCESS_NODE_COUNT
     , NVL(NC.FAILED_NODE_COUNT, 0) AS FAILED_NODE_COUNT
     , PR.TOTAL_COUNT
  FROM PAGED_RUNS PR
  JOIN INIT$_TB_FLOW_WORK_RUN SR
    ON SR.FLOW_RUN_ID = PR.FLOW_RUN_ID
  LEFT JOIN JSON_TABLE(
       SR.PLAN_JSON
     , '$.quickEditSummary' NULL ON ERROR
       COLUMNS (
           PROJECT_CODE VARCHAR2(100) PATH '$.projectCode'
         , PROJECT_NAME VARCHAR2(200) PATH '$.projectName'
         , PROJECT_CREATED_AT VARCHAR2(64) PATH '$.projectCreatedAt'
         , SCENARIO_CODE VARCHAR2(100) PATH '$.scenarioCode'
         , SCENARIO_NAME VARCHAR2(200) PATH '$.scenarioName'
         , SCENARIO_CREATED_AT VARCHAR2(64) PATH '$.scenarioCreatedAt'
         , OWNER_NAME VARCHAR2(128) PATH '$.ownerName'
         , TABLE_NAME VARCHAR2(128) PATH '$.tableName'
         , FLOW_NAME VARCHAR2(200) PATH '$.flowName'
         , JOB_COUNT NUMBER PATH '$.jobCount'
       )
     ) QS
    ON 1=1
  LEFT JOIN NODE_COUNTS NC
    ON NC.FLOW_RUN_ID = PR.FLOW_RUN_ID
 ORDER BY PR.RN
;

-- [FLOW_WORK_QUICK_EDIT_HISTORY]
WITH STORED_QUICK_RUNS AS (
    SELECT R.FLOW_RUN_ID
         , R.FLOW_ID
         , F.PROJECT_ID
         , P.PROJECT_CODE
         , P.PROJECT_NAME
         , F.SCENARIO_ID
         , CAST(NULL AS VARCHAR2(100)) AS SCENARIO_CODE
         , CAST(NULL AS VARCHAR2(200)) AS SCENARIO_NAME
         , CAST(NULL AS NUMBER) AS SCENARIO_TABLE_ID
         , CAST(NULL AS VARCHAR2(128)) AS OWNER_NAME
         , CAST(NULL AS VARCHAR2(128)) AS TABLE_NAME
         , CAST(NULL AS VARCHAR2(128)) AS EDIT_OWNER_NAME
         , CAST(NULL AS VARCHAR2(128)) AS EDIT_TABLE_NAME
         , CAST(NULL AS VARCHAR2(255)) AS FILE_NAME
         , CAST(NULL AS NUMBER) AS FILE_SIZE
         , CAST(NULL AS NUMBER) AS ESTIMATED_ROW_COUNT
         , F.FLOW_NAME
         , CAST(NULL AS NUMBER) AS JOB_COUNT
         , R.RUN_TYPE
         , R.STATUS
         , R.MESSAGE
         , R.STARTED_AT
         , R.FINISHED_AT
         , R.CREATED_AT
         , 'Y' AS SUMMARY_YN
      FROM INIT$_TB_FLOW_WORK_RUN R
      JOIN INIT$_TB_FLOW_WORK F
        ON F.FLOW_ID = R.FLOW_ID
      JOIN INIT$_TB_PROJECT P
        ON P.PROJECT_ID = F.PROJECT_ID
     WHERE 1=1
       AND F.MENU_CODE = :menuCode
       AND R.RUN_TYPE = 'QUICK_EDIT'
       AND (:flowRunId IS NULL OR R.FLOW_RUN_ID = :flowRunId)
       AND (:includeAllUsers = 'Y' OR P.USER_ID = :userId)
)
, LEGACY_RUN_SCOPE AS (
    SELECT /*+ MATERIALIZE */ R.FLOW_RUN_ID
         , R.FLOW_ID
         , F.PROJECT_ID
         , P.PROJECT_CODE
         , P.PROJECT_NAME
         , F.SCENARIO_ID
         , F.FLOW_NAME
         , R.RUN_TYPE
         , R.STATUS
         , R.MESSAGE
         , R.STARTED_AT
         , R.FINISHED_AT
         , R.CREATED_AT
      FROM INIT$_TB_FLOW_WORK_RUN R
      JOIN INIT$_TB_FLOW_WORK F
        ON F.FLOW_ID = R.FLOW_ID
      JOIN INIT$_TB_PROJECT P
        ON P.PROJECT_ID = F.PROJECT_ID
     WHERE 1=1
       AND F.MENU_CODE = :menuCode
       AND NVL(R.RUN_TYPE, 'MANUAL') <> 'QUICK_EDIT'
       AND (
            P.PROJECT_CODE LIKE 'QE\_%' ESCAPE '\'
         OR P.PROJECT_CODE LIKE 'QEDIT\_%' ESCAPE '\'
           )
       AND DBMS_LOB.INSTR(R.PLAN_JSON, '"runRequestToken"') > 0
       AND (:flowRunId IS NULL OR R.FLOW_RUN_ID = :flowRunId)
       AND (:includeAllUsers = 'Y' OR P.USER_ID = :userId)
)
, LEGACY_FLOW_TABLE_SCOPE AS (
    SELECT FN.FLOW_ID
         , MAX(J.SCENARIO_TABLE_ID) AS SCENARIO_TABLE_ID
         , COUNT(DISTINCT J.SCENARIO_TABLE_ID) AS SCENARIO_TABLE_COUNT
         , COUNT(DISTINCT J.WORK_JOB_ID) AS JOB_COUNT
      FROM INIT$_TB_FLOW_WORK_NODE FN
      JOIN INIT$_TB_DATA_WORK_JOB J
        ON J.WORK_JOB_ID = FN.REF_WORK_JOB_ID
     WHERE J.SCENARIO_TABLE_ID IS NOT NULL
       AND EXISTS (
            SELECT 1
              FROM LEGACY_RUN_SCOPE LRS
             WHERE LRS.FLOW_ID = FN.FLOW_ID
           )
     GROUP BY FN.FLOW_ID
)
, LEGACY_QUICK_RUNS AS (
    SELECT LRS.FLOW_RUN_ID
         , LRS.FLOW_ID
         , LRS.PROJECT_ID
         , LRS.PROJECT_CODE
         , LRS.PROJECT_NAME
         , LRS.SCENARIO_ID
         , S.SCENARIO_CODE
         , S.SCENARIO_NAME
         , FT.SCENARIO_TABLE_ID
         , ST.OWNER_NAME
         , ST.TABLE_NAME
         , ST.EDIT_OWNER_NAME
         , ST.EDIT_TABLE_NAME
         , UM.FILE_NAME
         , UM.FILE_SIZE
         , AT.NUM_ROWS AS ESTIMATED_ROW_COUNT
         , LRS.FLOW_NAME
         , FT.JOB_COUNT
         , LRS.RUN_TYPE
         , LRS.STATUS
         , LRS.MESSAGE
         , LRS.STARTED_AT
         , LRS.FINISHED_AT
         , LRS.CREATED_AT
         , 'N' AS SUMMARY_YN
      FROM LEGACY_RUN_SCOPE LRS
      JOIN INIT$_TB_SCENARIO S
        ON S.SCENARIO_ID = LRS.SCENARIO_ID
       AND S.PROJECT_ID = LRS.PROJECT_ID
      JOIN LEGACY_FLOW_TABLE_SCOPE FT
        ON FT.FLOW_ID = LRS.FLOW_ID
       AND FT.SCENARIO_TABLE_COUNT = 1
      JOIN INIT$_TB_TABLES ST
        ON ST.SCENARIO_TABLE_ID = FT.SCENARIO_TABLE_ID
       AND ST.PROJECT_ID = LRS.PROJECT_ID
       AND ST.SCENARIO_ID = LRS.SCENARIO_ID
      LEFT JOIN INIT$_TB_UPLOAD_TABLE_META UM
        ON UM.OWNER_NAME = ST.OWNER_NAME
       AND UM.TABLE_NAME = ST.TABLE_NAME
      LEFT JOIN ALL_TABLES AT
        ON AT.OWNER = ST.OWNER_NAME
       AND AT.TABLE_NAME = ST.TABLE_NAME
)
, QUICK_RUNS AS (
    SELECT FLOW_RUN_ID
         , FLOW_ID
         , PROJECT_ID
         , PROJECT_CODE
         , PROJECT_NAME
         , SCENARIO_ID
         , SCENARIO_CODE
         , SCENARIO_NAME
         , SCENARIO_TABLE_ID
         , OWNER_NAME
         , TABLE_NAME
         , EDIT_OWNER_NAME
         , EDIT_TABLE_NAME
         , FILE_NAME
         , FILE_SIZE
         , ESTIMATED_ROW_COUNT
         , FLOW_NAME
         , JOB_COUNT
         , RUN_TYPE
         , STATUS
         , MESSAGE
         , STARTED_AT
         , FINISHED_AT
         , CREATED_AT
         , SUMMARY_YN
      FROM STORED_QUICK_RUNS
     UNION ALL
    SELECT FLOW_RUN_ID
         , FLOW_ID
         , PROJECT_ID
         , PROJECT_CODE
         , PROJECT_NAME
         , SCENARIO_ID
         , SCENARIO_CODE
         , SCENARIO_NAME
         , SCENARIO_TABLE_ID
         , OWNER_NAME
         , TABLE_NAME
         , EDIT_OWNER_NAME
         , EDIT_TABLE_NAME
         , FILE_NAME
         , FILE_SIZE
         , ESTIMATED_ROW_COUNT
         , FLOW_NAME
         , JOB_COUNT
         , RUN_TYPE
         , STATUS
         , MESSAGE
         , STARTED_AT
         , FINISHED_AT
         , CREATED_AT
         , SUMMARY_YN
      FROM LEGACY_QUICK_RUNS
)
, ELIGIBLE_RUNS AS (
    SELECT QR.*
         , COUNT(*) OVER () AS TOTAL_COUNT
         , ROW_NUMBER() OVER (
               ORDER BY COALESCE(QR.STARTED_AT, QR.CREATED_AT) DESC
                      , QR.FLOW_RUN_ID DESC
           ) AS RN
      FROM QUICK_RUNS QR
)
, PAGED_RUNS AS (
    SELECT /*+ MATERIALIZE */ *
      FROM ELIGIBLE_RUNS
     WHERE RN > :offset
       AND RN <= :endRow
)
, NODE_COUNTS AS (
    SELECT NR.FLOW_RUN_ID
         , COUNT(*) AS NODE_COUNT
         , SUM(CASE WHEN NR.STATUS = 'SUCCESS' THEN 1 ELSE 0 END) AS SUCCESS_NODE_COUNT
         , SUM(CASE WHEN NR.STATUS IN ('FAILED', 'ERROR', 'CANCELLED') THEN 1 ELSE 0 END) AS FAILED_NODE_COUNT
      FROM INIT$_TB_FLOW_WORK_NODE_RUN NR
     WHERE EXISTS (
            SELECT 1
              FROM PAGED_RUNS PR
             WHERE PR.FLOW_RUN_ID = NR.FLOW_RUN_ID
           )
     GROUP BY NR.FLOW_RUN_ID
)
SELECT PR.FLOW_RUN_ID
     , PR.FLOW_ID
     , PR.PROJECT_ID
     , COALESCE(QS.PROJECT_CODE, PR.PROJECT_CODE) AS PROJECT_CODE
     , COALESCE(QS.PROJECT_NAME, PR.PROJECT_NAME) AS PROJECT_NAME
     , QS.PROJECT_CREATED_AT
     , PR.SCENARIO_ID
     , COALESCE(QS.SCENARIO_CODE, PR.SCENARIO_CODE) AS SCENARIO_CODE
     , COALESCE(QS.SCENARIO_NAME, PR.SCENARIO_NAME) AS SCENARIO_NAME
     , QS.SCENARIO_CREATED_AT
     , COALESCE(QS.SCENARIO_TABLE_ID, PR.SCENARIO_TABLE_ID) AS SCENARIO_TABLE_ID
     , COALESCE(QS.OWNER_NAME, PR.OWNER_NAME) AS OWNER_NAME
     , COALESCE(QS.TABLE_NAME, PR.TABLE_NAME) AS TABLE_NAME
     , COALESCE(QS.EDIT_OWNER_NAME, PR.EDIT_OWNER_NAME) AS EDIT_OWNER_NAME
     , COALESCE(QS.EDIT_TABLE_NAME, PR.EDIT_TABLE_NAME) AS EDIT_TABLE_NAME
     , COALESCE(QS.FILE_NAME, PR.FILE_NAME) AS FILE_NAME
     , COALESCE(QS.FILE_SIZE, PR.FILE_SIZE) AS FILE_SIZE
     , COALESCE(QS.ESTIMATED_ROW_COUNT, PR.ESTIMATED_ROW_COUNT) AS ESTIMATED_ROW_COUNT
     , COALESCE(QS.FLOW_NAME, PR.FLOW_NAME) AS FLOW_NAME
     , COALESCE(QS.JOB_COUNT, PR.JOB_COUNT) AS JOB_COUNT
     , PR.RUN_TYPE
     , PR.STATUS
     , PR.MESSAGE
     , PR.STARTED_AT
     , PR.FINISHED_AT
     , PR.CREATED_AT
     , NVL(NC.NODE_COUNT, 0) AS NODE_COUNT
     , NVL(NC.SUCCESS_NODE_COUNT, 0) AS SUCCESS_NODE_COUNT
     , NVL(NC.FAILED_NODE_COUNT, 0) AS FAILED_NODE_COUNT
     , PR.TOTAL_COUNT
  FROM PAGED_RUNS PR
  LEFT JOIN INIT$_TB_FLOW_WORK_RUN SR
    ON SR.FLOW_RUN_ID = PR.FLOW_RUN_ID
   AND PR.SUMMARY_YN = 'Y'
  LEFT JOIN JSON_TABLE(
       SR.PLAN_JSON
     , '$.quickEditSummary' NULL ON ERROR
       COLUMNS (
           PROJECT_CODE VARCHAR2(100) PATH '$.projectCode'
         , PROJECT_NAME VARCHAR2(200) PATH '$.projectName'
         , PROJECT_CREATED_AT VARCHAR2(64) PATH '$.projectCreatedAt'
         , SCENARIO_CODE VARCHAR2(100) PATH '$.scenarioCode'
         , SCENARIO_NAME VARCHAR2(200) PATH '$.scenarioName'
         , SCENARIO_CREATED_AT VARCHAR2(64) PATH '$.scenarioCreatedAt'
         , SCENARIO_TABLE_ID NUMBER PATH '$.scenarioTableId'
         , OWNER_NAME VARCHAR2(128) PATH '$.ownerName'
         , TABLE_NAME VARCHAR2(128) PATH '$.tableName'
         , EDIT_OWNER_NAME VARCHAR2(128) PATH '$.editOwnerName'
         , EDIT_TABLE_NAME VARCHAR2(128) PATH '$.editTableName'
         , FILE_NAME VARCHAR2(255) PATH '$.fileName'
         , FILE_SIZE NUMBER PATH '$.fileSize'
         , ESTIMATED_ROW_COUNT NUMBER PATH '$.estimatedRowCount'
         , FLOW_NAME VARCHAR2(200) PATH '$.flowName'
         , JOB_COUNT NUMBER PATH '$.jobCount'
       )
     ) QS
    ON 1=1
  LEFT JOIN NODE_COUNTS NC
    ON NC.FLOW_RUN_ID = PR.FLOW_RUN_ID
 ORDER BY PR.RN
;

-- [FLOW_WORK_RUN_ID_LATEST]
SELECT MAX(FLOW_RUN_ID) AS FLOW_RUN_ID
  FROM INIT$_TB_FLOW_WORK_RUN
 WHERE FLOW_ID = :flowId
;

-- [FLOW_WORK_RUN_EXISTS_FOR_FLOW]
SELECT COUNT(*) AS RUN_COUNT
  FROM INIT$_TB_FLOW_WORK_RUN
 WHERE FLOW_ID = :flowId
   AND FLOW_RUN_ID = :flowRunId
;

-- [FLOW_WORK_RUN_LIST_BY_FLOW]
SELECT FLOW_RUN_ID
     , FLOW_ID
     , RUN_TYPE
     , STATUS
     , MESSAGE
     , PLAN_JSON
     , STARTED_AT
     , FINISHED_AT
     , CREATED_AT
     , CASE
           WHEN DBMS_LOB.INSTR(PLAN_JSON, '"editingSessionId"') > 0
             OR EXISTS (
                    SELECT 1
                      FROM INIT$_TB_FLOW_WORK_NODE_RUN NR
                     WHERE NR.FLOW_RUN_ID = INIT$_TB_FLOW_WORK_RUN.FLOW_RUN_ID
                       AND DBMS_LOB.INSTR(NR.RUNTIME_PARAM_JSON, '"INIT$EditingSessionId"') > 0
                )
           THEN 'Y'
           ELSE 'N'
       END AS EDITING_REVALIDATION_YN
  FROM INIT$_TB_FLOW_WORK_RUN
 WHERE FLOW_ID = :flowId
 ORDER BY FLOW_RUN_ID DESC
;

-- [FLOW_WORK_RUN_RESTART]
UPDATE INIT$_TB_FLOW_WORK_RUN
   SET RUN_TYPE = :runType
     , STATUS = :status
     , MESSAGE = :message
     , PLAN_JSON = :planJson
     , STARTED_AT = CASE WHEN :startedYn = 'Y' THEN SYSTIMESTAMP ELSE STARTED_AT END
     , FINISHED_AT = NULL
     , UPDATED_AT = SYSTIMESTAMP
 WHERE FLOW_ID = :flowId
   AND FLOW_RUN_ID = :flowRunId
;

-- [FLOW_WORK_RUN_RESUME]
UPDATE INIT$_TB_FLOW_WORK_RUN
   SET RUN_TYPE = :runType
     , STATUS = :status
     , MESSAGE = :message
     , PLAN_JSON = :planJson
     , STARTED_AT = SYSTIMESTAMP
     , FINISHED_AT = NULL
 WHERE FLOW_ID = :flowId
   AND FLOW_RUN_ID = :flowRunId
;

-- [FLOW_WORK_NODE_RUN_DELETE_BY_RUN]
DELETE FROM INIT$_TB_FLOW_WORK_NODE_RUN
 WHERE FLOW_RUN_ID = :flowRunId
;

-- [FLOW_WORK_NODE_RUN_DELETE_BY_RUN_KEY]
DELETE FROM INIT$_TB_FLOW_WORK_NODE_RUN
 WHERE FLOW_RUN_ID = :flowRunId
   AND NODE_KEY = :nodeKey
;

-- [FLOW_WORK_NODE_RUN_INSERT]
INSERT INTO INIT$_TB_FLOW_WORK_NODE_RUN (
    FLOW_RUN_ID
  , FLOW_ID
  , NODE_KEY
  , NODE_NAME
  , NODE_TYPE
  , RUN_LEVEL
  , SORT_ORDER
  , STATUS
  , MESSAGE
  , RUNTIME_PARAM_JSON
  , NODE_PAYLOAD_JSON
  , CREATED_AT
) VALUES (
    :flowRunId
  , :flowId
  , :nodeKey
  , :nodeName
  , :nodeType
  , :runLevel
  , :sortOrder
  , :status
  , :message
  , :runtimeParamJson
  , :nodePayloadJson
  , SYSTIMESTAMP
)
;

-- [FLOW_WORK_NODE_RUN_UPDATE]
UPDATE /*+ NO_PARALLEL(NR) */ INIT$_TB_FLOW_WORK_NODE_RUN NR
   SET STATUS = :status
     , MESSAGE = :message
     , STARTED_AT = CASE WHEN :startedYn = 'Y' THEN COALESCE(STARTED_AT, SYSTIMESTAMP) ELSE STARTED_AT END
     , FINISHED_AT = CASE WHEN :finishedYn = 'Y' THEN SYSTIMESTAMP ELSE FINISHED_AT END
     , UPDATED_AT = SYSTIMESTAMP
 WHERE NR.FLOW_NODE_RUN_ID = :flowNodeRunId
;

-- [FLOW_WORK_NODE_RUN_UPDATE_BY_KEY]
UPDATE /*+ NO_PARALLEL(NR) */ INIT$_TB_FLOW_WORK_NODE_RUN NR
   SET STATUS = :status
     , MESSAGE = :message
     , STARTED_AT = CASE WHEN :startedYn = 'Y' THEN COALESCE(STARTED_AT, SYSTIMESTAMP) ELSE STARTED_AT END
     , FINISHED_AT = CASE WHEN :finishedYn = 'Y' THEN SYSTIMESTAMP ELSE FINISHED_AT END
     , UPDATED_AT = SYSTIMESTAMP
 WHERE NR.FLOW_RUN_ID = :flowRunId
   AND NR.NODE_KEY = :nodeKey
;

-- [FLOW_WORK_NODE_RUN_UPDATE_RUNTIME_PARAMS]
UPDATE /*+ NO_PARALLEL(NR) */ INIT$_TB_FLOW_WORK_NODE_RUN NR
   SET RUNTIME_PARAM_JSON = :runtimeParamJson
     , UPDATED_AT = SYSTIMESTAMP
 WHERE NR.FLOW_RUN_ID = :flowRunId
   AND NR.NODE_KEY = :nodeKey
;

-- [FLOW_WORK_NODE_RUN_UPDATE_OUTPUT]
UPDATE /*+ NO_PARALLEL(NR) */ INIT$_TB_FLOW_WORK_NODE_RUN NR
   SET RUN_OUTPUT_JSON = :runOutputJson
     , UPDATED_AT = SYSTIMESTAMP
 WHERE NR.FLOW_RUN_ID = :flowRunId
   AND NR.NODE_KEY = :nodeKey
;

-- [FLOW_WORK_NODE_RUN_START_BY_KEY]
UPDATE /*+ NO_PARALLEL(NR) */ INIT$_TB_FLOW_WORK_NODE_RUN NR
   SET STATUS = 'RUNNING'
     , MESSAGE = :message
     , RUNTIME_PARAM_JSON = :runtimeParamJson
     , STARTED_AT = COALESCE(STARTED_AT, SYSTIMESTAMP)
     , UPDATED_AT = SYSTIMESTAMP
 WHERE NR.FLOW_RUN_ID = :flowRunId
   AND NR.NODE_KEY = :nodeKey
;

-- [FLOW_WORK_NODE_RUN_SKIP_BY_KEY]
UPDATE /*+ NO_PARALLEL(NR) */ INIT$_TB_FLOW_WORK_NODE_RUN NR
   SET STATUS = 'SKIPPED'
     , MESSAGE = :message
     , RUNTIME_PARAM_JSON = :runtimeParamJson
     , FINISHED_AT = SYSTIMESTAMP
     , UPDATED_AT = SYSTIMESTAMP
 WHERE NR.FLOW_RUN_ID = :flowRunId
   AND NR.NODE_KEY = :nodeKey
;

-- [FLOW_WORK_NODE_RUN_LIST]
SELECT NR.FLOW_NODE_RUN_ID
     , NR.FLOW_RUN_ID
     , NR.FLOW_ID
     , NR.NODE_KEY
     , NR.NODE_NAME
     , NR.NODE_TYPE
     , NR.RUN_LEVEL
     , NR.SORT_ORDER
     , NR.STATUS
     , NR.MESSAGE
     , FN.REF_WORK_JOB_ID
     , J.PARAM_JSON AS JOB_PARAM_JSON
     , NR.RUNTIME_PARAM_JSON
     , NR.NODE_PAYLOAD_JSON
     , NR.RUN_OUTPUT_JSON
     , NR.STARTED_AT
     , NR.FINISHED_AT
     , NR.CREATED_AT
     , NR.UPDATED_AT
  FROM INIT$_TB_FLOW_WORK_NODE_RUN NR
  LEFT JOIN INIT$_TB_FLOW_WORK_NODE FN
    ON FN.FLOW_ID = NR.FLOW_ID
   AND FN.NODE_KEY = NR.NODE_KEY
  LEFT JOIN INIT$_TB_DATA_WORK_JOB J
    ON J.WORK_JOB_ID = FN.REF_WORK_JOB_ID
 WHERE NR.FLOW_RUN_ID = :flowRunId
 ORDER BY NR.RUN_LEVEL, NR.SORT_ORDER NULLS LAST, NR.FLOW_NODE_RUN_ID
;

-- [FLOW_WORK_RUN_UPDATE]
UPDATE INIT$_TB_FLOW_WORK_RUN
   SET STATUS = :status
     , MESSAGE = :message
     , PLAN_JSON = :planJson
     , FINISHED_AT = SYSTIMESTAMP
 WHERE FLOW_RUN_ID = :flowRunId
;

-- [FLOW_WORK_RUN_START]
UPDATE INIT$_TB_FLOW_WORK_RUN
   SET STATUS = 'STARTED'
     , MESSAGE = :message
     , STARTED_AT = COALESCE(STARTED_AT, SYSTIMESTAMP)
     , FINISHED_AT = NULL
 WHERE FLOW_RUN_ID = :flowRunId
;

-- [FLOW_WORK_RUN_LIST]
SELECT R.FLOW_RUN_ID
     , 'FLOW_WORK' AS RUN_SOURCE_TYPE
     , R.FLOW_RUN_ID AS RUN_ID
     , R.FLOW_ID
     , F.MENU_CODE
     , F.PROJECT_ID
     , F.SCENARIO_ID
     , F.FLOW_GROUP
     , F.FLOW_NAME
     , R.RUN_TYPE
     , R.STATUS
     , R.MESSAGE
     , R.PLAN_JSON
     , R.STARTED_AT
     , R.FINISHED_AT
     , R.CREATED_AT
     , CASE
           WHEN DBMS_LOB.INSTR(R.PLAN_JSON, '"editingSessionId"') > 0
             OR EXISTS (
                    SELECT 1
                      FROM INIT$_TB_FLOW_WORK_NODE_RUN NR
                     WHERE NR.FLOW_RUN_ID = R.FLOW_RUN_ID
                       AND DBMS_LOB.INSTR(NR.RUNTIME_PARAM_JSON, '"INIT$EditingSessionId"') > 0
                )
           THEN 'Y'
           ELSE 'N'
       END AS EDITING_REVALIDATION_YN
  FROM INIT$_TB_FLOW_WORK_RUN R
  JOIN INIT$_TB_FLOW_WORK F
    ON F.FLOW_ID = R.FLOW_ID
 WHERE F.MENU_CODE = :menuCode
   AND F.PROJECT_ID = :projectId
   AND F.SCENARIO_ID = :scenarioId
   AND (:flowId IS NULL OR F.FLOW_ID = :flowId)
 ORDER BY COALESCE(R.STARTED_AT, R.CREATED_AT) DESC
        , R.FLOW_RUN_ID DESC
;

-- [FLOW_WORK_RUN_GET]
SELECT R.FLOW_RUN_ID
     , 'FLOW_WORK' AS RUN_SOURCE_TYPE
     , R.FLOW_RUN_ID AS RUN_ID
     , R.FLOW_ID
     , F.MENU_CODE
     , F.PROJECT_ID
     , F.SCENARIO_ID
     , F.FLOW_GROUP
     , F.FLOW_NAME
     , R.RUN_TYPE
     , R.STATUS
     , R.MESSAGE
     , R.PLAN_JSON
     , R.STARTED_AT
     , R.FINISHED_AT
     , R.CREATED_AT
     , (
        SELECT MAX(NR.UPDATED_AT)
          FROM INIT$_TB_FLOW_WORK_NODE_RUN NR
         WHERE NR.FLOW_RUN_ID = R.FLOW_RUN_ID
       ) AS NODE_UPDATED_AT
     , CASE
           WHEN DBMS_LOB.INSTR(R.PLAN_JSON, '"editingSessionId"') > 0
             OR EXISTS (
                    SELECT 1
                      FROM INIT$_TB_FLOW_WORK_NODE_RUN NR
                     WHERE NR.FLOW_RUN_ID = R.FLOW_RUN_ID
                       AND DBMS_LOB.INSTR(NR.RUNTIME_PARAM_JSON, '"INIT$EditingSessionId"') > 0
                )
           THEN 'Y'
           ELSE 'N'
       END AS EDITING_REVALIDATION_YN
  FROM INIT$_TB_FLOW_WORK_RUN R
  JOIN INIT$_TB_FLOW_WORK F
    ON F.FLOW_ID = R.FLOW_ID
 WHERE 1=1
   AND R.FLOW_RUN_ID = :flowRunId
   AND F.MENU_CODE = :menuCode
   AND F.PROJECT_ID = :projectId
   AND F.SCENARIO_ID = :scenarioId
;

-- [FLOW_WORK_RESULT_COLUMN_LIST]
SELECT COLUMN_NAME
  FROM ALL_TAB_COLUMNS
 WHERE OWNER = :owner
   AND TABLE_NAME = :tableName
 ORDER BY COLUMN_ID
;

-- [FLOW_WORK_RESULT_SQL_COUNT]
SELECT COUNT(*) AS TOTAL_COUNT
  FROM (
        /* --DYNAMIC_SQL-- */
       )
;

-- [FLOW_WORK_RESULT_SQL_PAGE]
SELECT *
  FROM (
        /* --DYNAMIC_SQL-- */
       )
 OFFSET :offset ROWS
 FETCH NEXT :limit ROWS ONLY
;

-- [FLOW_WORK_DISABLE_PARALLEL_DML]
ALTER SESSION DISABLE PARALLEL DML
;
