-- [MCOMMON_STATS_TABLE_COLUMNS]
SELECT C.COLUMN_NAME
     , C.DATA_TYPE
     , C.DATA_LENGTH
     , C.DATA_PRECISION
     , C.DATA_SCALE
     , C.COLUMN_ID
     , CC.COMMENTS AS COLUMN_COMMENT
     , (
        SELECT MAX(TRIM(F.TYPE_GROUP_CODE))
          FROM "INIT$_TB_COLTYPE_FINAL" F
         WHERE F.OWNER = C.OWNER
           AND F.TABLE_NAME = C.TABLE_NAME
           AND F.COLUMN_NAME = C.COLUMN_NAME
       ) AS TYPE_GROUP_CODE
  FROM ALL_TAB_COLUMNS C
  LEFT JOIN ALL_COL_COMMENTS CC
    ON CC.OWNER = C.OWNER
   AND CC.TABLE_NAME = C.TABLE_NAME
   AND CC.COLUMN_NAME = C.COLUMN_NAME
 WHERE C.OWNER = :ownerName
   AND C.TABLE_NAME = :tableName
 ORDER BY C.COLUMN_ID
;

-- [MCOMMON_STATS_EDIT_CONTINUOUS_COLUMNS]
SELECT DISTINCT R.TARGET_COLUMN AS COLUMN_NAME
  FROM "INIT$_TB_EDIT_SESSION_RULE" SR
  JOIN "INIT$_TB_EDIT_RULE" R
    ON R.EDIT_RULE_ID = SR.EDIT_RULE_ID
 WHERE SR.EDIT_SESSION_ID = :editSessionId
   AND R.SOURCE_RULE_TYPE = 'SYMBOLIC'
   AND R.TARGET_COLUMN IS NOT NULL
 ORDER BY R.TARGET_COLUMN
;

-- [MCOMMON_STATS_TABLE_PAIR]
SELECT T.PROJECT_ID
     , T.SCENARIO_ID
     , T.OWNER_NAME AS SOURCE_OWNER
     , T.TABLE_NAME AS SOURCE_TABLE
     , T.EDIT_OWNER_NAME AS EDIT_OWNER
     , T.EDIT_TABLE_NAME AS EDIT_TABLE
     , T.CASE_ID_COLUMN
  FROM "INIT$_TB_TABLES" T
 WHERE T.PROJECT_ID = :projectId
   AND (:scenarioId IS NULL OR T.SCENARIO_ID = :scenarioId)
   AND T.USE_YN = 'Y'
   AND (
          (T.OWNER_NAME = :targetOwner AND T.TABLE_NAME = :targetTable)
       OR (T.EDIT_OWNER_NAME = :targetOwner AND T.EDIT_TABLE_NAME = :targetTable)
       )
 ORDER BY CASE
              WHEN T.OWNER_NAME = :targetOwner AND T.TABLE_NAME = :targetTable THEN 0
              ELSE 1
          END
        , T.SCENARIO_TABLE_ID
;

-- [MCOMMON_STATS_FLOW_CONTEXT]
SELECT F.PROJECT_ID
     , F.SCENARIO_ID
  FROM "INIT$_TB_FLOW_WORK_RUN" FR
  JOIN "INIT$_TB_FLOW_WORK" F
    ON F.FLOW_ID = FR.FLOW_ID
  JOIN "INIT$_TB_PROJECT" P
    ON P.PROJECT_ID = F.PROJECT_ID
 WHERE FR.FLOW_RUN_ID = :flowRunId
   AND F.MENU_CODE = 'M04001'
   AND (:includeAllUsers = 'Y' OR P.USER_ID = :userId)
;

-- [MCOMMON_STATS_VIOLATION_COLUMNS]
WITH VIOLATION_BY_TYPE AS
(
    SELECT V.RESULT_COLUMN AS COLUMN_NAME
         , 'CATEGORICAL' AS RULE_TYPE
         , COUNT(*) AS VIOLATION_COUNT
         , COUNT(DISTINCT NVL(V.CASE_ID, V.CASE_ROWID)) AS VIOLATED_ROW_COUNT
         , COUNT(DISTINCT V.RULE_ID) AS RULE_COUNT
         , MAX(V.VIOLATION_SCORE) AS MAX_VIOLATION_SCORE
      FROM "INIT$_TB_RULEVIOL_ASSOC" V
     WHERE V.RUN_SOURCE_TYPE = :runSourceType
       AND V.RUN_ID = :runId
       AND V.TARGET_OWNER = :targetOwner
       AND V.TARGET_TABLE = :targetTable
       AND V.RESULT_COLUMN IS NOT NULL
     GROUP BY V.RESULT_COLUMN
    UNION ALL
    SELECT V.TARGET_COLUMN AS COLUMN_NAME
         , 'CONTINUOUS' AS RULE_TYPE
         , COUNT(*) AS VIOLATION_COUNT
         , COUNT(DISTINCT NVL(V.CASE_ID, V.CASE_ROWID)) AS VIOLATED_ROW_COUNT
         , COUNT(DISTINCT V.RULE_ID) AS RULE_COUNT
         , MAX(V.VIOLATION_SCORE) AS MAX_VIOLATION_SCORE
      FROM "INIT$_TB_RULEVIOL_SYMBOLIC" V
     WHERE V.RUN_SOURCE_TYPE = :runSourceType
       AND V.RUN_ID = :runId
       AND V.TARGET_OWNER = :targetOwner
       AND V.TARGET_TABLE = :targetTable
       AND V.TARGET_COLUMN IS NOT NULL
     GROUP BY V.TARGET_COLUMN
)
, VIOLATION_BY_COLUMN AS
(
    SELECT V.COLUMN_NAME
         , SUM(V.VIOLATION_COUNT) AS VIOLATION_COUNT
         , SUM(V.VIOLATED_ROW_COUNT) AS VIOLATED_ROW_COUNT
         , SUM(V.RULE_COUNT) AS RULE_COUNT
         , MAX(V.MAX_VIOLATION_SCORE) AS MAX_VIOLATION_SCORE
         , SUM(CASE WHEN V.RULE_TYPE = 'CATEGORICAL' THEN V.VIOLATION_COUNT ELSE 0 END) AS CATEGORICAL_VIOLATION_COUNT
         , SUM(CASE WHEN V.RULE_TYPE = 'CONTINUOUS' THEN V.VIOLATION_COUNT ELSE 0 END) AS CONTINUOUS_VIOLATION_COUNT
      FROM VIOLATION_BY_TYPE V
     GROUP BY V.COLUMN_NAME
)
SELECT V.COLUMN_NAME
     , C.DATA_TYPE
     , CC.COMMENTS AS COLUMN_COMMENT
     , V.VIOLATION_COUNT
     , V.VIOLATED_ROW_COUNT
     , V.RULE_COUNT
     , V.MAX_VIOLATION_SCORE
     , V.CATEGORICAL_VIOLATION_COUNT
     , V.CONTINUOUS_VIOLATION_COUNT
  FROM VIOLATION_BY_COLUMN V
  LEFT JOIN ALL_TAB_COLUMNS C
    ON C.OWNER = :targetOwner
   AND C.TABLE_NAME = :targetTable
   AND C.COLUMN_NAME = V.COLUMN_NAME
  LEFT JOIN ALL_COL_COMMENTS CC
    ON CC.OWNER = :targetOwner
   AND CC.TABLE_NAME = :targetTable
   AND CC.COLUMN_NAME = V.COLUMN_NAME
 ORDER BY V.VIOLATION_COUNT DESC
        , V.VIOLATED_ROW_COUNT DESC
        , V.COLUMN_NAME
;

-- [MCOMMON_STATS_AGGREGATE]
WITH NORMALIZED_VALUES AS
(
    SELECT /*+ MATERIALIZE NO_PARALLEL(T) */
           /* --DYNAMIC_COLUMNS-- */
      FROM /* --DYNAMIC_TABLE-- */ T
)
, LONG_VALUES AS
(
    SELECT /*+ MATERIALIZE */ COLUMN_NAME
         , NUMERIC_VALUE
      FROM NORMALIZED_VALUES
   UNPIVOT INCLUDE NULLS
     (
       NUMERIC_VALUE FOR COLUMN_NAME IN
       (
         /* --DYNAMIC_UNPIVOT-- */
       )
     )
)
, BASE_STATS AS
(
    SELECT COLUMN_NAME
         , COUNT(*) AS TOTAL_ROW_COUNT
         , COUNT(NUMERIC_VALUE) AS VALUE_COUNT
         , COUNT(DISTINCT NUMERIC_VALUE) AS DISTINCT_COUNT
         , SUM(NUMERIC_VALUE) AS SUM_VALUE
         , AVG(NUMERIC_VALUE) AS MEAN_VALUE
         , VAR_POP(NUMERIC_VALUE) AS VARIANCE_VALUE
         , STDDEV_POP(NUMERIC_VALUE) AS STDDEV_VALUE
         , MEDIAN(NUMERIC_VALUE) AS MEDIAN_VALUE
         , MIN(NUMERIC_VALUE) AS MIN_VALUE
         , PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY NUMERIC_VALUE) AS Q1_VALUE
         , PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY NUMERIC_VALUE) AS Q3_VALUE
         , MAX(NUMERIC_VALUE) AS MAX_VALUE
      FROM LONG_VALUES
     GROUP BY COLUMN_NAME
)
, CENTRAL_MOMENTS AS
(
    SELECT V.COLUMN_NAME
         , AVG(POWER(V.NUMERIC_VALUE - B.MEAN_VALUE, 3)) AS THIRD_MOMENT
         , AVG(POWER(V.NUMERIC_VALUE - B.MEAN_VALUE, 4)) AS FOURTH_MOMENT
      FROM LONG_VALUES V
      JOIN BASE_STATS B
        ON B.COLUMN_NAME = V.COLUMN_NAME
     WHERE V.NUMERIC_VALUE IS NOT NULL
     GROUP BY V.COLUMN_NAME
)
SELECT B.COLUMN_NAME
     , B.TOTAL_ROW_COUNT
     , B.VALUE_COUNT
     , B.TOTAL_ROW_COUNT - B.VALUE_COUNT AS NULL_COUNT
     , B.DISTINCT_COUNT
     , B.DISTINCT_COUNT / NULLIF(B.VALUE_COUNT, 0) AS DISTINCT_RATE
     , B.SUM_VALUE
     , B.MEAN_VALUE
     , B.VARIANCE_VALUE
     , B.STDDEV_VALUE
     , CASE
           WHEN B.VALUE_COUNT >= 3 AND B.VARIANCE_VALUE > 0
           THEN M.THIRD_MOMENT / POWER(B.VARIANCE_VALUE, 1.5)
       END AS SKEWNESS_VALUE
     , CASE
           WHEN B.VALUE_COUNT >= 4 AND B.VARIANCE_VALUE > 0
           THEN M.FOURTH_MOMENT / POWER(B.VARIANCE_VALUE, 2) - 3
       END AS KURTOSIS_VALUE
     , B.MEDIAN_VALUE
     , B.MIN_VALUE
     , B.Q1_VALUE
     , B.Q3_VALUE
     , B.MAX_VALUE
  FROM BASE_STATS B
  LEFT JOIN CENTRAL_MOMENTS M
    ON M.COLUMN_NAME = B.COLUMN_NAME
 ORDER BY B.COLUMN_NAME
;

-- [MCOMMON_STATS_GENERAL_AGGREGATE]
WITH NORMALIZED_VALUES AS
(
    SELECT /*+ MATERIALIZE NO_PARALLEL(T) */
           /* --DYNAMIC_COLUMNS-- */
      FROM /* --DYNAMIC_TABLE-- */ T
)
, LONG_VALUES AS
(
    SELECT /*+ MATERIALIZE */ COLUMN_NAME
         , TEXT_VALUE
      FROM NORMALIZED_VALUES
   UNPIVOT INCLUDE NULLS
     (
       TEXT_VALUE FOR COLUMN_NAME IN
       (
         /* --DYNAMIC_UNPIVOT-- */
       )
     )
)
SELECT COLUMN_NAME
     , COUNT(*) AS TOTAL_ROW_COUNT
     , COUNT(TEXT_VALUE) AS VALUE_COUNT
     , COUNT(*) - COUNT(TEXT_VALUE) AS NULL_COUNT
     , COUNT(DISTINCT TEXT_VALUE) AS DISTINCT_COUNT
     , COUNT(DISTINCT TEXT_VALUE) / NULLIF(COUNT(TEXT_VALUE), 0) AS DISTINCT_RATE
     , MIN(TEXT_VALUE) AS MIN_TEXT_VALUE
     , MAX(TEXT_VALUE) AS MAX_TEXT_VALUE
     , MIN(LENGTH(TEXT_VALUE)) AS MIN_LENGTH
     , MAX(LENGTH(TEXT_VALUE)) AS MAX_LENGTH
     , AVG(LENGTH(TEXT_VALUE)) AS AVG_LENGTH
  FROM LONG_VALUES
 GROUP BY COLUMN_NAME
 ORDER BY COLUMN_NAME
;

-- [MCOMMON_STATS_TOP_VALUES]
WITH NORMALIZED_VALUES AS
(
    SELECT /*+ MATERIALIZE NO_PARALLEL(T) */
           /* --DYNAMIC_COLUMNS-- */
      FROM /* --DYNAMIC_TABLE-- */ T
)
, LONG_VALUES AS
(
    SELECT /*+ MATERIALIZE */ COLUMN_NAME
         , TEXT_VALUE
      FROM NORMALIZED_VALUES
   UNPIVOT INCLUDE NULLS
     (
       TEXT_VALUE FOR COLUMN_NAME IN
       (
         /* --DYNAMIC_UNPIVOT-- */
       )
     )
)
, VALUE_COUNTS AS
(
    SELECT COLUMN_NAME
         , TEXT_VALUE
         , COUNT(*) AS VALUE_COUNT
      FROM LONG_VALUES
     WHERE TEXT_VALUE IS NOT NULL
     GROUP BY COLUMN_NAME
            , TEXT_VALUE
)
, RANKED_VALUES AS
(
    SELECT V.COLUMN_NAME
         , V.TEXT_VALUE
         , V.VALUE_COUNT
         , ROW_NUMBER() OVER
           (
             PARTITION BY V.COLUMN_NAME
                 ORDER BY V.VALUE_COUNT DESC
                        , V.TEXT_VALUE
           ) AS VALUE_RANK
      FROM VALUE_COUNTS V
)
SELECT COLUMN_NAME
     , TEXT_VALUE
     , VALUE_COUNT
     , VALUE_RANK
  FROM RANKED_VALUES
 WHERE VALUE_RANK <= 10
 ORDER BY COLUMN_NAME
        , VALUE_RANK
;

-- [MCOMMON_STATS_DISTRIBUTION]
WITH COLUMN_BOUNDS AS
(
    /* --DYNAMIC_BOUNDS-- */
)
, NORMALIZED_VALUES AS
(
    SELECT /*+ MATERIALIZE NO_PARALLEL(T) */
           /* --DYNAMIC_COLUMNS-- */
      FROM /* --DYNAMIC_TABLE-- */ T
)
, LONG_VALUES AS
(
    SELECT /*+ MATERIALIZE */ COLUMN_NAME
         , NUMERIC_VALUE
      FROM NORMALIZED_VALUES
   UNPIVOT INCLUDE NULLS
     (
       NUMERIC_VALUE FOR COLUMN_NAME IN
       (
         /* --DYNAMIC_UNPIVOT-- */
       )
     )
)
, BUCKETED_VALUES AS
(
    SELECT V.COLUMN_NAME
         , CASE
               WHEN B.MAX_VALUE = B.MIN_VALUE THEN 1
               ELSE LEAST(
                        :binCount
                      , GREATEST(
                            1
                          , WIDTH_BUCKET(V.NUMERIC_VALUE, B.MIN_VALUE, B.MAX_VALUE, :binCount)
                        )
                    )
           END AS BUCKET_NO
      FROM LONG_VALUES V
      JOIN COLUMN_BOUNDS B
        ON B.COLUMN_NAME = V.COLUMN_NAME
     WHERE V.NUMERIC_VALUE IS NOT NULL
)
SELECT COLUMN_NAME
     , BUCKET_NO
     , COUNT(*) AS BUCKET_COUNT
  FROM BUCKETED_VALUES
 GROUP BY COLUMN_NAME
        , BUCKET_NO
 ORDER BY COLUMN_NAME
        , BUCKET_NO
;
