-- [DATA_WORK_JOB_LIST]
SELECT WORK_JOB_ID AS PROFILE_JOB_ID
     , WORK_JOB_ID
     , MENU_CODE
     , PROJECT_ID
     , SCENARIO_ID
     , SCENARIO_TABLE_ID
     , JOB_GROUP
     , JOB_NAME
     , JOB_DESC
     , OWNER_NAME
     , TABLE_NAME
     , EXEC_SOURCE_TYPE
     , EXEC_RESOURCE_ID
     , EXEC_METHOD
     , EXEC_SPEC_JSON
     , EXEC_OBJECT_ID
     , EXEC_OWNER
     , EXEC_OBJECT_TYPE
     , EXEC_OBJECT_NAME
     , EXEC_OBJECT_LABEL
     , USE_YN
     , SORT_ORDER
     , RESULT_CREATE_YN
     , RESULT_OWNER
     , RESULT_TABLE_NAME
     , STATUS
     , STARTED_AT
     , FINISHED_AT
     , CREATED_AT
     , UPDATED_AT
  FROM INIT$_TB_DATA_WORK_JOB
 WHERE MENU_CODE = :menuCode
   AND PROJECT_ID = :projectId
   AND SCENARIO_ID = :scenarioId
ORDER BY JOB_GROUP, SORT_ORDER NULLS LAST, WORK_JOB_ID
;

-- [DATA_WORK_IMPORT_JOB_LIST]
SELECT J.WORK_JOB_ID AS PROFILE_JOB_ID
     , J.JOB_NAME
     , J.JOB_DESC
     , J.EXEC_SOURCE_TYPE
     , J.EXEC_OBJECT_LABEL
     , J.EXEC_OBJECT_NAME
     , J.RESULT_CREATE_YN
  FROM INIT$_TB_DATA_WORK_JOB J
  JOIN INIT$_TB_PROJECT P
    ON P.PROJECT_ID = J.PROJECT_ID
 WHERE J.MENU_CODE = :menuCode
   AND J.JOB_GROUP = :jobGroup
   AND J.PROJECT_ID = :projectId
   AND J.SCENARIO_ID = :scenarioId
   AND (:includeAllUsers = 'Y' OR P.USER_ID = :userId)
 ORDER BY J.SORT_ORDER NULLS LAST, J.WORK_JOB_ID
;

-- [DATA_WORK_IMPORT_JOB_DETAIL]
SELECT J.JOB_NAME
     , J.JOB_DESC
     , J.EXEC_SOURCE_TYPE
     , J.EXEC_METHOD
     , J.EXEC_OWNER
     , J.EXEC_OBJECT_TYPE
     , J.EXEC_OBJECT_NAME
     , J.EXEC_OBJECT_LABEL
     , J.PARAM_JSON
     , J.EXEC_PLSQL
     , J.RESULT_CREATE_YN
     , J.RESULT_OWNER
     , J.RESULT_TABLE_NAME
  FROM INIT$_TB_DATA_WORK_JOB J
  JOIN INIT$_TB_PROJECT P
    ON P.PROJECT_ID = J.PROJECT_ID
 WHERE J.MENU_CODE = :menuCode
   AND J.JOB_GROUP = :jobGroup
   AND J.WORK_JOB_ID = :profileJobId
   AND J.PROJECT_ID = :projectId
   AND J.SCENARIO_ID = :scenarioId
   AND (:includeAllUsers = 'Y' OR P.USER_ID = :userId)
;

-- [DATA_WORK_OML_RESOURCE_LIST]
SELECT OML_RESOURCE_ID
     , RESOURCE_NAME
     , RESOURCE_LABEL
     , RESOURCE_TYPE
     , LANGUAGE
     , EXEC_API
     , EXEC_METHOD
     , SCRIPT_NAME
     , SCRIPT_OWNER
     , INPUT_MODE
     , DESCRIPTION
     , TIMEOUT_SEC
     , USE_YN
     , SORT_ORDER
  FROM INIT$_TB_OML_RESOURCE
 WHERE USE_YN = 'Y'
   AND LANGUAGE = 'PYTHON'
 ORDER BY SORT_ORDER NULLS LAST, RESOURCE_NAME
;

-- [DATA_WORK_OML_RESOURCE_DETAIL]
SELECT R.OML_RESOURCE_ID
     , R.RESOURCE_NAME
     , R.RESOURCE_LABEL
     , R.RESOURCE_TYPE
     , R.LANGUAGE
     , R.EXEC_API
     , R.EXEC_METHOD
     , R.SCRIPT_NAME
     , R.SCRIPT_OWNER
     , R.INPUT_MODE
     , R.OUTPUT_FORMAT
     , R.SPEC_JSON
     , R.DESCRIPTION
     , R.TIMEOUT_SEC
     , P.PARAM_NAME
     , P.BIND_NAME
     , P.DATA_TYPE
     , P.REQUIRED_YN
     , P.PARAM_DESC
     , P.DEFAULT_VALUE
     , P.ITEM_ORDER
  FROM INIT$_TB_OML_RESOURCE R
  LEFT JOIN INIT$_TB_OML_RESOURCE_PARAM P
    ON P.OML_RESOURCE_ID = R.OML_RESOURCE_ID
 WHERE R.OML_RESOURCE_ID = :resourceId
 ORDER BY P.ITEM_ORDER NULLS LAST, P.PARAM_NAME
;

-- [DATA_WORK_MODEL_DETAIL_VIEW_LIST]
WITH VIEW_TYPES AS (
    SELECT 'VA' AS VIEW_TYPE, 'Attribute/detail view' AS DESCRIPTION, :viewNameVa AS VIEW_NAME FROM DUAL UNION ALL
    SELECT 'VG', 'Global/detail view', :viewNameVg FROM DUAL UNION ALL
    SELECT 'VI', 'Itemset/detail view', :viewNameVi FROM DUAL UNION ALL
    SELECT 'VN', 'Node/detail view', :viewNameVn FROM DUAL UNION ALL
    SELECT 'VP', 'Pattern/partition/detail view', :viewNameVp FROM DUAL UNION ALL
    SELECT 'VR', 'Rule/detail view', :viewNameVr FROM DUAL UNION ALL
    SELECT 'VT', 'Transformation/detail view', :viewNameVt FROM DUAL
)
SELECT V.VIEW_TYPE
     , V.VIEW_NAME
     , V.DESCRIPTION
     , O.OBJECT_TYPE
     , CASE WHEN O.OBJECT_NAME IS NULL THEN 'N' ELSE 'Y' END AS EXISTS_YN
  FROM VIEW_TYPES V
  LEFT JOIN ALL_OBJECTS O
    ON O.OWNER = :owner
   AND O.OBJECT_NAME = V.VIEW_NAME
 ORDER BY V.VIEW_TYPE
;

-- [DATA_WORK_PREDICTED_TYPE_RUN_ID]
SELECT MAX(RUN_ID) AS RUN_ID
  FROM /* --PREDICTED_TYPE_OBJECT-- */
 WHERE OWNER = :sourceOwner
   AND TABLE_NAME = :sourceTable
   AND RUN_SOURCE_TYPE = 'DATA_WORK'
/* --MODEL_NAME_FILTER-- */
;

-- [DATA_WORK_RESULT_TABLE_RUN_ID]
SELECT MAX(RUN_ID) AS RUN_ID
  FROM /* --RESULT_TABLE_OBJECT-- */
 WHERE /* --OWNER_COLUMN-- */ = :sourceOwner
   AND /* --TABLE_COLUMN-- */ = :sourceTable
   AND RUN_SOURCE_TYPE = 'DATA_WORK'
;

-- [DATA_WORK_CONTEXT_RUN_ID_GET]
SELECT NVL(DATA_WORK_RUN_ID, 0) AS DATA_WORK_RUN_ID
     , DATA_WORK_RUN_AT
  FROM INIT$_TB_SCENARIO
 WHERE PROJECT_ID = :projectId
   AND SCENARIO_ID = :scenarioId
;

-- [DATA_WORK_CONTEXT_RUN_ID_ENSURE]
UPDATE INIT$_TB_SCENARIO
   SET DATA_WORK_RUN_ID = 1
     , DATA_WORK_RUN_AT = SYSTIMESTAMP
     , UPDATED_AT = SYSTIMESTAMP
 WHERE PROJECT_ID = :projectId
   AND SCENARIO_ID = :scenarioId
   AND NVL(DATA_WORK_RUN_ID, 0) <= 0
;

-- [DATA_WORK_CONTEXT_RUN_ID_NEXT]
UPDATE INIT$_TB_SCENARIO
   SET DATA_WORK_RUN_ID = NVL(DATA_WORK_RUN_ID, 0) + 1
     , DATA_WORK_RUN_AT = SYSTIMESTAMP
     , UPDATED_AT = SYSTIMESTAMP
 WHERE PROJECT_ID = :projectId
   AND SCENARIO_ID = :scenarioId
;

-- [DATA_WORK_TABLE_COLUMN_NAMES]
SELECT COLUMN_NAME
  FROM ALL_TAB_COLUMNS
 WHERE OWNER = :owner
   AND TABLE_NAME = :tableName
 ORDER BY COLUMN_ID
;

-- [DATA_WORK_EDITABLE_DATA_COUNT]
SELECT COUNT(*) AS TOTAL_COUNT
  FROM /* --DYNAMIC_TABLE-- */ T
/* --DYNAMIC_SQL-- */
;

-- [DATA_WORK_EDITABLE_DATA_PAGE]
SELECT ROWIDTOCHAR(T.ROWID) AS "INIT$ROWID"
     , /* --DYNAMIC_COLUMNS-- */
  FROM /* --DYNAMIC_TABLE-- */ T
/* --DYNAMIC_SQL-- */
 OFFSET :offset ROWS
 FETCH NEXT :limit ROWS ONLY
;

-- [DATA_WORK_COLUMN_TYPE_CONFIRM]
BEGIN
    INIT$_SP_COLUMN_TYPE_CONFIRM(
        p_owner           => :owner
      , p_table_name      => :tableName
      , p_column_name     => :columnName
      , p_display_type    => :displayType
      , p_reason          => :reason
      , p_run_source_type => :runSourceType
      , p_run_id          => :runId
      , p_model_name      => :modelName
      , p_user_id         => :userId
      , p_label_source    => 'USER_CONFIRMED'
      , p_confirmed_yn    => :confirmedYn
    );
END;

-- [DATA_WORK_JOB_DETAIL]
SELECT WORK_JOB_ID AS PROFILE_JOB_ID
     , WORK_JOB_ID
     , MENU_CODE
     , PROJECT_ID
     , SCENARIO_ID
     , SCENARIO_TABLE_ID
     , JOB_GROUP
     , JOB_NAME
     , JOB_DESC
     , OWNER_NAME
     , TABLE_NAME
     , EXEC_SOURCE_TYPE
     , EXEC_RESOURCE_ID
     , EXEC_METHOD
     , EXEC_SPEC_JSON
     , EXEC_OBJECT_ID
     , EXEC_OWNER
     , EXEC_OBJECT_TYPE
     , EXEC_OBJECT_NAME
     , EXEC_OBJECT_LABEL
     , USE_YN
     , SORT_ORDER
     , PARAM_JSON
     , EXEC_PLSQL
     , RESULT_CREATE_YN
     , RESULT_OWNER
     , RESULT_TABLE_NAME
     , STATUS
     , STARTED_AT
     , FINISHED_AT
     , CREATED_AT
     , UPDATED_AT
  FROM INIT$_TB_DATA_WORK_JOB
 WHERE MENU_CODE = :menuCode
   AND WORK_JOB_ID = :profileJobId
;

-- [DATA_WORK_JOB_INSERT]
INSERT INTO INIT$_TB_DATA_WORK_JOB (
    MENU_CODE
  , PROJECT_ID
  , SCENARIO_ID
  , SCENARIO_TABLE_ID
  , JOB_GROUP
  , JOB_NAME
  , JOB_DESC
  , OWNER_NAME
  , TABLE_NAME
  , EXEC_SOURCE_TYPE
  , EXEC_RESOURCE_ID
  , EXEC_METHOD
  , EXEC_SPEC_JSON
  , EXEC_OBJECT_ID
  , EXEC_OWNER
  , EXEC_OBJECT_TYPE
  , EXEC_OBJECT_NAME
  , EXEC_OBJECT_LABEL
  , USE_YN
  , SORT_ORDER
  , PARAM_JSON
  , EXEC_PLSQL
  , RESULT_CREATE_YN
  , RESULT_OWNER
  , RESULT_TABLE_NAME
  , STATUS
  , CREATED_AT
) VALUES (
    :menuCode
  , :projectId
  , :scenarioId
  , :scenarioTableId
  , :jobGroup
  , :jobName
  , :jobDesc
  , :ownerName
  , :tableName
  , :execSourceType
  , :execResourceId
  , :execMethod
  , :execSpecJson
  , :execObjectId
  , :execOwner
  , :execObjectType
  , :execObjectName
  , :execObjectLabel
  , :useYn
  , :sortOrder
  , :paramJson
  , :execPlsql
  , :resultCreateYn
  , :resultOwner
  , :resultTableName
  , :status
  , SYSTIMESTAMP
)
;

-- [DATA_WORK_JOB_UPDATE]
UPDATE INIT$_TB_DATA_WORK_JOB
   SET SCENARIO_TABLE_ID = :scenarioTableId
     , JOB_GROUP = :jobGroup
     , JOB_NAME = :jobName
     , JOB_DESC = :jobDesc
     , OWNER_NAME = :ownerName
     , TABLE_NAME = :tableName
     , EXEC_SOURCE_TYPE = :execSourceType
     , EXEC_RESOURCE_ID = :execResourceId
     , EXEC_METHOD = :execMethod
     , EXEC_SPEC_JSON = :execSpecJson
     , EXEC_OBJECT_ID = :execObjectId
     , EXEC_OWNER = :execOwner
     , EXEC_OBJECT_TYPE = :execObjectType
     , EXEC_OBJECT_NAME = :execObjectName
     , EXEC_OBJECT_LABEL = :execObjectLabel
     , USE_YN = :useYn
     , SORT_ORDER = :sortOrder
     , PARAM_JSON = :paramJson
     , EXEC_PLSQL = :execPlsql
     , RESULT_CREATE_YN = :resultCreateYn
     , RESULT_OWNER = :resultOwner
     , RESULT_TABLE_NAME = :resultTableName
     , STATUS = :status
     , UPDATED_AT = SYSTIMESTAMP
 WHERE MENU_CODE = :menuCode
   AND WORK_JOB_ID = :profileJobId
   AND PROJECT_ID = :projectId
   AND SCENARIO_ID = :scenarioId
;

-- [DATA_WORK_JOB_ID_LATEST]
SELECT MAX(WORK_JOB_ID) AS PROFILE_JOB_ID
  FROM INIT$_TB_DATA_WORK_JOB
 WHERE MENU_CODE = :menuCode
   AND PROJECT_ID = :projectId
   AND SCENARIO_ID = :scenarioId
   AND JOB_GROUP = :jobGroup
   AND JOB_NAME = :jobName
   AND OWNER_NAME = :ownerName
   AND TABLE_NAME = :tableName
;

-- Free-tier/Autonomous DB safeguard: keep job delete cleanup serial to avoid
-- ORA-12839 in parent/child delete transactions. Review before changing for
-- production DB parallel DML policy.
-- [DATA_WORK_RUN_DELETE_BY_JOB]
DELETE /*+ NO_PARALLEL */
  FROM INIT$_TB_DATA_WORK_RUN
 WHERE WORK_JOB_ID = :profileJobId
;

-- [DATA_WORK_JOB_FLOW_REF_LIST]
SELECT F.MENU_CODE AS FLOW_MENU_CODE
     , F.FLOW_ID
     , F.FLOW_GROUP
     , F.FLOW_NAME
     , N.FLOW_NODE_ID
     , N.NODE_KEY
     , N.NODE_NAME
  FROM INIT$_TB_FLOW_WORK_NODE N
  JOIN INIT$_TB_FLOW_WORK F
    ON F.FLOW_ID = N.FLOW_ID
 WHERE N.REF_WORK_JOB_ID = :profileJobId
 ORDER BY F.MENU_CODE, F.FLOW_NAME, N.NODE_NAME, N.NODE_KEY
;

-- [DATA_WORK_JOB_DELETE]
DELETE /*+ NO_PARALLEL */
  FROM INIT$_TB_DATA_WORK_JOB
 WHERE MENU_CODE = :menuCode
   AND WORK_JOB_ID = :profileJobId
   AND PROJECT_ID = :projectId
   AND SCENARIO_ID = :scenarioId
;

-- [DATA_WORK_JOB_RUN_LIST]
SELECT WORK_JOB_ID AS PROFILE_JOB_ID
     , WORK_JOB_ID
     , MENU_CODE
     , PROJECT_ID
     , SCENARIO_ID
     , SCENARIO_TABLE_ID
     , JOB_GROUP
     , JOB_NAME
     , JOB_DESC
     , OWNER_NAME
     , TABLE_NAME
     , EXEC_SOURCE_TYPE
     , EXEC_RESOURCE_ID
     , EXEC_METHOD
     , EXEC_OBJECT_ID
     , EXEC_OWNER
     , EXEC_OBJECT_TYPE
     , EXEC_OBJECT_NAME
     , EXEC_OBJECT_LABEL
     , USE_YN
     , SORT_ORDER
     , RESULT_CREATE_YN
     , RESULT_OWNER
     , RESULT_TABLE_NAME
     , STATUS
     , STARTED_AT
     , FINISHED_AT
     , CREATED_AT
     , UPDATED_AT
  FROM INIT$_TB_DATA_WORK_JOB
 WHERE MENU_CODE = :menuCode
   AND PROJECT_ID = :projectId
   AND SCENARIO_ID = :scenarioId
   AND USE_YN = 'Y'
 ORDER BY JOB_GROUP, SORT_ORDER NULLS LAST, WORK_JOB_ID
;

-- [DATA_WORK_JOB_STATUS_UPDATE]
UPDATE INIT$_TB_DATA_WORK_JOB
   SET STATUS = :status
     , RESULT_OWNER = :resultOwner
     , RESULT_TABLE_NAME = :resultTableName
     , STARTED_AT = CASE WHEN :startedYn = 'Y' THEN SYSTIMESTAMP ELSE STARTED_AT END
     , FINISHED_AT = CASE WHEN :finishedYn = 'Y' THEN SYSTIMESTAMP ELSE FINISHED_AT END
     , UPDATED_AT = SYSTIMESTAMP
 WHERE MENU_CODE = :menuCode
   AND WORK_JOB_ID = :profileJobId
;

-- [DATA_WORK_RUN_INSERT]
INSERT INTO INIT$_TB_DATA_WORK_RUN (
    WORK_JOB_ID
  , DATA_RUN_ID
  , RUN_TYPE
  , STATUS
  , MESSAGE
  , RESULT_OWNER
  , RESULT_TABLE_NAME
  , STARTED_AT
  , CREATED_AT
) VALUES (
    :profileJobId
  , :dataRunId
  , :runType
  , :status
  , :message
  , :resultOwner
  , :resultTableName
  , SYSTIMESTAMP
  , SYSTIMESTAMP
)
;

-- [DATA_WORK_RUN_ID_LATEST]
SELECT MAX(WORK_RUN_ID) AS PROFILE_RUN_ID
  FROM INIT$_TB_DATA_WORK_RUN
 WHERE WORK_JOB_ID = :profileJobId
;

-- [DATA_WORK_RUN_EXISTS_FOR_JOB]
SELECT COUNT(*) AS RUN_COUNT
  FROM INIT$_TB_DATA_WORK_RUN
 WHERE WORK_JOB_ID = :profileJobId
   AND WORK_RUN_ID = :profileRunId
;

-- [DATA_WORK_RUN_RESTART]
UPDATE INIT$_TB_DATA_WORK_RUN
   SET RUN_TYPE = :runType
     , STATUS = :status
     , MESSAGE = :message
     , RESULT_OWNER = :resultOwner
     , RESULT_TABLE_NAME = :resultTableName
     , STARTED_AT = SYSTIMESTAMP
     , FINISHED_AT = NULL
     , UPDATED_AT = SYSTIMESTAMP
 WHERE WORK_JOB_ID = :profileJobId
   AND WORK_RUN_ID = :profileRunId
;

-- [DATA_WORK_RUN_UPDATE]
UPDATE INIT$_TB_DATA_WORK_RUN
   SET STATUS = :status
     , MESSAGE = :message
     , RESULT_OWNER = :resultOwner
     , RESULT_TABLE_NAME = :resultTableName
     , FINISHED_AT = SYSTIMESTAMP
 WHERE WORK_RUN_ID = :profileRunId
;

-- [DATA_WORK_COLTYPE_MODEL_EXECUTION_LOG]
WITH LATEST_EXECUTION_RESULT AS
     (
      SELECT R."MODEL_NAME"
           , R."MODEL_VERSION_ID"
           , R."MODEL_VERSION"
           , R."MODL_PREDICTED_TYPE"
           , ROW_NUMBER() OVER (
                 PARTITION BY R."COLUMN_NAME"
                     ORDER BY R."CREATE_DT" DESC
                            , NVL(R."MODEL_VERSION_ID", -1) DESC
                            , R."MODEL_NAME" DESC
             ) AS RN
        FROM "INIT$_TB_COLTYPE_RESULT" R
       WHERE R."RUN_SOURCE_TYPE" = :runSourceType
         AND R."RUN_ID" = :runId
         AND R."OWNER" = :targetOwner
         AND R."TABLE_NAME" = :targetTable
     ),
     ACTIVE_MODEL AS
     (
      SELECT R."PHYSICAL_MODEL_NAME"
           , R."MODEL_VERSION_ID"
           , R."VERSION_NO"
        FROM "INIT$_TB_OML_ACTIVE_MODEL" A
        JOIN "INIT$_TB_OML_MODEL_REGISTRY" R
          ON R."MODEL_VERSION_ID" = A."MODEL_VERSION_ID"
       WHERE A."MODEL_KEY" = 'COLUMN_TYPE'
     )
SELECT MAX(L."MODEL_NAME") AS PHYSICAL_MODEL_NAME
     , MAX(L."MODEL_VERSION_ID") AS MODEL_VERSION_ID
     , MAX(L."MODEL_VERSION") AS MODEL_VERSION
     , MAX(A."PHYSICAL_MODEL_NAME") AS ACTIVE_PHYSICAL_MODEL_NAME
     , MAX(A."MODEL_VERSION_ID") AS ACTIVE_MODEL_VERSION_ID
     , MAX(A."VERSION_NO") AS ACTIVE_MODEL_VERSION
     , COUNT(*) AS RESULT_ROW_COUNT
     , SUM(CASE WHEN L."MODL_PREDICTED_TYPE" IS NOT NULL THEN 1 ELSE 0 END) AS MODEL_PREDICTED_ROW_COUNT
  FROM LATEST_EXECUTION_RESULT L
  LEFT JOIN ACTIVE_MODEL A
    ON 1 = 1
 WHERE L.RN = 1
;

-- [DATA_WORK_RUN_LIST]
SELECT R.WORK_RUN_ID AS PROFILE_RUN_ID
     , R.WORK_JOB_ID AS PROFILE_JOB_ID
     , R.WORK_RUN_ID
     , R.DATA_RUN_ID
     , 'DATA_WORK' AS RUN_SOURCE_TYPE
     , R.DATA_RUN_ID AS RUN_ID
     , R.WORK_JOB_ID
     , J.MENU_CODE
     , J.JOB_GROUP
     , J.JOB_NAME
     , J.SORT_ORDER
     , R.RUN_TYPE
     , R.STATUS
     , R.MESSAGE
     , R.RESULT_OWNER
     , R.RESULT_TABLE_NAME
     , R.STARTED_AT
     , R.FINISHED_AT
     , R.CREATED_AT
  FROM INIT$_TB_DATA_WORK_RUN R
  JOIN INIT$_TB_DATA_WORK_JOB J
    ON J.WORK_JOB_ID = R.WORK_JOB_ID
 WHERE J.MENU_CODE = :menuCode
   AND J.PROJECT_ID = :projectId
   AND J.SCENARIO_ID = :scenarioId
 ORDER BY R.CREATED_AT DESC, R.WORK_RUN_ID DESC
;
