-- [XAI_SCHEMA_CHECK]
SELECT TABLE_NAME
  FROM USER_TABLES
 WHERE TABLE_NAME IN ('INIT$_TB_XAI_RUN', 'INIT$_TB_RULEDISC_XAI', 'INIT$_TB_RULEVIOL_XAI')
;

-- [XAI_SOURCE_COLUMNS]
SELECT COLUMN_NAME
     , DATA_TYPE
     , DATA_LENGTH
  FROM ALL_TAB_COLS
 WHERE OWNER = :owner
   AND TABLE_NAME = :tableName
   AND HIDDEN_COLUMN = 'NO'
 ORDER BY COLUMN_ID
;

-- [XAI_SOURCE_SAMPLE]
SELECT /*+ NO_PARALLEL(T) */ /*COLUMNS*/
  FROM /*TARGET*/ T
 WHERE ROWNUM <= :rowLimit
;

-- [XAI_RUN_ACCESS]
SELECT P.USER_ID
  FROM INIT$_TB_FLOW_WORK_RUN R
  JOIN INIT$_TB_FLOW_WORK F
    ON F.FLOW_ID = R.FLOW_ID
  JOIN INIT$_TB_PROJECT P
    ON P.PROJECT_ID = F.PROJECT_ID
  JOIN INIT$_TB_TABLES T
    ON T.PROJECT_ID = F.PROJECT_ID
   AND T.SCENARIO_ID = F.SCENARIO_ID
 WHERE :runSourceType = 'FLOW_WORK'
   AND R.FLOW_RUN_ID = :runId
   AND P.USER_ID = :userId
   AND ((T.OWNER_NAME = :owner AND T.TABLE_NAME = :tableName)
     OR (T.EDIT_OWNER_NAME = :owner AND T.EDIT_TABLE_NAME = :tableName))
UNION ALL
SELECT P.USER_ID
  FROM INIT$_TB_DATA_WORK_RUN R
  JOIN INIT$_TB_DATA_WORK_JOB J
    ON J.WORK_JOB_ID = R.WORK_JOB_ID
  JOIN INIT$_TB_PROJECT P
    ON P.PROJECT_ID = J.PROJECT_ID
 WHERE :runSourceType = 'DATA_WORK'
   AND R.DATA_RUN_ID = :runId
   AND P.USER_ID = :userId
   AND J.OWNER_NAME = :owner
   AND J.TABLE_NAME = :tableName
;

-- [XAI_FLOW_ACCESS]
SELECT F.FLOW_ID
  FROM INIT$_TB_FLOW_WORK_RUN R
  JOIN INIT$_TB_FLOW_WORK F
    ON F.FLOW_ID = R.FLOW_ID
  JOIN INIT$_TB_PROJECT P
    ON P.PROJECT_ID = F.PROJECT_ID
 WHERE R.FLOW_RUN_ID = :runId
   AND (:includeAllUsers = 'Y' OR P.USER_ID = :userId)
;

-- [XAI_DATA_DISCOVERY_SCOPE]
SELECT A.WORK_JOB_ID
  FROM INIT$_TB_DATA_WORK_RUN AR
  JOIN INIT$_TB_DATA_WORK_JOB A
    ON A.WORK_JOB_ID = AR.WORK_JOB_ID
  JOIN INIT$_TB_DATA_WORK_RUN BR
    ON BR.DATA_RUN_ID = :discoveryRunId
  JOIN INIT$_TB_DATA_WORK_JOB B
    ON B.WORK_JOB_ID = BR.WORK_JOB_ID
   AND B.PROJECT_ID = A.PROJECT_ID
   AND B.SCENARIO_ID = A.SCENARIO_ID
   AND B.OWNER_NAME = A.OWNER_NAME
   AND B.TABLE_NAME = A.TABLE_NAME
 WHERE AR.DATA_RUN_ID = :runId
   AND A.OWNER_NAME = :owner
   AND A.TABLE_NAME = :tableName
;

-- [XAI_CLEAR_VIOLATIONS]
DELETE FROM INIT$_TB_RULEVIOL_XAI
 WHERE RUN_SOURCE_TYPE = :runSourceType
   AND RUN_ID = :runId
   AND TARGET_OWNER = :owner
   AND TARGET_TABLE = :tableName
;

-- [XAI_CLEAR_RULES]
DELETE FROM INIT$_TB_RULEDISC_XAI
 WHERE RUN_SOURCE_TYPE = :runSourceType
   AND RUN_ID = :runId
   AND TARGET_OWNER = :owner
   AND TARGET_TABLE = :tableName
;

-- [XAI_CLEAR_RUN]
DELETE FROM INIT$_TB_XAI_RUN
 WHERE RUN_SOURCE_TYPE = :runSourceType
   AND RUN_ID = :runId
   AND TARGET_OWNER = :owner
   AND TARGET_TABLE = :tableName
;

-- [XAI_INSERT_RUN]
INSERT INTO INIT$_TB_XAI_RUN (
    RUN_SOURCE_TYPE
  , RUN_ID
  , TARGET_OWNER
  , TARGET_TABLE
  , SUMMARY_JSON
) VALUES (
    :runSourceType
  , :runId
  , :owner
  , :tableName
  , :summaryJson
)
;

-- [XAI_UPDATE_RUN]
UPDATE INIT$_TB_XAI_RUN
   SET SUMMARY_JSON = :summaryJson
     , UPDATED_AT = SYSTIMESTAMP
 WHERE RUN_SOURCE_TYPE = :runSourceType
   AND RUN_ID = :runId
   AND TARGET_OWNER = :owner
   AND TARGET_TABLE = :tableName
;

-- [XAI_INSERT_RULE]
INSERT INTO INIT$_TB_RULEDISC_XAI (
    RUN_SOURCE_TYPE
  , RUN_ID
  , TARGET_OWNER
  , TARGET_TABLE
  , RULE_ID
  , RULE_TEXT
  , CONDITION_JSON
  , SUPPORT_COUNT
  , ANOMALY_COUNT
  , RULE_PURITY
  , VALIDATION_JSON
) VALUES (
    :runSourceType
  , :runId
  , :owner
  , :tableName
  , :ruleId
  , :ruleText
  , :conditionJson
  , :supportCount
  , :anomalyCount
  , :purity
  , :validationJson
)
;

-- [XAI_CLEAR_RULE_MATCHES]
UPDATE INIT$_TB_RULEDISC_XAI
   SET MATCH_COUNT = NULL
 WHERE RUN_SOURCE_TYPE = :runSourceType
   AND RUN_ID = :runId
   AND TARGET_OWNER = :owner
   AND TARGET_TABLE = :tableName
;

-- [XAI_UPDATE_RULE_MATCHES]
UPDATE INIT$_TB_RULEDISC_XAI
   SET MATCH_COUNT = :matchCount
 WHERE RUN_SOURCE_TYPE = :runSourceType
   AND RUN_ID = :runId
   AND TARGET_OWNER = :owner
   AND TARGET_TABLE = :tableName
   AND RULE_ID = :ruleId
;

-- [XAI_INSERT_VIOLATION]
INSERT INTO INIT$_TB_RULEVIOL_XAI (
    RUN_SOURCE_TYPE
  , RUN_ID
  , TARGET_OWNER
  , TARGET_TABLE
  , DISCOVERY_RUN_ID
  , RULE_ID
  , CASE_ID
  , ROW_DATA_JSON
  , RULE_PURITY
) VALUES (
    :runSourceType
  , :runId
  , :owner
  , :tableName
  , :discoveryRunId
  , :ruleId
  , :caseId
  , :rowDataJson
  , :purity
)
;

-- [XAI_RULE_LIST]
SELECT RULE_ID
     , RULE_TEXT
     , CONDITION_JSON
     , RULE_PURITY
     , SUPPORT_COUNT
     , ANOMALY_COUNT
     , MATCH_COUNT
     , VALIDATION_JSON
  FROM INIT$_TB_RULEDISC_XAI
 WHERE RUN_SOURCE_TYPE = :runSourceType
   AND RUN_ID = :runId
   AND TARGET_OWNER = :owner
   AND TARGET_TABLE = :tableName
 ORDER BY RULE_PURITY DESC, RULE_ID
;

-- [XAI_RUN_SUMMARY]
SELECT SUMMARY_JSON
  FROM INIT$_TB_XAI_RUN
 WHERE RUN_SOURCE_TYPE = :runSourceType
   AND RUN_ID = :runId
   AND TARGET_OWNER = :owner
   AND TARGET_TABLE = :tableName
;

-- [XAI_MATCH_COUNTS]
SELECT /*+ NO_PARALLEL(T) */ /*COUNTS*/
  FROM /*TARGET*/ T
;

-- [XAI_MATCH_PREVIEW]
SELECT /*+ NO_PARALLEL(T) */ /*CASE_ID*/ AS XAI_CASE_ID
     , /*COLUMNS*/
  FROM /*TARGET*/ T
 WHERE /*PREDICATE*/
   AND ROWNUM <= :rowLimit
;

-- [XAI_FLOW_SUMMARIES]
SELECT TARGET_OWNER
     , TARGET_TABLE
     , SUMMARY_JSON
  FROM INIT$_TB_XAI_RUN
 WHERE RUN_SOURCE_TYPE = 'FLOW_WORK'
   AND RUN_ID = :runId
   AND (:owner IS NULL OR TARGET_OWNER = :owner)
   AND (:tableName IS NULL OR TARGET_TABLE = :tableName)
 ORDER BY TARGET_OWNER, TARGET_TABLE
;

-- [XAI_FLOW_RULES]
SELECT TARGET_OWNER
     , TARGET_TABLE
     , RULE_ID
     , RULE_TEXT
     , CONDITION_JSON
     , SUPPORT_COUNT
     , ANOMALY_COUNT
     , RULE_PURITY
     , MATCH_COUNT
     , VALIDATION_JSON
     , STATUS
  FROM INIT$_TB_RULEDISC_XAI
 WHERE RUN_SOURCE_TYPE = 'FLOW_WORK'
   AND RUN_ID = :runId
   AND (:owner IS NULL OR TARGET_OWNER = :owner)
   AND (:tableName IS NULL OR TARGET_TABLE = :tableName)
 ORDER BY TARGET_OWNER, TARGET_TABLE, RULE_PURITY DESC, RULE_ID
 FETCH FIRST 1000 ROWS ONLY
;

-- [XAI_FLOW_VIOLATIONS]
SELECT TARGET_OWNER
     , TARGET_TABLE
     , RULE_ID
     , CASE_ID
     , ANOMALY_SCORE
     , RULE_PURITY
     , ROW_DATA_JSON
  FROM INIT$_TB_RULEVIOL_XAI
 WHERE RUN_SOURCE_TYPE = 'FLOW_WORK'
   AND RUN_ID = :runId
   AND (:owner IS NULL OR TARGET_OWNER = :owner)
   AND (:tableName IS NULL OR TARGET_TABLE = :tableName)
 ORDER BY TARGET_OWNER, TARGET_TABLE, RULE_PURITY DESC, RULE_ID, CASE_ID
 FETCH FIRST 1000 ROWS ONLY
;

-- [XAI_FLOW_COLUMN_COMMENTS]
SELECT C.COLUMN_NAME
     , C.COMMENTS
  FROM ALL_COL_COMMENTS C
 WHERE 1=1
   AND EXISTS
       (
        SELECT 1
          FROM INIT$_TB_XAI_RUN R
         WHERE R.RUN_SOURCE_TYPE = 'FLOW_WORK'
           AND R.RUN_ID = :runId
           AND R.TARGET_OWNER = C.OWNER
           AND R.TARGET_TABLE = C.TABLE_NAME
           AND (:owner IS NULL OR R.TARGET_OWNER = :owner)
           AND (:tableName IS NULL OR R.TARGET_TABLE = :tableName)
       )
;

-- [XAI_FLOW_RULES_PAGE]
SELECT TARGET_OWNER
     , TARGET_TABLE
     , RULE_ID
     , RULE_TEXT
     , CONDITION_JSON
     , SUPPORT_COUNT
     , ANOMALY_COUNT
     , RULE_PURITY
     , MATCH_COUNT
     , VALIDATION_JSON
     , STATUS
  FROM INIT$_TB_RULEDISC_XAI
 WHERE 1=1
   AND RUN_SOURCE_TYPE = 'FLOW_WORK'
   AND RUN_ID = :runId
   AND (:owner IS NULL OR TARGET_OWNER = :owner)
   AND (:tableName IS NULL OR TARGET_TABLE = :tableName)
 ORDER BY TARGET_OWNER
        , TARGET_TABLE
        , RULE_ID
OFFSET :offset ROWS FETCH NEXT :pageSize ROWS ONLY
;

-- [XAI_FLOW_SELECTED_RULE]
SELECT R.*
  FROM INIT$_TB_RULEDISC_XAI R
 WHERE 1=1
   AND RUN_SOURCE_TYPE = 'FLOW_WORK'
   AND RUN_ID = :runId
   AND TARGET_OWNER = :owner
   AND TARGET_TABLE = :tableName
   AND RULE_ID = :ruleId
;

-- [XAI_FLOW_SELECTED_VIOLATION_COUNT]
SELECT COUNT(*) AS TOTAL
  FROM INIT$_TB_RULEVIOL_XAI
 WHERE 1=1
   AND RUN_SOURCE_TYPE = 'FLOW_WORK'
   AND RUN_ID = :runId
   AND TARGET_OWNER = :owner
   AND TARGET_TABLE = :tableName
   AND RULE_ID = :ruleId
;

-- [XAI_FLOW_SELECTED_VIOLATIONS]
SELECT V.*
  FROM INIT$_TB_RULEVIOL_XAI V
 WHERE 1=1
   AND RUN_SOURCE_TYPE = 'FLOW_WORK'
   AND RUN_ID = :runId
   AND TARGET_OWNER = :owner
   AND TARGET_TABLE = :tableName
   AND RULE_ID = :ruleId
 ORDER BY CASE_ID
OFFSET :offset ROWS FETCH NEXT :pageSize ROWS ONLY
;
