-- 1. 규칙발굴 실행 이력 관리
CREATE TABLE RULE_DISCOVERY_HISTORY (
    HIST_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TARGET_TABLE VARCHAR2(50) NOT NULL,
    TARGET_COLUMN VARCHAR2(50),
    EXEC_START_DT DATE DEFAULT SYSDATE,
    EXEC_END_DT DATE,
    STATUS VARCHAR2(20), -- 'RUNNING', 'COMPLETED', 'FAILED'
    RESULT_SUMMARY VARCHAR2(500)
);

-- 2. 발굴된 규칙 저장 테이블
CREATE TABLE DISCOVERED_RULES (
    RULE_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    HIST_ID NUMBER REFERENCES RULE_DISCOVERY_HISTORY(HIST_ID),
    RULE_TYPE VARCHAR2(50), -- 'UNIQUE', 'RANGE', 'FORMAT', 'DEPENDENCY'
    RULE_DESC VARCHAR2(500),
    CONFIDENCE NUMBER(5,2), -- 신뢰도 (%)
    IS_CONFIRMED CHAR(1) DEFAULT 'N' -- 규칙 확정 여부
);