CREATE OR REPLACE FUNCTION "INIT$_FN_EDIT_TABLE_NAME" (
    P_SOURCE_TABLE IN VARCHAR2
) RETURN VARCHAR2
IS
    v_source_table VARCHAR2(128);
BEGIN
    v_source_table := UPPER(TRIM(DBMS_ASSERT.SIMPLE_SQL_NAME(P_SOURCE_TABLE)));
    IF v_source_table NOT LIKE 'INITUP$%' THEN
        RAISE_APPLICATION_ERROR(-20001, 'Editing source table must start with INITUP$.');
    END IF;
    RETURN 'INITDN$' || SUBSTR(v_source_table, LENGTH('INITUP$') + 1);
END;
/

CREATE OR REPLACE FUNCTION "INIT$_FN_SOURCE_TABLE_NAME" (
    P_EDIT_TABLE IN VARCHAR2
) RETURN VARCHAR2
IS
    v_edit_table VARCHAR2(128);
BEGIN
    v_edit_table := UPPER(TRIM(DBMS_ASSERT.SIMPLE_SQL_NAME(P_EDIT_TABLE)));
    IF v_edit_table NOT LIKE 'INITDN$%' THEN
        RAISE_APPLICATION_ERROR(-20002, 'Editing table must start with INITDN$.');
    END IF;
    RETURN 'INITUP$' || SUBSTR(v_edit_table, LENGTH('INITDN$') + 1);
END;
/

CREATE OR REPLACE FUNCTION "INIT$_FN_IS_EDIT_TABLE_PAIR" (
    P_SOURCE_TABLE IN VARCHAR2,
    P_EDIT_TABLE   IN VARCHAR2
) RETURN CHAR
IS
BEGIN
    IF "INIT$_FN_EDIT_TABLE_NAME"(P_SOURCE_TABLE) = UPPER(TRIM(P_EDIT_TABLE)) THEN
        RETURN 'Y';
    END IF;
    RETURN 'N';
EXCEPTION
    WHEN OTHERS THEN
        RETURN 'N';
END;
/
