CREATE OR REPLACE FUNCTION "INIT$_FN_EDIT_TABLE_NAME" (
    P_SOURCE_TABLE IN VARCHAR2
) RETURN VARCHAR2
IS
    v_source_table VARCHAR2(128);
    v_edit_table VARCHAR2(128);
BEGIN
    v_source_table := UPPER(TRIM(DBMS_ASSERT.SIMPLE_SQL_NAME(P_SOURCE_TABLE)));
    SELECT MIN(T.EDIT_TABLE_NAME)
      INTO v_edit_table
      FROM INIT$_TB_TABLES T
     WHERE T.OWNER_NAME = SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA')
       AND T.TABLE_NAME = v_source_table
       AND T.EDIT_OWNER_NAME = T.OWNER_NAME
       AND T.EDIT_TABLE_NAME IS NOT NULL
       AND T.USE_YN = 'Y'
    HAVING COUNT(DISTINCT T.EDIT_TABLE_NAME) = 1;

    RETURN v_edit_table;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20001, 'A unique saved editing-table mapping was not found.');
END;
/

CREATE OR REPLACE FUNCTION "INIT$_FN_SOURCE_TABLE_NAME" (
    P_EDIT_TABLE IN VARCHAR2
) RETURN VARCHAR2
IS
    v_edit_table VARCHAR2(128);
    v_source_table VARCHAR2(128);
BEGIN
    v_edit_table := UPPER(TRIM(DBMS_ASSERT.SIMPLE_SQL_NAME(P_EDIT_TABLE)));
    SELECT MIN(T.TABLE_NAME)
      INTO v_source_table
      FROM INIT$_TB_TABLES T
     WHERE T.EDIT_OWNER_NAME = SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA')
       AND T.EDIT_TABLE_NAME = v_edit_table
       AND T.OWNER_NAME = T.EDIT_OWNER_NAME
       AND T.USE_YN = 'Y'
    HAVING COUNT(DISTINCT T.TABLE_NAME) = 1;

    RETURN v_source_table;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20002, 'A unique saved source-table mapping was not found.');
END;
/

CREATE OR REPLACE FUNCTION "INIT$_FN_IS_EDIT_TABLE_PAIR" (
    P_SOURCE_TABLE IN VARCHAR2,
    P_EDIT_TABLE   IN VARCHAR2
) RETURN CHAR
IS
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM INIT$_TB_TABLES T
     WHERE T.OWNER_NAME = SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA')
       AND T.TABLE_NAME = UPPER(TRIM(DBMS_ASSERT.SIMPLE_SQL_NAME(P_SOURCE_TABLE)))
       AND T.EDIT_OWNER_NAME = T.OWNER_NAME
       AND T.EDIT_TABLE_NAME = UPPER(TRIM(DBMS_ASSERT.SIMPLE_SQL_NAME(P_EDIT_TABLE)))
       AND T.USE_YN = 'Y';

    IF v_count > 0 THEN
        RETURN 'Y';
    END IF;
    RETURN 'N';
EXCEPTION
    WHEN OTHERS THEN
        RETURN 'N';
END;
/
