(function() {
    MCOMMON.createDataWorkPage({
        pageCode: "M03001",
        defaultJobGroup: "M03001",
        labels: {
            menuName: "Column Type Analysis",
            contextHeader: "Project Scenario",
            contextHeaderDesc: "Select the required project and scenario for this menu.",
            tableHeader: "Scenario Tables",
            tableHeaderDesc: "Tables registered to the selected scenario.",
            contextSummaryEmpty: "No context selected.",
            changeContext: "Change",
            hideContext: "Hide",
            refreshContextTitle: "Refresh project and scenario",
            project: "Project",
            scenario: "Scenario",
            workTab: "Data Work",
            dataTab: "Data",
            sqlTab: "User SQL",
            historyTab: "Run History",
            jobsTitle: "Jobs",
            jobsDescription: "Saved work for the selected scenario.",
            newWorkTitle: "New work",
            runAllTitle: "All Execute",
            runAllQueueTitle: "All Queue batch",
            refreshJobsTitle: "Refresh jobs",
            workTitle: "work",
            workDescriptionEmpty: "Select a scenario table and registered executable object.",
            saveWork: "Save",
            deleteWork: "Delete",
            testDraft: "Test",
            runNow: "Run",
            queueBatch: "Queue",
            jobId: "Job ID",
            jobGroup: "Job Group",
            jobName: "Job Name",
            jobDesc: "Job Desc",
            targetOwner: "Target Owner",
            targetTable: "Target Table",
            use: "Use",
            sort: "Sort",
            executableObject: "Registered Model / Procedure",
            resultTableCreate: "Result Table Create",
            resultOwner: "Result Owner",
            resultTable: "Result Table",
            resultTablePlaceholder: "RESULT_TABLE",
            parameters: "Parameters",
            executableObjectHint: "Registered Model / Procedure defaults come from M90001 object details.",
            noExecutableObject: "No registered object selected.",
            parameterList: "Parameter List",
            generatedScript: "PL/SQL",
            generateScript: "Generate PL/SQL",
            runSql: "Run SQL(Ctrl+Enter)",
            runAllSql: "Run All SQL(F5)",
            queryData: "Query Data",
            saveUpdates: "Save Updates",
            whereCondition: "Where",
            whereConditionPlaceholder: "OWNER = 'INIT$EDIT01'",
            gridTotal: "Total {count} rows",
            page: "Page",
            go: "Go",
            previousPage: "Previous page",
            nextPage: "Next page",
            rowsPerPage: "Rows per page",
            pageRowsLoaded: "Page {page}: {count} rows loaded.",
            confirmDiscardPageEdits: "Unsaved grid changes will be discarded. Continue?",
            copyBaseToFinal: "BASE → FINAL",
            copyBaseToFinalTitle: "Copy BASE_PREDICTED_TYPE values to FINAL_PREDICTED_TYPE on this grid page",
            copyModelToFinal: "MODL → FINAL",
            copyModelToFinalTitle: "Copy MODL_PREDICTED_TYPE values to FINAL_PREDICTED_TYPE on this grid page",
            pasteFocusedValueDownTitle: "Paste the focused cell value downward in the current grid order",
            copyPredictionValueDone: "Copied {count} {source} value(s) to FINAL_PREDICTED_TYPE on this grid page.",
            copyPredictionColumnsUnavailable: "BASE/MODL and FINAL predicted-type columns are required for this action.",
            freezeColumns: "Freeze",
            freezeColumnsTitle: "Freeze No plus this many data columns while scrolling horizontally",
            exportExcelTitle: "Export this grid page as Excel",
            exportCsvTitle: "Export this grid page as CSV",
            exportJsonTitle: "Export this grid page as JSON",
            rows: "Rows",
            refreshHistory: "Refresh history"
        }
    });
})();
