(function() {
    MCOMMON.createDataWorkPage({
        pageCode: "M03004",
        defaultJobGroup: "M03004",
        labels: {
            menuName: "Rule Violation Detection",
            contextHeader: "Project Scenario",
            contextHeaderDesc: "Select the required project and scenario for this menu.",
            tableHeader: "Scenario Tables",
            tableHeaderDesc: "Tables registered to the selected scenario.",
            contextSummaryEmpty: "No context selected.",
            changeContext: "Change",
            hideContext: "Hide",
            refreshContextTitle: "Refresh project and scenario",
            project: "Project",
            scenario: "Scenario",
            workTab: "Data Work",
            sqlTab: "User SQL",
            historyTab: "Run History",
            jobsTitle: "[Rule Violation Detection] Jobs",
            jobsDescription: "Saved work for the selected scenario.",
            newWorkTitle: "New work",
            runAllTitle: "All Execute",
            runAllQueueTitle: "All Queue batch",
            refreshJobsTitle: "Refresh jobs",
            workTitle: "[Rule Violation Detection] work",
            workDescriptionEmpty: "Select a scenario table and registered rule violation detection object.",
            saveWork: "Save work",
            deleteWork: "Delete work",
            runNow: "Run now",
            queueBatch: "Queue batch",
            jobId: "Job ID",
            jobGroup: "Job Group",
            jobName: "Job Name",
            jobDesc: "Job Desc",
            targetOwner: "Target Owner",
            targetTable: "Target Table",
            use: "Use",
            sort: "Sort",
            executableObject: "Violation Detection Procedure / Model",
            resultTableCreate: "Result Table Create",
            resultOwner: "Result Owner",
            resultTable: "Result Table",
            resultTablePlaceholder: "RESULT_TABLE",
            parameters: "Parameters",
            executableObjectHint: "Violation detection procedure defaults come from M90001 object details.",
            noExecutableObject: "No violation detection object selected.",
            parameterList: "Parameter List",
            generatedScript: "[Rule Violation Detection] PL/SQL",
            generateScript: "Generate PL/SQL",
            runSql: "Run SQL(Ctrl+Enter)",
            runAllSql: "Run All SQL(F5)",
            rows: "Rows",
            refreshHistory: "Refresh history"
        }
    });
})();
