(function() {
    MCOMMON.createDataWorkPage({
        pageCode: "M03002",
        defaultJobGroup: "M03002",
        labels: {
            menuName: "Column Correlation Analysis",
            contextHeader: "Project Scenario",
            contextHeaderDesc: "Select the required project and scenario for this menu.",
            tableHeader: "Scenario Tables",
            tableHeaderDesc: "Tables registered to the selected scenario.",
            contextSummaryEmpty: "No context selected.",
            changeContext: "Change",
            hideContext: "Hide",
            refreshContextTitle: "Refresh project and scenario",
            project: "Project",
            scenario: "Scenario",
            workTab: "Data Work",
            sqlTab: "User SQL",
            historyTab: "Run History",
            jobsTitle: "Jobs",
            jobsDescription: "Saved work for the selected scenario.",
            newWorkTitle: "New work",
            runAllTitle: "All Execute",
            runAllQueueTitle: "All Queue batch",
            refreshJobsTitle: "Refresh jobs",
            workTitle: "work",
            workDescriptionEmpty: "Select a scenario table and registered correlation analysis object.",
            saveWork: "Save",
            deleteWork: "Delete",
            testDraft: "Test",
            runNow: "Run",
            queueBatch: "Queue",
            jobId: "Job ID",
            jobGroup: "Job Group",
            jobName: "Job Name",
            jobDesc: "Job Desc",
            targetOwner: "Target Owner",
            targetTable: "Target Table",
            use: "Use",
            sort: "Sort",
            executableObject: "Correlation Procedure / Model",
            resultTableCreate: "Result Table Create",
            resultOwner: "Result Owner",
            resultTable: "Result Table",
            resultTablePlaceholder: "RESULT_TABLE",
            parameters: "Parameters",
            executableObjectHint: "Correlation procedure defaults come from M90001 object details.",
            noExecutableObject: "No correlation object selected.",
            parameterList: "Parameter List",
            generatedScript: "PL/SQL",
            generateScript: "Generate PL/SQL",
            runSql: "Run SQL(Ctrl+Enter)",
            runAllSql: "Run All SQL(F5)",
            rows: "Rows",
            refreshHistory: "Refresh history"
        }
    });
})();
