(function() {
    MCOMMON.createFlowWorkPage({
        pageCode: "M04001",
        flowType: "INTEGRATED_EDITING_SCENARIO",
        defaultFlowGroup: "M04001",
        scenarioTableApi: "M04001",
        labels: {
            menuName: "Integrated Editing Scenario",
            contextHeader: "Project Scenario",
            contextHeaderDesc: "Select the project and scenario for this flow.",
            flowHeader: "Data Editing Flow",
            flowHeaderDesc: "Connect jobs as a DAG. Independent nodes can run in parallel; connected nodes run after their upstream dependencies.",
            contextSummaryEmpty: "No context selected.",
            changeContext: "Change",
            hideContext: "Hide",
            refreshContextTitle: "Refresh project and scenario",
            project: "Project",
            scenario: "Scenario",
            flowVersion: "Saved Flows",
            designerTab: "Flow Designer",
            planTab: "Execution Plan",
            historyTab: "Run History",
            flowAssetsTitle: "Flow Assets",
            flowAssetsDescription: "Drag a step, registered job, input, or output onto the canvas.",
            collapseFlowAssetsTitle: "Collapse Flow Assets",
            refreshSavedFlowsTitle: "Refresh saved flows",
            copySavedFlowTitle: "Copy selected saved flow",
            refreshJobsTitle: "Refresh jobs",
            stepPalette: "Step Palette",
            stepPaletteHint: "Business phases that can be connected as nodes.",
            ioPalette: "Input / Output",
            ioPaletteHint: "Reusable table, value, array, and output nodes.",
            tableInputNode: "Table Input",
            tableInputNodeDesc: "Owner/table or temporary result table",
            valueInputNode: "Value Input",
            valueInputNodeDesc: "Scalar threshold, date, owner, or option",
            arrayInputNode: "Array Input",
            arrayInputNodeDesc: "Column list, rule list, or option array",
            tableOutputNode: "Table Output",
            tableOutputNodeDesc: "Persisted result table or downstream target",
            registeredJobs: "Registered Jobs",
            registeredJobsHint: "Jobs saved in each business step.",
            flowTitle: "Data Editing Flow",
            flowDescription: "Design a reusable graph that connects data editing jobs, tables, values, and arrays.",
            saveFlow: "Save flow",
            deleteFlow: "Delete flow",
            validateFlow: "Validate",
            runNow: "Run now",
            queueBatch: "Queue batch",
            showSampleNodesTitle: "Show sample nodes",
            reloadCanvasTitle: "Reload saved canvas",
            zoomInTitle: "Zoom in",
            zoomOutTitle: "Zoom out",
            resetZoomTitle: "Reset zoom",
            fitCanvasTitle: "Fit canvas",
            autoLayoutTitle: "Tree layout",
            maximizeCanvasTitle: "Maximize canvas",
            collapseInspectorTitle: "Collapse inspector",
            removeNode: "Remove selected node",
            clearFlowCanvasTitle: "Clear flow canvas",
            flowId: "Flow ID",
            flowGroup: "Flow Code",
            flowName: "Flow Name",
            flowDesc: "Flow Desc",
            use: "Use",
            flowCanvas: "Flow Canvas",
            graph: "Graph",
            graphHint: "실선은 선행 노드가 SUCCESS일 때 후행 노드를 실행하고, 점선은 선행 노드가 종료되면 성공 여부와 관계없이 후행 노드를 실행합니다.",
            sampleFlowLabel: "오른쪽 출력 커넥터를 클릭한 뒤 연결할 노드의 왼쪽 입력 커넥터를 클릭하세요.\nShift를 누르고 연결하면 선행 노드 종료 후 실행되는 점선 연결을 만들 수 있습니다.",
            nodeInspector: "Node Inspector",
            nodeUseYn: "Execute",
            ownerName: "Target Owner",
            tableName: "Target Table",
            inputPorts: "Inputs",
            outputPorts: "Outputs",
            runtimeBindVariables: "Runtime Bind Variables",
            edgeList: "Edge List",
            flowVariables: "Flow Variables",
            backToDesigner: "Back to designer",
            buildPlan: "Build execution plan",
            refreshHistory: "Refresh history"
        },
        messages: {}
    });
})();
