(function() {
    MCOMMON.createFlowWorkPage({
        pageCode: "M04001",
        flowType: "INTEGRATED_EDITING_SCENARIO",
        defaultFlowGroup: "M04001",
        scenarioTableApi: "M04001",
        labels: {
            menuName: "Integrated Editing Scenario",
            contextHeader: "Project Scenario",
            contextHeaderDesc: "Select the project and scenario for this flow.",
            flowHeader: "Data Editing Flow",
            flowHeaderDesc: "Connect jobs as serial or parallel processing nodes.",
            contextSummaryEmpty: "No context selected.",
            changeContext: "Change",
            refreshContextTitle: "Refresh project and scenario",
            project: "Project",
            scenario: "Scenario",
            flowVersion: "Saved Flow",
            designerTab: "Flow Designer",
            planTab: "Execution Plan",
            historyTab: "Run History",
            flowAssetsTitle: "[Integrated Scenario] Flow Assets",
            flowAssetsDescription: "Drag a step, registered job, input, or output onto the canvas.",
            stepPalette: "Step Palette",
            stepPaletteHint: "Business phases that can be connected as nodes.",
            ioPalette: "Input / Output",
            ioPaletteHint: "Reusable table, value, array, and output nodes.",
            tableInputNode: "Table Input",
            tableInputNodeDesc: "Owner/table or temporary result table",
            valueInputNode: "Value Input",
            valueInputNodeDesc: "Scalar threshold, date, owner, or option",
            arrayInputNode: "Array Input",
            arrayInputNodeDesc: "Column list, rule list, or option array",
            tableOutputNode: "Table Output",
            tableOutputNodeDesc: "Persisted result table or downstream target",
            registeredJobs: "Registered Jobs",
            registeredJobsHint: "Jobs saved in each business step.",
            flowTitle: "[Integrated Scenario] Data Editing Flow",
            flowDescription: "Design a reusable graph that connects data editing jobs, tables, values, and arrays.",
            saveFlow: "Save flow",
            deleteFlow: "Delete flow",
            validateFlow: "Validate",
            runNow: "Run now",
            queueBatch: "Queue batch",
            zoomInTitle: "Zoom in",
            zoomOutTitle: "Zoom out",
            resetZoomTitle: "Reset zoom",
            fitCanvasTitle: "Fit canvas",
            autoLayoutTitle: "Tree layout",
            maximizeCanvasTitle: "Maximize canvas",
            collapseInspectorTitle: "Collapse inspector",
            flowId: "Flow ID",
            flowGroup: "Flow Group",
            flowName: "Flow Name",
            flowDesc: "Flow Desc",
            executionMode: "Execution Mode",
            use: "Use",
            flowCanvas: "Flow Canvas",
            graph: "Graph",
            graphHint: "Solid edges define execution order. Dashed edges are reference/value inputs that do not create a primary execution step.",
            sampleFlowLabel: "Solid line: execution dependency / dashed line: reference or value input.",
            nodeInspector: "Node Inspector",
            inputPorts: "Inputs",
            outputPorts: "Outputs",
            edgeList: "Edge List",
            flowVariables: "Flow Variables",
            buildPlan: "Build execution plan",
            refreshHistory: "Refresh history"
        },
        messages: {}
    });
})();
